# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class ImportExport:
    """Stub for Teamcenter.Services.Internal.Strong.Globalmultisite._2017_05.ImportExport.ImportExport"""
    def __init__(self) -> None: ...
    def TransformData(self, InputFileTickets: typing.Sequence[str], RuleFileNamesOrTickets: typing.Sequence[str], SessionOptions: typing.Sequence[typing.Any]) -> typing.Any: ...

class TransformDataResponse:
    """Stub for Teamcenter.Services.Internal.Strong.Globalmultisite._2017_05.ImportExport.TransformDataResponse"""
    def __init__(self) -> None: ...
    OutputFileTicket: str
    LogFileTicket: str
    ServiceData: typing.Any

__all__ = [
    'ImportExport',
    'TransformDataResponse',
]
