# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class AdditionalInfo:
    """Stub for Teamcenter.Services.Internal.Strong.Visualization._2020_12.StructureManagement.AdditionalInfo"""
    def __init__(self) -> None: ...
    StrToDateVectorMap: typing.Any
    StrToDoubleVectorMap: typing.Any
    StrToStringVectorMap: typing.Any
    StrToObjectVectorMap: typing.Any
    StrToIntegerVectorMap: typing.Any

class ExpandPSData1:
    """Stub for Teamcenter.Services.Internal.Strong.Visualization._2020_12.StructureManagement.ExpandPSData1"""
    def __init__(self) -> None: ...
    BomLine: typing.Any
    ObjectOfBOMLine: typing.Any
    IndexOfrelatedObjectsInfo: typing.Sequence[int]
    ResolutionStatus: int
    IsAlternate: bool

class ExpandPSFromOccurrenceListOutput:
    """Stub for Teamcenter.Services.Internal.Strong.Visualization._2020_12.StructureManagement.ExpandPSFromOccurrenceListOutput"""
    def __init__(self) -> None: ...
    ClientId: str
    OccurrenceList: typing.Sequence[typing.Any]

class ExpandPSFromOccurrenceListResponse:
    """Stub for Teamcenter.Services.Internal.Strong.Visualization._2020_12.StructureManagement.ExpandPSFromOccurrenceListResponse"""
    def __init__(self) -> None: ...
    Output: typing.Sequence[typing.Any]
    ServiceData: typing.Any
    RelatedObjects: typing.Sequence[typing.Any]
    ChildrenOfParent: typing.Any
    AdditionalInfo: typing.Any

class OccurrenceChainResult:
    """Stub for Teamcenter.Services.Internal.Strong.Visualization._2020_12.StructureManagement.OccurrenceChainResult"""
    def __init__(self) -> None: ...
    ClientId: str
    OccurrenceChain: typing.Sequence[typing.Any]

class OccurrenceListResults:
    """Stub for Teamcenter.Services.Internal.Strong.Visualization._2020_12.StructureManagement.OccurrenceListResults"""
    def __init__(self) -> None: ...
    ClientId: str
    Parent: typing.Any
    OccurrenceList: typing.Sequence[typing.Any]

class StructureManagement:
    """Stub for Teamcenter.Services.Internal.Strong.Visualization._2020_12.StructureManagement.StructureManagement"""
    def __init__(self) -> None: ...
    def ExpandPSFromOccurrenceList2(self, Info: typing.Sequence[typing.Any], Pref: typing.Any, AdditionalInfo: typing.Any) -> typing.Any: ...

__all__ = [
    'AdditionalInfo',
    'ExpandPSData1',
    'ExpandPSFromOccurrenceListOutput',
    'ExpandPSFromOccurrenceListResponse',
    'OccurrenceChainResult',
    'OccurrenceListResults',
    'StructureManagement',
]
