# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class AttributeInfo:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.DataManagement.AttributeInfo"""
    def __init__(self) -> None: ...
    Name: str
    Values: typing.Sequence[str]

class BoundingBox:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.DataManagement.BoundingBox"""
    def __init__(self) -> None: ...
    Xmin: float
    Ymin: float
    Zmin: float
    Xmax: float
    Ymax: float
    Zmax: float

class CommitDatasetFileInfo:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.DataManagement.CommitDatasetFileInfo"""
    def __init__(self) -> None: ...
    Dataset: typing.Any
    CreateNewVersion: bool
    DatasetFileTicketInfos: typing.Sequence[typing.Any]

class CreateOrUpdatePartsOutput:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.DataManagement.CreateOrUpdatePartsOutput"""
    def __init__(self) -> None: ...
    ClientId: str
    Item: typing.Any
    ItemRev: typing.Any
    DatasetOutput: typing.Sequence[typing.Any]
    ExtraItemObjs: typing.Sequence[typing.Any]
    ExtraItemRevObjs: typing.Sequence[typing.Any]

class CreateOrUpdatePartsResponse:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.DataManagement.CreateOrUpdatePartsResponse"""
    def __init__(self) -> None: ...
    Output: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class DataManagement:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.DataManagement.DataManagement"""
    def __init__(self) -> None: ...
    def CreateOrUpdateParts(self, PartInput: typing.Sequence[typing.Any], Pref: typing.Any) -> typing.Any: ...
    def ExpandFoldersForCAD(self, Folders: typing.Sequence[typing.Any], Pref: typing.Any) -> typing.Any: ...

class DatasetFileInfo:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.DataManagement.DatasetFileInfo"""
    def __init__(self) -> None: ...
    ClientId: str
    FileName: str
    NamedReferencedName: str
    IsText: bool
    AllowReplace: bool
    BoundingBoxesAvailable: bool
    BoundingBoxes: typing.Sequence[typing.Any]

class DatasetFileTicketInfo:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.DataManagement.DatasetFileTicketInfo"""
    def __init__(self) -> None: ...
    DatasetFileInfo: typing.Any
    Ticket: str

class DatasetInfo:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.DataManagement.DatasetInfo"""
    def __init__(self) -> None: ...
    ClientId: str
    Dataset: typing.Any
    Name: str
    BasisName: str
    Description: str
    Type: str
    LastModifiedOfDataset: typing.Any
    Id: str
    DatasetRev: str
    ItemRevRelationName: str
    CreateNewVersion: bool
    MapAttributesWithoutDataset: bool
    NamedReferencePreference: str
    AttrList: typing.Sequence[typing.Any]
    MappingAttributes: typing.Sequence[typing.Any]
    ExtraObject: typing.Sequence[typing.Any]
    DatasetFileInfos: typing.Sequence[typing.Any]
    NamedReferenceObjectInfos: typing.Sequence[typing.Any]

class DatasetOutput:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.DataManagement.DatasetOutput"""
    def __init__(self) -> None: ...
    ClientId: str
    Dataset: typing.Any
    CommitInfo: typing.Sequence[typing.Any]
    ExtraObjs: typing.Sequence[typing.Any]
    NamedRefObjs: typing.Sequence[typing.Any]

class ExpandFolderForCADPref2:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.DataManagement.ExpandFolderForCADPref2"""
    def __init__(self) -> None: ...
    ExpItemRev: bool
    LatestNRevs: int
    Info: typing.Sequence[typing.Any]
    ContentTypesFilter: typing.Sequence[str]

class ExpandFoldersForCADOutput2:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.DataManagement.ExpandFoldersForCADOutput2"""
    def __init__(self) -> None: ...
    InputFolder: typing.Any
    FstlvlFolders: typing.Sequence[typing.Any]
    ItemsOutput: typing.Sequence[typing.Any]
    ItemRevsOutput: typing.Sequence[typing.Any]
    Contents: typing.Sequence[typing.Any]

class ExpandFoldersForCADResponse2:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.DataManagement.ExpandFoldersForCADResponse2"""
    def __init__(self) -> None: ...
    Output: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class ExtraObjectInfo:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.DataManagement.ExtraObjectInfo"""
    def __init__(self) -> None: ...
    Object: typing.Any
    ClientId: str
    RelationTypeName: str
    TypeName: str
    AttrNameValuePairs: typing.Sequence[typing.Any]

class ItemInfo:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.DataManagement.ItemInfo"""
    def __init__(self) -> None: ...
    Item: typing.Any
    ItemId: str
    ItemType: str
    Name: str
    Description: str
    AttrList: typing.Sequence[typing.Any]
    ExtraObject: typing.Sequence[typing.Any]
    Folder: typing.Any

class ItemRevInfo:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.DataManagement.ItemRevInfo"""
    def __init__(self) -> None: ...
    ItemRevision: typing.Any
    RevId: str
    AttrList: typing.Sequence[typing.Any]
    ExtraObject: typing.Sequence[typing.Any]

class NamedReferenceObjectInfo:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.DataManagement.NamedReferenceObjectInfo"""
    def __init__(self) -> None: ...
    ClientId: str
    Object: typing.Any
    NamedReferenceName: str
    NamedReferenceType: str
    TypeName: str
    AttrNameValuePairs: typing.Sequence[typing.Any]

class PartInfo:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.DataManagement.PartInfo"""
    def __init__(self) -> None: ...
    ClientId: str
    ItemInput: typing.Any
    ItemRevInput: typing.Any
    DatasetInput: typing.Sequence[typing.Any]

__all__ = [
    'AttributeInfo',
    'BoundingBox',
    'CommitDatasetFileInfo',
    'CreateOrUpdatePartsOutput',
    'CreateOrUpdatePartsResponse',
    'DataManagement',
    'DatasetFileInfo',
    'DatasetFileTicketInfo',
    'DatasetInfo',
    'DatasetOutput',
    'ExpandFolderForCADPref2',
    'ExpandFoldersForCADOutput2',
    'ExpandFoldersForCADResponse2',
    'ExtraObjectInfo',
    'ItemInfo',
    'ItemRevInfo',
    'NamedReferenceObjectInfo',
    'PartInfo',
]
