# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class CopyRecursivelyResponse:
    """Stub for Teamcenter.Services.Internal.Strong.Structuremanagement._2008_06.Structure.CopyRecursivelyResponse"""
    def __init__(self) -> None: ...
    CreatedIcRevs: typing.Sequence[typing.Any]
    CreatedFutureIcRevs: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class FindHighestFindNumInExpandInput:
    """Stub for Teamcenter.Services.Internal.Strong.Structuremanagement._2008_06.Structure.FindHighestFindNumInExpandInput"""
    def __init__(self) -> None: ...
    ClientId: str
    Bvr: typing.Any
    OccType: str

class FindHighestFindNumberInExpandResponse:
    """Stub for Teamcenter.Services.Internal.Strong.Structuremanagement._2008_06.Structure.FindHighestFindNumberInExpandResponse"""
    def __init__(self) -> None: ...
    IncrementNumber: int
    ServiceData: typing.Any
    Output: typing.Sequence[typing.Any]

class FindHighestFindNumberOutputStruct:
    """Stub for Teamcenter.Services.Internal.Strong.Structuremanagement._2008_06.Structure.FindHighestFindNumberOutputStruct"""
    def __init__(self) -> None: ...
    HighestFindNumber: int
    ClientId: str

class Structure:
    """Stub for Teamcenter.Services.Internal.Strong.Structuremanagement._2008_06.Structure.Structure"""
    def __init__(self) -> None: ...
    def CopyRecursively(self, ObjectToClone: typing.Any, CopyActionRulesKey: str, TemplateBOMWindow: typing.Any, WindowOfSelectedLine: typing.Any, NewName: str, NewDescription: str, NewId: str, NewRevId: str, CopyFutureEffectivities: bool) -> typing.Any: ...
    def FindHighestFindNumberInExpand(self, Input: typing.Sequence[typing.Any]) -> typing.Any: ...

__all__ = [
    'CopyRecursivelyResponse',
    'FindHighestFindNumInExpandInput',
    'FindHighestFindNumberInExpandResponse',
    'FindHighestFindNumberOutputStruct',
    'Structure',
]
