# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class Session:
    """Stub for Teamcenter.Services.Strong.Core._2009_04.Session.Session"""
    def __init__(self) -> None: ...
    def StartOperation(self) -> str: ...
    def StopOperation(self, OpId: str) -> bool: ...

__all__ = [
    'Session',
]
