# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class AddParticipantInfo:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.DataManagement.AddParticipantInfo"""
    def __init__(self) -> None: ...
    ItemRev: typing.Any
    ParticipantInfo: typing.Sequence[typing.Any]

class AddParticipantOutput:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.DataManagement.AddParticipantOutput"""
    def __init__(self) -> None: ...
    ParticipantOutput: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class AttrInfo:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.DataManagement.AttrInfo"""
    def __init__(self) -> None: ...
    Name: str
    Value: str

class BOHierarchy:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.DataManagement.BOHierarchy"""
    def __init__(self) -> None: ...
    BOName: str
    BOParents: typing.Sequence[str]

class BOWithExclusionIn:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.DataManagement.BOWithExclusionIn"""
    def __init__(self) -> None: ...
    BoTypeName: str
    ExclusionBOTypeNames: typing.Sequence[str]

class BVROutput:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.DataManagement.BVROutput"""
    def __init__(self) -> None: ...
    Bvr: typing.Any
    ViewTypeName: str

class ConnectionOutput:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.DataManagement.ConnectionOutput"""
    def __init__(self) -> None: ...
    ClientId: str
    Connection: typing.Any
    ConnectionRev: typing.Any

class ConnectionProperties:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.DataManagement.ConnectionProperties"""
    def __init__(self) -> None: ...
    ClientId: str
    ConnId: str
    Name: str
    Type: str
    RevId: str
    Description: str
    ExtendedAttributes: typing.Sequence[typing.Any]

class CreateConnectionsResponse:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.DataManagement.CreateConnectionsResponse"""
    def __init__(self) -> None: ...
    ServiceData: typing.Any
    Output: typing.Sequence[typing.Any]

class CreateIn:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.DataManagement.CreateIn"""
    def __init__(self) -> None: ...
    ClientId: str
    Data: typing.Any

class CreateInput:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.DataManagement.CreateInput"""
    def __init__(self) -> None: ...
    BoName: str
    StringProps: typing.Any
    StringArrayProps: typing.Any
    DoubleProps: typing.Any
    DoubleArrayProps: typing.Any
    FloatProps: typing.Any
    FloatArrayProps: typing.Any
    IntProps: typing.Any
    IntArrayProps: typing.Any
    BoolProps: typing.Any
    BoolArrayProps: typing.Any
    DateProps: typing.Any
    DateArrayProps: typing.Any
    TagProps: typing.Any
    TagArrayProps: typing.Any
    CompoundCreateInput: typing.Any

class CreateOrUpdateGDELinksResponse:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.DataManagement.CreateOrUpdateGDELinksResponse"""
    def __init__(self) -> None: ...
    SuccessfullyProcessedGDELinks: typing.Any
    ServiceData: typing.Any

class CreateOrUpdateItemElementsResponse:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.DataManagement.CreateOrUpdateItemElementsResponse"""
    def __init__(self) -> None: ...
    ServiceData: typing.Any
    Output: typing.Sequence[typing.Any]

class CreateOrUpdateRelationsInfo:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.DataManagement.CreateOrUpdateRelationsInfo"""
    def __init__(self) -> None: ...
    ClientId: str
    RelationType: str
    PrimaryObject: typing.Any
    SecondaryData: typing.Sequence[typing.Any]
    Relations: typing.Sequence[typing.Any]

class CreateOrUpdateRelationsOutput:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.DataManagement.CreateOrUpdateRelationsOutput"""
    def __init__(self) -> None: ...
    ClientId: str
    Relations: typing.Sequence[typing.Any]

class CreateOrUpdateRelationsResponse:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.DataManagement.CreateOrUpdateRelationsResponse"""
    def __init__(self) -> None: ...
    Output: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class CreateOut:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.DataManagement.CreateOut"""
    def __init__(self) -> None: ...
    ClientId: str
    Objects: typing.Sequence[typing.Any]

class CreateResponse:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.DataManagement.CreateResponse"""
    def __init__(self) -> None: ...
    Output: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class DataManagement:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.DataManagement.DataManagement"""
    def __init__(self) -> None: ...
    def AddParticipants(self, AddParticipantInfo: typing.Sequence[typing.Any]) -> typing.Any: ...
    def CreateConnections(self, Properties: typing.Sequence[typing.Any], Container: typing.Any, RelationType: str) -> typing.Any: ...
    def CreateDatasets2(self, Input: typing.Sequence[typing.Any]) -> typing.Any: ...
    def CreateObjects(self, Input: typing.Sequence[typing.Any]) -> typing.Any: ...
    def CreateOrUpdateGDELinks(self, GdeLinkInfos: typing.Sequence[typing.Any]) -> typing.Any: ...
    def CreateOrUpdateItemElements(self, Properties: typing.Sequence[typing.Any]) -> typing.Any: ...
    def CreateOrUpdateRelations(self, Infos: typing.Sequence[typing.Any], Sync: bool) -> typing.Any: ...
    def FindDisplayableSubBusinessObjects(self, Input: typing.Sequence[typing.Any]) -> typing.Any: ...
    def GetItemAndRelatedObjects(self, Infos: typing.Sequence[typing.Any]) -> typing.Any: ...
    def GetNRPatternsWithCounters(self, VAttachInfo: typing.Sequence[typing.Any]) -> typing.Any: ...
    def GetNextIds(self, VInfoForNextId: typing.Sequence[typing.Any]) -> typing.Any: ...
    def GetRevNRAttachDetails(self, TypeAndItemRevInfos: typing.Sequence[typing.Any]) -> typing.Any: ...
    def RemoveParticipants(self, Participants: typing.Sequence[typing.Any]) -> typing.Any: ...
    def Revise2(self, Info: typing.Sequence[typing.Any]) -> typing.Any: ...
    def SaveAsNewItem2(self, Info: typing.Sequence[typing.Any]) -> typing.Any: ...

class DatasetFilter:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.DataManagement.DatasetFilter"""
    def __init__(self) -> None: ...
    UseNameFirst: bool
    Processing: str
    NrFilters: typing.Sequence[typing.Any]
    Name: str
    RelationFilters: typing.Sequence[typing.Any]

class DatasetInfo:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.DataManagement.DatasetInfo"""
    def __init__(self) -> None: ...
    ClientId: str
    Uid: str
    Filter: typing.Any
    NamedRefs: typing.Sequence[typing.Any]

class DatasetOutput:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.DataManagement.DatasetOutput"""
    def __init__(self) -> None: ...
    ClientId: str
    Dataset: typing.Any
    RelationTypeName: str
    NamedReferenceOutput: typing.Sequence[typing.Any]

class DatasetProperties2:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.DataManagement.DatasetProperties2"""
    def __init__(self) -> None: ...
    ClientId: str
    Type: str
    Name: str
    Description: str
    ToolUsed: str
    DatasetId: str
    DatasetRev: str
    Container: typing.Any
    RelationType: str

class DatasetRelationFilter:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.DataManagement.DatasetRelationFilter"""
    def __init__(self) -> None: ...
    RelationTypeName: str
    DatasetTypeName: str

class DeepCopyData:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.DataManagement.DeepCopyData"""
    def __init__(self) -> None: ...
    OtherSideObjectTag: typing.Any
    RelationTypeName: str
    NewName: str
    Action: int
    IsTargetPrimary: bool
    IsRequired: bool
    CopyRelations: bool

class DisplayableBOsOut:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.DataManagement.DisplayableBOsOut"""
    def __init__(self) -> None: ...
    BoTypeName: str
    DisplayableBOTypeNames: typing.Sequence[typing.Any]

class DisplayableSubBOsResponse:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.DataManagement.DisplayableSubBOsResponse"""
    def __init__(self) -> None: ...
    Output: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class GDELinkInfo:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.DataManagement.GDELinkInfo"""
    def __init__(self) -> None: ...
    ClientID: str
    Name: str
    Description: str
    Type: str
    GdeLink: typing.Any
    Attributes: typing.Sequence[typing.Any]

class GetItemAndRelatedObjectsInfo:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.DataManagement.GetItemAndRelatedObjectsInfo"""
    def __init__(self) -> None: ...
    ClientId: str
    ItemInfo: typing.Any
    RevInfo: typing.Any
    DatasetInfo: typing.Any
    BvrTypeNames: typing.Sequence[str]

class GetItemAndRelatedObjectsItemOutput:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.DataManagement.GetItemAndRelatedObjectsItemOutput"""
    def __init__(self) -> None: ...
    ClientId: str
    Item: typing.Any
    ItemRevOutput: typing.Sequence[typing.Any]

class GetItemAndRelatedObjectsResponse:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.DataManagement.GetItemAndRelatedObjectsResponse"""
    def __init__(self) -> None: ...
    Output: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class GetNRPatternsWithCountersResponse:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.DataManagement.GetNRPatternsWithCountersResponse"""
    def __init__(self) -> None: ...
    Patterns: typing.Sequence[typing.Any]
    PreferredPattern: typing.Sequence[str]
    Condition: typing.Sequence[str]
    ServiceData: typing.Any

class GetNextIdsResponse:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.DataManagement.GetNextIdsResponse"""
    def __init__(self) -> None: ...
    NextIds: typing.Sequence[str]
    ServiceData: typing.Any

class GetRevNRAttachResponse:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.DataManagement.GetRevNRAttachResponse"""
    def __init__(self) -> None: ...
    InitRevDetails: typing.Sequence[typing.Any]
    SecRevDetails: typing.Sequence[typing.Any]
    SupplRevDetails: typing.Sequence[typing.Any]
    ExcludedLetters: typing.Sequence[str]
    ServiceData: typing.Any

class InfoForNextId:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.DataManagement.InfoForNextId"""
    def __init__(self) -> None: ...
    TypeName: str
    PropName: str
    Pattern: str

class ItemElementProperties:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.DataManagement.ItemElementProperties"""
    def __init__(self) -> None: ...
    ClientId: str
    Name: str
    Type: str
    Description: str
    ItemElemAttributes: typing.Any
    ItemElement: typing.Any

class ItemElementsOutput:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.DataManagement.ItemElementsOutput"""
    def __init__(self) -> None: ...
    ClientId: str
    ItemElem: typing.Any

class ItemInfo:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.DataManagement.ItemInfo"""
    def __init__(self) -> None: ...
    ClientId: str
    UseIdFirst: bool
    Uid: str
    Ids: typing.Sequence[typing.Any]

class MasterFormPropertiesInfo:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.DataManagement.MasterFormPropertiesInfo"""
    def __init__(self) -> None: ...
    Form: typing.Any
    PropertyValueInfo: typing.Sequence[typing.Any]

class NRAttachInfo:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.DataManagement.NRAttachInfo"""
    def __init__(self) -> None: ...
    TypeName: str
    PropName: str

class NROutput:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.DataManagement.NROutput"""
    def __init__(self) -> None: ...
    NamedReference: typing.Any
    NamedReferenceName: str
    Ticket: str

class NameValueStruct:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.DataManagement.NameValueStruct"""
    def __init__(self) -> None: ...
    Name: str
    Values: typing.Sequence[str]

class NamedReferenceFilter:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.DataManagement.NamedReferenceFilter"""
    def __init__(self) -> None: ...
    NamedReference: str
    UidReferenced: str

class NamedReferenceList:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.DataManagement.NamedReferenceList"""
    def __init__(self) -> None: ...
    NamedReference: str
    Ticket: bool

class ParticipantInfo:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.DataManagement.ParticipantInfo"""
    def __init__(self) -> None: ...
    Assignee: typing.Any
    ParticipantType: str
    ClientId: str

class Participants:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.DataManagement.Participants"""
    def __init__(self) -> None: ...
    ItemRev: typing.Any
    Participant: typing.Sequence[typing.Any]

class PatternsWithCounters:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.DataManagement.PatternsWithCounters"""
    def __init__(self) -> None: ...
    PatternStrings: typing.Sequence[str]

class PropertyNameValueInfo:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.DataManagement.PropertyNameValueInfo"""
    def __init__(self) -> None: ...
    PropertyName: str
    PropertyValues: typing.Sequence[str]

class RelatedObjectInfo:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.DataManagement.RelatedObjectInfo"""
    def __init__(self) -> None: ...
    RelatedObject: typing.Any
    Action: int
    IsSecondary: bool

class RevInfo:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.DataManagement.RevInfo"""
    def __init__(self) -> None: ...
    ClientId: str
    Processing: str
    UseIdFirst: bool
    Uid: str
    Id: str
    NRevs: int
    RevisionRule: str

class RevOptionDetails:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.DataManagement.RevOptionDetails"""
    def __init__(self) -> None: ...
    RevOption: str
    RevFormat: int

class ReviseInfo:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.DataManagement.ReviseInfo"""
    def __init__(self) -> None: ...
    ClientId: str
    BaseItemRevision: typing.Any
    NewRevId: str
    Name: str
    Description: str
    DeepCopyInfo: typing.Sequence[typing.Any]
    NewItemRevisionMasterProperties: typing.Any

class ReviseOutput:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.DataManagement.ReviseOutput"""
    def __init__(self) -> None: ...
    NewItemRev: typing.Any
    RelatedObjects: typing.Sequence[typing.Any]

class ReviseResponse2:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.DataManagement.ReviseResponse2"""
    def __init__(self) -> None: ...
    ReviseOutputMap: typing.Any
    ServiceData: typing.Any

class RevisionOutput:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.DataManagement.RevisionOutput"""
    def __init__(self) -> None: ...
    ClientId: str
    ItemRevision: typing.Any
    Bvrs: typing.Sequence[typing.Any]
    DatasetOutput: typing.Sequence[typing.Any]

class SaveAsNewItemInfo:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.DataManagement.SaveAsNewItemInfo"""
    def __init__(self) -> None: ...
    ClientId: str
    BaseItemRevision: typing.Any
    NewItemId: str
    NewRevId: str
    Name: str
    Description: str
    DeepCopyInfo: typing.Sequence[typing.Any]
    NewItemMasterProperties: typing.Any
    NewItemRevisionMasterProperties: typing.Any

class SaveAsNewItemOutput2:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.DataManagement.SaveAsNewItemOutput2"""
    def __init__(self) -> None: ...
    NewItem: typing.Any
    NewItemRev: typing.Any
    RelatedObjects: typing.Sequence[typing.Any]

class SaveAsNewItemResponse2:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.DataManagement.SaveAsNewItemResponse2"""
    def __init__(self) -> None: ...
    SaveAsOutputMap: typing.Any
    ServiceData: typing.Any

class SecondaryData:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.DataManagement.SecondaryData"""
    def __init__(self) -> None: ...
    ClientId: str
    Secondary: typing.Any
    UserData: typing.Any
    Properties: typing.Sequence[typing.Any]

class TypeAndItemRevInfo:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.DataManagement.TypeAndItemRevInfo"""
    def __init__(self) -> None: ...
    TypeName: str
    ItemRev: typing.Any

__all__ = [
    'AddParticipantInfo',
    'AddParticipantOutput',
    'AttrInfo',
    'BOHierarchy',
    'BOWithExclusionIn',
    'BVROutput',
    'ConnectionOutput',
    'ConnectionProperties',
    'CreateConnectionsResponse',
    'CreateIn',
    'CreateInput',
    'CreateOrUpdateGDELinksResponse',
    'CreateOrUpdateItemElementsResponse',
    'CreateOrUpdateRelationsInfo',
    'CreateOrUpdateRelationsOutput',
    'CreateOrUpdateRelationsResponse',
    'CreateOut',
    'CreateResponse',
    'DataManagement',
    'DatasetFilter',
    'DatasetInfo',
    'DatasetOutput',
    'DatasetProperties2',
    'DatasetRelationFilter',
    'DeepCopyData',
    'DisplayableBOsOut',
    'DisplayableSubBOsResponse',
    'GDELinkInfo',
    'GetItemAndRelatedObjectsInfo',
    'GetItemAndRelatedObjectsItemOutput',
    'GetItemAndRelatedObjectsResponse',
    'GetNRPatternsWithCountersResponse',
    'GetNextIdsResponse',
    'GetRevNRAttachResponse',
    'InfoForNextId',
    'ItemElementProperties',
    'ItemElementsOutput',
    'ItemInfo',
    'MasterFormPropertiesInfo',
    'NRAttachInfo',
    'NROutput',
    'NameValueStruct',
    'NamedReferenceFilter',
    'NamedReferenceList',
    'ParticipantInfo',
    'Participants',
    'PatternsWithCounters',
    'PropertyNameValueInfo',
    'RelatedObjectInfo',
    'RevInfo',
    'RevOptionDetails',
    'ReviseInfo',
    'ReviseOutput',
    'ReviseResponse2',
    'RevisionOutput',
    'SaveAsNewItemInfo',
    'SaveAsNewItemOutput2',
    'SaveAsNewItemResponse2',
    'SecondaryData',
    'TypeAndItemRevInfo',
]
