# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class ExportToApplicationInputData2:
    """Stub for Awp0.Services.Internal.Strong.Aws2._2016_03.RequirementsManagement.ExportToApplicationInputData2"""
    def __init__(self) -> None: ...
    ObjectsToExport: typing.Sequence[typing.Any]
    TargetObjectsToExport: typing.Sequence[typing.Any]
    AttributesToExport: typing.Sequence[str]
    ApplicationFormat: str
    TemplateName: str

class ExportToApplicationResponse2:
    """Stub for Awp0.Services.Internal.Strong.Aws2._2016_03.RequirementsManagement.ExportToApplicationResponse2"""
    def __init__(self) -> None: ...
    TransientFileReadTickets: typing.Sequence[str]
    Contents: typing.Sequence[str]
    ServiceData: typing.Any

class RequirementsManagement:
    """Stub for Awp0.Services.Internal.Strong.Aws2._2016_03.RequirementsManagement.RequirementsManagement"""
    def __init__(self) -> None: ...
    def ExportToApplication(self, Input: typing.Sequence[typing.Any]) -> typing.Any: ...

__all__ = [
    'ExportToApplicationInputData2',
    'ExportToApplicationResponse2',
    'RequirementsManagement',
]
