# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class EffectivityInfo:
    """Stub for Teamcenter.Services.Internal.Strong.Visualization._2018_11.StructureManagement.EffectivityInfo"""
    def __init__(self) -> None: ...
    EffectivityUnitNo: int
    EffectivityDate: typing.Any
    EndItem: typing.Any

class GetProductStructureIdResponse:
    """Stub for Teamcenter.Services.Internal.Strong.Visualization._2018_11.StructureManagement.GetProductStructureIdResponse"""
    def __init__(self) -> None: ...
    PsIdInfos: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class ProductAndConfigInfo:
    """Stub for Teamcenter.Services.Internal.Strong.Visualization._2018_11.StructureManagement.ProductAndConfigInfo"""
    def __init__(self) -> None: ...
    Product: typing.Any
    RevisionRule: typing.Any
    EffectivityInfos: typing.Sequence[typing.Any]
    VariantInfos: typing.Sequence[typing.Any]

class ProductStructureIdInfo:
    """Stub for Teamcenter.Services.Internal.Strong.Visualization._2018_11.StructureManagement.ProductStructureIdInfo"""
    def __init__(self) -> None: ...
    ClientId: str
    ProductStrutureIdentifier: str
    ProductAndConfig: typing.Any
    RevRuleInfo: typing.Sequence[typing.Any]

class ProductStructureIdInput:
    """Stub for Teamcenter.Services.Internal.Strong.Visualization._2018_11.StructureManagement.ProductStructureIdInput"""
    def __init__(self) -> None: ...
    ClientId: str
    RecipeObject: typing.Any
    ProductAndConfig: typing.Any

class RevRuleInfo:
    """Stub for Teamcenter.Services.Internal.Strong.Visualization._2018_11.StructureManagement.RevRuleInfo"""
    def __init__(self) -> None: ...
    RevRuleEntryNames: typing.Sequence[str]
    EffectivityExpr: str
    VariantExpr: str
    RevRuleDate: typing.Any
    Context: str

class StructureManagement:
    """Stub for Teamcenter.Services.Internal.Strong.Visualization._2018_11.StructureManagement.StructureManagement"""
    def __init__(self) -> None: ...
    def GetStructureIdFromRecipe(self, ProductStructureIdInput: typing.Sequence[typing.Any]) -> typing.Any: ...

class VariantRuleInfo:
    """Stub for Teamcenter.Services.Internal.Strong.Visualization._2018_11.StructureManagement.VariantRuleInfo"""
    def __init__(self) -> None: ...
    VariantRule: typing.Any
    VariantRuleOwningObject: typing.Any

__all__ = [
    'EffectivityInfo',
    'GetProductStructureIdResponse',
    'ProductAndConfigInfo',
    'ProductStructureIdInfo',
    'ProductStructureIdInput',
    'RevRuleInfo',
    'StructureManagement',
    'VariantRuleInfo',
]
