# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class AsBuilt:
    """Stub for Teamcenter.Services.Strong.Asbuilt._2014_06.AsBuilt.AsBuilt"""
    def __init__(self) -> None: ...
    def GenerateAsBuiltStructure(self, Input: typing.Sequence[typing.Any]) -> typing.Any: ...

class AsBuiltStructureInfo1:
    """Stub for Teamcenter.Services.Strong.Asbuilt._2014_06.AsBuilt.AsBuiltStructureInfo1"""
    def __init__(self) -> None: ...
    NeutralItemId: str
    SerialNumber: str
    LotNumber: str
    ManufacturerId: str
    StructureContext: str
    InstallationDate: typing.Any
    ManufacturingDate: typing.Any
    UseSerialNumberGenerators: bool
    NumberOfLevels: int
    ExtendedData: typing.Any
    Quantity: float

class GenerateAsBuiltStructInput1:
    """Stub for Teamcenter.Services.Strong.Asbuilt._2014_06.AsBuilt.GenerateAsBuiltStructInput1"""
    def __init__(self) -> None: ...
    ClientId: str
    NeutralBOMLine: typing.Any
    AsBuiltStructureInfo: typing.Any

__all__ = [
    'AsBuilt',
    'AsBuiltStructureInfo1',
    'GenerateAsBuiltStructInput1',
]
