# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
from teamcenter.esm0.services.strong.esmbase import ESMBaseService

class ESMBaseRestBindingStub(ESMBaseService):
    """Stub for Esm0.Services.Strong.Esmbase.ESMBaseRestBindingStub"""
    def __init__(self, connection: typing.Any) -> None: ...
    def GenerateHardwareSoftwareReport(self, GenerateReportInputs: typing.Sequence[typing.Any]) -> typing.Any: ...
    def GenerateSoftwareHardwareReport(self, GenerateReportInputs: typing.Sequence[typing.Any]) -> typing.Any: ...

class ESMBaseService:
    """Stub for Esm0.Services.Strong.Esmbase.ESMBaseService"""
    def __init__(self) -> None: ...
    def GenerateHardwareSoftwareReport(self, GenerateReportInputs: typing.Sequence[typing.Any]) -> typing.Any: ...
    def GenerateSoftwareHardwareReport(self, GenerateReportInputs: typing.Sequence[typing.Any]) -> typing.Any: ...
    @classmethod
    def getService(cls, connection: typing.Any) -> typing.Any: ...

__all__ = [
    'ESMBaseRestBindingStub',
    'ESMBaseService',
    '_2011_06',
]
