# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class DiagramLegendData:
    """Stub for Ase0.Services.Strong.Activeworkspacesyseng._2014_11.DiagramManagement.DiagramLegendData"""
    def __init__(self) -> None: ...
    Name: str
    DisplayName: str
    DefaultLayout: str
    ObjectGroup: typing.Sequence[typing.Any]
    RelationGroup: typing.Sequence[typing.Any]

class DiagramLegendData1:
    """Stub for Ase0.Services.Strong.Activeworkspacesyseng._2014_11.DiagramManagement.DiagramLegendData1"""
    def __init__(self) -> None: ...
    Name: str
    DisplayName: str
    DefaultLayout: str
    GroupData: typing.Sequence[typing.Any]

class DiagramLegendResponse:
    """Stub for Ase0.Services.Strong.Activeworkspacesyseng._2014_11.DiagramManagement.DiagramLegendResponse"""
    def __init__(self) -> None: ...
    LegendData: typing.Sequence[typing.Any]
    PresentationRulesXML: str
    PresentationStylesXML: str
    ServiceData: typing.Any

class DiagramLegendResponse1:
    """Stub for Ase0.Services.Strong.Activeworkspacesyseng._2014_11.DiagramManagement.DiagramLegendResponse1"""
    def __init__(self) -> None: ...
    LegendData: typing.Sequence[typing.Any]
    PresentationRulesXML: str
    PresentationStylesXML: str
    ServiceData: typing.Any

class DiagramManagement:
    """Stub for Ase0.Services.Strong.Activeworkspacesyseng._2014_11.DiagramManagement.DiagramManagement"""
    def __init__(self) -> None: ...
    def GetDiagramLegend2(self, ViewName: str) -> typing.Any: ...
    def GetDiagramLegend3(self, ViewName: str) -> typing.Any: ...

class FilterData:
    """Stub for Ase0.Services.Strong.Activeworkspacesyseng._2014_11.DiagramManagement.FilterData"""
    def __init__(self) -> None: ...
    Name: str
    DisplayName: str
    Types: typing.Sequence[typing.Any]
    Color: typing.Any

class FilterData1:
    """Stub for Ase0.Services.Strong.Activeworkspacesyseng._2014_11.DiagramManagement.FilterData1"""
    def __init__(self) -> None: ...
    Name: str
    DisplayName: str
    Types: typing.Sequence[typing.Any]
    Color: typing.Any
    GroupType: str

class TypeData1:
    """Stub for Ase0.Services.Strong.Activeworkspacesyseng._2014_11.DiagramManagement.TypeData1"""
    def __init__(self) -> None: ...
    TypeName: str
    DisplayName: str
    IsAuthorable: bool

__all__ = [
    'DiagramLegendData',
    'DiagramLegendData1',
    'DiagramLegendResponse',
    'DiagramLegendResponse1',
    'DiagramManagement',
    'FilterData',
    'FilterData1',
    'TypeData1',
]
