# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class ConditionData:
    """Stub for Teamcenter.Services.Internal.Strong.Vendormanagement._2008_06.VendorManagement.ConditionData"""
    def __init__(self) -> None: ...
    CondName: str
    CondExpress: str

class GetVPSRConditionsResponse:
    """Stub for Teamcenter.Services.Internal.Strong.Vendormanagement._2008_06.VendorManagement.GetVPSRConditionsResponse"""
    def __init__(self) -> None: ...
    CondData: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class VendorManagement:
    """Stub for Teamcenter.Services.Internal.Strong.Vendormanagement._2008_06.VendorManagement.VendorManagement"""
    def __init__(self) -> None: ...
    def GetVPSRConditions(self) -> typing.Any: ...

__all__ = [
    'ConditionData',
    'GetVPSRConditionsResponse',
    'VendorManagement',
]
