# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class AdditionalInfo:
    """Stub for Teamcenter.Services.Internal.Strong.Changemanagement._2015_03.ChangeManagement.AdditionalInfo"""
    def __init__(self) -> None: ...
    IntMap: typing.Any
    DblMap: typing.Any
    StrMap: typing.Any
    ObjMap: typing.Any
    DateMap: typing.Any

class ChangeManagement:
    """Stub for Teamcenter.Services.Internal.Strong.Changemanagement._2015_03.ChangeManagement.ChangeManagement"""
    def __init__(self) -> None: ...
    def ConnectChangeNoticeToContext(self, Input: typing.Sequence[typing.Any]) -> typing.Any: ...
    def CreateOrUpdatePreviousEffectivity(self, Input: typing.Sequence[typing.Any]) -> typing.Any: ...
    def DisconnectChangeNoticeFromContext(self, Input: typing.Sequence[typing.Any]) -> typing.Any: ...
    def RemovePrevEffectivityFromChgNotice(self, Input: typing.Sequence[typing.Any]) -> typing.Any: ...
    def UpdateChangeNoticeRelations(self, Inputs: typing.Sequence[typing.Any]) -> typing.Any: ...

class ConnectChangeNoticeToContextInElem:
    """Stub for Teamcenter.Services.Internal.Strong.Changemanagement._2015_03.ChangeManagement.ConnectChangeNoticeToContextInElem"""
    def __init__(self) -> None: ...
    ChangeObject: typing.Any
    Context: typing.Any
    ShareMode: str
    Info: typing.Any

class ConnectChangeNoticeToContextResp:
    """Stub for Teamcenter.Services.Internal.Strong.Changemanagement._2015_03.ChangeManagement.ConnectChangeNoticeToContextResp"""
    def __init__(self) -> None: ...
    Info: typing.Any
    ServiceData: typing.Any

class CreateOrUpdatePreviousEffResp:
    """Stub for Teamcenter.Services.Internal.Strong.Changemanagement._2015_03.ChangeManagement.CreateOrUpdatePreviousEffResp"""
    def __init__(self) -> None: ...
    Info: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class PreviousEffectivity:
    """Stub for Teamcenter.Services.Internal.Strong.Changemanagement._2015_03.ChangeManagement.PreviousEffectivity"""
    def __init__(self) -> None: ...
    ChangeObject: typing.Any
    EndItem: typing.Any
    Unit: str
    Date: typing.Any
    Info: typing.Any

class UpdateChangeNoticeRelationsIn:
    """Stub for Teamcenter.Services.Internal.Strong.Changemanagement._2015_03.ChangeManagement.UpdateChangeNoticeRelationsIn"""
    def __init__(self) -> None: ...
    SelectedLines: typing.Sequence[typing.Any]
    Action: str
    IsRecursive: bool
    AdditionalInfo: typing.Any

class UpdateChangeNoticeRelationsResp:
    """Stub for Teamcenter.Services.Internal.Strong.Changemanagement._2015_03.ChangeManagement.UpdateChangeNoticeRelationsResp"""
    def __init__(self) -> None: ...
    Info: typing.Sequence[typing.Any]
    ServiceData: typing.Any

__all__ = [
    'AdditionalInfo',
    'ChangeManagement',
    'ConnectChangeNoticeToContextInElem',
    'ConnectChangeNoticeToContextResp',
    'CreateOrUpdatePreviousEffResp',
    'PreviousEffectivity',
    'UpdateChangeNoticeRelationsIn',
    'UpdateChangeNoticeRelationsResp',
]
