# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class MapSrchCriteriaToLinesInputInfo:
    """Stub for Teamcenter.Services.Internal.Strong.Manufacturing._2012_09.StructureSearch.MapSrchCriteriaToLinesInputInfo"""
    def __init__(self) -> None: ...
    Criteria: typing.Any
    Contexts: typing.Sequence[typing.Any]

class MapSrchCriteriaToLinesResponse:
    """Stub for Teamcenter.Services.Internal.Strong.Manufacturing._2012_09.StructureSearch.MapSrchCriteriaToLinesResponse"""
    def __init__(self) -> None: ...
    Output: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class SaveOGLinesInSrchCriteriaInputInfo:
    """Stub for Teamcenter.Services.Internal.Strong.Manufacturing._2012_09.StructureSearch.SaveOGLinesInSrchCriteriaInputInfo"""
    def __init__(self) -> None: ...
    SelectedNodes: typing.Sequence[typing.Any]
    UnselectedNodes: typing.Sequence[typing.Any]
    ScopeAttribute: bool

class SaveOGLinesInSrchCriteriaResponse:
    """Stub for Teamcenter.Services.Internal.Strong.Manufacturing._2012_09.StructureSearch.SaveOGLinesInSrchCriteriaResponse"""
    def __init__(self) -> None: ...
    SrchCriterias: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class SrchCriteriaToLinesMap:
    """Stub for Teamcenter.Services.Internal.Strong.Manufacturing._2012_09.StructureSearch.SrchCriteriaToLinesMap"""
    def __init__(self) -> None: ...
    SrchCriteria: typing.Any
    SelectedNodes: typing.Sequence[typing.Any]
    UnselectedNodes: typing.Sequence[typing.Any]

class StructureSearch:
    """Stub for Teamcenter.Services.Internal.Strong.Manufacturing._2012_09.StructureSearch.StructureSearch"""
    def __init__(self) -> None: ...
    def MapSrchCriteriaToLines(self, Inputs: typing.Sequence[typing.Any]) -> typing.Any: ...
    def SaveOGLinesInSrchCriteria(self, Inputs: typing.Sequence[typing.Any]) -> typing.Any: ...

__all__ = [
    'MapSrchCriteriaToLinesInputInfo',
    'MapSrchCriteriaToLinesResponse',
    'SaveOGLinesInSrchCriteriaInputInfo',
    'SaveOGLinesInSrchCriteriaResponse',
    'SrchCriteriaToLinesMap',
    'StructureSearch',
]
