# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class CommitFeatData:
    """Stub for Teamcenter.Services.Internal.Strong.Productionmanagement._2020_12.EngineeringDataLoad.CommitFeatData"""
    def __init__(self) -> None: ...
    CommitFeatureLabel: str
    CommitFeatureID: str
    IsCommitted: bool
    Message: str

class EngineeringDataLoad:
    """Stub for Teamcenter.Services.Internal.Strong.Productionmanagement._2020_12.EngineeringDataLoad.EngineeringDataLoad"""
    def __init__(self) -> None: ...
    def UpdateEngineeringWorkbook(self, RoutineID: str, RoutineRev: str, FeatureRows: typing.Sequence[typing.Any]) -> typing.Any: ...

class ExcelFeatData:
    """Stub for Teamcenter.Services.Internal.Strong.Productionmanagement._2020_12.EngineeringDataLoad.ExcelFeatData"""
    def __init__(self) -> None: ...
    ExcelFeatureName: str
    ExcelFeatureID: str

class UpdateEngineeringWorkbookResponse:
    """Stub for Teamcenter.Services.Internal.Strong.Productionmanagement._2020_12.EngineeringDataLoad.UpdateEngineeringWorkbookResponse"""
    def __init__(self) -> None: ...
    CommittedFeatures: typing.Sequence[typing.Any]
    ExcelFeatures: typing.Sequence[typing.Any]
    ServiceData: typing.Any

__all__ = [
    'CommitFeatData',
    'EngineeringDataLoad',
    'ExcelFeatData',
    'UpdateEngineeringWorkbookResponse',
]
