# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class AlignmentExtensions:
    """Stub for Serilog.Sinks.SystemConsole.Rendering.AlignmentExtensions"""
    def __init__(self) -> None: ...
    @classmethod
    def Widen(cls, alignment: typing.Any, amount: int) -> typing.Any: ...

class Casing:
    """Stub for Serilog.Sinks.SystemConsole.Rendering.Casing"""
    def __init__(self) -> None: ...
    @classmethod
    def Format(cls, value: str, format: str | None = None) -> str: ...

class Padding:
    """Stub for Serilog.Sinks.SystemConsole.Rendering.Padding"""
    def __init__(self) -> None: ...
    @classmethod
    def Apply(cls, output: typing.Any, value: str, alignment: typing.Optional[typing.Any]) -> None: ...

class ThemedMessageTemplateRenderer:
    """Stub for Serilog.Sinks.SystemConsole.Rendering.ThemedMessageTemplateRenderer"""
    def __init__(self, theme: typing.Any, valueFormatter: typing.Any, isLiteral: bool) -> None: ...
    def Render(self, template: typing.Any, properties: typing.Any, output: typing.Any) -> int: ...

__all__ = [
    'AlignmentExtensions',
    'Casing',
    'Padding',
    'ThemedMessageTemplateRenderer',
]
