# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class BoundingBoxInfo:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2010_09.StructureSearch.BoundingBoxInfo"""
    def __init__(self) -> None: ...
    Xmin: float
    Ymin: float
    Zmin: float
    Xmax: float
    Ymax: float
    Zmax: float

class BoundingBoxInfoResponse:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2010_09.StructureSearch.BoundingBoxInfoResponse"""
    def __init__(self) -> None: ...
    BoundingBoxes: typing.Any
    ServiceData: typing.Any

class SearchExpressionSet:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2010_09.StructureSearch.SearchExpressionSet"""
    def __init__(self) -> None: ...
    ItemAndRevisionAttributeExpressions: typing.Sequence[typing.Any]
    OccurrenceNoteExpressions: typing.Sequence[typing.Any]
    FormAttributeExpressions: typing.Sequence[typing.Any]
    ProximitySearchExpressions: typing.Sequence[typing.Any]
    BoxZoneExpressions: typing.Sequence[typing.Any]
    PlaneZoneExpressions: typing.Sequence[typing.Any]
    SavedQueryExpressions: typing.Sequence[typing.Any]
    InClassQueryExpressions: typing.Sequence[typing.Any]
    SizeSearchExpression: typing.Any
    DoTrushapeRefinement: bool
    ReturnScopedSubTreesHit: bool
    ExecuteVOOFilter: bool
    ExecuteRemoteSearch: bool
    RemoteSiteID: str

class StructureSearch:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2010_09.StructureSearch.StructureSearch"""
    def __init__(self) -> None: ...
    def GetAssemblyBoundingBox(self, Items: typing.Sequence[typing.Any]) -> typing.Any: ...
    def IsSpatialDataAvailable(self, TopItem: typing.Any) -> bool: ...
    def StartSearch(self, Scope: typing.Any, SearchExpression: typing.Any) -> typing.Any: ...

__all__ = [
    'BoundingBoxInfo',
    'BoundingBoxInfoResponse',
    'SearchExpressionSet',
    'StructureSearch',
]
