# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class SimStructureManagement:
    """Stub for Cae0.Services.Strong.Simproc._2017_05.SimStructureManagement.SimStructureManagement"""
    def __init__(self) -> None: ...
    def ExecuteStructureMap(self, StructureMapInputs: typing.Any) -> typing.Any: ...

class StructureMapExecutionResponse:
    """Stub for Cae0.Services.Strong.Simproc._2017_05.SimStructureManagement.StructureMapExecutionResponse"""
    def __init__(self) -> None: ...
    ServiceData: typing.Any
    ActivityLog: str

class StructureMapInputsInfo:
    """Stub for Cae0.Services.Strong.Simproc._2017_05.SimStructureManagement.StructureMapInputsInfo"""
    def __init__(self) -> None: ...
    RootIR: typing.Any
    SnapshotFolder: typing.Any
    RevRule: typing.Any
    VariantRule: typing.Any
    Domain: str
    StructureMapIR: typing.Any
    InputOptions: typing.Any

__all__ = [
    'SimStructureManagement',
    'StructureMapExecutionResponse',
    'StructureMapInputsInfo',
]
