# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class BomLineInfo:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2012_02.IncrementalChange.BomLineInfo"""
    def __init__(self) -> None: ...
    SourceLine: typing.Any
    TargetLine: typing.Any

class IncrementalChange:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2012_02.IncrementalChange.IncrementalChange"""
    def __init__(self) -> None: ...
    def CarryOver(self, BomLineInfos: typing.Sequence[typing.Any]) -> typing.Any: ...

__all__ = [
    'BomLineInfo',
    'IncrementalChange',
]
