# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class FilterExpression:
    """Stub for Lbr0.Services.Strong.Librarymanagement._2014_10.LibrarySearch.FilterExpression"""
    def __init__(self) -> None: ...
    PropertyName: str
    Expression: str

class LibrarySearch:
    """Stub for Lbr0.Services.Strong.Librarymanagement._2014_10.LibrarySearch.LibrarySearch"""
    def __init__(self) -> None: ...
    def DiscardSearchResults(self, ResultSet: str) -> typing.Any: ...
    def SearchLibraries(self, Contexts: typing.Sequence[typing.Any], SearchExprs: typing.Sequence[typing.Any]) -> typing.Any: ...
    def SearchLibraryElements(self, SearchInput: typing.Any) -> typing.Any: ...

class SearchLibraryElementsCriteria:
    """Stub for Lbr0.Services.Strong.Librarymanagement._2014_10.LibrarySearch.SearchLibraryElementsCriteria"""
    def __init__(self) -> None: ...
    Specification: typing.Any
    SourceMember: typing.Any
    SourceMemberExprs: typing.Sequence[typing.Any]
    SearchExpressions: typing.Sequence[typing.Any]

class SearchLibraryElementsIn:
    """Stub for Lbr0.Services.Strong.Librarymanagement._2014_10.LibrarySearch.SearchLibraryElementsIn"""
    def __init__(self) -> None: ...
    ClientID: str
    NodeToSearchIn: typing.Any
    ConfigContext: typing.Any
    SearchOptions: typing.Any
    SearchCriteria: typing.Any

class SearchLibraryElementsOptions:
    """Stub for Lbr0.Services.Strong.Librarymanagement._2014_10.LibrarySearch.SearchLibraryElementsOptions"""
    def __init__(self) -> None: ...
    SortOrder: typing.Sequence[typing.Any]
    Options: int
    Start: int
    LoadCount: int

class SearchResponse:
    """Stub for Lbr0.Services.Strong.Librarymanagement._2014_10.LibrarySearch.SearchResponse"""
    def __init__(self) -> None: ...
    NumTotalResults: int
    Objects: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class SortOrder:
    """Stub for Lbr0.Services.Strong.Librarymanagement._2014_10.LibrarySearch.SortOrder"""
    def __init__(self) -> None: ...
    AscendingSort: bool
    SortProperty: str

__all__ = [
    'FilterExpression',
    'LibrarySearch',
    'SearchLibraryElementsCriteria',
    'SearchLibraryElementsIn',
    'SearchLibraryElementsOptions',
    'SearchResponse',
    'SortOrder',
]
