# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class ImportUnmanagedDataResponse:
    """Stub for Teamcenter.Services.Internal.Strong.Requirementsmanagement._2009_10.RequirementsManagement.ImportUnmanagedDataResponse"""
    def __init__(self) -> None: ...
    TransientFileReadTickets: typing.Sequence[str]
    ModifiedObjectList: typing.Sequence[str]
    ServiceData: typing.Any

class RelativeStructureChildInfo:
    """Stub for Teamcenter.Services.Internal.Strong.Requirementsmanagement._2009_10.RequirementsManagement.RelativeStructureChildInfo"""
    def __init__(self) -> None: ...
    ChildID: str
    ObjectType: str
    RefDesignator: str
    ChildAttrList: typing.Any
    AttrListRel: typing.Any
    RelationType: str
    ActionRequired: str
    StructModification: typing.Any
    ChildChangeType: typing.Any

class RelativeStructureParentInfo:
    """Stub for Teamcenter.Services.Internal.Strong.Requirementsmanagement._2009_10.RequirementsManagement.RelativeStructureParentInfo"""
    def __init__(self) -> None: ...
    ParentID: str
    ObjectType: str
    ParentAttrList: typing.Any
    ChildInfo: typing.Sequence[typing.Any]
    ActionRequired: str
    ParentChangeType: typing.Any

class RequirementsManagement:
    """Stub for Teamcenter.Services.Internal.Strong.Requirementsmanagement._2009_10.RequirementsManagement.RequirementsManagement"""
    def __init__(self) -> None: ...
    def ImportUnmanagedData(self, RelativeStructParent: typing.Sequence[typing.Any], ImportOptions: typing.Sequence[str]) -> typing.Any: ...

__all__ = [
    'ImportUnmanagedDataResponse',
    'RelativeStructureChildInfo',
    'RelativeStructureParentInfo',
    'RequirementsManagement',
]
