# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class ExportConfigRuntimeOverrideInfo:
    """Stub for Cae0.Services.Strong.Simproc._2014_12.SimulationToolLaunch.ExportConfigRuntimeOverrideInfo"""
    def __init__(self) -> None: ...
    PlmxmlExportFileName: str
    RuntimeArguments: typing.Sequence[str]

class ImportConfigRuntimeOverrideInfo:
    """Stub for Cae0.Services.Strong.Simproc._2014_12.SimulationToolLaunch.ImportConfigRuntimeOverrideInfo"""
    def __init__(self) -> None: ...
    ItemCreationSetting: str
    DatasetCreationSetting: str
    OutputNamePatterns: typing.Sequence[str]

class LaunchInputInfo:
    """Stub for Cae0.Services.Strong.Simproc._2014_12.SimulationToolLaunch.LaunchInputInfo"""
    def __init__(self) -> None: ...
    InputObject: typing.Any
    ConfigurationContext: typing.Any

class SimulationToolLaunch:
    """Stub for Cae0.Services.Strong.Simproc._2014_12.SimulationToolLaunch.SimulationToolLaunch"""
    def __init__(self) -> None: ...
    def ExecuteSimulationToolLaunch(self, SimulationTool: typing.Any, InputObjects: typing.Sequence[typing.Any], WorkingDirectory: str, LaunchType: str, ExportRuntimeConfiguration: typing.Any, ImportRuntimeConfiguration: typing.Any) -> typing.Any: ...

__all__ = [
    'ExportConfigRuntimeOverrideInfo',
    'ImportConfigRuntimeOverrideInfo',
    'LaunchInputInfo',
    'SimulationToolLaunch',
]
