# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class ACFavoriteInfo:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2014_06.StructureVerification.ACFavoriteInfo"""
    def __init__(self) -> None: ...
    AccSettings: typing.Any
    ServiceData: typing.Any

class ACFavoritesInput:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2014_06.StructureVerification.ACFavoritesInput"""
    def __init__(self) -> None: ...
    AccSettings: typing.Any
    Name: str
    Description: str
    DatasetUID: str
    Action: str

class ACFavoritesResponse:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2014_06.StructureVerification.ACFavoritesResponse"""
    def __init__(self) -> None: ...
    Dataset: typing.Any
    ServiceData: typing.Any

class StructureVerification:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2014_06.StructureVerification.StructureVerification"""
    def __init__(self) -> None: ...
    def GetACFavorite(self, DatasetUID: str) -> typing.Any: ...
    def ManageACFavorites(self, Input: typing.Any) -> typing.Any: ...

__all__ = [
    'ACFavoriteInfo',
    'ACFavoritesInput',
    'ACFavoritesResponse',
    'StructureVerification',
]
