# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class BulkSearchOutput:
    """Stub for Sc0.Services.Internal.Strong.Suppliercollaboration._2014_12.SupplierCollaboration.BulkSearchOutput"""
    def __init__(self) -> None: ...
    InputExchangeLine: typing.Any
    SearchContactInfo: typing.Any

class BulkSearchResponse:
    """Stub for Sc0.Services.Internal.Strong.Suppliercollaboration._2014_12.SupplierCollaboration.BulkSearchResponse"""
    def __init__(self) -> None: ...
    OutputData: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class CompanyContactInfo:
    """Stub for Sc0.Services.Internal.Strong.Suppliercollaboration._2014_12.SupplierCollaboration.CompanyContactInfo"""
    def __init__(self) -> None: ...
    AttrValueMap: typing.Any

class SearchContactsIn:
    """Stub for Sc0.Services.Internal.Strong.Suppliercollaboration._2014_12.SupplierCollaboration.SearchContactsIn"""
    def __init__(self) -> None: ...
    LineObject: typing.Any
    IsProgramExchangeSearch: bool
    SearchCriterion: typing.Any

class SearchContactsOut:
    """Stub for Sc0.Services.Internal.Strong.Suppliercollaboration._2014_12.SupplierCollaboration.SearchContactsOut"""
    def __init__(self) -> None: ...
    ServiceData: typing.Any
    CompanyContactInfos: typing.Any

class SplitInfoInput:
    """Stub for Sc0.Services.Internal.Strong.Suppliercollaboration._2014_12.SupplierCollaboration.SplitInfoInput"""
    def __init__(self) -> None: ...
    Mode: int
    TraverseBOM: bool
    RevisionRule: str
    Level: int
    PropNames: typing.Sequence[str]
    SplitInfos: typing.Any

class SplitInfoResponse:
    """Stub for Sc0.Services.Internal.Strong.Suppliercollaboration._2014_12.SupplierCollaboration.SplitInfoResponse"""
    def __init__(self) -> None: ...
    ServiceData: typing.Any
    SplitInfos: typing.Any

class SplitValues:
    """Stub for Sc0.Services.Internal.Strong.Suppliercollaboration._2014_12.SupplierCollaboration.SplitValues"""
    def __init__(self) -> None: ...
    PropValues: typing.Sequence[str]

class SupplierCollaboration:
    """Stub for Sc0.Services.Internal.Strong.Suppliercollaboration._2014_12.SupplierCollaboration.SupplierCollaboration"""
    def __init__(self) -> None: ...
    def SearchContactInBulk(self, SearchCompanyContactsInBulk: typing.Sequence[typing.Any]) -> typing.Any: ...
    def SearchContacts(self, SearchCompanyContactsIn: typing.Any) -> typing.Any: ...
    def SetSplitInfo(self, RetrieveOrUpdateSplitInfoIn: typing.Any) -> typing.Any: ...

__all__ = [
    'BulkSearchOutput',
    'BulkSearchResponse',
    'CompanyContactInfo',
    'SearchContactsIn',
    'SearchContactsOut',
    'SplitInfoInput',
    'SplitInfoResponse',
    'SplitValues',
    'SupplierCollaboration',
]
