# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class AnalyticsMultipleResourceAssignmentStacks:
    """Stub for Teamcenter.Services.Strong.Projectmanagement._2014_10.ScheduleManagement.AnalyticsMultipleResourceAssignmentStacks"""
    def __init__(self) -> None: ...
    StacksVector: typing.Sequence[typing.Any]

class AnalyticsResourceAssignmentDayStack:
    """Stub for Teamcenter.Services.Strong.Projectmanagement._2014_10.ScheduleManagement.AnalyticsResourceAssignmentDayStack"""
    def __init__(self) -> None: ...
    NumElements: int
    Stack: typing.Sequence[typing.Any]

class AnalyticsResourceAssignmentSingleTask:
    """Stub for Teamcenter.Services.Strong.Projectmanagement._2014_10.ScheduleManagement.AnalyticsResourceAssignmentSingleTask"""
    def __init__(self) -> None: ...
    Day: typing.Any
    UserUid: str
    CalUid: str
    SchUid: str
    SchTaskUid: str
    SchName: str
    SchStartDate: typing.Any
    SchEndDate: typing.Any
    TaskName: str
    TaskstartDate: typing.Any
    TaskEndDate: typing.Any
    TaskMinutes: float
    ResourceMinutes: float
    StackBase: float
    TaskMinutesOverLoad: float
    UserData: str

class AnalyticsResourceAssignmentStacks:
    """Stub for Teamcenter.Services.Strong.Projectmanagement._2014_10.ScheduleManagement.AnalyticsResourceAssignmentStacks"""
    def __init__(self) -> None: ...
    UserName: str
    NumDays: int
    Stacks: typing.Sequence[typing.Any]

class CostDetailContainer:
    """Stub for Teamcenter.Services.Strong.Projectmanagement._2014_10.ScheduleManagement.CostDetailContainer"""
    def __init__(self) -> None: ...
    TotalEstimatedMinutes: int
    TotalAccruedMinutes: int
    TotalEstimatedCost: float
    TotalAccruedCost: float
    BillCode: str
    BillSubCode: str
    BillingType: str
    BillRate: typing.Any
    Currency: str
    Task: typing.Any
    Numchildren: int
    FixedCostData: typing.Sequence[typing.Any]
    TaskCostDetails: typing.Sequence[typing.Any]

class CostDetailResponse:
    """Stub for Teamcenter.Services.Strong.Projectmanagement._2014_10.ScheduleManagement.CostDetailResponse"""
    def __init__(self) -> None: ...
    CostDetails: typing.Sequence[typing.Any]
    CostServiceData: typing.Any

class DetachScheduleContainer:
    """Stub for Teamcenter.Services.Strong.Projectmanagement._2014_10.ScheduleManagement.DetachScheduleContainer"""
    def __init__(self) -> None: ...
    SubSchedule: typing.Any
    MasterSchedule: typing.Any

class EVMDataRequest:
    """Stub for Teamcenter.Services.Strong.Projectmanagement._2014_10.ScheduleManagement.EVMDataRequest"""
    def __init__(self) -> None: ...
    TaskVector: typing.Sequence[typing.Any]
    CalcBasisSelected: bool
    CalcWorkComplete: bool
    SelectedLabel: bool

class EVMResultsContainer:
    """Stub for Teamcenter.Services.Strong.Projectmanagement._2014_10.ScheduleManagement.EVMResultsContainer"""
    def __init__(self) -> None: ...
    Task: typing.Any
    EvmResults: typing.Any

class EVMResultsResponse:
    """Stub for Teamcenter.Services.Strong.Projectmanagement._2014_10.ScheduleManagement.EVMResultsResponse"""
    def __init__(self) -> None: ...
    EvmData: typing.Any
    EvmServiceData: typing.Any

class FailedObjectContainer:
    """Stub for Teamcenter.Services.Strong.Projectmanagement._2014_10.ScheduleManagement.FailedObjectContainer"""
    def __init__(self) -> None: ...
    Tasks: typing.Sequence[typing.Any]
    ErrorMsgs: typing.Sequence[str]
    ServiceData: typing.Any

class InsertScheduleContainer:
    """Stub for Teamcenter.Services.Strong.Projectmanagement._2014_10.ScheduleManagement.InsertScheduleContainer"""
    def __init__(self) -> None: ...
    SubSchedule: typing.Any
    MasterSchedule: typing.Any
    MasterScheduleTask: typing.Any
    AdjustMasterDates: bool

class LoadResourceGraphContainer:
    """Stub for Teamcenter.Services.Strong.Projectmanagement._2014_10.ScheduleManagement.LoadResourceGraphContainer"""
    def __init__(self) -> None: ...
    Resources: typing.Sequence[typing.Any]
    StartDate: typing.Any
    EndDate: typing.Any

class ScheduleManagement:
    """Stub for Teamcenter.Services.Strong.Projectmanagement._2014_10.ScheduleManagement.ScheduleManagement"""
    def __init__(self) -> None: ...
    def CreatePhaseGateTask(self, TaskInputContainer: typing.Any) -> typing.Any: ...
    def DetachSchedule(self, DetachScheduleContainer: typing.Sequence[typing.Any]) -> typing.Any: ...
    def GetCostRollupData(self, CostDetailRequest: typing.Sequence[typing.Any]) -> typing.Any: ...
    def GetEVMResults(self, InputEVMData: typing.Any) -> typing.Any: ...
    def GetResourceGraphData(self, LoadResourceGraphContainer: typing.Any) -> typing.Any: ...
    def InsertSchedule(self, InsertScheduleContainer: typing.Sequence[typing.Any]) -> typing.Any: ...
    def ReplaceAssignment(self, Schedule: typing.Any, NewAssignments: typing.Sequence[typing.Any], AssignmentDeletes: typing.Sequence[typing.Any]) -> typing.Any: ...
    def VerifySchedule(self, Schedule: typing.Any) -> typing.Any: ...

__all__ = [
    'AnalyticsMultipleResourceAssignmentStacks',
    'AnalyticsResourceAssignmentDayStack',
    'AnalyticsResourceAssignmentSingleTask',
    'AnalyticsResourceAssignmentStacks',
    'CostDetailContainer',
    'CostDetailResponse',
    'DetachScheduleContainer',
    'EVMDataRequest',
    'EVMResultsContainer',
    'EVMResultsResponse',
    'FailedObjectContainer',
    'InsertScheduleContainer',
    'LoadResourceGraphContainer',
    'ScheduleManagement',
]
