# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class DataManagement:
    """Stub for Awb0.Services.Internal.Strong.Activeworkspacebom._2019_12.DataManagement.DataManagement"""
    def __init__(self) -> None: ...
    def GetViewModelForCreate(self, Input: typing.Any) -> typing.Any: ...

class GetViewModelForCreateInfo:
    """Stub for Awb0.Services.Internal.Strong.Activeworkspacebom._2019_12.DataManagement.GetViewModelForCreateInfo"""
    def __init__(self) -> None: ...
    BusinessObjectType: str
    PropertyNames: typing.Sequence[str]
    Parent: typing.Any

class GetViewModelForCreateResponse:
    """Stub for Awb0.Services.Internal.Strong.Activeworkspacebom._2019_12.DataManagement.GetViewModelForCreateResponse"""
    def __init__(self) -> None: ...
    ViewModelCreateInObjsJsonStrings: typing.Sequence[str]
    ColumnPropToCreateInPropMap: typing.Any
    CreateHtmlProviders: typing.Sequence[str]
    ServiceData: typing.Any

__all__ = [
    'DataManagement',
    'GetViewModelForCreateInfo',
    'GetViewModelForCreateResponse',
]
