# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class DataManagement:
    """Stub for Teamcenter.Services.Internal.Strong.Manufacturing._2020_04.DataManagement.DataManagement"""
    def __init__(self) -> None: ...
    def GetProductScopeForProcess(self, ProcessLine: typing.Sequence[typing.Any]) -> typing.Any: ...

class GetProductScopeForProcessResponse:
    """Stub for Teamcenter.Services.Internal.Strong.Manufacturing._2020_04.DataManagement.GetProductScopeForProcessResponse"""
    def __init__(self) -> None: ...
    ScopedProductBOMLine: typing.Sequence[typing.Any]
    ServiceData: typing.Any

__all__ = [
    'DataManagement',
    'GetProductScopeForProcessResponse',
]
