# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class ContextManagement:
    """Stub for Teamcenter.Services.Strong.Rdv._2012_09.ContextManagement.ContextManagement"""
    def __init__(self) -> None: ...
    def CreateFormAttrSearchCriteria(self, Inputs: typing.Sequence[typing.Any]) -> typing.Any: ...
    def CreateSearchCriteriaScope(self, Inputs: typing.Sequence[typing.Any]) -> typing.Any: ...
    def CreateSearchSCO(self, Inputs: typing.Sequence[typing.Any]) -> typing.Any: ...
    def GetICSClassNames(self, SearchCriteriaInClass: typing.Sequence[typing.Any]) -> typing.Any: ...
    def UpdateSearchSCO(self, Inputs: typing.Sequence[typing.Any]) -> typing.Any: ...

class CreateFormAttrSearchCriteriaInputInfo:
    """Stub for Teamcenter.Services.Strong.Rdv._2012_09.ContextManagement.CreateFormAttrSearchCriteriaInputInfo"""
    def __init__(self) -> None: ...
    Relationtype: str
    ParentType: bool
    FormType: str
    LogicalOpr: str
    PropertyName: str
    MathOpr: str
    PropertyType: str
    Values: typing.Sequence[str]

class CreateFormAttrSearchCriteriaResponse:
    """Stub for Teamcenter.Services.Strong.Rdv._2012_09.ContextManagement.CreateFormAttrSearchCriteriaResponse"""
    def __init__(self) -> None: ...
    FormAttrSchCriteria: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class CreateSearchCriteriaScopeInfo:
    """Stub for Teamcenter.Services.Strong.Rdv._2012_09.ContextManagement.CreateSearchCriteriaScopeInfo"""
    def __init__(self) -> None: ...
    Nodes: typing.Sequence[typing.Any]
    Collections: typing.Sequence[typing.Any]

class CreateSearchCriteriaScpResponse:
    """Stub for Teamcenter.Services.Strong.Rdv._2012_09.ContextManagement.CreateSearchCriteriaScpResponse"""
    def __init__(self) -> None: ...
    SearchCriteriaScpObjects: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class CreateSearchSCOInputInfo:
    """Stub for Teamcenter.Services.Strong.Rdv._2012_09.ContextManagement.CreateSearchSCOInputInfo"""
    def __init__(self) -> None: ...
    ScoInputInfo: typing.Any
    ResultStored: bool
    IsShared: bool
    Nodes: typing.Sequence[typing.Any]

class CreateSearchSCOResponse:
    """Stub for Teamcenter.Services.Strong.Rdv._2012_09.ContextManagement.CreateSearchSCOResponse"""
    def __init__(self) -> None: ...
    SrchSCO: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class GetICSClassNamesResponse:
    """Stub for Teamcenter.Services.Strong.Rdv._2012_09.ContextManagement.GetICSClassNamesResponse"""
    def __init__(self) -> None: ...
    IcsClassNames: typing.Sequence[str]
    ServiceData: typing.Any

class UpdateSearchSCOInputInfo:
    """Stub for Teamcenter.Services.Strong.Rdv._2012_09.ContextManagement.UpdateSearchSCOInputInfo"""
    def __init__(self) -> None: ...
    SrchSCO: typing.Any
    ScoInfo: typing.Any
    ResultStored: bool
    Nodes: typing.Sequence[typing.Any]

class UpdateSearchSCOResponse:
    """Stub for Teamcenter.Services.Strong.Rdv._2012_09.ContextManagement.UpdateSearchSCOResponse"""
    def __init__(self) -> None: ...
    SrchSCO: typing.Sequence[typing.Any]
    ServiceData: typing.Any

__all__ = [
    'ContextManagement',
    'CreateFormAttrSearchCriteriaInputInfo',
    'CreateFormAttrSearchCriteriaResponse',
    'CreateSearchCriteriaScopeInfo',
    'CreateSearchCriteriaScpResponse',
    'CreateSearchSCOInputInfo',
    'CreateSearchSCOResponse',
    'GetICSClassNamesResponse',
    'UpdateSearchSCOInputInfo',
    'UpdateSearchSCOResponse',
]
