# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class CreateOrUpdateProductSubsetsInfo:
    """Stub for Mpr0.Services.Strong.Process._2017_11.ProductSubset.CreateOrUpdateProductSubsetsInfo"""
    def __init__(self) -> None: ...
    Context: typing.Any
    SourceSubset: typing.Any
    RevisionRule: typing.Any
    IntentOptions: typing.Sequence[typing.Any]

class ProductSubset:
    """Stub for Mpr0.Services.Strong.Process._2017_11.ProductSubset.ProductSubset"""
    def __init__(self) -> None: ...
    def CreateOrUpdateProductSubsets(self, Input: typing.Sequence[typing.Any]) -> typing.Any: ...

__all__ = [
    'CreateOrUpdateProductSubsetsInfo',
    'ProductSubset',
]
