# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class TaskSearchFilter:
    """Stub for Awp0.Services.Internal.Strong.Aws2._2013_12.Workflow.TaskSearchFilter"""
    def __init__(self) -> None: ...
    SearchFilterType: str
    StringValue: str
    StartDateValue: typing.Any
    EndDateValue: typing.Any
    StartNumericValue: float
    EndNumericValue: float
    Count: int
    Selected: bool
    StartEndRange: str

class TaskSearchFilterField:
    """Stub for Awp0.Services.Internal.Strong.Aws2._2013_12.Workflow.TaskSearchFilterField"""
    def __init__(self) -> None: ...
    InternalName: str
    DisplayName: str
    DefaultFilterValueDisplayCount: int

class TaskSearchInput:
    """Stub for Awp0.Services.Internal.Strong.Aws2._2013_12.Workflow.TaskSearchInput"""
    def __init__(self) -> None: ...
    StartIndex: int
    MaxToReturn: int
    MaxToLoad: int
    SearchFilterMap: typing.Any
    SearchSortCriteria: str
    SearchSortDirection: str
    SearchFilterFieldSortType: str
    SearchInboxContentType: str

class TaskSearchResponse:
    """Stub for Awp0.Services.Internal.Strong.Aws2._2013_12.Workflow.TaskSearchResponse"""
    def __init__(self) -> None: ...
    SearchResults: typing.Sequence[typing.Any]
    TotalFound: int
    TotalLoaded: int
    SearchFilterMap: typing.Any
    SearchFilterCategories: typing.Sequence[typing.Any]
    DefaultFilterFieldDisplayCount: int
    ServiceData: typing.Any

class Workflow:
    """Stub for Awp0.Services.Internal.Strong.Aws2._2013_12.Workflow.Workflow"""
    def __init__(self) -> None: ...
    def PerformTaskSearch(self, SearchInput: typing.Any) -> typing.Any: ...

__all__ = [
    'TaskSearchFilter',
    'TaskSearchFilterField',
    'TaskSearchInput',
    'TaskSearchResponse',
    'Workflow',
]
