# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class ApplyReleaseStatusToLinesInputData:
    """Stub for Mei0.Services.Strong.Mesinteg._2014_06.Release.ApplyReleaseStatusToLinesInputData"""
    def __init__(self) -> None: ...
    Roots: typing.Sequence[typing.Any]
    ReleaseStatus: str
    UnitEffectivityInfo: typing.Any
    IsRecursive: bool

class Release:
    """Stub for Mei0.Services.Strong.Mesinteg._2014_06.Release.Release"""
    def __init__(self) -> None: ...
    def ApplyReleaseStatusToLines(self, Input: typing.Sequence[typing.Any]) -> typing.Any: ...

class UnitEffectivityInfo:
    """Stub for Mei0.Services.Strong.Mesinteg._2014_06.Release.UnitEffectivityInfo"""
    def __init__(self) -> None: ...
    EndItem: typing.Any
    EndItemRev: typing.Any
    Effectivity: str

__all__ = [
    'ApplyReleaseStatusToLinesInputData',
    'Release',
    'UnitEffectivityInfo',
]
