# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class AvailableColumn:
    """Stub for Awp0.Services.Internal.Strong.Aws2._2023_12.Finder.AvailableColumn"""
    def __init__(self) -> None: ...
    IsDuplicate: bool
    PropertyName: str
    PropertyDescription: str
    AssociatedTypeName: str
    AssociatedTypeDisplayName: str
    DisplayName: str
    DataType: str
    Uid: str

class Finder:
    """Stub for Awp0.Services.Internal.Strong.Aws2._2023_12.Finder.Finder"""
    def __init__(self) -> None: ...
    def GetAvailableColumns(self, ObjectTypes: typing.Sequence[str], ProviderName: str, SearchCriteria: typing.Any, ColumnsToExclude: typing.Sequence[str], FilterString: str, StartIndex: int, MaxToReturn: int) -> typing.Any: ...

class GetAvailableColumnsResponse:
    """Stub for Awp0.Services.Internal.Strong.Aws2._2023_12.Finder.GetAvailableColumnsResponse"""
    def __init__(self) -> None: ...
    TotalFound: int
    EndIndex: int
    AvailableColumns: typing.Sequence[typing.Any]
    ServiceData: typing.Any

__all__ = [
    'AvailableColumn',
    'Finder',
    'GetAvailableColumnsResponse',
]
