# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class AttachmentChangeResponse:
    """Stub for Teamcenter.Services.Internal.Strong.Structuremanagement._2011_06.IncrementalChange.AttachmentChangeResponse"""
    def __init__(self) -> None: ...
    Response: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class AttachmentICEInfo:
    """Stub for Teamcenter.Services.Internal.Strong.Structuremanagement._2011_06.IncrementalChange.AttachmentICEInfo"""
    def __init__(self) -> None: ...
    Line: typing.Any
    AbsOccRootLine: str
    ChildEditIces: typing.Sequence[typing.Any]
    RelationIces: typing.Sequence[typing.Any]

class AttachmentInfo:
    """Stub for Teamcenter.Services.Internal.Strong.Structuremanagement._2011_06.IncrementalChange.AttachmentInfo"""
    def __init__(self) -> None: ...
    ListOfAttachments: typing.Sequence[typing.Any]

class AttributeChangeResponse:
    """Stub for Teamcenter.Services.Internal.Strong.Structuremanagement._2011_06.IncrementalChange.AttributeChangeResponse"""
    def __init__(self) -> None: ...
    Response: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class AttributeICEInfo:
    """Stub for Teamcenter.Services.Internal.Strong.Structuremanagement._2011_06.IncrementalChange.AttributeICEInfo"""
    def __init__(self) -> None: ...
    BaseICEInfo: typing.Any
    Attributes: typing.Any

class AttributeInfoOutput:
    """Stub for Teamcenter.Services.Internal.Strong.Structuremanagement._2011_06.IncrementalChange.AttributeInfoOutput"""
    def __init__(self) -> None: ...
    AttributeInfo: typing.Sequence[typing.Any]

class BaseICEInfo:
    """Stub for Teamcenter.Services.Internal.Strong.Structuremanagement._2011_06.IncrementalChange.BaseICEInfo"""
    def __init__(self) -> None: ...
    TypeOfIce: int
    HowConfigured: str
    IcRev: typing.Any
    Ice: typing.Any

class ICEAttributes:
    """Stub for Teamcenter.Services.Internal.Strong.Structuremanagement._2011_06.IncrementalChange.ICEAttributes"""
    def __init__(self) -> None: ...
    AttributeName: str
    AttributeValue: str
    AbsOccRootLine: str
    BomViewRevision: typing.Any

class IncrementalChange:
    """Stub for Teamcenter.Services.Internal.Strong.Structuremanagement._2011_06.IncrementalChange.IncrementalChange"""
    def __init__(self) -> None: ...
    def GetAttachmentChanges(self, Attachmentlines: typing.Sequence[typing.Any], FRefresh: bool) -> typing.Any: ...
    def GetAttributeChanges(self, AttributeOccLines: typing.Sequence[typing.Any], FRefresh: bool) -> typing.Any: ...
    def GetParentAndChildComponents(self, IcRevision: typing.Any) -> typing.Any: ...
    def GetPredecessorChanges(self, PredecessorLines: typing.Sequence[typing.Any], FRefresh: bool) -> typing.Any: ...
    def GetStructureChanges(self, Bomlines: typing.Sequence[typing.Any], FRefresh: bool) -> typing.Any: ...

class ParentAndChildComponentsResponse:
    """Stub for Teamcenter.Services.Internal.Strong.Structuremanagement._2011_06.IncrementalChange.ParentAndChildComponentsResponse"""
    def __init__(self) -> None: ...
    ParentAndChildInfoResponse: typing.Any
    ServiceData: typing.Any

class ParentAndChildInfos:
    """Stub for Teamcenter.Services.Internal.Strong.Structuremanagement._2011_06.IncrementalChange.ParentAndChildInfos"""
    def __init__(self) -> None: ...
    ParentChildInfos: typing.Sequence[typing.Any]

class ParentChildInfo:
    """Stub for Teamcenter.Services.Internal.Strong.Structuremanagement._2011_06.IncrementalChange.ParentChildInfo"""
    def __init__(self) -> None: ...
    Context: str
    Parent: typing.Any
    Child: typing.Any
    Ice: typing.Any

class PredecessorChangeInfo:
    """Stub for Teamcenter.Services.Internal.Strong.Structuremanagement._2011_06.IncrementalChange.PredecessorChangeInfo"""
    def __init__(self) -> None: ...
    BaseICEInfo: typing.Sequence[typing.Any]
    ListOfPredecessors: typing.Sequence[typing.Any]

class PredecessorChangeResponse:
    """Stub for Teamcenter.Services.Internal.Strong.Structuremanagement._2011_06.IncrementalChange.PredecessorChangeResponse"""
    def __init__(self) -> None: ...
    ServiceData: typing.Any
    Response: typing.Sequence[typing.Any]

class PredecessorICEInfo:
    """Stub for Teamcenter.Services.Internal.Strong.Structuremanagement._2011_06.IncrementalChange.PredecessorICEInfo"""
    def __init__(self) -> None: ...
    PredecessorName: str
    SequenceNumber: str

class StructureChangeResponse:
    """Stub for Teamcenter.Services.Internal.Strong.Structuremanagement._2011_06.IncrementalChange.StructureChangeResponse"""
    def __init__(self) -> None: ...
    Response: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class StructureChangesOutput:
    """Stub for Teamcenter.Services.Internal.Strong.Structuremanagement._2011_06.IncrementalChange.StructureChangesOutput"""
    def __init__(self) -> None: ...
    BaseInfo: typing.Sequence[typing.Any]

__all__ = [
    'AttachmentChangeResponse',
    'AttachmentICEInfo',
    'AttachmentInfo',
    'AttributeChangeResponse',
    'AttributeICEInfo',
    'AttributeInfoOutput',
    'BaseICEInfo',
    'ICEAttributes',
    'IncrementalChange',
    'ParentAndChildComponentsResponse',
    'ParentAndChildInfos',
    'ParentChildInfo',
    'PredecessorChangeInfo',
    'PredecessorChangeResponse',
    'PredecessorICEInfo',
    'StructureChangeResponse',
    'StructureChangesOutput',
]
