# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class ByteArrayScalarConversionPolicy:
    """Stub for Serilog.Policies.ByteArrayScalarConversionPolicy"""
    def __init__(self) -> None: ...
    def TryConvertToScalar(self, value: typing.Any, result: typing.Any) -> bool: ...

class DelegateDestructuringPolicy:
    """Stub for Serilog.Policies.DelegateDestructuringPolicy"""
    def __init__(self) -> None: ...
    def TryDestructure(self, value: typing.Any, propertyValueFactory: typing.Any, result: typing.Any) -> bool: ...

class EnumScalarConversionPolicy:
    """Stub for Serilog.Policies.EnumScalarConversionPolicy"""
    def __init__(self) -> None: ...
    def TryConvertToScalar(self, value: typing.Any, result: typing.Any) -> bool: ...

class ProjectedDestructuringPolicy:
    """Stub for Serilog.Policies.ProjectedDestructuringPolicy"""
    def __init__(self, canApply: typing.Any, projection: typing.Any) -> None: ...
    def TryDestructure(self, value: typing.Any, propertyValueFactory: typing.Any, result: typing.Any) -> bool: ...

class ReflectionTypesScalarDestructuringPolicy:
    """Stub for Serilog.Policies.ReflectionTypesScalarDestructuringPolicy"""
    def __init__(self) -> None: ...
    def TryDestructure(self, value: typing.Any, propertyValueFactory: typing.Any, result: typing.Any) -> bool: ...

class SimpleScalarConversionPolicy:
    """Stub for Serilog.Policies.SimpleScalarConversionPolicy"""
    def __init__(self, scalarTypes: typing.Iterable[typing.Any]) -> None: ...
    def TryConvertToScalar(self, value: typing.Any, result: typing.Any) -> bool: ...

__all__ = [
    'ByteArrayScalarConversionPolicy',
    'DelegateDestructuringPolicy',
    'EnumScalarConversionPolicy',
    'ProjectedDestructuringPolicy',
    'ReflectionTypesScalarDestructuringPolicy',
    'SimpleScalarConversionPolicy',
]
