# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class ClosureRuleVariableInfo:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2011_06.Structure.ClosureRuleVariableInfo"""
    def __init__(self) -> None: ...
    Name: str
    Value: str

class DuplicateIdStructure:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2011_06.Structure.DuplicateIdStructure"""
    def __init__(self) -> None: ...
    OldItemComponent: typing.Any
    NewItemInfo: typing.Any

class DuplicateInputInfo3:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2011_06.Structure.DuplicateInputInfo3"""
    def __init__(self) -> None: ...
    TopLine: typing.Any
    ClonedIdStructure: typing.Sequence[typing.Any]
    DefaultName: typing.Any
    RenameCadFile: bool
    Options: typing.Sequence[str]
    Projects: typing.Any
    DuplicateOption: int

class ExpandOrUpdateDuplicateItemsOutput2:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2011_06.Structure.ExpandOrUpdateDuplicateItemsOutput2"""
    def __init__(self) -> None: ...
    Object: typing.Any
    RelatedObjInfo: typing.Sequence[typing.Any]

class ExpandOrUpdateDuplicateItemsResponse2:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2011_06.Structure.ExpandOrUpdateDuplicateItemsResponse2"""
    def __init__(self) -> None: ...
    Outputs: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class RelatedItemsInfo2:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2011_06.Structure.RelatedItemsInfo2"""
    def __init__(self) -> None: ...
    RelObj: typing.Any
    RelationshipName: str
    DepType: str
    Mandatory: bool

class Structure:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2011_06.Structure.Structure"""
    def __init__(self) -> None: ...
    def Duplicate3(self, Inputs: typing.Sequence[typing.Any]) -> typing.Any: ...
    def ExpandOrUpdateDuplicateItems3(self, OpInput: typing.Sequence[typing.Any], SelectionOption: int) -> typing.Any: ...
    def SetClosureRuleVariablesAndValues(self, Window: typing.Any, ClosureRuleName: str, ClosureRuleVariableInfos: typing.Sequence[typing.Any]) -> typing.Any: ...
    def UnloadBelow(self, Bomlines: typing.Sequence[typing.Any], UnloadType: str) -> typing.Any: ...
    def ValidateStructureItemIds3(self, Inputs: typing.Sequence[typing.Any]) -> typing.Any: ...

class ValidateStructureItemIdsInfo3:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2011_06.Structure.ValidateStructureItemIdsInfo3"""
    def __init__(self) -> None: ...
    TopLine: typing.Any
    ClonedIdStructure: typing.Sequence[typing.Any]
    DefaultName: typing.Any
    Options: typing.Sequence[str]
    Projects: typing.Any

class ValidateStructureItemIdsResponse3:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2011_06.Structure.ValidateStructureItemIdsResponse3"""
    def __init__(self) -> None: ...
    ClonedIdStructure: typing.Sequence[typing.Any]
    ServiceData: typing.Any

__all__ = [
    'ClosureRuleVariableInfo',
    'DuplicateIdStructure',
    'DuplicateInputInfo3',
    'ExpandOrUpdateDuplicateItemsOutput2',
    'ExpandOrUpdateDuplicateItemsResponse2',
    'RelatedItemsInfo2',
    'Structure',
    'ValidateStructureItemIdsInfo3',
    'ValidateStructureItemIdsResponse3',
]
