# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class Reservation:
    """Stub for Teamcenter.Services.Strong.Core._2008_06.Reservation.Reservation"""
    def __init__(self) -> None: ...
    def TransferCheckout(self, Objects: typing.Sequence[typing.Any], UserId: typing.Any) -> typing.Any: ...

__all__ = [
    'Reservation',
]
