# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
from teamcenter.awp0.services.strong.aws2 import RequirementsManagementService

class RequirementsManagementRestBindingStub(RequirementsManagementService):
    """Stub for Awp0.Services.Strong.Aws2.RequirementsManagementRestBindingStub"""
    def __init__(self, connection: typing.Any) -> None: ...
    def CreateTracelinks(self, Input: typing.Sequence[typing.Any]) -> typing.Any: ...

class RequirementsManagementService:
    """Stub for Awp0.Services.Strong.Aws2.RequirementsManagementService"""
    def __init__(self) -> None: ...
    def CreateTracelinks(self, Input: typing.Sequence[typing.Any]) -> typing.Any: ...
    @classmethod
    def getService(cls, connection: typing.Any) -> typing.Any: ...

__all__ = [
    'RequirementsManagementRestBindingStub',
    'RequirementsManagementService',
    '_2018_12',
]
