# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class DiagramLegendData1:
    """Stub for Ase0.Services.Strong.Activeworkspacesyseng._2015_10.DiagramManagement.DiagramLegendData1"""
    def __init__(self) -> None: ...
    Name: str
    DisplayName: str
    DefaultLayout: str
    GroupData: typing.Sequence[typing.Any]

class DiagramLegendResponse1:
    """Stub for Ase0.Services.Strong.Activeworkspacesyseng._2015_10.DiagramManagement.DiagramLegendResponse1"""
    def __init__(self) -> None: ...
    LegendData: typing.Sequence[typing.Any]
    PresentationRulesXML: str
    PresentationStylesXML: str
    ServiceData: typing.Any

class DiagramManagement:
    """Stub for Ase0.Services.Strong.Activeworkspacesyseng._2015_10.DiagramManagement.DiagramManagement"""
    def __init__(self) -> None: ...
    def GetDiagramLegend4(self, ViewName: str) -> typing.Any: ...

class FilterData1:
    """Stub for Ase0.Services.Strong.Activeworkspacesyseng._2015_10.DiagramManagement.FilterData1"""
    def __init__(self) -> None: ...
    Name: str
    DisplayName: str
    Types: typing.Sequence[typing.Any]
    Color: typing.Any
    GroupType: str
    ScopeFilter: str

__all__ = [
    'DiagramLegendData1',
    'DiagramLegendResponse1',
    'DiagramManagement',
    'FilterData1',
]
