# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class AddPartSolutionInputInfo:
    """Stub for Teamcenter.Services.Internal.Strong.Rdv._2010_04.VariantManagement.AddPartSolutionInputInfo"""
    def __init__(self) -> None: ...
    Values: typing.Sequence[typing.Any]
    Component: typing.Any
    AbeLine: typing.Any
    ProdRevs: typing.Sequence[typing.Any]
    AbeApn: typing.Any
    MetaExpr: typing.Sequence[typing.Any]
    Validate: bool
    Quantity: int

class AddPartSolutionOutputInfo:
    """Stub for Teamcenter.Services.Internal.Strong.Rdv._2010_04.VariantManagement.AddPartSolutionOutputInfo"""
    def __init__(self) -> None: ...
    Component: typing.Any
    PartSolutionAPN: typing.Any

class AddPartSolutionResponse:
    """Stub for Teamcenter.Services.Internal.Strong.Rdv._2010_04.VariantManagement.AddPartSolutionResponse"""
    def __init__(self) -> None: ...
    Output: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class BackgroundOccurrences:
    """Stub for Teamcenter.Services.Internal.Strong.Rdv._2010_04.VariantManagement.BackgroundOccurrences"""
    def __init__(self) -> None: ...
    NumProcessedRequests: int
    NumSuggestedRequests: int
    NodeanswerLists: typing.Sequence[typing.Any]

class BackgroundOccurrencesResponse:
    """Stub for Teamcenter.Services.Internal.Strong.Rdv._2010_04.VariantManagement.BackgroundOccurrencesResponse"""
    def __init__(self) -> None: ...
    Output: typing.Any
    Servicedata: typing.Any

class NodeAnswer:
    """Stub for Teamcenter.Services.Internal.Strong.Rdv._2010_04.VariantManagement.NodeAnswer"""
    def __init__(self) -> None: ...
    BackgroundNodeList: typing.Sequence[str]

class OccNotesAttributes:
    """Stub for Teamcenter.Services.Internal.Strong.Rdv._2010_04.VariantManagement.OccNotesAttributes"""
    def __init__(self) -> None: ...
    NoteType: str
    NoteText: str

class ProximityTarget:
    """Stub for Teamcenter.Services.Internal.Strong.Rdv._2010_04.VariantManagement.ProximityTarget"""
    def __init__(self) -> None: ...
    ProxtargetId: str
    Proximity: float
    Target: str

class ReplacePartSolutionInputInfo:
    """Stub for Teamcenter.Services.Internal.Strong.Rdv._2010_04.VariantManagement.ReplacePartSolutionInputInfo"""
    def __init__(self) -> None: ...
    Values: typing.Sequence[typing.Any]
    Component: typing.Any
    BomLine: typing.Any
    AbeAPN: typing.Any
    MetaExpr: typing.Sequence[typing.Any]
    Validate: bool
    SplitAndClone: bool
    CarrySubstitutes: bool
    Quantity: int

class ReplacePartSolutionOutputInfo:
    """Stub for Teamcenter.Services.Internal.Strong.Rdv._2010_04.VariantManagement.ReplacePartSolutionOutputInfo"""
    def __init__(self) -> None: ...
    BomLine: typing.Any
    Component: typing.Any

class ReplacePartSolutionResponse:
    """Stub for Teamcenter.Services.Internal.Strong.Rdv._2010_04.VariantManagement.ReplacePartSolutionResponse"""
    def __init__(self) -> None: ...
    Output: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class TargetOccurrences:
    """Stub for Teamcenter.Services.Internal.Strong.Rdv._2010_04.VariantManagement.TargetOccurrences"""
    def __init__(self) -> None: ...
    ClientId: str
    Topitemrev: str
    Revrulename: str
    DisttargetsList: typing.Sequence[typing.Any]

class VariantManagement:
    """Stub for Teamcenter.Services.Internal.Strong.Rdv._2010_04.VariantManagement.VariantManagement"""
    def __init__(self) -> None: ...
    def AddPartToProduct(self, Inputs: typing.Sequence[typing.Any]) -> typing.Any: ...
    def GetValidBackgroundOverlays(self, AbortOnError: bool, Questions: typing.Sequence[typing.Any]) -> typing.Any: ...
    def ReplacePartInProduct(self, Inputs: typing.Sequence[typing.Any]) -> typing.Any: ...

__all__ = [
    'AddPartSolutionInputInfo',
    'AddPartSolutionOutputInfo',
    'AddPartSolutionResponse',
    'BackgroundOccurrences',
    'BackgroundOccurrencesResponse',
    'NodeAnswer',
    'OccNotesAttributes',
    'ProximityTarget',
    'ReplacePartSolutionInputInfo',
    'ReplacePartSolutionOutputInfo',
    'ReplacePartSolutionResponse',
    'TargetOccurrences',
    'VariantManagement',
]
