# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class ChildrenInputData:
    """Stub for Teamcenter.Services.Strong.Core._2014_10.DataManagement.ChildrenInputData"""
    def __init__(self) -> None: ...
    ClientId: str
    ParentObj: typing.Any
    ChildrenObj: typing.Sequence[typing.Any]
    PropertyName: str

class DataManagement:
    """Stub for Teamcenter.Services.Strong.Core._2014_10.DataManagement.DataManagement"""
    def __init__(self) -> None: ...
    def AddChildren(self, InputData: typing.Sequence[typing.Any]) -> typing.Any: ...
    def GenerateIdsUsingIDGenerationRules(self, GenerateIdsInputs: typing.Sequence[typing.Any]) -> typing.Any: ...
    def GetDeepCopyData(self, DeepCopyDataInput: typing.Sequence[typing.Any]) -> typing.Any: ...
    def GetPasteRelations2(self, Inputs: typing.Sequence[typing.Any]) -> typing.Any: ...
    def PruneNamedReferences(self, NamedReferences: typing.Sequence[typing.Any]) -> typing.Any: ...
    def RemoveChildren(self, InputData: typing.Sequence[typing.Any]) -> typing.Any: ...
    def SaveAsObjectsAndRelate(self, IVecSoaSavAsIn: typing.Sequence[typing.Any], IVecSoaRelteInfoIn: typing.Sequence[typing.Any]) -> typing.Any: ...

class DeepCopyData:
    """Stub for Teamcenter.Services.Strong.Core._2014_10.DataManagement.DeepCopyData"""
    def __init__(self) -> None: ...
    AttachedObject: typing.Any
    PropertyValuesMap: typing.Any
    OperationInputTypeName: str
    ChildDeepCopyData: typing.Sequence[typing.Any]
    OperationInputs: typing.Any

class DeepCopyDataInput:
    """Stub for Teamcenter.Services.Strong.Core._2014_10.DataManagement.DeepCopyDataInput"""
    def __init__(self) -> None: ...
    Operation: str
    BusinessObject: typing.Any

class GenerateIdInput:
    """Stub for Teamcenter.Services.Strong.Core._2014_10.DataManagement.GenerateIdInput"""
    def __init__(self) -> None: ...
    CreateInput: typing.Any
    PropertyName: str
    Quantity: int

class GenerateIdResponseStruct:
    """Stub for Teamcenter.Services.Strong.Core._2014_10.DataManagement.GenerateIdResponseStruct"""
    def __init__(self) -> None: ...
    GeneratedIDs: typing.Sequence[str]

class GenerateIdsResponse:
    """Stub for Teamcenter.Services.Strong.Core._2014_10.DataManagement.GenerateIdsResponse"""
    def __init__(self) -> None: ...
    GenerateIdsOutput: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class GetDeepCopyDataResponse:
    """Stub for Teamcenter.Services.Strong.Core._2014_10.DataManagement.GetDeepCopyDataResponse"""
    def __init__(self) -> None: ...
    DeepCopyInfoMap: typing.Any
    ServiceData: typing.Any

class GetPasteRelationsOutput2:
    """Stub for Teamcenter.Services.Strong.Core._2014_10.DataManagement.GetPasteRelationsOutput2"""
    def __init__(self) -> None: ...
    ClientId: str
    PasteRelInfo: typing.Sequence[typing.Any]
    IndexOfPreferred: int

class GetPasteRelationsResponse2:
    """Stub for Teamcenter.Services.Strong.Core._2014_10.DataManagement.GetPasteRelationsResponse2"""
    def __init__(self) -> None: ...
    Outputs: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class PasteRelationsInfo2:
    """Stub for Teamcenter.Services.Strong.Core._2014_10.DataManagement.PasteRelationsInfo2"""
    def __init__(self) -> None: ...
    PastRelName: str
    PastRelDisplayName: str
    IsExpandable: bool

class SaveAsIn:
    """Stub for Teamcenter.Services.Strong.Core._2014_10.DataManagement.SaveAsIn"""
    def __init__(self) -> None: ...
    TargetObject: typing.Any
    InputPropValues: typing.Any
    DeepCopyDatas: typing.Sequence[typing.Any]

__all__ = [
    'ChildrenInputData',
    'DataManagement',
    'DeepCopyData',
    'DeepCopyDataInput',
    'GenerateIdInput',
    'GenerateIdResponseStruct',
    'GenerateIdsResponse',
    'GetDeepCopyDataResponse',
    'GetPasteRelationsOutput2',
    'GetPasteRelationsResponse2',
    'PasteRelationsInfo2',
    'SaveAsIn',
]
