# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class AttrInfoForSpec:
    """Stub for Teamcenter.Services.Strong.Productionmanagement._2014_12.EngineeringDataQuery.AttrInfoForSpec"""
    def __init__(self) -> None: ...
    FtrAttrCode: str
    LowerSpecLimit: float
    UpperSpecLimit: float
    Target: float

class EngineeringDataQuery:
    """Stub for Teamcenter.Services.Strong.Productionmanagement._2014_12.EngineeringDataQuery.EngineeringDataQuery"""
    def __init__(self) -> None: ...
    def GetFeatureAttributesForSpec(self, InputToGetFtrAtt: typing.Sequence[typing.Any]) -> typing.Any: ...
    def GetSpecSheetNames(self, PlantAndRtnInfo: typing.Sequence[typing.Any]) -> typing.Any: ...
    def GetSpecificationLimits(self, SpecLimitInput: typing.Sequence[typing.Any]) -> typing.Any: ...

class FtrAttrbs:
    """Stub for Teamcenter.Services.Strong.Productionmanagement._2014_12.EngineeringDataQuery.FtrAttrbs"""
    def __init__(self) -> None: ...
    FeatureId: str
    FeatureName: str
    FeatureAttribCode: typing.Sequence[str]

class FtrInfoForSpec:
    """Stub for Teamcenter.Services.Strong.Productionmanagement._2014_12.EngineeringDataQuery.FtrInfoForSpec"""
    def __init__(self) -> None: ...
    FeatureId: str
    FeatureName: str
    SpecInfo: typing.Sequence[typing.Any]

class GetFtrAttResponse:
    """Stub for Teamcenter.Services.Strong.Productionmanagement._2014_12.EngineeringDataQuery.GetFtrAttResponse"""
    def __init__(self) -> None: ...
    FeatureInfo: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class GetSpecLimitInfoResponse:
    """Stub for Teamcenter.Services.Strong.Productionmanagement._2014_12.EngineeringDataQuery.GetSpecLimitInfoResponse"""
    def __init__(self) -> None: ...
    SpecLimits: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class GetSpecLimitInput:
    """Stub for Teamcenter.Services.Strong.Productionmanagement._2014_12.EngineeringDataQuery.GetSpecLimitInput"""
    def __init__(self) -> None: ...
    PlantId: str
    RoutineId: str
    RoutineRev: str
    SpecSheetName: str
    FtrAttribCodeInfo: typing.Sequence[typing.Any]
    LastNumOfJobs: int
    FromDate: str
    ToDate: str

class InputToGetAttrCode:
    """Stub for Teamcenter.Services.Strong.Productionmanagement._2014_12.EngineeringDataQuery.InputToGetAttrCode"""
    def __init__(self) -> None: ...
    PlantId: str
    RoutineId: str
    RoutineRev: str
    SpecSheetName: str
    ConsiderActiveSignificance: bool

class InputToGetSpecSheetNames:
    """Stub for Teamcenter.Services.Strong.Productionmanagement._2014_12.EngineeringDataQuery.InputToGetSpecSheetNames"""
    def __init__(self) -> None: ...
    PlantId: str
    RoutineId: str
    RoutineRev: str

class MainSpecLimitOutPut:
    """Stub for Teamcenter.Services.Strong.Productionmanagement._2014_12.EngineeringDataQuery.MainSpecLimitOutPut"""
    def __init__(self) -> None: ...
    PlantId: str
    RoutineId: str
    SpecLimitOutPut: typing.Sequence[typing.Any]

class SpecInfo:
    """Stub for Teamcenter.Services.Strong.Productionmanagement._2014_12.EngineeringDataQuery.SpecInfo"""
    def __init__(self) -> None: ...
    SpecSheetName: str

class SpecInfoForQuery:
    """Stub for Teamcenter.Services.Strong.Productionmanagement._2014_12.EngineeringDataQuery.SpecInfoForQuery"""
    def __init__(self) -> None: ...
    ActualValue: float
    BuildLabel: str
    EventDateTime: str

class SpecInfoResponse:
    """Stub for Teamcenter.Services.Strong.Productionmanagement._2014_12.EngineeringDataQuery.SpecInfoResponse"""
    def __init__(self) -> None: ...
    SpecInfoRes: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class SpecLimitInfo:
    """Stub for Teamcenter.Services.Strong.Productionmanagement._2014_12.EngineeringDataQuery.SpecLimitInfo"""
    def __init__(self) -> None: ...
    FeatureId: str
    FeatureName: str
    FeatureAttribCode: str
    LowerSpecLimit: float
    Target: float
    UpperSpecLimit: float
    AttributeInfo: typing.Sequence[typing.Any]

__all__ = [
    'AttrInfoForSpec',
    'EngineeringDataQuery',
    'FtrAttrbs',
    'FtrInfoForSpec',
    'GetFtrAttResponse',
    'GetSpecLimitInfoResponse',
    'GetSpecLimitInput',
    'InputToGetAttrCode',
    'InputToGetSpecSheetNames',
    'MainSpecLimitOutPut',
    'SpecInfo',
    'SpecInfoForQuery',
    'SpecInfoResponse',
    'SpecLimitInfo',
]
