# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class StructureManagement:
    """Stub for Teamcenter.Services.Internal.Strong.Cae._2012_09.StructureManagement.StructureManagement"""
    def __init__(self) -> None: ...
    def CreateNewModelByDM(self, ProductBOMLine: typing.Any, ModelParentBOMLine: typing.Any, ModelExistingBOMLine: typing.Any, Domain: str) -> typing.Any: ...
    def ExecuteMarkUpToDate(self, InputItemRevList: typing.Sequence[typing.Any]) -> typing.Any: ...
    def UpdateModelAttsByDM(self, ProductBOMLine: typing.Any, ModelParentBOMLine: typing.Any, ModelRevTag: typing.Any, ModelExistingBOMLine: typing.Any, Domain: str, BomlineAttribsOnly: bool, DoRevise: bool) -> typing.Any: ...

__all__ = [
    'StructureManagement',
]
