# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class BusinessObjectQueryClause:
    """Stub for Teamcenter.Services.Strong.Query._2010_09.SavedQuery.BusinessObjectQueryClause"""
    def __init__(self) -> None: ...
    PropName: str
    PropValue: str
    MathOperator: str
    LogicOperator: str

class BusinessObjectQueryInput:
    """Stub for Teamcenter.Services.Strong.Query._2010_09.SavedQuery.BusinessObjectQueryInput"""
    def __init__(self) -> None: ...
    TypeName: str
    Clauses: typing.Sequence[typing.Any]
    MaxNumToReturn: int
    RequestId: str
    ClientId: str

class SavedQuery:
    """Stub for Teamcenter.Services.Strong.Query._2010_09.SavedQuery.SavedQuery"""
    def __init__(self) -> None: ...
    def ExecuteBusinessObjectQueries(self, Inputs: typing.Sequence[typing.Any]) -> typing.Any: ...

__all__ = [
    'BusinessObjectQueryClause',
    'BusinessObjectQueryInput',
    'SavedQuery',
]
