# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class CrfReports:
    """Stub for Teamcenter.Services.Strong.Reports._2015_10.CrfReports.CrfReports"""
    def __init__(self) -> None: ...
    def GetOfficeStylesheets(self, ReportDefinition: typing.Any) -> typing.Any: ...

class GetOfficeStyleSheetResponse:
    """Stub for Teamcenter.Services.Strong.Reports._2015_10.CrfReports.GetOfficeStyleSheetResponse"""
    def __init__(self) -> None: ...
    Officetemplates: typing.Sequence[str]
    ServiceData: typing.Any

__all__ = [
    'CrfReports',
    'GetOfficeStyleSheetResponse',
]
