# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class AdditionalFieldQueryCriteria:
    """Stub for Cba1.Services.Internal.Strong.Cbaext._2016_03.QueryManagement.AdditionalFieldQueryCriteria"""
    def __init__(self) -> None: ...
    FieldQueryCriteriaList: typing.Sequence[typing.Any]

class BOMSolveInputInfo:
    """Stub for Cba1.Services.Internal.Strong.Cbaext._2016_03.QueryManagement.BOMSolveInputInfo"""
    def __init__(self) -> None: ...
    Type: str
    ProductType: str
    VehicleLine: str
    ModelExpression: str
    ModelOption: str
    RevisionRule: str

class FieldQueryCriteria:
    """Stub for Cba1.Services.Internal.Strong.Cbaext._2016_03.QueryManagement.FieldQueryCriteria"""
    def __init__(self) -> None: ...
    FieldName: str
    TableName: str
    AdditionalCriteriaField: typing.Any

class QueryManagement:
    """Stub for Cba1.Services.Internal.Strong.Cbaext._2016_03.QueryManagement.QueryManagement"""
    def __init__(self) -> None: ...
    def ExecuteSpatialSearch(self, Input: typing.Sequence[typing.Any]) -> typing.Any: ...

class SpatialSearchInput:
    """Stub for Cba1.Services.Internal.Strong.Cbaext._2016_03.QueryManagement.SpatialSearchInput"""
    def __init__(self) -> None: ...
    ClientID: str
    TargetDetails: typing.Any
    SpatialSearchCriterias: typing.Any
    AdditionalFieldQueryCriteria: typing.Any

class SpatialSearchTargetInfo:
    """Stub for Cba1.Services.Internal.Strong.Cbaext._2016_03.QueryManagement.SpatialSearchTargetInfo"""
    def __init__(self) -> None: ...
    TargetLOUs: typing.Any
    TargetSolutions: typing.Any
    TargetLOUSolutionsMap: typing.Any
    TableSpecificQuery: typing.Sequence[typing.Any]
    BomSolveInput: typing.Any
    CommonCriteria: typing.Any
    Reconcile: bool
    IsVisRequested: bool
    RootContext: str

__all__ = [
    'AdditionalFieldQueryCriteria',
    'BOMSolveInputInfo',
    'FieldQueryCriteria',
    'QueryManagement',
    'SpatialSearchInput',
    'SpatialSearchTargetInfo',
]
