# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class ExportFilesOfflineFileInfo:
    """Stub for Teamcenter.Services.Strong.Globalmultisite._2021_06.ImportExport.ExportFilesOfflineFileInfo"""
    def __init__(self) -> None: ...
    Properties: typing.Any

class ExportFilesOfflineResponse:
    """Stub for Teamcenter.Services.Strong.Globalmultisite._2021_06.ImportExport.ExportFilesOfflineResponse"""
    def __init__(self) -> None: ...
    Files: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class ImportExport:
    """Stub for Teamcenter.Services.Strong.Globalmultisite._2021_06.ImportExport.ImportExport"""
    def __init__(self) -> None: ...
    def ExportFilesOffline(self, Uids: typing.Sequence[str], Options: typing.Sequence[typing.Any]) -> typing.Any: ...
    def ImportNXFiles(self, Inputs: typing.Sequence[typing.Any]) -> typing.Any: ...

class ImportNXFileInfo:
    """Stub for Teamcenter.Services.Strong.Globalmultisite._2021_06.ImportExport.ImportNXFileInfo"""
    def __init__(self) -> None: ...
    DatasetUid: str
    Ticket: str

__all__ = [
    'ExportFilesOfflineFileInfo',
    'ExportFilesOfflineResponse',
    'ImportExport',
    'ImportNXFileInfo',
]
