# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class EffectivityRange:
    """Stub for Awb0.Services.Internal.Strong.Activeworkspacebom._2018_12.OccurrenceManagement.EffectivityRange"""
    def __init__(self) -> None: ...
    UnitIn: int
    UnitOut: int
    DateIn: typing.Any
    DateOut: typing.Any
    IntentFormula: str

class OccurrenceConfigInput:
    """Stub for Awb0.Services.Internal.Strong.Activeworkspacebom._2018_12.OccurrenceManagement.OccurrenceConfigInput"""
    def __init__(self) -> None: ...
    ProductContext: typing.Any
    RevisionRule: typing.Any
    EffectivityDate: typing.Any
    UnitNo: int
    EndItem: typing.Any
    VariantRules: typing.Sequence[typing.Any]
    SvrOwningProduct: typing.Any
    EffectivityRanges: typing.Sequence[typing.Any]
    OccurrenceScheme: typing.Any
    SourceContext: typing.Any
    ChangeContext: typing.Any

class OccurrenceManagement:
    """Stub for Awb0.Services.Internal.Strong.Activeworkspacebom._2018_12.OccurrenceManagement.OccurrenceManagement"""
    def __init__(self) -> None: ...
    def GetOccurrences(self, InputData: typing.Any) -> typing.Any: ...

class OccurrencesData:
    """Stub for Awb0.Services.Internal.Strong.Activeworkspacebom._2018_12.OccurrenceManagement.OccurrencesData"""
    def __init__(self) -> None: ...
    Product: typing.Any
    ParentElement: str
    FocusOccurrenceInput: typing.Any
    Config: typing.Any
    Cursor: typing.Any
    Filter: typing.Any
    SortCriteria: typing.Any
    RequestPref: typing.Any

class OccurrencesResp:
    """Stub for Awb0.Services.Internal.Strong.Activeworkspacebom._2018_12.OccurrenceManagement.OccurrencesResp"""
    def __init__(self) -> None: ...
    RootProductContext: typing.Any
    ParentProductContext: typing.Any
    ParentOccurrence: typing.Any
    FocusProductContext: typing.Any
    FocusChildOccurrence: typing.Any
    Occurrences: typing.Sequence[typing.Any]
    Cursor: typing.Any
    UserWorkingContextInfo: typing.Any
    Filter: typing.Any
    ElementToPCIMap: typing.Any
    SourceContextToInfoMap: typing.Any
    ParentChildrenInfos: typing.Sequence[typing.Any]
    RequestPref: typing.Any
    ServiceData: typing.Any

class SourceContextInfo:
    """Stub for Awb0.Services.Internal.Strong.Activeworkspacebom._2018_12.OccurrenceManagement.SourceContextInfo"""
    def __init__(self) -> None: ...
    RevRuleName: str
    VarRuleName: typing.Sequence[str]
    EffectivityFormula: str

__all__ = [
    'EffectivityRange',
    'OccurrenceConfigInput',
    'OccurrenceManagement',
    'OccurrencesData',
    'OccurrencesResp',
    'SourceContextInfo',
]
