# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class ApplyBOMVariantRulesResponse2:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2019_06.VariantManagement.ApplyBOMVariantRulesResponse2"""
    def __init__(self) -> None: ...
    Rules: typing.Sequence[typing.Any]
    ServiceData: typing.Any
    Window: typing.Any

class BOMVariantRuleContents2:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2019_06.VariantManagement.BOMVariantRuleContents2"""
    def __init__(self) -> None: ...
    VariantRule: typing.Any
    Svr: typing.Any
    IsSVRModified: bool
    BomVariantOptionValueEntry: typing.Sequence[typing.Any]
    IsConstraintsEvaluated: bool

class BOMVariantRuleOutput2:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2019_06.VariantManagement.BOMVariantRuleOutput2"""
    def __init__(self) -> None: ...
    Window: typing.Any
    Rules: typing.Sequence[typing.Any]
    ClientId: str

class BOMVariantRulesResponse2:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2019_06.VariantManagement.BOMVariantRulesResponse2"""
    def __init__(self) -> None: ...
    VariantRuleData: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class SetBOMVariantRuleData2:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2019_06.VariantManagement.SetBOMVariantRuleData2"""
    def __init__(self) -> None: ...
    Window: typing.Any
    Rules: typing.Sequence[typing.Any]
    ClientId: str

class SetBOMVariantRulesResponse2:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2019_06.VariantManagement.SetBOMVariantRulesResponse2"""
    def __init__(self) -> None: ...
    VariantRuleData: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class VariantManagement:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2019_06.VariantManagement.VariantManagement"""
    def __init__(self) -> None: ...
    def ApplyBOMVariantRules2(self, Window: typing.Any, Rules: typing.Sequence[typing.Any]) -> typing.Any: ...
    def GetBOMVariantRules2(self, VariantRuleInput: typing.Sequence[typing.Any]) -> typing.Any: ...
    def SetBOMVariantRules2(self, SetBOMVariantRuleInput: typing.Sequence[typing.Any]) -> typing.Any: ...

__all__ = [
    'ApplyBOMVariantRulesResponse2',
    'BOMVariantRuleContents2',
    'BOMVariantRuleOutput2',
    'BOMVariantRulesResponse2',
    'SetBOMVariantRuleData2',
    'SetBOMVariantRulesResponse2',
    'VariantManagement',
]
