# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class DataManagement:
    """Stub for Mdl0.Services.Strong.Modelcore._2011_06.DataManagement.DataManagement"""
    def __init__(self) -> None: ...
    def DeleteModelContent(self, ObjectsToDelete: typing.Sequence[typing.Any]) -> typing.Any: ...
    def ReviseObjects(self, SaveAsIn: typing.Sequence[typing.Any]) -> typing.Any: ...

class DeepCopyData:
    """Stub for Mdl0.Services.Strong.Modelcore._2011_06.DataManagement.DeepCopyData"""
    def __init__(self) -> None: ...
    AttachedObject: typing.Any
    PropertyName: str
    PropertyType: str
    CopyAction: str
    IsTargetPrimary: bool
    IsRequired: bool
    SaveAsInput: typing.Any
    ChildDeepCopyData: typing.Sequence[typing.Any]
    CopyRelations: bool

class DeleteModelContentResponse:
    """Stub for Mdl0.Services.Strong.Modelcore._2011_06.DataManagement.DeleteModelContentResponse"""
    def __init__(self) -> None: ...
    UndeletedObjects: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class SaveAsIn:
    """Stub for Mdl0.Services.Strong.Modelcore._2011_06.DataManagement.SaveAsIn"""
    def __init__(self) -> None: ...
    TargetObject: typing.Any
    SaveAsInput: typing.Any
    DeepCopyDatas: typing.Sequence[typing.Any]

class SaveAsInput:
    """Stub for Mdl0.Services.Strong.Modelcore._2011_06.DataManagement.SaveAsInput"""
    def __init__(self) -> None: ...
    BoName: str
    StringProps: typing.Any
    StringArrayProps: typing.Any
    DoubleProps: typing.Any
    DoubleArrayProps: typing.Any
    FloatProps: typing.Any
    FloatArrayProps: typing.Any
    IntProps: typing.Any
    IntArrayProps: typing.Any
    BoolProps: typing.Any
    BoolArrayProps: typing.Any
    DateProps: typing.Any
    DateArrayProps: typing.Any
    TagProps: typing.Any
    TagArrayProps: typing.Any

class SaveAsObjectsResponse:
    """Stub for Mdl0.Services.Strong.Modelcore._2011_06.DataManagement.SaveAsObjectsResponse"""
    def __init__(self) -> None: ...
    Output: typing.Sequence[typing.Any]
    SaveAsTrees: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class SaveAsOut:
    """Stub for Mdl0.Services.Strong.Modelcore._2011_06.DataManagement.SaveAsOut"""
    def __init__(self) -> None: ...
    TargetObject: typing.Any
    Objects: typing.Sequence[typing.Any]

class SaveAsTree:
    """Stub for Mdl0.Services.Strong.Modelcore._2011_06.DataManagement.SaveAsTree"""
    def __init__(self) -> None: ...
    OriginalObject: typing.Any
    ObjectCopy: typing.Any
    ChildSaveAsNodes: typing.Sequence[typing.Any]

__all__ = [
    'DataManagement',
    'DeepCopyData',
    'DeleteModelContentResponse',
    'SaveAsIn',
    'SaveAsInput',
    'SaveAsObjectsResponse',
    'SaveAsOut',
    'SaveAsTree',
]
