# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class BranchContents:
    """Stub for Bhv1.Services.Internal.Strong.Branchandversioning._2017_12.BranchingAndVersioning.BranchContents"""
    def __init__(self) -> None: ...
    BranchObjectNodeData: typing.Any
    VersionObjectNodesData: typing.Sequence[typing.Any]
    ChildrenBranches: typing.Sequence[typing.Any]

class BranchInfo:
    """Stub for Bhv1.Services.Internal.Strong.Branchandversioning._2017_12.BranchingAndVersioning.BranchInfo"""
    def __init__(self) -> None: ...
    ClientID: str
    NewBranchContent: typing.Any
    Edges: typing.Sequence[typing.Any]

class BranchObjectNodeData:
    """Stub for Bhv1.Services.Internal.Strong.Branchandversioning._2017_12.BranchingAndVersioning.BranchObjectNodeData"""
    def __init__(self) -> None: ...
    BranchObjectNode: typing.Any
    TupleNode: typing.Any
    NodeInfoMap: typing.Any

class BranchOutNodeInput:
    """Stub for Bhv1.Services.Internal.Strong.Branchandversioning._2017_12.BranchingAndVersioning.BranchOutNodeInput"""
    def __init__(self) -> None: ...
    ClientID: str
    NewBranchName: str
    VersionNodes: typing.Sequence[typing.Any]
    BranchOutComment: typing.Any
    Config: typing.Any

class BranchOutNodesResponse:
    """Stub for Bhv1.Services.Internal.Strong.Branchandversioning._2017_12.BranchingAndVersioning.BranchOutNodesResponse"""
    def __init__(self) -> None: ...
    ServiceData: typing.Any
    BranchInfos: typing.Sequence[typing.Any]

class BranchingAndVersioning:
    """Stub for Bhv1.Services.Internal.Strong.Branchandversioning._2017_12.BranchingAndVersioning.BranchingAndVersioning"""
    def __init__(self) -> None: ...
    def BranchOutNodes(self, Inputs: typing.Sequence[typing.Any]) -> typing.Any: ...
    def CheckoutNodes(self, Inputs: typing.Sequence[typing.Any]) -> typing.Any: ...
    def ManageBranchDiagram2(self, Inputs: typing.Sequence[typing.Any]) -> typing.Any: ...
    def PromoteBranchNodes(self, Inputs: typing.Sequence[typing.Any]) -> typing.Any: ...
    def PublishBranchNodes(self, Inputs: typing.Sequence[typing.Any]) -> typing.Any: ...

class CheckoutNodeInput:
    """Stub for Bhv1.Services.Internal.Strong.Branchandversioning._2017_12.BranchingAndVersioning.CheckoutNodeInput"""
    def __init__(self) -> None: ...
    ClientID: str
    Branch: typing.Any
    CheckoutNodeObjects: typing.Sequence[typing.Any]
    Config: typing.Any

class CheckoutNodesResponse:
    """Stub for Bhv1.Services.Internal.Strong.Branchandversioning._2017_12.BranchingAndVersioning.CheckoutNodesResponse"""
    def __init__(self) -> None: ...
    ServiceData: typing.Any
    NewNodeList: typing.Sequence[typing.Any]

class CreateRelatedInput:
    """Stub for Bhv1.Services.Internal.Strong.Branchandversioning._2017_12.BranchingAndVersioning.CreateRelatedInput"""
    def __init__(self) -> None: ...
    BoName: str
    PropMap: typing.Any

class ManageBranchDiagramDataInput2:
    """Stub for Bhv1.Services.Internal.Strong.Branchandversioning._2017_12.BranchingAndVersioning.ManageBranchDiagramDataInput2"""
    def __init__(self) -> None: ...
    ClientID: str
    UserAction: str
    ContextObject: typing.Any
    SelectedObject: typing.Any

class ManageBranchDiagramDataOutput2:
    """Stub for Bhv1.Services.Internal.Strong.Branchandversioning._2017_12.BranchingAndVersioning.ManageBranchDiagramDataOutput2"""
    def __init__(self) -> None: ...
    ClientID: str
    BranchContents: typing.Sequence[typing.Any]
    Edges: typing.Sequence[typing.Any]

class ManageBranchDiagramDataResponse2:
    """Stub for Bhv1.Services.Internal.Strong.Branchandversioning._2017_12.BranchingAndVersioning.ManageBranchDiagramDataResponse2"""
    def __init__(self) -> None: ...
    ServiceData: typing.Any
    Outputs: typing.Sequence[typing.Any]

class NewNodeInfo:
    """Stub for Bhv1.Services.Internal.Strong.Branchandversioning._2017_12.BranchingAndVersioning.NewNodeInfo"""
    def __init__(self) -> None: ...
    ClientID: str
    NewObjects: typing.Sequence[typing.Any]
    BranchNodes: typing.Sequence[typing.Any]
    Edges: typing.Sequence[typing.Any]

class PromoteBranchNodeInput:
    """Stub for Bhv1.Services.Internal.Strong.Branchandversioning._2017_12.BranchingAndVersioning.PromoteBranchNodeInput"""
    def __init__(self) -> None: ...
    ClientID: str
    TargetBranch: typing.Any
    PromoteNodeObjects: typing.Sequence[typing.Any]
    PromoteComment: typing.Any
    Config: typing.Any

class PromoteNodesResponse:
    """Stub for Bhv1.Services.Internal.Strong.Branchandversioning._2017_12.BranchingAndVersioning.PromoteNodesResponse"""
    def __init__(self) -> None: ...
    ServiceData: typing.Any
    NewNodeList: typing.Sequence[typing.Any]

class PublishBranchNodeInput:
    """Stub for Bhv1.Services.Internal.Strong.Branchandversioning._2017_12.BranchingAndVersioning.PublishBranchNodeInput"""
    def __init__(self) -> None: ...
    ClientID: str
    PublishNodeObjects: typing.Sequence[typing.Any]
    PublishComment: typing.Any
    Config: typing.Any

class VersionObjectNodeData:
    """Stub for Bhv1.Services.Internal.Strong.Branchandversioning._2017_12.BranchingAndVersioning.VersionObjectNodeData"""
    def __init__(self) -> None: ...
    VersionObjectNode: typing.Any
    TupleNode: typing.Any
    NodeInfoMap: typing.Any

__all__ = [
    'BranchContents',
    'BranchInfo',
    'BranchObjectNodeData',
    'BranchOutNodeInput',
    'BranchOutNodesResponse',
    'BranchingAndVersioning',
    'CheckoutNodeInput',
    'CheckoutNodesResponse',
    'CreateRelatedInput',
    'ManageBranchDiagramDataInput2',
    'ManageBranchDiagramDataOutput2',
    'ManageBranchDiagramDataResponse2',
    'NewNodeInfo',
    'PromoteBranchNodeInput',
    'PromoteNodesResponse',
    'PublishBranchNodeInput',
    'VersionObjectNodeData',
]
