# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class FindObjectsAttrAndValues:
    """Stub for Teamcenter.Services.Internal.Strong.Query._2008_06.Finder.FindObjectsAttrAndValues"""
    def __init__(self) -> None: ...
    AttrName: str
    Values: typing.Sequence[str]

class FindObjectsInput:
    """Stub for Teamcenter.Services.Internal.Strong.Query._2008_06.Finder.FindObjectsInput"""
    def __init__(self) -> None: ...
    ClassName: str
    ClientId: str
    OutputAttributeNames: typing.Sequence[str]
    AttrAndValues: typing.Sequence[typing.Any]

class FindObjectsResponse:
    """Stub for Teamcenter.Services.Internal.Strong.Query._2008_06.Finder.FindObjectsResponse"""
    def __init__(self) -> None: ...
    ServiceData: typing.Any
    Result: typing.Sequence[typing.Any]
    AttrAndValues: typing.Sequence[typing.Any]

class Finder:
    """Stub for Teamcenter.Services.Internal.Strong.Query._2008_06.Finder.Finder"""
    def __init__(self) -> None: ...
    def FindObjectsByClassAndAttributes(self, Input: typing.Any) -> typing.Any: ...

__all__ = [
    'FindObjectsAttrAndValues',
    'FindObjectsInput',
    'FindObjectsResponse',
    'Finder',
]
