# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class Participant:
    """Stub for Fnd0.Services.Strong.Participant._2018_11.Participant.Participant"""
    def __init__(self) -> None: ...
    def AddParticipants(self, Input: typing.Sequence[typing.Any]) -> typing.Any: ...
    def ReassignParticipants(self, Input: typing.Sequence[typing.Any]) -> typing.Any: ...
    def RemoveParticipants(self, Input: typing.Sequence[typing.Any]) -> typing.Any: ...

class ParticipantInfo:
    """Stub for Fnd0.Services.Strong.Participant._2018_11.Participant.ParticipantInfo"""
    def __init__(self) -> None: ...
    ClientId: str
    Wso: typing.Any
    Participants: typing.Sequence[typing.Any]
    AdditionalData: typing.Any

class ParticipantInfoInput:
    """Stub for Fnd0.Services.Strong.Participant._2018_11.Participant.ParticipantInfoInput"""
    def __init__(self) -> None: ...
    Wso: typing.Any
    AdditionalData: typing.Any
    ParticipantInputData: typing.Sequence[typing.Any]

class ParticipantInfoOutput:
    """Stub for Fnd0.Services.Strong.Participant._2018_11.Participant.ParticipantInfoOutput"""
    def __init__(self) -> None: ...
    ClientId: str
    WsoList: typing.Sequence[typing.Any]
    AdditionalData: typing.Any

class ParticipantInput:
    """Stub for Fnd0.Services.Strong.Participant._2018_11.Participant.ParticipantInput"""
    def __init__(self) -> None: ...
    ClientId: str
    Assignee: typing.Any
    ParticipantType: str

class ParticipantResponse:
    """Stub for Fnd0.Services.Strong.Participant._2018_11.Participant.ParticipantResponse"""
    def __init__(self) -> None: ...
    Output: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class ReassignParticipantInfoInput:
    """Stub for Fnd0.Services.Strong.Participant._2018_11.Participant.ReassignParticipantInfoInput"""
    def __init__(self) -> None: ...
    ClientId: str
    WsoList: typing.Sequence[typing.Any]
    FromAssignee: typing.Any
    ToAssignee: typing.Any
    ParticipantTypes: typing.Sequence[str]
    AllParticipantTypes: bool
    Comment: str
    AdditionalData: typing.Any

class ReassignParticipantResponse:
    """Stub for Fnd0.Services.Strong.Participant._2018_11.Participant.ReassignParticipantResponse"""
    def __init__(self) -> None: ...
    Output: typing.Sequence[typing.Any]
    ServiceData: typing.Any

__all__ = [
    'Participant',
    'ParticipantInfo',
    'ParticipantInfoInput',
    'ParticipantInfoOutput',
    'ParticipantInput',
    'ParticipantResponse',
    'ReassignParticipantInfoInput',
    'ReassignParticipantResponse',
]
