# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class ApplicableIMDSUploadAction:
    """Stub for Sci0.Services.Strong.Imdsintegration._2016_09.IMDSIntegration.ApplicableIMDSUploadAction"""
    def __init__(self) -> None: ...
    DisplayName: str
    InternalValue: int

class ApplicableIMDSUploadActionResponse:
    """Stub for Sci0.Services.Strong.Imdsintegration._2016_09.IMDSIntegration.ApplicableIMDSUploadActionResponse"""
    def __init__(self) -> None: ...
    Output: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class ApplicableIMDSUploadActionsSet:
    """Stub for Sci0.Services.Strong.Imdsintegration._2016_09.IMDSIntegration.ApplicableIMDSUploadActionsSet"""
    def __init__(self) -> None: ...
    InputObject: typing.Any
    ApplicableUploadActions: typing.Sequence[typing.Any]

class IMDSIntegration:
    """Stub for Sci0.Services.Strong.Imdsintegration._2016_09.IMDSIntegration.IMDSIntegration"""
    def __init__(self) -> None: ...
    def GetApplicableIMDSUploadActions(self, Input: typing.Sequence[typing.Any]) -> typing.Any: ...
    def SendDataToIMDS(self, Input: typing.Sequence[typing.Any]) -> typing.Any: ...

class SendIMDSInput1:
    """Stub for Sci0.Services.Strong.Imdsintegration._2016_09.IMDSIntegration.SendIMDSInput1"""
    def __init__(self) -> None: ...
    ClientId: str
    InputObject: typing.Any
    UploadAction: int

__all__ = [
    'ApplicableIMDSUploadAction',
    'ApplicableIMDSUploadActionResponse',
    'ApplicableIMDSUploadActionsSet',
    'IMDSIntegration',
    'SendIMDSInput1',
]
