# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class VendorManagement:
    """Stub for Teamcenter.Services.Strong.Vendormanagement._2012_09.VendorManagement.VendorManagement"""
    def __init__(self) -> None: ...
    def AddRemoveVendorRoles(self, VendorRoles: typing.Sequence[typing.Any], VendorRevRef: typing.Any) -> typing.Any: ...

class VendorRoleData:
    """Stub for Teamcenter.Services.Strong.Vendormanagement._2012_09.VendorManagement.VendorRoleData"""
    def __init__(self) -> None: ...
    ClientId: str
    Description: str
    RoleType: str
    Remove: bool

__all__ = [
    'VendorManagement',
    'VendorRoleData',
]
