# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class AttributeConfiguration:
    """Stub for Teamcenter.Services.Strong.Classification._2009_10.Classification.AttributeConfiguration"""
    def __init__(self) -> None: ...
    PreConfig: str
    Config: str
    PostConfig: str

class AutoComputeAttribute:
    """Stub for Teamcenter.Services.Strong.Classification._2009_10.Classification.AutoComputeAttribute"""
    def __init__(self) -> None: ...
    Values: typing.Sequence[typing.Any]
    UnitName: str
    Length: int
    AttributeProperties: int
    IsModified: bool

class AutoComputeAttributesResponse:
    """Stub for Teamcenter.Services.Strong.Classification._2009_10.Classification.AutoComputeAttributesResponse"""
    def __init__(self) -> None: ...
    AutoComputedAttrs: typing.Any
    ServiceData: typing.Any

class ClassAttribute2:
    """Stub for Teamcenter.Services.Strong.Classification._2009_10.Classification.ClassAttribute2"""
    def __init__(self) -> None: ...
    Id: int
    Name: str
    ShortName: str
    Description: str
    MetricFormat: typing.Any
    NonMetricFormat: typing.Any
    Annotation: str
    AttributeConfiguration: typing.Any
    ArraySize: int
    Options: int
    ExtendedProperties: typing.Sequence[typing.Any]

class Classification:
    """Stub for Teamcenter.Services.Strong.Classification._2009_10.Classification.Classification"""
    def __init__(self) -> None: ...
    def AutoComputeAttributes(self, IcoId: str, Wso: typing.Any, ClassId: str, ViewId: str, InputAttrs: typing.Any, UnitSystem: int, Mode: int) -> typing.Any: ...
    def CreateOrUpdateKeyLOVs(self, KeyLOVsInput: typing.Sequence[typing.Any]) -> typing.Any: ...
    def GetAttributesForClasses2(self, ClassIds: typing.Sequence[str]) -> typing.Any: ...
    def GetKeyLOVs2(self, KeyLOVIds: typing.Sequence[str]) -> typing.Any: ...

class ExtendedProeprty:
    """Stub for Teamcenter.Services.Strong.Classification._2009_10.Classification.ExtendedProeprty"""
    def __init__(self) -> None: ...
    PropertyName: str
    Values: typing.Sequence[typing.Any]

class ExtendedPropertyValues:
    """Stub for Teamcenter.Services.Strong.Classification._2009_10.Classification.ExtendedPropertyValues"""
    def __init__(self) -> None: ...
    Value: str

class FormatProperties:
    """Stub for Teamcenter.Services.Strong.Classification._2009_10.Classification.FormatProperties"""
    def __init__(self) -> None: ...
    Format: typing.Any
    UnitName: str
    DefaultValue: str
    MinimumValue: str
    MaximumValue: str

class GetAttributesForClassesResponse2:
    """Stub for Teamcenter.Services.Strong.Classification._2009_10.Classification.GetAttributesForClassesResponse2"""
    def __init__(self) -> None: ...
    Attributes: typing.Any
    Data: typing.Any

class GetKeyLOVsResponse2:
    """Stub for Teamcenter.Services.Strong.Classification._2009_10.Classification.GetKeyLOVsResponse2"""
    def __init__(self) -> None: ...
    KeyLOVs: typing.Any
    Data: typing.Any

class KeyLOVDefinition2:
    """Stub for Teamcenter.Services.Strong.Classification._2009_10.Classification.KeyLOVDefinition2"""
    def __init__(self) -> None: ...
    Id: str
    Name: str
    KeyLovtag: typing.Any
    Options: int
    KeyLovEntries: typing.Sequence[typing.Any]
    OwningSite: typing.Any
    SharedSites: typing.Sequence[typing.Any]

class KeyLOVEntry:
    """Stub for Teamcenter.Services.Strong.Classification._2009_10.Classification.KeyLOVEntry"""
    def __init__(self) -> None: ...
    LovKey: str
    LovValue: str
    DeprecatedSatus: bool

__all__ = [
    'AttributeConfiguration',
    'AutoComputeAttribute',
    'AutoComputeAttributesResponse',
    'ClassAttribute2',
    'Classification',
    'ExtendedProeprty',
    'ExtendedPropertyValues',
    'FormatProperties',
    'GetAttributesForClassesResponse2',
    'GetKeyLOVsResponse2',
    'KeyLOVDefinition2',
    'KeyLOVEntry',
]
