# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class ConfiguratorManagement:
    """Stub for Cfg0.Services.Strong.Configurator._2024_06.ConfiguratorManagement.ConfiguratorManagement"""
    def __init__(self) -> None: ...
    def SearchConstraints(self, Perspective: typing.Any, RuleTypes: typing.Sequence[str], Conditions: typing.Sequence[typing.Any], Subject: typing.Sequence[typing.Any], QueryInput: typing.Any, RequestInfo: typing.Any) -> typing.Any: ...

class QueryInput:
    """Stub for Cfg0.Services.Strong.Configurator._2024_06.ConfiguratorManagement.QueryInput"""
    def __init__(self) -> None: ...
    Query: typing.Any
    Entries: typing.Sequence[str]
    Values: typing.Sequence[str]

class SearchConstraintResponse:
    """Stub for Cfg0.Services.Strong.Configurator._2024_06.ConfiguratorManagement.SearchConstraintResponse"""
    def __init__(self) -> None: ...
    RuleObjects: typing.Sequence[typing.Any]
    ResponseInfo: typing.Sequence[typing.Any]
    ServiceData: typing.Any

__all__ = [
    'ConfiguratorManagement',
    'QueryInput',
    'SearchConstraintResponse',
]
