# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class ClosureRuleEditor:
    """Stub for Teamcenter.Services.Internal.Strong.Manufacturing._2019_06.ClosureRuleEditor.ClosureRuleEditor"""
    def __init__(self) -> None: ...
    def GetClosureRuleTraversalInfo(self, Input: typing.Any) -> typing.Any: ...
    def SetClosureRuleTraversalInfo(self, UpdatedTraversalInfo: typing.Any, ClosureRuleName: str) -> typing.Any: ...

class ClosureRuleTraversalInput:
    """Stub for Teamcenter.Services.Internal.Strong.Manufacturing._2019_06.ClosureRuleEditor.ClosureRuleTraversalInput"""
    def __init__(self) -> None: ...
    TopBOMLine: typing.Any
    ClosureRuleName: str

class ClosureRuleTraversalResponse:
    """Stub for Teamcenter.Services.Internal.Strong.Manufacturing._2019_06.ClosureRuleEditor.ClosureRuleTraversalResponse"""
    def __init__(self) -> None: ...
    TraversalInfo: typing.Any
    ServiceData: typing.Any

class TraversedSecondaryObjectInfo:
    """Stub for Teamcenter.Services.Internal.Strong.Manufacturing._2019_06.ClosureRuleEditor.TraversedSecondaryObjectInfo"""
    def __init__(self) -> None: ...
    SecondaryObjectType: str
    ImanRelationType: str
    ImanRelationDescription: str
    IsSecondaryIncluded: bool
    IsSecondaryEditable: bool
    IsPrimaryIncluded: bool
    IsPrimaryEditable: bool

__all__ = [
    'ClosureRuleEditor',
    'ClosureRuleTraversalInput',
    'ClosureRuleTraversalResponse',
    'TraversedSecondaryObjectInfo',
]
