# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class HasActiveMarkupAssociatedOut:
    """Stub for Teamcenter.Services.Internal.Strong.Changemanagement._2020_01.MassUpdate.HasActiveMarkupAssociatedOut"""
    def __init__(self) -> None: ...
    HasActiveMarkup: bool
    ServiceData: typing.Any

class MassUpdate:
    """Stub for Teamcenter.Services.Internal.Strong.Changemanagement._2020_01.MassUpdate.MassUpdate"""
    def __init__(self) -> None: ...
    def HasActiveMarkupAssociated(self, ChangeObject: typing.Any) -> typing.Any: ...
    def SaveImpactedAssemblies(self, ChangeObject: typing.Any, ImpactedObjectsInfo: typing.Sequence[typing.Any]) -> typing.Any: ...

class MassUpdateChange:
    """Stub for Teamcenter.Services.Internal.Strong.Changemanagement._2020_01.MassUpdate.MassUpdateChange"""
    def __init__(self) -> None: ...
    PropName: str
    PropValue: str

class SaveImpactedAssembliesIn:
    """Stub for Teamcenter.Services.Internal.Strong.Changemanagement._2020_01.MassUpdate.SaveImpactedAssembliesIn"""
    def __init__(self) -> None: ...
    ImpactedObject: typing.Any
    MassUpdateChanges: typing.Sequence[typing.Any]

__all__ = [
    'HasActiveMarkupAssociatedOut',
    'MassUpdate',
    'MassUpdateChange',
    'SaveImpactedAssembliesIn',
]
