# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class GraphFilter:
    """Stub for Rv1.Services.Strong.Relationshipviewer._2014_11.NetworkEngine.GraphFilter"""
    def __init__(self) -> None: ...
    Name: str
    DisplayName: str
    Color: typing.Any
    Types: typing.Sequence[typing.Any]

class GraphGroup:
    """Stub for Rv1.Services.Strong.Relationshipviewer._2014_11.NetworkEngine.GraphGroup"""
    def __init__(self) -> None: ...
    Name: str
    Filters: typing.Sequence[typing.Any]

class GraphTypeListResponse:
    """Stub for Rv1.Services.Strong.Relationshipviewer._2014_11.NetworkEngine.GraphTypeListResponse"""
    def __init__(self) -> None: ...
    Views: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class GraphViewDescription:
    """Stub for Rv1.Services.Strong.Relationshipviewer._2014_11.NetworkEngine.GraphViewDescription"""
    def __init__(self) -> None: ...
    Name: str
    DisplayName: str
    DefaultLayout: str
    DefaultExpandDirection: str
    Visible: bool
    DiagramMode: bool
    Groups: typing.Sequence[typing.Any]

class NetworkEngine:
    """Stub for Rv1.Services.Strong.Relationshipviewer._2014_11.NetworkEngine.NetworkEngine"""
    def __init__(self) -> None: ...
    def GetViews3(self, Key: str) -> typing.Any: ...

__all__ = [
    'GraphFilter',
    'GraphGroup',
    'GraphTypeListResponse',
    'GraphViewDescription',
    'NetworkEngine',
]
