# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class ExportFilesOfflineInput:
    """Stub for Teamcenter.Services.Strong.Globalmultisite._2022_06.ImportExport.ExportFilesOfflineInput"""
    def __init__(self) -> None: ...
    DatasetUid: str
    ItemRevisionUid: str

class ImportExport:
    """Stub for Teamcenter.Services.Strong.Globalmultisite._2022_06.ImportExport.ImportExport"""
    def __init__(self) -> None: ...
    def ExportFilesOffline2(self, Input: typing.Sequence[typing.Any], Options: typing.Sequence[typing.Any]) -> typing.Any: ...

__all__ = [
    'ExportFilesOfflineInput',
    'ImportExport',
]
