# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class FileMgmt:
    """Stub for Awp0.Services.Internal.Strong.Aws2._2020_05.FileMgmt.FileMgmt"""
    def __init__(self) -> None: ...
    def GetFileNamesWithTicketInfo(self, BusinessObjectsIn: typing.Sequence[typing.Any]) -> typing.Any: ...

class FileNameTicketOut:
    """Stub for Awp0.Services.Internal.Strong.Aws2._2020_05.FileMgmt.FileNameTicketOut"""
    def __init__(self) -> None: ...
    FileName: str
    FileTicket: str

class GetFilesAndTicketsInfoResponse:
    """Stub for Awp0.Services.Internal.Strong.Aws2._2020_05.FileMgmt.GetFilesAndTicketsInfoResponse"""
    def __init__(self) -> None: ...
    ServiceData: typing.Any
    Output: typing.Sequence[typing.Any]

__all__ = [
    'FileMgmt',
    'FileNameTicketOut',
    'GetFilesAndTicketsInfoResponse',
]
