# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class Changes:
    """Stub for Cm1.Services.Internal.Strong.Cmaws._2022_12.Changes.Changes"""
    def __init__(self) -> None: ...
    def GetMergeCandidates(self, SourceObject: typing.Any, TargetObject: typing.Any) -> typing.Any: ...

class MergeCandidateOutput:
    """Stub for Cm1.Services.Internal.Strong.Cmaws._2022_12.Changes.MergeCandidateOutput"""
    def __init__(self) -> None: ...
    ObjectToBeMerged: typing.Any
    MergeRelatedData: typing.Any
    IsAlreadyMerged: bool

class MergeCandidateResponse:
    """Stub for Cm1.Services.Internal.Strong.Cmaws._2022_12.Changes.MergeCandidateResponse"""
    def __init__(self) -> None: ...
    MergeCandidates: typing.Sequence[typing.Any]
    ServiceData: typing.Any

__all__ = [
    'Changes',
    'MergeCandidateOutput',
    'MergeCandidateResponse',
]
