# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class AttachMeasurableAttrInput:
    """Stub for Att1.Services.Strong.Attrtargetmgmtaw._2017_06.AttributeTargetManagement.AttachMeasurableAttrInput"""
    def __init__(self) -> None: ...
    ClientId: str
    ParentObj: typing.Any
    AttrList: typing.Sequence[typing.Any]
    Relation: str
    AddAsCopy: bool

class AttachMeasurableAttrOutput:
    """Stub for Att1.Services.Strong.Attrtargetmgmtaw._2017_06.AttributeTargetManagement.AttachMeasurableAttrOutput"""
    def __init__(self) -> None: ...
    ClientId: str
    AddedAttrList: typing.Sequence[typing.Any]
    IgnoredAttrList: typing.Sequence[typing.Any]

class AttachMeasurableAttrResp:
    """Stub for Att1.Services.Strong.Attrtargetmgmtaw._2017_06.AttributeTargetManagement.AttachMeasurableAttrResp"""
    def __init__(self) -> None: ...
    Outputs: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class AttributeTargetManagement:
    """Stub for Att1.Services.Strong.Attrtargetmgmtaw._2017_06.AttributeTargetManagement.AttributeTargetManagement"""
    def __init__(self) -> None: ...
    def AttachMeasurableAttributes(self, Inputs: typing.Sequence[typing.Any]) -> typing.Any: ...

__all__ = [
    'AttachMeasurableAttrInput',
    'AttachMeasurableAttrOutput',
    'AttachMeasurableAttrResp',
    'AttributeTargetManagement',
]
