# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
from teamcenter.services.internal.strong.query import FinderService
from teamcenter.services.internal.strong.query import SavedQueryService

class FinderRestBindingStub(FinderService):
    """Stub for Teamcenter.Services.Internal.Strong.Query.FinderRestBindingStub"""
    def __init__(self, connection: typing.Any) -> None: ...
    def FindObjectsByClassAndAttributes(self, Input: typing.Any) -> typing.Any: ...

class FinderService:
    """Stub for Teamcenter.Services.Internal.Strong.Query.FinderService"""
    def __init__(self) -> None: ...
    def FindObjectsByClassAndAttributes(self, Input: typing.Any) -> typing.Any: ...
    @classmethod
    def getService(cls, connection: typing.Any) -> typing.Any: ...

class SavedQueryRestBindingStub(SavedQueryService):
    """Stub for Teamcenter.Services.Internal.Strong.Query.SavedQueryRestBindingStub"""
    def __init__(self, connection: typing.Any) -> None: ...
    def DescribeSavedQueryDefinitions(self, RequestedQueries: typing.Sequence[typing.Any]) -> typing.Any: ...
    def DescribeSavedQueryDefinitions2(self, RequestedQueries: typing.Sequence[typing.Any]) -> typing.Any: ...
    def DescribeSavedQueryDefinitions3(self, RequestedQueries: typing.Sequence[typing.Any]) -> typing.Any: ...

class SavedQueryService:
    """Stub for Teamcenter.Services.Internal.Strong.Query.SavedQueryService"""
    def __init__(self) -> None: ...
    def DescribeSavedQueryDefinitions(self, RequestedQueries: typing.Sequence[typing.Any]) -> typing.Any: ...
    def DescribeSavedQueryDefinitions2(self, RequestedQueries: typing.Sequence[typing.Any]) -> typing.Any: ...
    def DescribeSavedQueryDefinitions3(self, RequestedQueries: typing.Sequence[typing.Any]) -> typing.Any: ...
    @classmethod
    def getService(cls, connection: typing.Any) -> typing.Any: ...

__all__ = [
    'FinderRestBindingStub',
    'FinderService',
    'SavedQueryRestBindingStub',
    'SavedQueryService',
    '_2008_06',
    '_2012_02',
    '_2013_05',
    '_2014_10',
]
