# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class AutoFilterValue:
    """Stub for Cla0.Services.Internal.Strong.Classificationcommon._2021_06.Classification.AutoFilterValue"""
    def __init__(self) -> None: ...
    UnitSystem: int
    PropertyValue: str
    Count: int

class ClassDescriptor:
    """Stub for Cla0.Services.Internal.Strong.Classificationcommon._2021_06.Classification.ClassDescriptor"""
    def __init__(self) -> None: ...
    Irdi: str
    ClassNamespace: str
    Id: str
    Revision: str
    Status: str
    ClassType: str
    IsAbstract: bool
    UnitSystem: int
    Name: typing.Any
    ShortName: typing.Any
    Definition: typing.Any
    Note: typing.Any
    Remark: typing.Any
    ClassAttributes: typing.Sequence[typing.Any]
    AdditionalProperties: typing.Any

class Classification:
    """Stub for Cla0.Services.Internal.Strong.Classificationcommon._2021_06.Classification.Classification"""
    def __init__(self) -> None: ...
    def FindValues(self, FindValueInputs: typing.Sequence[typing.Any]) -> typing.Any: ...
    def GetGraphicsTemplateInfo(self, ClassificationObjects: typing.Sequence[str], ClassificationClasses: typing.Sequence[str]) -> typing.Any: ...
    def SaveGraphicsMember(self, RequestObjects: typing.Sequence[typing.Any]) -> typing.Any: ...
    def SearchClassDescriptor(self, SearchCriteria: typing.Sequence[typing.Any], Options: int) -> typing.Any: ...
    def SearchClassificationObjects(self, SearchCriteria: typing.Sequence[typing.Any], Options: int) -> typing.Any: ...

class EmptyProperty:
    """Stub for Cla0.Services.Internal.Strong.Classificationcommon._2021_06.Classification.EmptyProperty"""
    def __init__(self) -> None: ...
    PropertyName: str
    PropertyIdentifier: str
    PropertyAnnotation: str

class FindValueInput:
    """Stub for Cla0.Services.Internal.Strong.Classificationcommon._2021_06.Classification.FindValueInput"""
    def __init__(self) -> None: ...
    PropertyID: str
    ClassID: str
    ActiveUnitsystem: int
    FindValuePropertyValues: typing.Sequence[typing.Any]

class FindValuePropertyValue:
    """Stub for Cla0.Services.Internal.Strong.Classificationcommon._2021_06.Classification.FindValuePropertyValue"""
    def __init__(self) -> None: ...
    PropertyID: str
    PropertyValue: str

class FindValuesOutput:
    """Stub for Cla0.Services.Internal.Strong.Classificationcommon._2021_06.Classification.FindValuesOutput"""
    def __init__(self) -> None: ...
    AutoFilterValues: typing.Sequence[typing.Any]

class FindValuesResponse:
    """Stub for Cla0.Services.Internal.Strong.Classificationcommon._2021_06.Classification.FindValuesResponse"""
    def __init__(self) -> None: ...
    FindValuesOutputs: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class GetGraphicsTemplateInfoResponse:
    """Stub for Cla0.Services.Internal.Strong.Classificationcommon._2021_06.Classification.GetGraphicsTemplateInfoResponse"""
    def __init__(self) -> None: ...
    GraphicsTemplateInfos: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class GraphicsTemplateInfo:
    """Stub for Cla0.Services.Internal.Strong.Classificationcommon._2021_06.Classification.GraphicsTemplateInfo"""
    def __init__(self) -> None: ...
    TemplateType: str
    TemplateName: str
    TemplateObject: typing.Any
    Unitsystem: int
    EmptyProperties: typing.Sequence[typing.Any]

class GraphicsTemplateInfos:
    """Stub for Cla0.Services.Internal.Strong.Classificationcommon._2021_06.Classification.GraphicsTemplateInfos"""
    def __init__(self) -> None: ...
    TemplatesInfos: typing.Sequence[typing.Any]

class OrderByTerm:
    """Stub for Cla0.Services.Internal.Strong.Classificationcommon._2021_06.Classification.OrderByTerm"""
    def __init__(self) -> None: ...
    PropertyName: str
    SortAscending: bool

class PropertyValue:
    """Stub for Cla0.Services.Internal.Strong.Classificationcommon._2021_06.Classification.PropertyValue"""
    def __init__(self) -> None: ...
    Datatype: str
    BoolValue: typing.Sequence[bool]
    IntValue: typing.Sequence[int]
    DoubleValue: typing.Sequence[float]
    StringValue: typing.Sequence[str]

class SaveGraphicsMemberRequest:
    """Stub for Cla0.Services.Internal.Strong.Classificationcommon._2021_06.Classification.SaveGraphicsMemberRequest"""
    def __init__(self) -> None: ...
    TemplateObject: typing.Any
    ClassificationObject: str
    CreatePartFile: bool
    CreateJTFile: bool
    RecreateFromTemplate: bool

class SearchClassDescriptorResponse:
    """Stub for Cla0.Services.Internal.Strong.Classificationcommon._2021_06.Classification.SearchClassDescriptorResponse"""
    def __init__(self) -> None: ...
    SearchResults: typing.Sequence[typing.Any]
    ClassDescriptors: typing.Any
    Parents: typing.Any
    Children: typing.Any
    Blocks: typing.Any
    KeyLOVs: typing.Any
    ServiceData: typing.Any

class SearchClassDescriptorResult:
    """Stub for Cla0.Services.Internal.Strong.Classificationcommon._2021_06.Classification.SearchClassDescriptorResult"""
    def __init__(self) -> None: ...
    ClassIRDI: str
    SelectProperties: typing.Sequence[typing.Any]

class SearchClassDescriptorResults:
    """Stub for Cla0.Services.Internal.Strong.Classificationcommon._2021_06.Classification.SearchClassDescriptorResults"""
    def __init__(self) -> None: ...
    ResultStatus: int
    ErrorDetails: typing.Sequence[str]
    TotalFound: int
    TotalLoaded: int
    Results: typing.Sequence[typing.Any]

class SearchCriteria:
    """Stub for Cla0.Services.Internal.Strong.Classificationcommon._2021_06.Classification.SearchCriteria"""
    def __init__(self) -> None: ...
    SelectProperties: typing.Sequence[str]
    SearchExpressions: typing.Sequence[typing.Any]
    OrderByTerms: typing.Sequence[typing.Any]
    Limit: int
    Offset: int

class SearchExpression:
    """Stub for Cla0.Services.Internal.Strong.Classificationcommon._2021_06.Classification.SearchExpression"""
    def __init__(self) -> None: ...
    OperatorExpression: str
    PropertyName: str
    PropertyValue: typing.Any

class SearchIcoCriteria:
    """Stub for Cla0.Services.Internal.Strong.Classificationcommon._2021_06.Classification.SearchIcoCriteria"""
    def __init__(self) -> None: ...
    SelectProperties: typing.Sequence[str]
    SearchExpressions: typing.Sequence[typing.Any]
    OrderByTerms: typing.Sequence[typing.Any]
    SearchInHierarchy: bool
    Offset: int
    Limit: int
    LoadClassificationObjects: bool
    LoadClassDescriptors: bool

class SearchIcoResponse:
    """Stub for Cla0.Services.Internal.Strong.Classificationcommon._2021_06.Classification.SearchIcoResponse"""
    def __init__(self) -> None: ...
    SearchResults: typing.Sequence[typing.Any]
    ClassificationObjects: typing.Any
    ClassDescriptors: typing.Any
    Blocks: typing.Any
    KeyLOVs: typing.Any
    ServiceData: typing.Any

class SearchIcoResult:
    """Stub for Cla0.Services.Internal.Strong.Classificationcommon._2021_06.Classification.SearchIcoResult"""
    def __init__(self) -> None: ...
    ObjectUID: str
    SelectProperties: typing.Sequence[typing.Any]

class SearchIcoResults:
    """Stub for Cla0.Services.Internal.Strong.Classificationcommon._2021_06.Classification.SearchIcoResults"""
    def __init__(self) -> None: ...
    ResultStatus: int
    ErrorDetails: typing.Sequence[str]
    TotalFound: int
    TotalLoaded: int
    Results: typing.Sequence[typing.Any]

class SelectValue:
    """Stub for Cla0.Services.Internal.Strong.Classificationcommon._2021_06.Classification.SelectValue"""
    def __init__(self) -> None: ...
    PropertyName: str
    PropertyValues: typing.Sequence[typing.Any]

__all__ = [
    'AutoFilterValue',
    'ClassDescriptor',
    'Classification',
    'EmptyProperty',
    'FindValueInput',
    'FindValuePropertyValue',
    'FindValuesOutput',
    'FindValuesResponse',
    'GetGraphicsTemplateInfoResponse',
    'GraphicsTemplateInfo',
    'GraphicsTemplateInfos',
    'OrderByTerm',
    'PropertyValue',
    'SaveGraphicsMemberRequest',
    'SearchClassDescriptorResponse',
    'SearchClassDescriptorResult',
    'SearchClassDescriptorResults',
    'SearchCriteria',
    'SearchExpression',
    'SearchIcoCriteria',
    'SearchIcoResponse',
    'SearchIcoResult',
    'SearchIcoResults',
    'SelectValue',
]
