# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class ChangeManagement:
    """Stub for Teamcenter.Services.Internal.Strong.Changemanagement._2012_10.ChangeManagement.ChangeManagement"""
    def __init__(self) -> None: ...
    def GetCreatableChangeTypes(self, Inputs: typing.Sequence[typing.Any]) -> typing.Any: ...

class ChangeTypeInfo:
    """Stub for Teamcenter.Services.Internal.Strong.Changemanagement._2012_10.ChangeManagement.ChangeTypeInfo"""
    def __init__(self) -> None: ...
    TypeName: str
    TypeDisplayName: str

class ContextDataInput:
    """Stub for Teamcenter.Services.Internal.Strong.Changemanagement._2012_10.ChangeManagement.ContextDataInput"""
    def __init__(self) -> None: ...
    ClientId: str
    Object: str
    BaseTypeName: str
    ExclusionTypeNames: typing.Sequence[str]

class CreatableChangeTypesOut:
    """Stub for Teamcenter.Services.Internal.Strong.Changemanagement._2012_10.ChangeManagement.CreatableChangeTypesOut"""
    def __init__(self) -> None: ...
    ClientId: str
    AllowedChangeTypes: typing.Sequence[typing.Any]

class CreatableChangeTypesResponse:
    """Stub for Teamcenter.Services.Internal.Strong.Changemanagement._2012_10.ChangeManagement.CreatableChangeTypesResponse"""
    def __init__(self) -> None: ...
    Output: typing.Sequence[typing.Any]
    ServiceData: typing.Any

__all__ = [
    'ChangeManagement',
    'ChangeTypeInfo',
    'ContextDataInput',
    'CreatableChangeTypesOut',
    'CreatableChangeTypesResponse',
]
