# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class Session:
    """Stub for Teamcenter.Services.Internal.Strong.Core._2014_11.Session.Session"""
    def __init__(self) -> None: ...
    def GetSecurityToken(self, Duration: int) -> str: ...

__all__ = [
    'Session',
]
