# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class Assignment:
    """Stub for Mpr0.Services.Internal.Strong.Process._2017_05.Assignment.Assignment"""
    def __init__(self) -> None: ...
    def GetAssignmentData(self, Input: typing.Sequence[typing.Any]) -> typing.Any: ...
    def GetAssignmentTypeInformation(self) -> typing.Any: ...
    def GetClientRequiredInfo(self, Input: typing.Sequence[typing.Any]) -> typing.Any: ...
    def GetConnectedInfo(self, SourceObjects: typing.Sequence[typing.Any], Context: typing.Any) -> typing.Any: ...
    def GetDesignModelViews(self, Input: typing.Any) -> typing.Any: ...
    def GetObjectsByVisualizationID(self, Input: typing.Sequence[typing.Any]) -> typing.Any: ...
    def GetVisualizationIDs(self, Elements: typing.Sequence[typing.Any], AssignmentTypesFilter: typing.Sequence[typing.Any], IncludeBackground: bool) -> typing.Any: ...
    def GetVisualizationIDsInWorkset(self, Process: typing.Any, Workset: typing.Any) -> typing.Any: ...
    def Search(self, Input: typing.Sequence[typing.Any]) -> typing.Any: ...

class AssignmentDataInput:
    """Stub for Mpr0.Services.Internal.Strong.Process._2017_05.Assignment.AssignmentDataInput"""
    def __init__(self) -> None: ...
    Context: typing.Any
    Scope: typing.Any
    SearchOptions: typing.Any
    FilterCriteria: typing.Sequence[typing.Any]
    ClientRequiredInformation: typing.Sequence[str]

class AssignmentDataOutput:
    """Stub for Mpr0.Services.Internal.Strong.Process._2017_05.Assignment.AssignmentDataOutput"""
    def __init__(self) -> None: ...
    Context: typing.Any
    AssignedObjects: typing.Sequence[typing.Any]
    Finished: bool
    TotalFound: int
    ClientRequiredInfo: typing.Any
    AssignObjClientRequiredInfo: typing.Sequence[typing.Any]

class AssignmentDataResponse:
    """Stub for Mpr0.Services.Internal.Strong.Process._2017_05.Assignment.AssignmentDataResponse"""
    def __init__(self) -> None: ...
    ServiceData: typing.Any
    Output: typing.Sequence[typing.Any]

class AssignmentTypeInformation:
    """Stub for Mpr0.Services.Internal.Strong.Process._2017_05.Assignment.AssignmentTypeInformation"""
    def __init__(self) -> None: ...
    AssigneeType: typing.Any
    AssignToType: typing.Any
    ValidAssignmentTypes: typing.Sequence[typing.Any]
    DefaultAssignmentType: typing.Any

class ClientRequiredInfo:
    """Stub for Mpr0.Services.Internal.Strong.Process._2017_05.Assignment.ClientRequiredInfo"""
    def __init__(self) -> None: ...
    StringInfo: typing.Any
    StringArrayInfo: typing.Any
    TagInfo: typing.Any
    TagArrayInfo: typing.Any
    BooleanInfo: typing.Any
    BooleanArrayInfo: typing.Any
    IntegerInfo: typing.Any
    IntegerArrayInfo: typing.Any
    DoubleInfo: typing.Any
    DoubleArrayInfo: typing.Any
    TagToTagVectorMapInfo: typing.Any

class ConnectedObjectInfo:
    """Stub for Mpr0.Services.Internal.Strong.Process._2017_05.Assignment.ConnectedObjectInfo"""
    def __init__(self) -> None: ...
    Obj: typing.Any
    ClientInfo: typing.Any
    ConnectedObjects: typing.Sequence[typing.Any]
    ConnectedObjClientInfo: typing.Sequence[typing.Any]

class DesignDisclosureViewData:
    """Stub for Mpr0.Services.Internal.Strong.Process._2017_05.Assignment.DesignDisclosureViewData"""
    def __init__(self) -> None: ...
    DesignDisclosure: typing.Any
    StructureContext: typing.Any
    Views: typing.Sequence[typing.Any]

class DesignElementViewsData:
    """Stub for Mpr0.Services.Internal.Strong.Process._2017_05.Assignment.DesignElementViewsData"""
    def __init__(self) -> None: ...
    OwningObjectCSID: str
    Views: typing.Sequence[typing.Any]

class DesignModelViewsData:
    """Stub for Mpr0.Services.Internal.Strong.Process._2017_05.Assignment.DesignModelViewsData"""
    def __init__(self) -> None: ...
    Views: typing.Any
    ViewsOfAncestors: typing.Any

class GetAssignmentTypeInformationResponse:
    """Stub for Mpr0.Services.Internal.Strong.Process._2017_05.Assignment.GetAssignmentTypeInformationResponse"""
    def __init__(self) -> None: ...
    AssignmentTypes: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class GetClientRequiredInformationInput:
    """Stub for Mpr0.Services.Internal.Strong.Process._2017_05.Assignment.GetClientRequiredInformationInput"""
    def __init__(self) -> None: ...
    Context: typing.Any
    ClientRequiredInformation: typing.Sequence[str]
    UpdatedObjects: typing.Sequence[typing.Any]

class GetClientRequiredInformationOutput:
    """Stub for Mpr0.Services.Internal.Strong.Process._2017_05.Assignment.GetClientRequiredInformationOutput"""
    def __init__(self) -> None: ...
    ObjectClientRequiredInfoMap: typing.Any
    GlobalClientRequiredInfo: typing.Any

class GetClientRequiredInformationResponse:
    """Stub for Mpr0.Services.Internal.Strong.Process._2017_05.Assignment.GetClientRequiredInformationResponse"""
    def __init__(self) -> None: ...
    Output: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class GetConnectedInfoOutput:
    """Stub for Mpr0.Services.Internal.Strong.Process._2017_05.Assignment.GetConnectedInfoOutput"""
    def __init__(self) -> None: ...
    SourceObject: typing.Any
    ConnectedObjectInfo: typing.Sequence[typing.Any]

class GetConnectedInfoResponse:
    """Stub for Mpr0.Services.Internal.Strong.Process._2017_05.Assignment.GetConnectedInfoResponse"""
    def __init__(self) -> None: ...
    Output: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class GetDesignModelViewsResponse:
    """Stub for Mpr0.Services.Internal.Strong.Process._2017_05.Assignment.GetDesignModelViewsResponse"""
    def __init__(self) -> None: ...
    ForegroundData: typing.Any
    BackgroundData: typing.Any
    DesignDisclosureData: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class GetObjectsByVisualizationIDInfo:
    """Stub for Mpr0.Services.Internal.Strong.Process._2017_05.Assignment.GetObjectsByVisualizationIDInfo"""
    def __init__(self) -> None: ...
    Context: typing.Any
    SearchOptions: typing.Any
    VisualizationIDs: typing.Sequence[str]
    FilterCriteria: typing.Sequence[typing.Any]
    ClientRequiredInformation: typing.Sequence[str]

class GetVisualizationIDsInWorksetResponse:
    """Stub for Mpr0.Services.Internal.Strong.Process._2017_05.Assignment.GetVisualizationIDsInWorksetResponse"""
    def __init__(self) -> None: ...
    CsidMap: typing.Any
    ServiceData: typing.Any

class GetVisualizationIDsResponse:
    """Stub for Mpr0.Services.Internal.Strong.Process._2017_05.Assignment.GetVisualizationIDsResponse"""
    def __init__(self) -> None: ...
    VisualizationIDsInfo: typing.Any
    ServiceData: typing.Any

class ProductElementFilterCriteriaInput:
    """Stub for Mpr0.Services.Internal.Strong.Process._2017_05.Assignment.ProductElementFilterCriteriaInput"""
    def __init__(self) -> None: ...
    FilterName: str
    FilterValues: typing.Sequence[str]

class SearchInfo:
    """Stub for Mpr0.Services.Internal.Strong.Process._2017_05.Assignment.SearchInfo"""
    def __init__(self) -> None: ...
    Context: typing.Any
    Scope: typing.Any
    SearchOptions: typing.Any
    SearchTerm: str
    PropertyNames: typing.Sequence[str]
    ProductElementsFilterCriteria: typing.Sequence[typing.Any]
    ClientRequiredInformation: typing.Sequence[str]

class SearchOptions:
    """Stub for Mpr0.Services.Internal.Strong.Process._2017_05.Assignment.SearchOptions"""
    def __init__(self) -> None: ...
    StartFrom: typing.Any
    PageSize: int
    SortOptions: typing.Sequence[typing.Any]

class SearchOutput:
    """Stub for Mpr0.Services.Internal.Strong.Process._2017_05.Assignment.SearchOutput"""
    def __init__(self) -> None: ...
    Index: int
    TotalFound: int
    Finished: bool
    Results: typing.Sequence[typing.Any]
    AssignedAncestorsClientReqInfo: typing.Any

class SearchResponse:
    """Stub for Mpr0.Services.Internal.Strong.Process._2017_05.Assignment.SearchResponse"""
    def __init__(self) -> None: ...
    SearchOutput: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class SearchResult:
    """Stub for Mpr0.Services.Internal.Strong.Process._2017_05.Assignment.SearchResult"""
    def __init__(self) -> None: ...
    Obj: typing.Any
    Breadcrumbs: typing.Sequence[typing.Any]
    ClientRequiredInfo: typing.Any

class SortOptions:
    """Stub for Mpr0.Services.Internal.Strong.Process._2017_05.Assignment.SortOptions"""
    def __init__(self) -> None: ...
    SortAttribute: str
    Ascending: bool

class TagToTagVectorInfo:
    """Stub for Mpr0.Services.Internal.Strong.Process._2017_05.Assignment.TagToTagVectorInfo"""
    def __init__(self) -> None: ...
    TagToTagVectorMap: typing.Any

class VisualizationIDsInfo:
    """Stub for Mpr0.Services.Internal.Strong.Process._2017_05.Assignment.VisualizationIDsInfo"""
    def __init__(self) -> None: ...
    ForegroundElementsIDs: typing.Sequence[str]
    BackgroundElementsIDs: typing.Sequence[str]

__all__ = [
    'Assignment',
    'AssignmentDataInput',
    'AssignmentDataOutput',
    'AssignmentDataResponse',
    'AssignmentTypeInformation',
    'ClientRequiredInfo',
    'ConnectedObjectInfo',
    'DesignDisclosureViewData',
    'DesignElementViewsData',
    'DesignModelViewsData',
    'GetAssignmentTypeInformationResponse',
    'GetClientRequiredInformationInput',
    'GetClientRequiredInformationOutput',
    'GetClientRequiredInformationResponse',
    'GetConnectedInfoOutput',
    'GetConnectedInfoResponse',
    'GetDesignModelViewsResponse',
    'GetObjectsByVisualizationIDInfo',
    'GetVisualizationIDsInWorksetResponse',
    'GetVisualizationIDsResponse',
    'ProductElementFilterCriteriaInput',
    'SearchInfo',
    'SearchOptions',
    'SearchOutput',
    'SearchResponse',
    'SearchResult',
    'SortOptions',
    'TagToTagVectorInfo',
    'VisualizationIDsInfo',
]
