# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class ContextGroup:
    """Stub for Tca0.Services.Strong.Tcmaccess._2017_06.StudyManagement.ContextGroup"""
    def __init__(self) -> None: ...
    Contexts: typing.Sequence[typing.Any]
    CollaborationContext: typing.Any

class CreateInput:
    """Stub for Tca0.Services.Strong.Tcmaccess._2017_06.StudyManagement.CreateInput"""
    def __init__(self) -> None: ...
    Type: str
    StringProps: typing.Any
    StringArrayProps: typing.Any
    DoubleProps: typing.Any
    DoubleArrayProps: typing.Any
    FloatProps: typing.Any
    FloatArrayProps: typing.Any
    IntProps: typing.Any
    IntArrayProps: typing.Any
    BoolProps: typing.Any
    BoolArrayProps: typing.Any
    DateProps: typing.Any
    DateArrayProps: typing.Any
    TagProps: typing.Any
    TagArrayProps: typing.Any
    CompoundCreateInput: typing.Any

class OpenContextInfo:
    """Stub for Tca0.Services.Strong.Tcmaccess._2017_06.StudyManagement.OpenContextInfo"""
    def __init__(self) -> None: ...
    Context: typing.Any
    ObjectInfo: typing.Any
    Views: typing.Sequence[typing.Any]
    StructureContext: typing.Any

class OpenContextInput:
    """Stub for Tca0.Services.Strong.Tcmaccess._2017_06.StudyManagement.OpenContextInput"""
    def __init__(self) -> None: ...
    InputObject: typing.Any
    StructureContextTypes: typing.Sequence[str]
    OpenViews: bool
    OpenAssociatedContexts: bool
    ContextSettings: typing.Any

class OpenContextsResponse:
    """Stub for Tca0.Services.Strong.Tcmaccess._2017_06.StudyManagement.OpenContextsResponse"""
    def __init__(self) -> None: ...
    Output: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class StudyManagement:
    """Stub for Tca0.Services.Strong.Tcmaccess._2017_06.StudyManagement.StudyManagement"""
    def __init__(self) -> None: ...
    def OpenContexts(self, Input: typing.Sequence[typing.Any]) -> typing.Any: ...

__all__ = [
    'ContextGroup',
    'CreateInput',
    'OpenContextInfo',
    'OpenContextInput',
    'OpenContextsResponse',
    'StudyManagement',
]
