# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
from teamcenter.mat1.services.strong.materialmanagement import MaterialManagementService

class MaterialManagementRestBindingStub(MaterialManagementService):
    """Stub for Mat1.Services.Strong.Materialmanagement.MaterialManagementRestBindingStub"""
    def __init__(self, connection: typing.Any) -> None: ...
    def ExportMaterialsData(self, Input: typing.Sequence[typing.Any]) -> typing.Any: ...
    def GetMaterialSubstanceInfo(self, Objs: typing.Sequence[typing.Any]) -> typing.Any: ...
    def ImportMaterialsData(self, Input: typing.Sequence[typing.Any]) -> typing.Any: ...

class MaterialManagementService:
    """Stub for Mat1.Services.Strong.Materialmanagement.MaterialManagementService"""
    def __init__(self) -> None: ...
    def ExportMaterialsData(self, Input: typing.Sequence[typing.Any]) -> typing.Any: ...
    def GetMaterialSubstanceInfo(self, Objs: typing.Sequence[typing.Any]) -> typing.Any: ...
    def ImportMaterialsData(self, Input: typing.Sequence[typing.Any]) -> typing.Any: ...
    @classmethod
    def getService(cls, connection: typing.Any) -> typing.Any: ...

__all__ = [
    'MaterialManagementRestBindingStub',
    'MaterialManagementService',
    '_2012_09',
    '_2021_06',
]
