# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class EffectivitiesInputInfo2:
    """Stub for Teamcenter.Services.Internal.Strong.Structuremanagement._2021_12.EffectivitiesManagement.EffectivitiesInputInfo2"""
    def __init__(self) -> None: ...
    ClientId: str
    EffectivityComponent: typing.Any
    EndItemComponent: typing.Any
    DateRange: typing.Sequence[typing.Any]
    OpenEndedStatus: int
    Decision: int

class EffectivitiesManagement:
    """Stub for Teamcenter.Services.Internal.Strong.Structuremanagement._2021_12.EffectivitiesManagement.EffectivitiesManagement"""
    def __init__(self) -> None: ...
    def CreateOrUpdateDateEffectivities(self, EffectivitiesInfo: typing.Sequence[typing.Any], EffectivityGroupRevision: typing.Any) -> typing.Any: ...

__all__ = [
    'EffectivitiesInputInfo2',
    'EffectivitiesManagement',
]
