# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class CreateOccEffectivityInput:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2014_12.Effectivity.CreateOccEffectivityInput"""
    def __init__(self) -> None: ...
    BomLines: typing.Sequence[typing.Any]
    EffectivityInfoInput: typing.Any
    IsShared: bool

class Effectivity:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2014_12.Effectivity.Effectivity"""
    def __init__(self) -> None: ...
    def CreateOccurrenceEffectivities(self, Input: typing.Sequence[typing.Any]) -> typing.Any: ...
    def CreateReleaseStatusEffectivity(self, Input: typing.Sequence[typing.Any]) -> typing.Any: ...

class EffectivityInfoInput:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2014_12.Effectivity.EffectivityInfoInput"""
    def __init__(self) -> None: ...
    EffectivityId: str
    EndItem: typing.Any
    EndItemRev: typing.Any
    UnitRangeText: str
    DateRange: typing.Sequence[typing.Any]
    OpenEndedStatus: int
    IsProtected: bool

class ReleaseStatusEffectivityInput:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2014_12.Effectivity.ReleaseStatusEffectivityInput"""
    def __init__(self) -> None: ...
    ReleaseStatus: typing.Any
    EffectivityInfoInput: typing.Any

__all__ = [
    'CreateOccEffectivityInput',
    'Effectivity',
    'EffectivityInfoInput',
    'ReleaseStatusEffectivityInput',
]
