# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class Allocation:
    """Stub for Teamcenter.Services.Strong.Allocations._2011_06.Allocation.Allocation"""
    def __init__(self) -> None: ...
    def CreateAllocationContext2(self, Input: typing.Any) -> typing.Any: ...

class AllocationContextInput2:
    """Stub for Teamcenter.Services.Strong.Allocations._2011_06.Allocation.AllocationContextInput2"""
    def __init__(self) -> None: ...
    Id: str
    Name: str
    Type: str
    Revision: str
    OpenedBOMWindows: typing.Sequence[typing.Any]
    AttrValueMap: typing.Any

__all__ = [
    'Allocation',
    'AllocationContextInput2',
]
