# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class AttributeExchange:
    """Stub for Teamcenter.Services.Strong.Documentmanagement._2018_06.AttributeExchange.AttributeExchange"""
    def __init__(self) -> None: ...
    def UpdateDocumentProperties(self, InputObjects: typing.Sequence[typing.Any], CheckConfiguration: bool) -> typing.Any: ...

__all__ = [
    'AttributeExchange',
]
