# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class Column:
    """Stub for Saw1.Services.Internal.Strong.Projectmanagementaw._2019_12.ScheduleManagementAw.Column"""
    def __init__(self) -> None: ...
    ColumnName: str
    Order: str

class DayRanges3:
    """Stub for Saw1.Services.Internal.Strong.Projectmanagementaw._2019_12.ScheduleManagementAw.DayRanges3"""
    def __init__(self) -> None: ...
    Day: int
    Ranges: typing.Sequence[str]

class Filter:
    """Stub for Saw1.Services.Internal.Strong.Projectmanagementaw._2019_12.ScheduleManagementAw.Filter"""
    def __init__(self) -> None: ...
    AttributeName: str
    Criteria: str
    FilterValue: str

class FilterSet:
    """Stub for Saw1.Services.Internal.Strong.Projectmanagementaw._2019_12.ScheduleManagementAw.FilterSet"""
    def __init__(self) -> None: ...
    Filters: typing.Sequence[typing.Any]

class ManageProgramViewResponse:
    """Stub for Saw1.Services.Internal.Strong.Projectmanagementaw._2019_12.ScheduleManagementAw.ManageProgramViewResponse"""
    def __init__(self) -> None: ...
    ProgramView: typing.Any
    Configuration: typing.Any
    DayRanges: typing.Sequence[typing.Any]
    EventDateRanges: typing.Any
    Options: typing.Sequence[typing.Any]
    ProgramViewNodes: typing.Sequence[typing.Any]
    ProgramViewNodesJson: str
    ServiceData: typing.Any

class NameValueStringPair:
    """Stub for Saw1.Services.Internal.Strong.Projectmanagementaw._2019_12.ScheduleManagementAw.NameValueStringPair"""
    def __init__(self) -> None: ...
    Name: str
    StringValue: str

class ProgramViewConfiguration:
    """Stub for Saw1.Services.Internal.Strong.Projectmanagementaw._2019_12.ScheduleManagementAw.ProgramViewConfiguration"""
    def __init__(self) -> None: ...
    ScheduleUIDs: typing.Sequence[str]
    Columns: typing.Sequence[typing.Any]
    Groups: typing.Sequence[typing.Any]
    FilterSets: typing.Sequence[typing.Any]

class ProgramViewGroup:
    """Stub for Saw1.Services.Internal.Strong.Projectmanagementaw._2019_12.ScheduleManagementAw.ProgramViewGroup"""
    def __init__(self) -> None: ...
    AttributeName: str
    Range: str
    Color: str
    Order: str
    Rollups: typing.Sequence[typing.Any]

class ProgramViewInfo:
    """Stub for Saw1.Services.Internal.Strong.Projectmanagementaw._2019_12.ScheduleManagementAw.ProgramViewInfo"""
    def __init__(self) -> None: ...
    ProgramView: typing.Any
    OperationType: str
    ContextNodeId: str
    ReferenceNodeId: str
    InputOptions: typing.Sequence[typing.Any]
    ProgramViewConfiguration: typing.Any

class ProgramViewNode:
    """Stub for Saw1.Services.Internal.Strong.Projectmanagementaw._2019_12.ScheduleManagementAw.ProgramViewNode"""
    def __init__(self) -> None: ...
    IsTcObject: bool
    NodeProperties: typing.Sequence[typing.Any]

class ScheduleManagementAw:
    """Stub for Saw1.Services.Internal.Strong.Projectmanagementaw._2019_12.ScheduleManagementAw.ScheduleManagementAw"""
    def __init__(self) -> None: ...
    def ManageProgramView(self, ProgramViewInfo: typing.Any) -> typing.Any: ...

__all__ = [
    'Column',
    'DayRanges3',
    'Filter',
    'FilterSet',
    'ManageProgramViewResponse',
    'NameValueStringPair',
    'ProgramViewConfiguration',
    'ProgramViewGroup',
    'ProgramViewInfo',
    'ProgramViewNode',
    'ScheduleManagementAw',
]
