# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class AttributeTargetManagement:
    """Stub for Att1.Services.Strong.Attrtargetmgmtaw._2021_12.AttributeTargetManagement.AttributeTargetManagement"""
    def __init__(self) -> None: ...
    def PublishParameters(self, Inputs: typing.Sequence[typing.Any], Options: typing.Any) -> typing.Any: ...

class ComparisonElementPublishInput:
    """Stub for Att1.Services.Strong.Attrtargetmgmtaw._2021_12.AttributeTargetManagement.ComparisonElementPublishInput"""
    def __init__(self) -> None: ...
    SourceElements: typing.Sequence[typing.Any]
    ComparsionElement: typing.Any

class PublishParamOut:
    """Stub for Att1.Services.Strong.Attrtargetmgmtaw._2021_12.AttributeTargetManagement.PublishParamOut"""
    def __init__(self) -> None: ...
    ComparisonElement: typing.Any
    ProcessedParams: typing.Sequence[typing.Any]
    UnprocessedParams: typing.Sequence[typing.Any]

class PublishParametersInput:
    """Stub for Att1.Services.Strong.Attrtargetmgmtaw._2021_12.AttributeTargetManagement.PublishParametersInput"""
    def __init__(self) -> None: ...
    ClientId: str
    CompElementPublishInput: typing.Any
    ParametersPublishInput: typing.Sequence[typing.Any]

class PublishParametersOutput:
    """Stub for Att1.Services.Strong.Attrtargetmgmtaw._2021_12.AttributeTargetManagement.PublishParametersOutput"""
    def __init__(self) -> None: ...
    ClientId: str
    PublishParamOut: typing.Sequence[typing.Any]

class PublishParametersResp:
    """Stub for Att1.Services.Strong.Attrtargetmgmtaw._2021_12.AttributeTargetManagement.PublishParametersResp"""
    def __init__(self) -> None: ...
    Output: typing.Sequence[typing.Any]
    ServiceData: typing.Any

__all__ = [
    'AttributeTargetManagement',
    'ComparisonElementPublishInput',
    'PublishParamOut',
    'PublishParametersInput',
    'PublishParametersOutput',
    'PublishParametersResp',
]
