# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class Cae1GenerateCAEStructureInputs:
    """Stub for Cae1.Services.Internal.Strong.Caeaw._2018_12.SimulationManagementAw.Cae1GenerateCAEStructureInputs"""
    def __init__(self) -> None: ...
    RootElement: typing.Any
    SelectedElements: typing.Sequence[typing.Any]
    RevisionRule: typing.Any
    VariantRules: typing.Sequence[typing.Any]
    Domain: str
    StructureMapIR: typing.Any
    IsAsyncMode: bool

class Cae1SelectedBOMLineInfo:
    """Stub for Cae1.Services.Internal.Strong.Caeaw._2018_12.SimulationManagementAw.Cae1SelectedBOMLineInfo"""
    def __init__(self) -> None: ...
    CloneStableId: str
    BlLevel: str

class Cae1StructureMapFilterInclusionRule:
    """Stub for Cae1.Services.Internal.Strong.Caeaw._2018_12.SimulationManagementAw.Cae1StructureMapFilterInclusionRule"""
    def __init__(self) -> None: ...
    InclusionRuleFileTicket: str
    InclusionRuleFileItemRevName: str
    InclusionRuleFileItemRevDesc: str
    SelectedInclusionRuleItemRev: typing.Any

class Cae1TableColumnInfo:
    """Stub for Cae1.Services.Internal.Strong.Caeaw._2018_12.SimulationManagementAw.Cae1TableColumnInfo"""
    def __init__(self) -> None: ...
    Name: str
    DisplayName: str
    TypeName: str
    EnablePinning: bool
    PinnedLeft: bool
    EnableFiltering: bool
    EnableSorting: bool

class SimulationManagementAw:
    """Stub for Cae1.Services.Internal.Strong.Caeaw._2018_12.SimulationManagementAw.SimulationManagementAw"""
    def __init__(self) -> None: ...
    def GenerateCAEStructure(self, GenerateCAEStructureInputs: typing.Any) -> typing.Any: ...

__all__ = [
    'Cae1GenerateCAEStructureInputs',
    'Cae1SelectedBOMLineInfo',
    'Cae1StructureMapFilterInclusionRule',
    'Cae1TableColumnInfo',
    'SimulationManagementAw',
]
