# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class ConfigRuleInput:
    """Stub for Awb0.Services.Internal.Strong.Activeworkspacebom._2017_06.OccurrenceConfiguration.ConfigRuleInput"""
    def __init__(self) -> None: ...
    ProductContext: typing.Any
    StartIndex: int
    MaxToLoad: int
    TypeToFetch: str
    FetchOnlyPreferredConfiguration: bool
    SearchCriteria: str
    RequestPref: typing.Any

class ConfigRuleResponse:
    """Stub for Awb0.Services.Internal.Strong.Activeworkspacebom._2017_06.OccurrenceConfiguration.ConfigRuleResponse"""
    def __init__(self) -> None: ...
    Marker: int
    EndIndex: int
    TotalFound: int
    GlobalRevisionRule: typing.Any
    RevisionRules: typing.Sequence[typing.Any]
    PreferredEffectivityInfo: typing.Any
    AddOpenObjAsPreferredEndItem: bool
    VariantRules: typing.Sequence[typing.Any]
    PreferredVarRuleOwningObjects: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class EffectivityInfo:
    """Stub for Awb0.Services.Internal.Strong.Activeworkspacebom._2017_06.OccurrenceConfiguration.EffectivityInfo"""
    def __init__(self) -> None: ...
    EffectivityUnits: typing.Sequence[int]
    EffectivityEndItems: typing.Sequence[typing.Any]
    EffectivityDates: typing.Sequence[typing.Any]

class OccurrenceConfiguration:
    """Stub for Awb0.Services.Internal.Strong.Activeworkspacebom._2017_06.OccurrenceConfiguration.OccurrenceConfiguration"""
    def __init__(self) -> None: ...
    def GetConfigurationRules(self, Input: typing.Any) -> typing.Any: ...

__all__ = [
    'ConfigRuleInput',
    'ConfigRuleResponse',
    'EffectivityInfo',
    'OccurrenceConfiguration',
]
