# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class Realization:
    """Stub for Cpd0.Services.Strong.Cpdcore._2017_05.Realization.Realization"""
    def __init__(self) -> None: ...
    def UpdateSubsetsContent(self, SubsetContentInfos: typing.Sequence[typing.Any]) -> typing.Any: ...

class SubsetContentInfo:
    """Stub for Cpd0.Services.Strong.Cpdcore._2017_05.Realization.SubsetContentInfo"""
    def __init__(self) -> None: ...
    Subset: typing.Any
    ExecuteRecipe: bool

class SubsetContentsResponse:
    """Stub for Cpd0.Services.Strong.Cpdcore._2017_05.Realization.SubsetContentsResponse"""
    def __init__(self) -> None: ...
    RealizedContent: typing.Sequence[typing.Any]
    ServiceData: typing.Any

__all__ = [
    'Realization',
    'SubsetContentInfo',
    'SubsetContentsResponse',
]
