# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class BVRAnd4GDesignInstancesInput:
    """Stub for Mdo0.Services.Strong.Mdomanagement._2020_12.MultiDisciplinaryDataMgt.BVRAnd4GDesignInstancesInput"""
    def __init__(self) -> None: ...
    ClientId: str
    DesignInstancesFor4G: typing.Sequence[typing.Any]
    BvrDesignInstances: typing.Sequence[typing.Any]
    MdoObject: typing.Any
    Context: typing.Any

class BVRAnd4GDesignInstancesUnlinkInput:
    """Stub for Mdo0.Services.Strong.Mdomanagement._2020_12.MultiDisciplinaryDataMgt.BVRAnd4GDesignInstancesUnlinkInput"""
    def __init__(self) -> None: ...
    ClientId: str
    DesignInstancesFor4G: typing.Sequence[typing.Any]
    BvrDesignInstances: typing.Sequence[typing.Any]
    Context: typing.Any
    UnlinkAllAssociatedDesignInstances: bool

class BVRAssemblyDetails:
    """Stub for Mdo0.Services.Strong.Mdomanagement._2020_12.MultiDisciplinaryDataMgt.BVRAssemblyDetails"""
    def __init__(self) -> None: ...
    ToplineObject: typing.Any
    ConfigData: typing.Any

class BVRInstanceData:
    """Stub for Mdo0.Services.Strong.Mdomanagement._2020_12.MultiDisciplinaryDataMgt.BVRInstanceData"""
    def __init__(self) -> None: ...
    InstanceOccThreadPath: str
    ConfiguredObject: typing.Any
    AssemblyDetails: typing.Any

class GetLinked4GAndBVRInstancesResponse:
    """Stub for Mdo0.Services.Strong.Mdomanagement._2020_12.MultiDisciplinaryDataMgt.GetLinked4GAndBVRInstancesResponse"""
    def __init__(self) -> None: ...
    Output: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class GetLinkedInstancesInputFor4G:
    """Stub for Mdo0.Services.Strong.Mdomanagement._2020_12.MultiDisciplinaryDataMgt.GetLinkedInstancesInputFor4G"""
    def __init__(self) -> None: ...
    ClientId: str
    Input4GDesignInstance: typing.Any
    Context: typing.Any
    ConfigForOtherSide4GData: typing.Any
    ConfigForOtherSideBVRData: typing.Sequence[typing.Any]

class GetLinkedInstancesInputForBVR:
    """Stub for Mdo0.Services.Strong.Mdomanagement._2020_12.MultiDisciplinaryDataMgt.GetLinkedInstancesInputForBVR"""
    def __init__(self) -> None: ...
    ClientId: str
    InputBVRDesignInstance: typing.Any
    Context: typing.Any
    ConfigForOtherSide4GData: typing.Any
    ConfigForOtherSideBVRData: typing.Sequence[typing.Any]

class Impacted4GAndBVRInstanceInfo:
    """Stub for Mdo0.Services.Strong.Mdomanagement._2020_12.MultiDisciplinaryDataMgt.Impacted4GAndBVRInstanceInfo"""
    def __init__(self) -> None: ...
    DesignInstanceFor4G: typing.Any
    BvrInstanceData: typing.Any
    NeedsValidation: bool
    IsValidated: bool
    RelevantDomains: typing.Sequence[str]
    IrrelevantDomains: typing.Sequence[str]

class InstanceDataFor4G:
    """Stub for Mdo0.Services.Strong.Mdomanagement._2020_12.MultiDisciplinaryDataMgt.InstanceDataFor4G"""
    def __init__(self) -> None: ...
    DesignInstanceFor4G: typing.Any
    IsPreciseLink: bool

class InstancesToUnlinkOutput2:
    """Stub for Mdo0.Services.Strong.Mdomanagement._2020_12.MultiDisciplinaryDataMgt.InstancesToUnlinkOutput2"""
    def __init__(self) -> None: ...
    ClientId: str
    InstanceLinkingObject: typing.Sequence[typing.Any]

class InstancesToUnlinkResponse2:
    """Stub for Mdo0.Services.Strong.Mdomanagement._2020_12.MultiDisciplinaryDataMgt.InstancesToUnlinkResponse2"""
    def __init__(self) -> None: ...
    Output: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class Linked4GAndBVRInstances:
    """Stub for Mdo0.Services.Strong.Mdomanagement._2020_12.MultiDisciplinaryDataMgt.Linked4GAndBVRInstances"""
    def __init__(self) -> None: ...
    Context: typing.Any
    MdiObject: typing.Any
    MdoObjectsLinkedToMDI: typing.Sequence[typing.Any]
    InstancesInfo: typing.Sequence[typing.Any]

class Linked4GAndBVRInstancesOuput:
    """Stub for Mdo0.Services.Strong.Mdomanagement._2020_12.MultiDisciplinaryDataMgt.Linked4GAndBVRInstancesOuput"""
    def __init__(self) -> None: ...
    ClientId: str
    HasLinkedInstance: bool
    LinkedInstances: typing.Sequence[typing.Any]

class MultiDisciplinaryDataMgt:
    """Stub for Mdo0.Services.Strong.Mdomanagement._2020_12.MultiDisciplinaryDataMgt.MultiDisciplinaryDataMgt"""
    def __init__(self) -> None: ...
    def GetLinkedInstancesFor4G(self, Inputs: typing.Sequence[typing.Any]) -> typing.Any: ...
    def GetLinkedInstancesForBVR(self, Inputs: typing.Sequence[typing.Any]) -> typing.Any: ...
    def Link4GAndBVRDesignInstances(self, Inputs: typing.Sequence[typing.Any]) -> typing.Any: ...
    def Unlink4GAndBVRDesignInstances(self, Inputs: typing.Sequence[typing.Any]) -> typing.Any: ...

__all__ = [
    'BVRAnd4GDesignInstancesInput',
    'BVRAnd4GDesignInstancesUnlinkInput',
    'BVRAssemblyDetails',
    'BVRInstanceData',
    'GetLinked4GAndBVRInstancesResponse',
    'GetLinkedInstancesInputFor4G',
    'GetLinkedInstancesInputForBVR',
    'Impacted4GAndBVRInstanceInfo',
    'InstanceDataFor4G',
    'InstancesToUnlinkOutput2',
    'InstancesToUnlinkResponse2',
    'Linked4GAndBVRInstances',
    'Linked4GAndBVRInstancesOuput',
    'MultiDisciplinaryDataMgt',
]
