# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class ExportSearchResultsResponse:
    """Stub for Awp0.Services.Internal.Strong.Aws2._2018_12.Finder.ExportSearchResultsResponse"""
    def __init__(self) -> None: ...
    ServiceData: typing.Any
    TransientFileReadTickets: typing.Sequence[str]

class Finder:
    """Stub for Awp0.Services.Internal.Strong.Aws2._2018_12.Finder.Finder"""
    def __init__(self) -> None: ...
    def ExportSearchResults(self, SearchInput: typing.Any, ColumnConfig: typing.Any, ExportAll: bool, SelectedObjectUIDs: typing.Sequence[str], ApplicationFormat: str) -> typing.Any: ...

__all__ = [
    'ExportSearchResultsResponse',
    'Finder',
]
