# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class InstanceManagement:
    """Stub for Tm0.Services.Internal.Strong.Testmanagement._2015_10.InstanceManagement.InstanceManagement"""
    def __init__(self) -> None: ...
    def GetTestSteps(self, Inputs: typing.Sequence[typing.Any]) -> typing.Any: ...

class TestStepInfo:
    """Stub for Tm0.Services.Internal.Strong.Testmanagement._2015_10.InstanceManagement.TestStepInfo"""
    def __init__(self) -> None: ...
    Contents: typing.Sequence[typing.Any]

class TestStepsInputInfo:
    """Stub for Tm0.Services.Internal.Strong.Testmanagement._2015_10.InstanceManagement.TestStepsInputInfo"""
    def __init__(self) -> None: ...
    ClientId: str
    BomLineScope: typing.Any
    TestObject: typing.Any
    CustomProps: typing.Any

class TestStepsResponse:
    """Stub for Tm0.Services.Internal.Strong.Testmanagement._2015_10.InstanceManagement.TestStepsResponse"""
    def __init__(self) -> None: ...
    StepResults: typing.Sequence[typing.Any]
    SrvcData: typing.Any

class TestStepsResult:
    """Stub for Tm0.Services.Internal.Strong.Testmanagement._2015_10.InstanceManagement.TestStepsResult"""
    def __init__(self) -> None: ...
    ClientId: str
    Steps: typing.Sequence[typing.Any]

class TextSegmentOrPlaceholderInfo:
    """Stub for Tm0.Services.Internal.Strong.Testmanagement._2015_10.InstanceManagement.TextSegmentOrPlaceholderInfo"""
    def __init__(self) -> None: ...
    ElementType: str
    UiValue: str
    AllowedTypes: str
    Bomlines: typing.Sequence[typing.Any]
    PlaceholderStatus: str
    CustomProps: typing.Any

__all__ = [
    'InstanceManagement',
    'TestStepInfo',
    'TestStepsInputInfo',
    'TestStepsResponse',
    'TestStepsResult',
    'TextSegmentOrPlaceholderInfo',
]
