# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class AsMaintained:
    """Stub for Teamcenter.Services.Strong.Asmaintained._2010_04.AsMaintained.AsMaintained"""
    def __init__(self) -> None: ...
    def SearchInstallablePhysPart(self, Input: typing.Sequence[typing.Any]) -> typing.Any: ...
    def SetMroWindowTopLine(self, Input: typing.Sequence[typing.Any]) -> typing.Any: ...

class SearchInstallablePhysPartInfo:
    """Stub for Teamcenter.Services.Strong.Asmaintained._2010_04.AsMaintained.SearchInstallablePhysPartInfo"""
    def __init__(self) -> None: ...
    SearchMap: typing.Any

class SearchInstallablePhysPartInputInfo:
    """Stub for Teamcenter.Services.Strong.Asmaintained._2010_04.AsMaintained.SearchInstallablePhysPartInputInfo"""
    def __init__(self) -> None: ...
    ClientId: str
    PhysBOMLine: typing.Any
    UsageBOMLine: typing.Any
    SearchInfo: typing.Any

class SearchInstallablePhysPartOutput:
    """Stub for Teamcenter.Services.Strong.Asmaintained._2010_04.AsMaintained.SearchInstallablePhysPartOutput"""
    def __init__(self) -> None: ...
    ClientId: str
    PrefInstallablePhysParts: typing.Sequence[typing.Any]
    AltInstallablePhysParts: typing.Sequence[typing.Any]
    SubInstallablePhysParts: typing.Sequence[typing.Any]
    DeviatedInstallablePhysParts: typing.Sequence[typing.Any]

class SearchInstallablePhysPartResponse:
    """Stub for Teamcenter.Services.Strong.Asmaintained._2010_04.AsMaintained.SearchInstallablePhysPartResponse"""
    def __init__(self) -> None: ...
    Output: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class SetMroWindowTopLineInfo:
    """Stub for Teamcenter.Services.Strong.Asmaintained._2010_04.AsMaintained.SetMroWindowTopLineInfo"""
    def __init__(self) -> None: ...
    ClientId: str
    BomWindow: typing.Any
    Item: typing.Any
    ItemRev: typing.Any
    MroRevRule: typing.Any

class SetMroWindowTopLineOutput:
    """Stub for Teamcenter.Services.Strong.Asmaintained._2010_04.AsMaintained.SetMroWindowTopLineOutput"""
    def __init__(self) -> None: ...
    ClientId: str
    TopLine: typing.Any

class SetMroWindowTopLineResponse:
    """Stub for Teamcenter.Services.Strong.Asmaintained._2010_04.AsMaintained.SetMroWindowTopLineResponse"""
    def __init__(self) -> None: ...
    Output: typing.Sequence[typing.Any]
    ServiceData: typing.Any

__all__ = [
    'AsMaintained',
    'SearchInstallablePhysPartInfo',
    'SearchInstallablePhysPartInputInfo',
    'SearchInstallablePhysPartOutput',
    'SearchInstallablePhysPartResponse',
    'SetMroWindowTopLineInfo',
    'SetMroWindowTopLineOutput',
    'SetMroWindowTopLineResponse',
]
