# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class ContentManagement:
    """Stub for Teamcenter.Services.Internal.Strong.Contmgmtbase._2020_01.ContentManagement.ContentManagement"""
    def __init__(self) -> None: ...
    def ImportTranslation(self, FileTickets: typing.Sequence[str]) -> typing.Any: ...

__all__ = [
    'ContentManagement',
]
