# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
from teamcenter.system import Attribute

class AllowNullAttribute(Attribute):
    """Stub for System.Diagnostics.CodeAnalysis.AllowNullAttribute"""
    def __init__(self) -> None: ...

class DoesNotReturnIfAttribute(Attribute):
    """Stub for System.Diagnostics.CodeAnalysis.DoesNotReturnIfAttribute"""
    def __init__(self, parameterValue: bool) -> None: ...
    @property
    def ParameterValue(self) -> bool: ...

class MaybeNullAttribute(Attribute):
    """Stub for System.Diagnostics.CodeAnalysis.MaybeNullAttribute"""
    def __init__(self) -> None: ...

class NotNullAttribute(Attribute):
    """Stub for System.Diagnostics.CodeAnalysis.NotNullAttribute"""
    def __init__(self) -> None: ...

class NotNullWhenAttribute(Attribute):
    """Stub for System.Diagnostics.CodeAnalysis.NotNullWhenAttribute"""
    def __init__(self, returnValue: bool) -> None: ...
    @property
    def ReturnValue(self) -> bool: ...

class UnconditionalSuppressMessageAttribute(Attribute):
    """Stub for System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessageAttribute"""
    def __init__(self, category: str, checkId: str) -> None: ...
    @property
    def Category(self) -> str: ...
    @property
    def CheckId(self) -> str: ...
    @property
    def Scope(self) -> str: ...
    @property
    def Target(self) -> str: ...
    @property
    def MessageId(self) -> str: ...
    @property
    def Justification(self) -> str: ...

__all__ = [
    'AllowNullAttribute',
    'DoesNotReturnIfAttribute',
    'MaybeNullAttribute',
    'NotNullAttribute',
    'NotNullWhenAttribute',
    'UnconditionalSuppressMessageAttribute',
]
