# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
from teamcenter.services.internal.strong.contmgmtbase import ContentManagementService

class ContentManagementRestBindingStub(ContentManagementService):
    """Stub for Teamcenter.Services.Internal.Strong.Contmgmtbase.ContentManagementRestBindingStub"""
    def __init__(self, connection: typing.Any) -> None: ...
    def GetTopicTypesAndRelatedTopics(self, TopicType: typing.Any, TopicTypeNameFilter: str, IncludeReferencedTopics: bool) -> typing.Any: ...
    def ImportTranslation(self, FileTickets: typing.Sequence[str]) -> typing.Any: ...

class ContentManagementService:
    """Stub for Teamcenter.Services.Internal.Strong.Contmgmtbase.ContentManagementService"""
    def __init__(self) -> None: ...
    def GetTopicTypesAndRelatedTopics(self, TopicType: typing.Any, TopicTypeNameFilter: str, IncludeReferencedTopics: bool) -> typing.Any: ...
    def ImportTranslation(self, FileTickets: typing.Sequence[str]) -> typing.Any: ...
    @classmethod
    def getService(cls, connection: typing.Any) -> typing.Any: ...

__all__ = [
    'ContentManagementRestBindingStub',
    'ContentManagementService',
    '_2020_01',
    '_2021_06',
]
