# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class PurgingCriteria:
    """Stub for Scp0.Services.Strong.Substancecompliance._2024_06.SubstanceCompliance.PurgingCriteria"""
    def __init__(self) -> None: ...
    ArchivalStatus: str
    Criteria: str
    StartDate: typing.Any
    EndDate: typing.Any

class SubstanceCompliance:
    """Stub for Scp0.Services.Strong.Substancecompliance._2024_06.SubstanceCompliance.SubstanceCompliance"""
    def __init__(self) -> None: ...
    def PurgeObjects(self, RunInBackground: bool, PurgingCriteria: typing.Sequence[typing.Any]) -> typing.Any: ...

__all__ = [
    'PurgingCriteria',
    'SubstanceCompliance',
]
