# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class DataManagement:
    """Stub for Teamcenter.Services.Internal.Strong.Cad._2007_12.DataManagement.DataManagement"""
    def __init__(self) -> None: ...
    def CreateAppUidObjects(self, Count: int) -> typing.Any: ...

__all__ = [
    'DataManagement',
]
