# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class ChangeContextStructIn:
    """Stub for Fnd0.Services.Strong.Editcontext._2016_10.DataManagement.ChangeContextStructIn"""
    def __init__(self) -> None: ...
    ChangeConfigurationMode: str
    InputObjects: typing.Sequence[typing.Any]

class ChangeContextStructOut:
    """Stub for Fnd0.Services.Strong.Editcontext._2016_10.DataManagement.ChangeContextStructOut"""
    def __init__(self) -> None: ...
    ChangeContext: typing.Any
    ConfiguredObjs: typing.Sequence[typing.Any]

class DataManagement:
    """Stub for Fnd0.Services.Strong.Editcontext._2016_10.DataManagement.DataManagement"""
    def __init__(self) -> None: ...
    def SetChangeContext2(self, Inputs: typing.Any) -> typing.Any: ...

class SetChangeContextResponse2:
    """Stub for Fnd0.Services.Strong.Editcontext._2016_10.DataManagement.SetChangeContextResponse2"""
    def __init__(self) -> None: ...
    ServiceData: typing.Any
    ConfiguredObjectsMap: typing.Any

__all__ = [
    'ChangeContextStructIn',
    'ChangeContextStructOut',
    'DataManagement',
    'SetChangeContextResponse2',
]
