# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class DataManagement:
    """Stub for Teamcenter.Services.Strong.Core._2011_06.DataManagement.DataManagement"""
    def __init__(self) -> None: ...
    def GetTraceReport(self, Input: typing.Any) -> typing.Any: ...
    def SaveAsObjects(self, SaveAsIn: typing.Sequence[typing.Any]) -> typing.Any: ...
    def ValidateRevIds(self, Inputs: typing.Sequence[typing.Any]) -> typing.Any: ...

class DeepCopyData:
    """Stub for Teamcenter.Services.Strong.Core._2011_06.DataManagement.DeepCopyData"""
    def __init__(self) -> None: ...
    AttachedObject: typing.Any
    PropertyName: str
    PropertyType: str
    CopyAction: str
    IsTargetPrimary: bool
    IsRequired: bool
    CopyRelations: bool
    SaveAsInputTypeName: str
    ChildDeepCopyData: typing.Sequence[typing.Any]
    SaveAsInput: typing.Any

class ObjectInfo:
    """Stub for Teamcenter.Services.Strong.Core._2011_06.DataManagement.ObjectInfo"""
    def __init__(self) -> None: ...
    ContextName: str
    DisplayObj: typing.Any
    Object: typing.Any
    BomView: typing.Any

class Report:
    """Stub for Teamcenter.Services.Strong.Core._2011_06.DataManagement.Report"""
    def __init__(self) -> None: ...
    Parent: typing.Any
    Children: typing.Sequence[typing.Any]

class SaveAsIn:
    """Stub for Teamcenter.Services.Strong.Core._2011_06.DataManagement.SaveAsIn"""
    def __init__(self) -> None: ...
    TargetObject: typing.Any
    SaveAsInput: typing.Any
    DeepCopyDatas: typing.Sequence[typing.Any]

class SaveAsInput:
    """Stub for Teamcenter.Services.Strong.Core._2011_06.DataManagement.SaveAsInput"""
    def __init__(self) -> None: ...
    BoName: str
    StringProps: typing.Any
    StringArrayProps: typing.Any
    DoubleProps: typing.Any
    DoubleArrayProps: typing.Any
    FloatProps: typing.Any
    FloatArrayProps: typing.Any
    IntProps: typing.Any
    IntArrayProps: typing.Any
    BoolProps: typing.Any
    BoolArrayProps: typing.Any
    DateProps: typing.Any
    DateArrayProps: typing.Any
    TagProps: typing.Any
    TagArrayProps: typing.Any

class SaveAsObjectsResponse:
    """Stub for Teamcenter.Services.Strong.Core._2011_06.DataManagement.SaveAsObjectsResponse"""
    def __init__(self) -> None: ...
    Output: typing.Sequence[typing.Any]
    SaveAsTrees: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class SaveAsOut:
    """Stub for Teamcenter.Services.Strong.Core._2011_06.DataManagement.SaveAsOut"""
    def __init__(self) -> None: ...
    TargetObject: typing.Any
    Objects: typing.Sequence[typing.Any]

class SaveAsTree:
    """Stub for Teamcenter.Services.Strong.Core._2011_06.DataManagement.SaveAsTree"""
    def __init__(self) -> None: ...
    OriginalObject: typing.Any
    ObjectCopy: typing.Any
    ChildSaveAsNodes: typing.Sequence[typing.Any]

class TraceReport:
    """Stub for Teamcenter.Services.Strong.Core._2011_06.DataManagement.TraceReport"""
    def __init__(self) -> None: ...
    DefiningTree: typing.Sequence[typing.Any]
    IndirectDefiningTree: typing.Sequence[typing.Any]
    ComplyingTree: typing.Sequence[typing.Any]
    IndirectComplyingTree: typing.Sequence[typing.Any]
    SelectedObject: typing.Any
    PersistentObjects: typing.Sequence[typing.Any]

class TraceabilityInfoInput:
    """Stub for Teamcenter.Services.Strong.Core._2011_06.DataManagement.TraceabilityInfoInput"""
    def __init__(self) -> None: ...
    SelectedObjs: typing.Sequence[typing.Any]
    ReportType: int
    ReportDepth: int
    IsIndirectTraceReportNeeded: bool
    RelationTypeName: str

class TraceabilityReportOutput:
    """Stub for Teamcenter.Services.Strong.Core._2011_06.DataManagement.TraceabilityReportOutput"""
    def __init__(self) -> None: ...
    TraceReports: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class ValidateRevIdsInfo:
    """Stub for Teamcenter.Services.Strong.Core._2011_06.DataManagement.ValidateRevIdsInfo"""
    def __init__(self) -> None: ...
    RevId: str
    ItemObject: typing.Any
    ItemType: str

class ValidateRevIdsOutput:
    """Stub for Teamcenter.Services.Strong.Core._2011_06.DataManagement.ValidateRevIdsOutput"""
    def __init__(self) -> None: ...
    ModRevId: str
    RevIdStatus: str

class ValidateRevIdsResponse:
    """Stub for Teamcenter.Services.Strong.Core._2011_06.DataManagement.ValidateRevIdsResponse"""
    def __init__(self) -> None: ...
    Output: typing.Sequence[typing.Any]
    ServiceData: typing.Any

__all__ = [
    'DataManagement',
    'DeepCopyData',
    'ObjectInfo',
    'Report',
    'SaveAsIn',
    'SaveAsInput',
    'SaveAsObjectsResponse',
    'SaveAsOut',
    'SaveAsTree',
    'TraceReport',
    'TraceabilityInfoInput',
    'TraceabilityReportOutput',
    'ValidateRevIdsInfo',
    'ValidateRevIdsOutput',
    'ValidateRevIdsResponse',
]
