# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class ACInput:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2012_02.StructureVerification.ACInput"""
    def __init__(self) -> None: ...
    SourceObjects: typing.Sequence[typing.Any]
    TargetObjects: typing.Sequence[typing.Any]
    Options: int
    SourceContextLine: typing.Any
    TargetContextLine: typing.Any
    MatchType: int
    SourceFilteringRule: str
    TargetFilteringRule: str
    SourceDepth: int
    TargetDepth: int
    ResultName: str
    ResultDesc: str
    ReportCriteria: typing.Any
    ReportMode: int
    PartialMatchCriteria: typing.Any
    IncludeScopeLines: bool

class AssignmentDetail:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2012_02.StructureVerification.AssignmentDetail"""
    def __init__(self) -> None: ...
    Assignments: typing.Sequence[typing.Any]
    MatchType: int

class AssignmentTypeDetail:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2012_02.StructureVerification.AssignmentTypeDetail"""
    def __init__(self) -> None: ...
    Index: int
    Details: typing.Sequence[typing.Any]
    EquivalentLines: typing.Sequence[typing.Any]

class AssignmentTypeDetailElement:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2012_02.StructureVerification.AssignmentTypeDetailElement"""
    def __init__(self) -> None: ...
    AssignmentType: str
    ManualAssignments: typing.Sequence[typing.Any]
    LogicalAssignments: typing.Sequence[typing.Any]

class AsyncACInput:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2012_02.StructureVerification.AsyncACInput"""
    def __init__(self) -> None: ...
    SourceObjects: typing.Sequence[typing.Any]
    TargetObjects: typing.Sequence[typing.Any]
    Options: int
    SourceContextLine: typing.Any
    TargetContextLine: typing.Any
    MatchType: int
    SourceFilteringRule: str
    TargetFilteringRule: str
    SourceDepth: int
    TargetDepth: int
    ResultName: str
    ResultDesc: str
    ReportCriteria: typing.Any
    ReportMode: int
    PartialMatchCriteria: typing.Any
    IncludeScopeLines: bool

class AsyncDetails:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2012_02.StructureVerification.AsyncDetails"""
    def __init__(self) -> None: ...
    Identifier: str
    Mode: str
    Site: int
    Priority: int
    StartTime: typing.Any
    EndTime: typing.Any
    DaysOfWeek: typing.Sequence[bool]
    EndAfterOccurrences: int
    PrimaryObjects: typing.Sequence[typing.Any]
    SecondaryObjects: typing.Sequence[typing.Any]

class AsyncPartialMatchCriteria:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2012_02.StructureVerification.AsyncPartialMatchCriteria"""
    def __init__(self) -> None: ...
    IntMap: typing.Any
    DblMap: typing.Any
    StrMap: typing.Any
    ObjMap: typing.Any

class AsyncReportCriteria:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2012_02.StructureVerification.AsyncReportCriteria"""
    def __init__(self) -> None: ...
    RdTag: typing.Any
    ReportName: str
    StylesheetTag: typing.Any
    StylesheetName: str
    DatasetName: str
    CriteriaName: typing.Sequence[str]
    CriteriaValues: typing.Sequence[str]
    DatasetCtxUID: str
    DatasetCtxObj: typing.Any
    RelationName: str
    DatasetType: str
    ReportOptionsNames: typing.Sequence[str]
    ReportOptionsValues: typing.Sequence[str]
    ContextObjects: typing.Sequence[typing.Any]
    ContextObjectUIDs: typing.Sequence[str]

class BOMLineNetEffectivityDetail:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2012_02.StructureVerification.BOMLineNetEffectivityDetail"""
    def __init__(self) -> None: ...
    Line: typing.Any
    EffDetails: typing.Sequence[typing.Any]

class BatchDetails:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2012_02.StructureVerification.BatchDetails"""
    def __init__(self) -> None: ...
    Identifier: str
    Mode: str
    Site: int
    Priority: int
    StartTime: typing.Any
    EndTime: typing.Any
    DaysOfWeek: typing.Sequence[bool]
    EndAfterOccurrences: int
    PrimaryObjects: typing.Sequence[typing.Any]
    SecondaryObjects: typing.Sequence[typing.Any]

class CompareNetEffectivityGroup:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2012_02.StructureVerification.CompareNetEffectivityGroup"""
    def __init__(self) -> None: ...
    SrcLineEffectivities: typing.Sequence[typing.Any]
    TargetLineEffectivities: typing.Sequence[typing.Any]
    MissingSrcDetails: typing.Sequence[typing.Any]
    MissingTargetDetails: typing.Sequence[typing.Any]
    OverlappingEffectivities: typing.Sequence[typing.Any]
    MatchingEffectivities: typing.Sequence[typing.Any]
    IsMisMatch: bool

class CompareNetEffectivityResponse:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2012_02.StructureVerification.CompareNetEffectivityResponse"""
    def __init__(self) -> None: ...
    CompareGroups: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class DescendentDetail:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2012_02.StructureVerification.DescendentDetail"""
    def __init__(self) -> None: ...
    Index: int
    Details: typing.Sequence[typing.Any]
    EquivalentLines: typing.Sequence[typing.Any]

class DescendentDetailElement:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2012_02.StructureVerification.DescendentDetailElement"""
    def __init__(self) -> None: ...
    Children: typing.Sequence[typing.Any]
    MatchType: int

class EndItemAndUnitDetails:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2012_02.StructureVerification.EndItemAndUnitDetails"""
    def __init__(self) -> None: ...
    EndItem: typing.Any
    Details: typing.Sequence[typing.Any]

class EquivalentLines:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2012_02.StructureVerification.EquivalentLines"""
    def __init__(self) -> None: ...
    EqvSrcLines: typing.Sequence[typing.Any]
    EqvTargetLines: typing.Sequence[typing.Any]

class EquivalentSetElement:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2012_02.StructureVerification.EquivalentSetElement"""
    def __init__(self) -> None: ...
    EqvSrcLines: typing.Sequence[typing.Any]
    EqvTargetLines: typing.Sequence[typing.Any]
    Criteria: typing.Any

class GetAssignmentComparisonDetailsResponse:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2012_02.StructureVerification.GetAssignmentComparisonDetailsResponse"""
    def __init__(self) -> None: ...
    Details: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class GetDescendentComparisonDetailsResponse:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2012_02.StructureVerification.GetDescendentComparisonDetailsResponse"""
    def __init__(self) -> None: ...
    Details: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class GetPartitionComparisonDetailsResponse:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2012_02.StructureVerification.GetPartitionComparisonDetailsResponse"""
    def __init__(self) -> None: ...
    Details: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class GetPredecessorComparisonDetailsResponse:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2012_02.StructureVerification.GetPredecessorComparisonDetailsResponse"""
    def __init__(self) -> None: ...
    Details: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class GetPropertyComparisonDetailsResponse:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2012_02.StructureVerification.GetPropertyComparisonDetailsResponse"""
    def __init__(self) -> None: ...
    Details: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class LogicalAssignmentDetail:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2012_02.StructureVerification.LogicalAssignmentDetail"""
    def __init__(self) -> None: ...
    Criteria: typing.Sequence[str]
    ResolvedAssignments: typing.Sequence[typing.Any]
    MatchType: int
    LogicalAssignments: typing.Sequence[typing.Any]

class PartialMatchCriteria:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2012_02.StructureVerification.PartialMatchCriteria"""
    def __init__(self) -> None: ...
    IntMap: typing.Any
    DblMap: typing.Any
    StrMap: typing.Any
    ObjMap: typing.Any
    DateMap: typing.Any

class PartitionDetail:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2012_02.StructureVerification.PartitionDetail"""
    def __init__(self) -> None: ...
    Index: int
    Partitions: typing.Sequence[typing.Any]
    IsDifferent: bool
    EquivalentLines: typing.Sequence[typing.Any]

class PredecessorDetail:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2012_02.StructureVerification.PredecessorDetail"""
    def __init__(self) -> None: ...
    Index: int
    Details: typing.Sequence[typing.Any]
    EquivalentLines: typing.Sequence[typing.Any]

class PredecessorDetailElement:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2012_02.StructureVerification.PredecessorDetailElement"""
    def __init__(self) -> None: ...
    Predecessors: typing.Sequence[typing.Any]
    MatchType: int

class PropagationInput:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2012_02.StructureVerification.PropagationInput"""
    def __init__(self) -> None: ...
    Target: typing.Any
    Sources: typing.Sequence[typing.Any]
    Criteria: typing.Any

class PropagationResponse:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2012_02.StructureVerification.PropagationResponse"""
    def __init__(self) -> None: ...
    Results: typing.Sequence[typing.Any]
    LogFileTicket: str
    ServiceData: typing.Any

class PropagationResult:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2012_02.StructureVerification.PropagationResult"""
    def __init__(self) -> None: ...
    Index: int
    PropagationResults: typing.Any

class PropagationResultElement:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2012_02.StructureVerification.PropagationResultElement"""
    def __init__(self) -> None: ...
    Object: typing.Any
    PropagatedProperties: typing.Sequence[str]
    LogFileTicket: str

class PropertyDetail:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2012_02.StructureVerification.PropertyDetail"""
    def __init__(self) -> None: ...
    Index: int
    Details: typing.Sequence[typing.Any]

class PropertyDetailsElement:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2012_02.StructureVerification.PropertyDetailsElement"""
    def __init__(self) -> None: ...
    PropertyName: str
    IsDifferent: bool

class StructureVerification:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2012_02.StructureVerification.StructureVerification"""
    def __init__(self) -> None: ...
    def AccountabilityCheck(self, Input: typing.Any, BatchDetails: typing.Any) -> typing.Any: ...
    def CompareNetEffectivity(self, Lines: typing.Sequence[typing.Any], IgnoreOverlapErrors: bool, UseStructureConfiguration: bool, ReturnOnFirstMismatch: bool) -> typing.Any: ...
    def GetAssignmentComparisonDetails(self, EquivalentObjects: typing.Sequence[typing.Any], PartRelationTypes: typing.Sequence[str], ToolRelationTypes: typing.Sequence[str], CompareLA: int, CompareManual: bool) -> typing.Any: ...
    def GetDescendentComparisonDetails(self, Input: typing.Sequence[typing.Any], IgnoreStructureSpecific: bool) -> typing.Any: ...
    def GetPartitionComparisonDetails(self, Input: typing.Sequence[typing.Any]) -> typing.Any: ...
    def GetPredecessorComparisonDetails(self, Input: typing.Sequence[typing.Any], IgnoreStructureSpecific: bool) -> typing.Any: ...
    def GetPropertyComparisonDetails(self, EquivalentObjects: typing.Sequence[typing.Any]) -> typing.Any: ...
    def PropagateProperties(self, Input: typing.Sequence[typing.Any]) -> typing.Any: ...

class UnitAndLineDetails:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2012_02.StructureVerification.UnitAndLineDetails"""
    def __init__(self) -> None: ...
    Units: typing.Sequence[int]
    Dates: typing.Sequence[typing.Any]
    SrcLines: typing.Sequence[typing.Any]
    TargetLines: typing.Sequence[typing.Any]

__all__ = [
    'ACInput',
    'AssignmentDetail',
    'AssignmentTypeDetail',
    'AssignmentTypeDetailElement',
    'AsyncACInput',
    'AsyncDetails',
    'AsyncPartialMatchCriteria',
    'AsyncReportCriteria',
    'BOMLineNetEffectivityDetail',
    'BatchDetails',
    'CompareNetEffectivityGroup',
    'CompareNetEffectivityResponse',
    'DescendentDetail',
    'DescendentDetailElement',
    'EndItemAndUnitDetails',
    'EquivalentLines',
    'EquivalentSetElement',
    'GetAssignmentComparisonDetailsResponse',
    'GetDescendentComparisonDetailsResponse',
    'GetPartitionComparisonDetailsResponse',
    'GetPredecessorComparisonDetailsResponse',
    'GetPropertyComparisonDetailsResponse',
    'LogicalAssignmentDetail',
    'PartialMatchCriteria',
    'PartitionDetail',
    'PredecessorDetail',
    'PredecessorDetailElement',
    'PropagationInput',
    'PropagationResponse',
    'PropagationResult',
    'PropagationResultElement',
    'PropertyDetail',
    'PropertyDetailsElement',
    'StructureVerification',
    'UnitAndLineDetails',
]
