# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class AddObjectData3:
    """Stub for Awb0.Services.Internal.Strong.Activeworkspacebom._2021_06.OccurrenceManagement.AddObjectData3"""
    def __init__(self) -> None: ...
    ParentElement: typing.Any
    ObjectsToBeAdded: typing.Sequence[typing.Any]
    SiblingElement: typing.Any
    InputCtxt: typing.Any
    SortCriteria: typing.Any
    AddObjectIntent: str
    FetchPagedOccurrences: bool
    RequestPref: typing.Any
    NumberOfElements: int
    CreateInputs: typing.Sequence[typing.Any]

class InfoForAddElemResp3:
    """Stub for Awb0.Services.Internal.Strong.Activeworkspacebom._2021_06.OccurrenceManagement.InfoForAddElemResp3"""
    def __init__(self) -> None: ...
    PreferredTypeInfo: typing.Any
    AllowedTypeInfos: typing.Sequence[typing.Any]
    PreferredExists: bool
    ServiceData: typing.Any
    RequestPref: typing.Any

class OccurrenceManagement:
    """Stub for Awb0.Services.Internal.Strong.Activeworkspacebom._2021_06.OccurrenceManagement.OccurrenceManagement"""
    def __init__(self) -> None: ...
    def AddObject3(self, Input: typing.Any) -> typing.Any: ...
    def GetInfoForAddElement4(self, GetInfoForElementIn: typing.Any) -> typing.Any: ...
    def UpdateContentBasedOnRevision2(self, Input: typing.Any) -> typing.Any: ...

class UpdateContentBasedOnRevInput2:
    """Stub for Awb0.Services.Internal.Strong.Activeworkspacebom._2021_06.OccurrenceManagement.UpdateContentBasedOnRevInput2"""
    def __init__(self) -> None: ...
    Element: typing.Any
    WorkspaceObject: typing.Any
    ProductContext: typing.Any
    RequestPref: typing.Any

__all__ = [
    'AddObjectData3',
    'InfoForAddElemResp3',
    'OccurrenceManagement',
    'UpdateContentBasedOnRevInput2',
]
