# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class ACLInfoResponse:
    """Stub for Teamcenter.Services.Internal.Strong.Administration._2008_06.IRM.ACLInfoResponse"""
    def __init__(self) -> None: ...
    AclNameInfos: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class ACLNameInfo:
    """Stub for Teamcenter.Services.Internal.Strong.Administration._2008_06.IRM.ACLNameInfo"""
    def __init__(self) -> None: ...
    AclObject: typing.Any
    AclName: str

class IRM:
    """Stub for Teamcenter.Services.Internal.Strong.Administration._2008_06.IRM.IRM"""
    def __init__(self) -> None: ...
    def GetACLsByType(self, AclsType: int) -> typing.Any: ...

__all__ = [
    'ACLInfoResponse',
    'ACLNameInfo',
    'IRM',
]
