# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class DataManagement:
    """Stub for Fnd0.Services.Strong.Editcontext._2016_04.DataManagement.DataManagement"""
    def __init__(self) -> None: ...
    def SetChangeContext(self, Inputs: typing.Any) -> typing.Any: ...

class SetChangeContextResponse:
    """Stub for Fnd0.Services.Strong.Editcontext._2016_04.DataManagement.SetChangeContextResponse"""
    def __init__(self) -> None: ...
    ServiceData: typing.Any
    ConfiguredObjects: typing.Any

__all__ = [
    'DataManagement',
    'SetChangeContextResponse',
]
