# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class ReviewDeclInfo:
    """Stub for Scp0.Services.Strong.Substancecompliance._2015_10.SubstanceCompliance.ReviewDeclInfo"""
    def __init__(self) -> None: ...
    TargetObject: typing.Any
    DeclarationRev: typing.Any
    ComplianceResults: typing.Sequence[typing.Any]
    DeclarationType: str

class ReviewDeclarationResponse:
    """Stub for Scp0.Services.Strong.Substancecompliance._2015_10.SubstanceCompliance.ReviewDeclarationResponse"""
    def __init__(self) -> None: ...
    ServiceData: typing.Any
    ReviewDeclInfoMap: typing.Any

class SubstanceCompliance:
    """Stub for Scp0.Services.Strong.Substancecompliance._2015_10.SubstanceCompliance.SubstanceCompliance"""
    def __init__(self) -> None: ...
    def GetDeclarationDetailsForReview(self, ReviewTasks: typing.Sequence[typing.Any]) -> typing.Any: ...

__all__ = [
    'ReviewDeclInfo',
    'ReviewDeclarationResponse',
    'SubstanceCompliance',
]
