# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class FindStudiesInfo:
    """Stub for Tca0.Services.Strong.Tcmaccess._2016_12.StudyManagement.FindStudiesInfo"""
    def __init__(self) -> None: ...
    CcObject: typing.Any
    Scopes: typing.Sequence[typing.Any]
    SearchType: str
    SearchParameters: typing.Any

class FindStudiesOutput:
    """Stub for Tca0.Services.Strong.Tcmaccess._2016_12.StudyManagement.FindStudiesOutput"""
    def __init__(self) -> None: ...
    Results: typing.Sequence[typing.Any]
    TotalFound: int
    Finished: bool

class FindStudiesResponse:
    """Stub for Tca0.Services.Strong.Tcmaccess._2016_12.StudyManagement.FindStudiesResponse"""
    def __init__(self) -> None: ...
    FindStudiesOutput: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class SearchParam:
    """Stub for Tca0.Services.Strong.Tcmaccess._2016_12.StudyManagement.SearchParam"""
    def __init__(self) -> None: ...
    SortAttribute: str
    IsAscending: bool
    StartFrom: typing.Any
    StartFromIndex: int
    PageSize: int
    SearchTerm: str
    PropertyNames: typing.Sequence[str]
    SearchFilterMap: typing.Any

class StudyAndStudyStructureContext:
    """Stub for Tca0.Services.Strong.Tcmaccess._2016_12.StudyManagement.StudyAndStudyStructureContext"""
    def __init__(self) -> None: ...
    Study: typing.Any
    StudySC: typing.Any

class StudyManagement:
    """Stub for Tca0.Services.Strong.Tcmaccess._2016_12.StudyManagement.StudyManagement"""
    def __init__(self) -> None: ...
    def FindStudiesInCC1(self, Input: typing.Sequence[typing.Any]) -> typing.Any: ...

__all__ = [
    'FindStudiesInfo',
    'FindStudiesOutput',
    'FindStudiesResponse',
    'SearchParam',
    'StudyAndStudyStructureContext',
    'StudyManagement',
]
