# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class ConditionalEnricher:
    """Stub for Serilog.Core.Enrichers.ConditionalEnricher"""
    def __init__(self, wrapped: typing.Any, condition: typing.Any) -> None: ...
    def Dispose(self) -> None: ...
    def Enrich(self, logEvent: typing.Any, propertyFactory: typing.Any) -> None: ...

class EmptyEnricher:
    """Stub for Serilog.Core.Enrichers.EmptyEnricher"""
    def __init__(self) -> None: ...
    def Enrich(self, logEvent: typing.Any, propertyFactory: typing.Any) -> None: ...

class FixedPropertyEnricher:
    """Stub for Serilog.Core.Enrichers.FixedPropertyEnricher"""
    def __init__(self, eventProperty: typing.Any) -> None: ...
    def Enrich(self, logEvent: typing.Any, propertyFactory: typing.Any) -> None: ...

class PropertyEnricher:
    """Stub for Serilog.Core.Enrichers.PropertyEnricher"""
    def __init__(self, name: str, value: typing.Any, destructureObjects: bool | None = None) -> None: ...
    def Enrich(self, logEvent: typing.Any, propertyFactory: typing.Any) -> None: ...

class SafeAggregateEnricher:
    """Stub for Serilog.Core.Enrichers.SafeAggregateEnricher"""
    def __init__(self, enrichers: typing.Iterable[typing.Any]) -> None: ...
    def Enrich(self, logEvent: typing.Any, propertyFactory: typing.Any) -> None: ...

__all__ = [
    'ConditionalEnricher',
    'EmptyEnricher',
    'FixedPropertyEnricher',
    'PropertyEnricher',
    'SafeAggregateEnricher',
]
