# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class ExtensionMountAttachTypeDetails:
    """Stub for Teamcenter.Services.Internal.Strong.Structuremanagement._2018_11.StructureVerification.ExtensionMountAttachTypeDetails"""
    def __init__(self) -> None: ...
    ExtensionName: str
    MountAttachDetailTypes: typing.Sequence[typing.Any]

class MountAttachComparisonsResponse:
    """Stub for Teamcenter.Services.Internal.Strong.Structuremanagement._2018_11.StructureVerification.MountAttachComparisonsResponse"""
    def __init__(self) -> None: ...
    MountAttachTypeDetails: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class MountAttachDetail:
    """Stub for Teamcenter.Services.Internal.Strong.Structuremanagement._2018_11.StructureVerification.MountAttachDetail"""
    def __init__(self) -> None: ...
    Attachments: typing.Sequence[typing.Any]
    MatchType: int

class MountAttachDetailTypeElement:
    """Stub for Teamcenter.Services.Internal.Strong.Structuremanagement._2018_11.StructureVerification.MountAttachDetailTypeElement"""
    def __init__(self) -> None: ...
    RelationType: typing.Any
    MountAttachDetails: typing.Sequence[typing.Any]

class MountAttachTypeDetail:
    """Stub for Teamcenter.Services.Internal.Strong.Structuremanagement._2018_11.StructureVerification.MountAttachTypeDetail"""
    def __init__(self) -> None: ...
    Index: int
    EquivalentLines: typing.Sequence[typing.Any]
    MountAttachTypeExtensions: typing.Sequence[typing.Any]

class StructureVerification:
    """Stub for Teamcenter.Services.Internal.Strong.Structuremanagement._2018_11.StructureVerification.StructureVerification"""
    def __init__(self) -> None: ...
    def GetMountAttachComparisonDetails(self, EquivalentObjects: typing.Sequence[typing.Any], PartialMatchCriteria: typing.Sequence[typing.Any]) -> typing.Any: ...

__all__ = [
    'ExtensionMountAttachTypeDetails',
    'MountAttachComparisonsResponse',
    'MountAttachDetail',
    'MountAttachDetailTypeElement',
    'MountAttachTypeDetail',
    'StructureVerification',
]
