# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class AttrExchangeMapping:
    """Stub for Teamcenter.Services.Strong.Documentmanagement._2011_06.AttributeExchange.AttrExchangeMapping"""
    def __init__(self) -> None: ...
    ForeignObjectPropertyName: str
    Mapping: typing.Any

class AttrExchangeMappingSetValue:
    """Stub for Teamcenter.Services.Strong.Documentmanagement._2011_06.AttributeExchange.AttrExchangeMappingSetValue"""
    def __init__(self) -> None: ...
    AttrExchange: typing.Any
    TcPropertyValue: str

class AttributeExchange:
    """Stub for Teamcenter.Services.Strong.Documentmanagement._2011_06.AttributeExchange.AttributeExchange"""
    def __init__(self) -> None: ...
    def ResolveAttrMappingsAndGetProperties(self, Info: typing.Sequence[typing.Any]) -> typing.Any: ...
    def ResolveAttrMappingsAndSetProperties(self, Info: typing.Sequence[typing.Any]) -> typing.Any: ...

class FailedObjInfo:
    """Stub for Teamcenter.Services.Strong.Documentmanagement._2011_06.AttributeExchange.FailedObjInfo"""
    def __init__(self) -> None: ...
    FailedForeignObjectName: str
    ErrorStack: typing.Sequence[str]

class MappingObject:
    """Stub for Teamcenter.Services.Strong.Documentmanagement._2011_06.AttributeExchange.MappingObject"""
    def __init__(self) -> None: ...
    ObjectType: str
    ReferencedName: str
    Path: str
    AttributeName: str
    NextLevelMappedObject: typing.Sequence[typing.Any]
    RelationObject: typing.Sequence[typing.Any]

class Relation:
    """Stub for Teamcenter.Services.Strong.Documentmanagement._2011_06.AttributeExchange.Relation"""
    def __init__(self) -> None: ...
    RelationName: str
    MappedObject: typing.Sequence[typing.Any]
    RelationType: str

class ResolveAndGetData:
    """Stub for Teamcenter.Services.Strong.Documentmanagement._2011_06.AttributeExchange.ResolveAndGetData"""
    def __init__(self) -> None: ...
    ForeignObjectPropertyName: str
    TcAttrVal: typing.Any
    IsFailed: bool
    ErrorStack: typing.Sequence[str]

class ResolveAndGetResult:
    """Stub for Teamcenter.Services.Strong.Documentmanagement._2011_06.AttributeExchange.ResolveAndGetResult"""
    def __init__(self) -> None: ...
    Dataset: typing.Any
    ResolveAndGetDataList: typing.Sequence[typing.Any]

class ResolveAndSetResult:
    """Stub for Teamcenter.Services.Strong.Documentmanagement._2011_06.AttributeExchange.ResolveAndSetResult"""
    def __init__(self) -> None: ...
    Dataset: typing.Any
    FailedObjInfos: typing.Sequence[typing.Any]

class ResolveAttrMappingsAndGetPropertiesInfo:
    """Stub for Teamcenter.Services.Strong.Documentmanagement._2011_06.AttributeExchange.ResolveAttrMappingsAndGetPropertiesInfo"""
    def __init__(self) -> None: ...
    Locale: str
    DatsetObject: typing.Any
    AttrExchange: typing.Sequence[typing.Any]

class ResolveAttrMappingsAndGetPropertiesResponse:
    """Stub for Teamcenter.Services.Strong.Documentmanagement._2011_06.AttributeExchange.ResolveAttrMappingsAndGetPropertiesResponse"""
    def __init__(self) -> None: ...
    ResolveAndGetResults: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class ResolveAttrMappingsAndSetPropertiesInfo:
    """Stub for Teamcenter.Services.Strong.Documentmanagement._2011_06.AttributeExchange.ResolveAttrMappingsAndSetPropertiesInfo"""
    def __init__(self) -> None: ...
    Locale: str
    DatasetObject: typing.Any
    AttrExchange: typing.Sequence[typing.Any]

class ResolveAttrMappingsAndSetPropertiesResponse:
    """Stub for Teamcenter.Services.Strong.Documentmanagement._2011_06.AttributeExchange.ResolveAttrMappingsAndSetPropertiesResponse"""
    def __init__(self) -> None: ...
    ServiceData: typing.Any
    ResolvedAndSetResults: typing.Sequence[typing.Any]

class TcAttributeValue:
    """Stub for Teamcenter.Services.Strong.Documentmanagement._2011_06.AttributeExchange.TcAttributeValue"""
    def __init__(self) -> None: ...
    TcVal: str
    TypeOfVal: str

__all__ = [
    'AttrExchangeMapping',
    'AttrExchangeMappingSetValue',
    'AttributeExchange',
    'FailedObjInfo',
    'MappingObject',
    'Relation',
    'ResolveAndGetData',
    'ResolveAndGetResult',
    'ResolveAndSetResult',
    'ResolveAttrMappingsAndGetPropertiesInfo',
    'ResolveAttrMappingsAndGetPropertiesResponse',
    'ResolveAttrMappingsAndSetPropertiesInfo',
    'ResolveAttrMappingsAndSetPropertiesResponse',
    'TcAttributeValue',
]
