# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class UserManagement:
    """Stub for Teamcenter.Services.Strong.Administration._2015_03.UserManagement.UserManagement"""
    def __init__(self) -> None: ...
    def SetUserProfileProperties(self, UserProfileInputs: typing.Sequence[typing.Any]) -> typing.Any: ...

class UserProfileProperties:
    """Stub for Teamcenter.Services.Strong.Administration._2015_03.UserManagement.UserProfileProperties"""
    def __init__(self) -> None: ...
    User: typing.Any
    PropertyMap: typing.Any

class UserProfilePropertiesResponse:
    """Stub for Teamcenter.Services.Strong.Administration._2015_03.UserManagement.UserProfilePropertiesResponse"""
    def __init__(self) -> None: ...
    UserProfileMap: typing.Any
    ServiceData: typing.Any

__all__ = [
    'UserManagement',
    'UserProfileProperties',
    'UserProfilePropertiesResponse',
]
