# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class AttachedDataCriteria:
    """Stub for Awb0.Services.Internal.Strong.Activeworkspacebom._2012_10.OccurrenceManagement.AttachedDataCriteria"""
    def __init__(self) -> None: ...
    RelationName: str
    AttachedObjectType: str
    NamedReferences: typing.Sequence[str]
    ReturnAttachedObject: bool
    ReturnNamedRefObject: bool
    ReturnFileTickets: bool

class AttachedObjectInfo:
    """Stub for Awb0.Services.Internal.Strong.Activeworkspacebom._2012_10.OccurrenceManagement.AttachedObjectInfo"""
    def __init__(self) -> None: ...
    RelationName: str
    AttachedObject: typing.Any
    NamedReferenceName: str
    NamedRefObject: typing.Any
    FileTicket: str

class ChildOccsLoadNxtCursor:
    """Stub for Awb0.Services.Internal.Strong.Activeworkspacebom._2012_10.OccurrenceManagement.ChildOccsLoadNxtCursor"""
    def __init__(self) -> None: ...
    ContextInfo: typing.Any
    ParentOccurrences: typing.Sequence[typing.Any]
    InputCtxt: typing.Any
    FirstLevelOnly: bool
    StartIndex: int
    EndIndex: int
    PageSize: int
    CursorData: typing.Sequence[str]

class ChildOccurrenceInfo:
    """Stub for Awb0.Services.Internal.Strong.Activeworkspacebom._2012_10.OccurrenceManagement.ChildOccurrenceInfo"""
    def __init__(self) -> None: ...
    ContextInfo: typing.Any
    Parent: typing.Any
    StartReached: bool
    EndReached: bool
    ChildOccurrences: typing.Sequence[typing.Any]
    FocusOccurrence: typing.Any

class ChildOccurrenceInfoList:
    """Stub for Awb0.Services.Internal.Strong.Activeworkspacebom._2012_10.OccurrenceManagement.ChildOccurrenceInfoList"""
    def __init__(self) -> None: ...
    ContextInfo: typing.Any
    ChildOccInfos: typing.Sequence[typing.Any]
    Cursor: typing.Any

class ChildOccurrencesData:
    """Stub for Awb0.Services.Internal.Strong.Activeworkspacebom._2012_10.OccurrenceManagement.ChildOccurrencesData"""
    def __init__(self) -> None: ...
    ParentOccurrences: typing.Sequence[typing.Any]
    InputCtxt: typing.Any
    FirstLevelOnly: bool
    StartFreshNavigation: bool
    CloneStableIdChains: typing.Sequence[str]

class ChildOccurrencesResp:
    """Stub for Awb0.Services.Internal.Strong.Activeworkspacebom._2012_10.OccurrenceManagement.ChildOccurrencesResp"""
    def __init__(self) -> None: ...
    Output: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class InfoForAddToBookmarkResp:
    """Stub for Awb0.Services.Internal.Strong.Activeworkspacebom._2012_10.OccurrenceManagement.InfoForAddToBookmarkResp"""
    def __init__(self) -> None: ...
    AllowedTypeInfos: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class InfoForElementCreation:
    """Stub for Awb0.Services.Internal.Strong.Activeworkspacebom._2012_10.OccurrenceManagement.InfoForElementCreation"""
    def __init__(self) -> None: ...
    ObjectTypeName: str
    ElementTypeName: str
    IsSearchable: bool
    SearchTypeName: str

class InputContext:
    """Stub for Awb0.Services.Internal.Strong.Activeworkspacebom._2012_10.OccurrenceManagement.InputContext"""
    def __init__(self) -> None: ...
    Filter: typing.Any
    Configuration: typing.Any
    AttachedDataCriteria: typing.Sequence[typing.Any]
    PageSize: int
    StructureContextObject: typing.Any
    ProductContext: typing.Any
    RequestPref: typing.Any
    UpdateAutoBookmark: bool

class InsertLevelInputData:
    """Stub for Awb0.Services.Internal.Strong.Activeworkspacebom._2012_10.OccurrenceManagement.InsertLevelInputData"""
    def __init__(self) -> None: ...
    ClientId: str
    Elements: typing.Sequence[typing.Any]
    Object: typing.Any

class InsertLevelResponse:
    """Stub for Awb0.Services.Internal.Strong.Activeworkspacebom._2012_10.OccurrenceManagement.InsertLevelResponse"""
    def __init__(self) -> None: ...
    Output: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class InsertLevelResponseData:
    """Stub for Awb0.Services.Internal.Strong.Activeworkspacebom._2012_10.OccurrenceManagement.InsertLevelResponseData"""
    def __init__(self) -> None: ...
    ClientId: str
    NewParent: typing.Any
    NewElements: typing.Sequence[typing.Any]

class NxtChildOccurrencesData:
    """Stub for Awb0.Services.Internal.Strong.Activeworkspacebom._2012_10.OccurrenceManagement.NxtChildOccurrencesData"""
    def __init__(self) -> None: ...
    Cursor: typing.Any
    GoForward: bool

class NxtOccsInProdData:
    """Stub for Awb0.Services.Internal.Strong.Activeworkspacebom._2012_10.OccurrenceManagement.NxtOccsInProdData"""
    def __init__(self) -> None: ...
    Cursor: typing.Any
    GoForward: bool

class OccsInProdLoadNxtCursor:
    """Stub for Awb0.Services.Internal.Strong.Activeworkspacebom._2012_10.OccurrenceManagement.OccsInProdLoadNxtCursor"""
    def __init__(self) -> None: ...
    ContextInfo: typing.Any
    Product: typing.Any
    InputCtxt: typing.Any
    FirstLevelOnly: bool
    CursorData: typing.Sequence[str]
    StartIndex: int
    EndIndex: int
    PageSize: int

class OccsInProdResp:
    """Stub for Awb0.Services.Internal.Strong.Activeworkspacebom._2012_10.OccurrenceManagement.OccsInProdResp"""
    def __init__(self) -> None: ...
    Data: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class OccsInProdRespData:
    """Stub for Awb0.Services.Internal.Strong.Activeworkspacebom._2012_10.OccurrenceManagement.OccsInProdRespData"""
    def __init__(self) -> None: ...
    ProductContextInfo: typing.Any
    Occurrences: typing.Sequence[typing.Any]
    RootOccurrence: typing.Any
    Cursor: typing.Any
    StartReached: bool
    EndReached: bool
    SearchFilterCategories: typing.Sequence[typing.Any]
    SearchFilterMap: typing.Any
    DefaultFilterFieldDisplayCount: int

class OccurrenceCnfgInfo:
    """Stub for Awb0.Services.Internal.Strong.Activeworkspacebom._2012_10.OccurrenceManagement.OccurrenceCnfgInfo"""
    def __init__(self) -> None: ...
    RevisionRule: typing.Any
    EffectivityDate: typing.Any
    Now: bool
    EndItem: typing.Any
    UnitNo: int
    VariantRule: typing.Any
    ConfigurationObject: typing.Any
    SvrOwningProduct: typing.Any

class OccurrenceFilter:
    """Stub for Awb0.Services.Internal.Strong.Activeworkspacebom._2012_10.OccurrenceManagement.OccurrenceFilter"""
    def __init__(self) -> None: ...
    SearchInput: typing.Any

class OccurrenceInfo:
    """Stub for Awb0.Services.Internal.Strong.Activeworkspacebom._2012_10.OccurrenceManagement.OccurrenceInfo"""
    def __init__(self) -> None: ...
    Occurrence: typing.Any
    AttachedObjects: typing.Sequence[typing.Any]

class OccurrenceManagement:
    """Stub for Awb0.Services.Internal.Strong.Activeworkspacebom._2012_10.OccurrenceManagement.OccurrenceManagement"""
    def __init__(self) -> None: ...
    def GetChildOccurrences(self, Input: typing.Sequence[typing.Any]) -> typing.Any: ...
    def GetInfoForAddToBookmark(self) -> typing.Any: ...
    def GetNextChildOccurrences(self, Input: typing.Sequence[typing.Any]) -> typing.Any: ...
    def GetNextOccurrencesInProduct(self, InputData: typing.Sequence[typing.Any]) -> typing.Any: ...
    def GetOccurrencesInProduct(self, InputData: typing.Sequence[typing.Any]) -> typing.Any: ...
    def InsertLevel(self, Input: typing.Sequence[typing.Any]) -> typing.Any: ...
    def UpdateSavedBookmark(self, SavedBookmarkObjects: typing.Sequence[typing.Any]) -> typing.Any: ...

class ProductInfoData:
    """Stub for Awb0.Services.Internal.Strong.Activeworkspacebom._2012_10.OccurrenceManagement.ProductInfoData"""
    def __init__(self) -> None: ...
    ProductCtxInfo: typing.Any
    RootElement: typing.Any

class ProductOccurrencesInput:
    """Stub for Awb0.Services.Internal.Strong.Activeworkspacebom._2012_10.OccurrenceManagement.ProductOccurrencesInput"""
    def __init__(self) -> None: ...
    Product: typing.Any
    InputCtxt: typing.Any
    FirstLevelOnly: bool

class SearchFilter:
    """Stub for Awb0.Services.Internal.Strong.Activeworkspacebom._2012_10.OccurrenceManagement.SearchFilter"""
    def __init__(self) -> None: ...
    SearchFilterType: str
    StringValue: str
    StartDateValue: typing.Any
    EndDateValue: typing.Any
    StartNumericValue: float
    EndNumericValue: float
    Count: int
    Selected: bool
    StartEndRange: str

class SearchFilterField:
    """Stub for Awb0.Services.Internal.Strong.Activeworkspacebom._2012_10.OccurrenceManagement.SearchFilterField"""
    def __init__(self) -> None: ...
    InternalName: str
    DisplayName: str
    DefaultFilterValueDisplayCount: int

class SearchInput:
    """Stub for Awb0.Services.Internal.Strong.Activeworkspacebom._2012_10.OccurrenceManagement.SearchInput"""
    def __init__(self) -> None: ...
    SearchString: str
    SearchFilterMap: typing.Any
    SearchSortCriteria: typing.Sequence[typing.Any]
    SearchFilterFieldSortType: str

class SearchSortCriteria:
    """Stub for Awb0.Services.Internal.Strong.Activeworkspacebom._2012_10.OccurrenceManagement.SearchSortCriteria"""
    def __init__(self) -> None: ...
    FieldName: str
    SortDirection: str

__all__ = [
    'AttachedDataCriteria',
    'AttachedObjectInfo',
    'ChildOccsLoadNxtCursor',
    'ChildOccurrenceInfo',
    'ChildOccurrenceInfoList',
    'ChildOccurrencesData',
    'ChildOccurrencesResp',
    'InfoForAddToBookmarkResp',
    'InfoForElementCreation',
    'InputContext',
    'InsertLevelInputData',
    'InsertLevelResponse',
    'InsertLevelResponseData',
    'NxtChildOccurrencesData',
    'NxtOccsInProdData',
    'OccsInProdLoadNxtCursor',
    'OccsInProdResp',
    'OccsInProdRespData',
    'OccurrenceCnfgInfo',
    'OccurrenceFilter',
    'OccurrenceInfo',
    'OccurrenceManagement',
    'ProductInfoData',
    'ProductOccurrencesInput',
    'SearchFilter',
    'SearchFilterField',
    'SearchInput',
    'SearchSortCriteria',
]
