# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class DataManagement:
    """Stub for Awv0.Services.Strong.Activeworkspacevis._2015_03.DataManagement.DataManagement"""
    def __init__(self) -> None: ...
    def CreateLaunchInfo(self, IdInfos: typing.Sequence[typing.Any], ServerInfo: typing.Any, UserDataAgentInfo: typing.Any, SessionInfo: typing.Any) -> typing.Any: ...

class IdInfo:
    """Stub for Awv0.Services.Strong.Activeworkspacevis._2015_03.DataManagement.IdInfo"""
    def __init__(self) -> None: ...
    LaunchedObject: typing.Any
    Item: typing.Any
    ItemRev: typing.Any
    OccurrencesList: typing.Sequence[typing.Any]
    CreateOptions: typing.Any
    IdAdditionalInfo: typing.Any

class LaunchInfoResponse:
    """Stub for Awv0.Services.Strong.Activeworkspacevis._2015_03.DataManagement.LaunchInfoResponse"""
    def __init__(self) -> None: ...
    Ticket: str
    VviStrBuffersOutputMap: typing.Any
    ServiceData: typing.Any

class OptionInfo:
    """Stub for Awv0.Services.Strong.Activeworkspacevis._2015_03.DataManagement.OptionInfo"""
    def __init__(self) -> None: ...
    OptionValue: str
    IncludeInLaunchFile: bool

class ServerInfo:
    """Stub for Awv0.Services.Strong.Activeworkspacevis._2015_03.DataManagement.ServerInfo"""
    def __init__(self) -> None: ...
    Protocol: str
    Hostpath: str
    Servermode: int
    ServerAdditionalInfo: typing.Any

class SessionInfo:
    """Stub for Awv0.Services.Strong.Activeworkspacevis._2015_03.DataManagement.SessionInfo"""
    def __init__(self) -> None: ...
    SessionDescriminator: str
    SessionOptions: typing.Any
    SessionAdditionalInfo: typing.Any

class UserAgentDataInfo:
    """Stub for Awv0.Services.Strong.Activeworkspacevis._2015_03.DataManagement.UserAgentDataInfo"""
    def __init__(self) -> None: ...
    UserApplication: str
    UserAppVersion: str
    UserAdditionalInfo: typing.Any

__all__ = [
    'DataManagement',
    'IdInfo',
    'LaunchInfoResponse',
    'OptionInfo',
    'ServerInfo',
    'SessionInfo',
    'UserAgentDataInfo',
]
