# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class GetICOMappingTargetsResponse:
    """Stub for Teamcenter.Services.Internal.Strong.Manufacturing._2019_06.ResourceManagement.GetICOMappingTargetsResponse"""
    def __init__(self) -> None: ...
    ServiceData: typing.Any
    MappingInfoVector: typing.Sequence[typing.Any]

class MappingInfo:
    """Stub for Teamcenter.Services.Internal.Strong.Manufacturing._2019_06.ResourceManagement.MappingInfo"""
    def __init__(self) -> None: ...
    SourceIcoID: str
    SourceIcoUID: str
    SourceClassID: str
    SourceClassName: str
    TargetMachine: str
    TargetWorkpiece: str
    TargetGTCBase: str
    TargetClasses: typing.Sequence[typing.Any]

class ResourceManagement:
    """Stub for Teamcenter.Services.Internal.Strong.Manufacturing._2019_06.ResourceManagement.ResourceManagement"""
    def __init__(self) -> None: ...
    def GetICOMappingTargets(self, IcoUIDs: typing.Sequence[str], ViewType: int) -> typing.Any: ...

class TargetClass:
    """Stub for Teamcenter.Services.Internal.Strong.Manufacturing._2019_06.ResourceManagement.TargetClass"""
    def __init__(self) -> None: ...
    TargetID: str
    TargetName: str

__all__ = [
    'GetICOMappingTargetsResponse',
    'MappingInfo',
    'ResourceManagement',
    'TargetClass',
]
