# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class CreateIn:
    """Stub for Cpd0.Services.Strong.Cpdcore._2020_01.DataManagement.CreateIn"""
    def __init__(self) -> None: ...
    ClientId: str
    Data: typing.Any

class CreateInput:
    """Stub for Cpd0.Services.Strong.Cpdcore._2020_01.DataManagement.CreateInput"""
    def __init__(self) -> None: ...
    BoName: str
    StringProps: typing.Any
    StringArrayProps: typing.Any
    DoubleProps: typing.Any
    DoubleArrayProps: typing.Any
    FloatProps: typing.Any
    FloatArrayProps: typing.Any
    IntProps: typing.Any
    IntArrayProps: typing.Any
    BoolProps: typing.Any
    BoolArrayProps: typing.Any
    DateProps: typing.Any
    DateArrayProps: typing.Any
    ObjectProps: typing.Any
    ObjectArrayProps: typing.Any
    CompoundCreateInput: typing.Any

class DataManagement:
    """Stub for Cpd0.Services.Strong.Cpdcore._2020_01.DataManagement.DataManagement"""
    def __init__(self) -> None: ...
    def GenerateDesignContext(self, DesignContextInfos: typing.Sequence[typing.Any]) -> typing.Any: ...

class GenerateDesignContextInfo:
    """Stub for Cpd0.Services.Strong.Cpdcore._2020_01.DataManagement.GenerateDesignContextInfo"""
    def __init__(self) -> None: ...
    CreateInput: typing.Any
    Option: typing.Any
    DesignItems: typing.Sequence[typing.Any]

class GenerateDesignContextOption:
    """Stub for Cpd0.Services.Strong.Cpdcore._2020_01.DataManagement.GenerateDesignContextOption"""
    def __init__(self) -> None: ...
    Configuration: typing.Any
    Models: typing.Sequence[typing.Any]
    ProximityDistance: float
    IncludeReuseOnly: bool
    IncludeSubordinate: bool

class GenerateDesignContextResponse:
    """Stub for Cpd0.Services.Strong.Cpdcore._2020_01.DataManagement.GenerateDesignContextResponse"""
    def __init__(self) -> None: ...
    ClientIdMap: typing.Any
    ServiceData: typing.Any

__all__ = [
    'CreateIn',
    'CreateInput',
    'DataManagement',
    'GenerateDesignContextInfo',
    'GenerateDesignContextOption',
    'GenerateDesignContextResponse',
]
