# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class CreateDatasetOfVersionArgs:
    """Stub for Teamcenter.Services.Internal.Strong.Core._2008_06.DispatcherManagement.CreateDatasetOfVersionArgs"""
    def __init__(self) -> None: ...
    ItemRevision: typing.Any
    DatasetName: str
    TypeName: str
    Tool: typing.Any
    Version: int

class CreateDatasetOfVersionResponse:
    """Stub for Teamcenter.Services.Internal.Strong.Core._2008_06.DispatcherManagement.CreateDatasetOfVersionResponse"""
    def __init__(self) -> None: ...
    CreatedDatasets: typing.Sequence[typing.Any]
    SvcData: typing.Any

class DispatcherManagement:
    """Stub for Teamcenter.Services.Internal.Strong.Core._2008_06.DispatcherManagement.DispatcherManagement"""
    def __init__(self) -> None: ...
    def CreateDatasetOfVersion(self, Inputs: typing.Sequence[typing.Any]) -> typing.Any: ...
    def InsertDatasetVersion(self, Inputs: typing.Sequence[typing.Any]) -> typing.Any: ...
    def QueryDispatcherRequests(self, Inputs: typing.Sequence[typing.Any]) -> typing.Any: ...
    def UpdateDispatcherRequests(self, Inputs: typing.Sequence[typing.Any]) -> typing.Any: ...

class InsertDatasetVersionArgs:
    """Stub for Teamcenter.Services.Internal.Strong.Core._2008_06.DispatcherManagement.InsertDatasetVersionArgs"""
    def __init__(self) -> None: ...
    Dataset: typing.Any
    VersionNumber: int

class InsertDatasetVersionResponse:
    """Stub for Teamcenter.Services.Internal.Strong.Core._2008_06.DispatcherManagement.InsertDatasetVersionResponse"""
    def __init__(self) -> None: ...
    DatasetTags: typing.Sequence[typing.Any]
    SvcData: typing.Any

class InternalDataFiles:
    """Stub for Teamcenter.Services.Internal.Strong.Core._2008_06.DispatcherManagement.InternalDataFiles"""
    def __init__(self) -> None: ...
    Key: str
    File: typing.Any

class InternalKeyValueArguments:
    """Stub for Teamcenter.Services.Internal.Strong.Core._2008_06.DispatcherManagement.InternalKeyValueArguments"""
    def __init__(self) -> None: ...
    Key: str
    Value: str

class QueryDispatcherRequestsArgs:
    """Stub for Teamcenter.Services.Internal.Strong.Core._2008_06.DispatcherManagement.QueryDispatcherRequestsArgs"""
    def __init__(self) -> None: ...
    Providers: typing.Sequence[str]
    Services: typing.Sequence[str]
    States: typing.Sequence[str]
    Priorities: typing.Sequence[int]
    ModifiedDate: str
    PrimaryObjects: typing.Sequence[typing.Any]
    TaskID: typing.Sequence[str]
    Type: typing.Sequence[str]
    UnLoaded: bool

class QueryDispatcherRequestsOutput:
    """Stub for Teamcenter.Services.Internal.Strong.Core._2008_06.DispatcherManagement.QueryDispatcherRequestsOutput"""
    def __init__(self) -> None: ...
    QueriedRequests: typing.Sequence[typing.Any]

class QueryDispatcherRequestsResponse:
    """Stub for Teamcenter.Services.Internal.Strong.Core._2008_06.DispatcherManagement.QueryDispatcherRequestsResponse"""
    def __init__(self) -> None: ...
    OutputObjects: typing.Sequence[typing.Any]
    SvcData: typing.Any

class UpdateDispatcherRequestArgs:
    """Stub for Teamcenter.Services.Internal.Strong.Core._2008_06.DispatcherManagement.UpdateDispatcherRequestArgs"""
    def __init__(self) -> None: ...
    RequestToUpdate: typing.Any
    CurrentState: str
    NextState: str
    Type: str
    KeyValueArgs: typing.Sequence[typing.Any]
    DataFiles: typing.Sequence[typing.Any]

class UpdateDispatcherRequestOutput:
    """Stub for Teamcenter.Services.Internal.Strong.Core._2008_06.DispatcherManagement.UpdateDispatcherRequestOutput"""
    def __init__(self) -> None: ...
    RequestUpdated: typing.Any
    WasRequestUpdated: bool

class UpdateDispatcherRequestResponse:
    """Stub for Teamcenter.Services.Internal.Strong.Core._2008_06.DispatcherManagement.UpdateDispatcherRequestResponse"""
    def __init__(self) -> None: ...
    OutputObjects: typing.Sequence[typing.Any]
    SvcData: typing.Any

__all__ = [
    'CreateDatasetOfVersionArgs',
    'CreateDatasetOfVersionResponse',
    'DispatcherManagement',
    'InsertDatasetVersionArgs',
    'InsertDatasetVersionResponse',
    'InternalDataFiles',
    'InternalKeyValueArguments',
    'QueryDispatcherRequestsArgs',
    'QueryDispatcherRequestsOutput',
    'QueryDispatcherRequestsResponse',
    'UpdateDispatcherRequestArgs',
    'UpdateDispatcherRequestOutput',
    'UpdateDispatcherRequestResponse',
]
