# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class SimulationProcessManagement:
    """Stub for Teamcenter.Services.Internal.Strong.Cae._2013_12.SimulationProcessManagement.SimulationProcessManagement"""
    def __init__(self) -> None: ...
    def ImportSimulationObjects2(self, ProcessHierarchy: str, WorkingDirectory: str, ItemID: str, ObjectUID: str, RevisionID: str, XmlFileName: str, ItemCreationSetting: str, DatasetCreationSetting: str) -> typing.Any: ...

__all__ = [
    'SimulationProcessManagement',
]
