# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class CreateRelationInput:
    """Stub for Rv1.Services.Strong.Relationshipviewer._2012_10.NetworkEngine.CreateRelationInput"""
    def __init__(self) -> None: ...
    ClientId: str
    RelationType: str
    PrimaryObject: typing.Any
    SecondaryObject: typing.Any
    Props: typing.Any

class CreateRelationsResponse:
    """Stub for Rv1.Services.Strong.Relationshipviewer._2012_10.NetworkEngine.CreateRelationsResponse"""
    def __init__(self) -> None: ...
    ClientId: str
    Edges: typing.Sequence[typing.Any]
    NodeUpdates: typing.Any
    ServiceData: typing.Any

class Edge:
    """Stub for Rv1.Services.Strong.Relationshipviewer._2012_10.NetworkEngine.Edge"""
    def __init__(self) -> None: ...
    LeftId: str
    RightId: str
    RelationType: str
    MetaObject: typing.Any
    StartPortObject: typing.Any
    EndPortObject: typing.Any
    Props: typing.Any

class Graph:
    """Stub for Rv1.Services.Strong.Relationshipviewer._2012_10.NetworkEngine.Graph"""
    def __init__(self) -> None: ...
    ViewName: str
    RootIds: typing.Sequence[str]
    ServiceCursor: int
    Nodes: typing.Sequence[typing.Any]
    Edges: typing.Sequence[typing.Any]
    AnalysisResult: typing.Any
    IsPartial: bool

class GraphFilter:
    """Stub for Rv1.Services.Strong.Relationshipviewer._2012_10.NetworkEngine.GraphFilter"""
    def __init__(self) -> None: ...
    Name: str
    Color: typing.Any
    Types: typing.Sequence[typing.Any]

class GraphGroup:
    """Stub for Rv1.Services.Strong.Relationshipviewer._2012_10.NetworkEngine.GraphGroup"""
    def __init__(self) -> None: ...
    Name: str
    Filters: typing.Sequence[typing.Any]

class GraphInquiry:
    """Stub for Rv1.Services.Strong.Relationshipviewer._2012_10.NetworkEngine.GraphInquiry"""
    def __init__(self) -> None: ...
    Name: str
    Description: str

class GraphParameterInfo:
    """Stub for Rv1.Services.Strong.Relationshipviewer._2012_10.NetworkEngine.GraphParameterInfo"""
    def __init__(self) -> None: ...
    Name: str
    ValueMask: str
    Type: str
    DefaultValue: str
    Description: str

class GraphStyleDefResponse:
    """Stub for Rv1.Services.Strong.Relationshipviewer._2012_10.NetworkEngine.GraphStyleDefResponse"""
    def __init__(self) -> None: ...
    StyleXMLStr: str
    ServiceData: typing.Any

class GraphTypeListResponse:
    """Stub for Rv1.Services.Strong.Relationshipviewer._2012_10.NetworkEngine.GraphTypeListResponse"""
    def __init__(self) -> None: ...
    Views: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class GraphViewDescription:
    """Stub for Rv1.Services.Strong.Relationshipviewer._2012_10.NetworkEngine.GraphViewDescription"""
    def __init__(self) -> None: ...
    Name: str
    DefaultLayout: str
    DefaultExpandDirection: str
    Visible: bool
    DiagramMode: bool
    Parameters: typing.Sequence[typing.Any]
    Inquiries: typing.Sequence[typing.Any]
    Groups: typing.Sequence[typing.Any]

class NetworkEngine:
    """Stub for Rv1.Services.Strong.Relationshipviewer._2012_10.NetworkEngine.NetworkEngine"""
    def __init__(self) -> None: ...
    def CreateRelations(self, Inputs: typing.Sequence[typing.Any]) -> typing.Any: ...
    def GetGraphStyleDef(self) -> typing.Any: ...
    def GetViews(self) -> typing.Any: ...
    def GetViews2(self, Key: str) -> typing.Any: ...
    def QueryNetwork(self, RootIds: typing.Sequence[str], ViewName: str, GraphParamMap: typing.Any, Inquiries: typing.Sequence[str]) -> typing.Any: ...
    def QueryNetwork2(self, Input: typing.Any) -> typing.Any: ...

class NetworkResponse:
    """Stub for Rv1.Services.Strong.Relationshipviewer._2012_10.NetworkEngine.NetworkResponse"""
    def __init__(self) -> None: ...
    Graph: typing.Any
    ServiceData: typing.Any

class Node:
    """Stub for Rv1.Services.Strong.Relationshipviewer._2012_10.NetworkEngine.Node"""
    def __init__(self) -> None: ...
    Id: str
    Name: str
    MetaObject: typing.Any
    Props: typing.Any

class QueryNetworkInputs:
    """Stub for Rv1.Services.Strong.Relationshipviewer._2012_10.NetworkEngine.QueryNetworkInputs"""
    def __init__(self) -> None: ...
    RootIds: typing.Sequence[str]
    ViewName: str
    QueryMode: str
    ServiceCursor: int
    GraphParamMap: typing.Any
    Inquiries: typing.Sequence[str]

class RGBValue:
    """Stub for Rv1.Services.Strong.Relationshipviewer._2012_10.NetworkEngine.RGBValue"""
    def __init__(self) -> None: ...
    RedValue: float
    GreenValue: float
    BlueValue: float

class Type:
    """Stub for Rv1.Services.Strong.Relationshipviewer._2012_10.NetworkEngine.Type"""
    def __init__(self) -> None: ...
    InternalName: str
    DisplayName: str

__all__ = [
    'CreateRelationInput',
    'CreateRelationsResponse',
    'Edge',
    'Graph',
    'GraphFilter',
    'GraphGroup',
    'GraphInquiry',
    'GraphParameterInfo',
    'GraphStyleDefResponse',
    'GraphTypeListResponse',
    'GraphViewDescription',
    'NetworkEngine',
    'NetworkResponse',
    'Node',
    'QueryNetworkInputs',
    'RGBValue',
    'Type',
]
