# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class DataManagement:
    """Stub for Teamcenter.Services.Strong.Core._2016_05.DataManagement.DataManagement"""
    def __init__(self) -> None: ...
    def GenerateContextSpecificIDs(self, GenerateContextIDsIn: typing.Sequence[typing.Any]) -> typing.Any: ...
    def ResetContextID(self, ContextNames: typing.Sequence[str]) -> typing.Any: ...
    def SetPropertiesAndDetectOverwrite(self, PropData: typing.Sequence[typing.Any], Options: typing.Any) -> typing.Any: ...

class GenerateContextIDsInput:
    """Stub for Teamcenter.Services.Strong.Core._2016_05.DataManagement.GenerateContextIDsInput"""
    def __init__(self) -> None: ...
    ClientID: str
    ContextName: str
    NumberOfIDs: int

class GenerateContextSpecificIDsResponse:
    """Stub for Teamcenter.Services.Strong.Core._2016_05.DataManagement.GenerateContextSpecificIDsResponse"""
    def __init__(self) -> None: ...
    ServiceData: typing.Any
    GeneratedContextIDValues: typing.Sequence[typing.Any]

class GeneratedContextIDs:
    """Stub for Teamcenter.Services.Strong.Core._2016_05.DataManagement.GeneratedContextIDs"""
    def __init__(self) -> None: ...
    ContextName: str
    GeneratedIDs: typing.Sequence[str]

class PropData:
    """Stub for Teamcenter.Services.Strong.Core._2016_05.DataManagement.PropData"""
    def __init__(self) -> None: ...
    BusinessObject: typing.Any
    VecPropNameVal: typing.Sequence[typing.Any]
    LastSavedDateExportedToClient: typing.Any

class PropertyNameValuesStruct:
    """Stub for Teamcenter.Services.Strong.Core._2016_05.DataManagement.PropertyNameValuesStruct"""
    def __init__(self) -> None: ...
    PropertyName: str
    OldValues: typing.Sequence[str]
    NewValues: typing.Sequence[str]

class SetPropsAndDetectOverwriteResponse:
    """Stub for Teamcenter.Services.Strong.Core._2016_05.DataManagement.SetPropsAndDetectOverwriteResponse"""
    def __init__(self) -> None: ...
    Data: typing.Any
    OverwriteDetectedObjPropMap: typing.Any

__all__ = [
    'DataManagement',
    'GenerateContextIDsInput',
    'GenerateContextSpecificIDsResponse',
    'GeneratedContextIDs',
    'PropData',
    'PropertyNameValuesStruct',
    'SetPropsAndDetectOverwriteResponse',
]
