# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class DatasetInfo2:
    """Stub for Teamcenter.Services.Internal.Strong.Structuremanagement._2013_12.StructureExpansionLite.DatasetInfo2"""
    def __init__(self) -> None: ...
    RelationName: str
    Dataset: typing.Any
    NamedRefInfo: typing.Sequence[typing.Any]

class ExpansionResponse2:
    """Stub for Teamcenter.Services.Internal.Strong.Structuremanagement._2013_12.StructureExpansionLite.ExpansionResponse2"""
    def __init__(self) -> None: ...
    ParentChildInfo: typing.Any
    DatasetInfo: typing.Sequence[typing.Any]
    ParentUndeliveredChildrenUids: typing.Any
    ServiceData: typing.Any

class NamedRefInfo2:
    """Stub for Teamcenter.Services.Internal.Strong.Structuremanagement._2013_12.StructureExpansionLite.NamedRefInfo2"""
    def __init__(self) -> None: ...
    Name: str
    Type: str
    OriginalFileName: str
    Object: typing.Any
    FileTicket: str

class StructureExpansionLite:
    """Stub for Teamcenter.Services.Internal.Strong.Structuremanagement._2013_12.StructureExpansionLite.StructureExpansionLite"""
    def __init__(self) -> None: ...
    def ExpandBasedOnOccurrenceList2(self, LinePaths: typing.Sequence[typing.Any], Controls: typing.Any) -> typing.Any: ...
    def ExpandNext2(self, LinesToExpand: typing.Sequence[typing.Any], Controls: typing.Any) -> typing.Any: ...
    def GetUndelivered2(self, UndeliveredLineUids: typing.Sequence[str], Controls: typing.Any) -> typing.Any: ...
    def UnloadBelow2(self, Lines: typing.Sequence[typing.Any]) -> typing.Any: ...

__all__ = [
    'DatasetInfo2',
    'ExpansionResponse2',
    'NamedRefInfo2',
    'StructureExpansionLite',
]
