# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class ConfiguratorManagement:
    """Stub for Cfg0.Services.Internal.Strong.Configurator._2014_12.ConfiguratorManagement.ConfiguratorManagement"""
    def __init__(self) -> None: ...
    def GetModelAndOptionConditions(self, OperationConfigPerspective: typing.Any, InputStructs: typing.Sequence[typing.Any]) -> typing.Any: ...
    def GetOverlapStates(self, Context: typing.Any, OverlapStateInputs: typing.Sequence[typing.Any]) -> typing.Any: ...
    def UpdateAdmissibility(self, UpdateAdmissibilityInputList: typing.Sequence[typing.Any]) -> typing.Any: ...

class GetModelOptionCondInput:
    """Stub for Cfg0.Services.Internal.Strong.Configurator._2014_12.ConfiguratorManagement.GetModelOptionCondInput"""
    def __init__(self) -> None: ...
    ConfigPerspective: typing.Any
    InputExpressions: typing.Sequence[typing.Any]

class GetModelOptionCondOutput:
    """Stub for Cfg0.Services.Internal.Strong.Configurator._2014_12.ConfiguratorManagement.GetModelOptionCondOutput"""
    def __init__(self) -> None: ...
    Index: int
    ModelOptionCondList: typing.Sequence[typing.Any]

class GetModelOptionCondResponse:
    """Stub for Cfg0.Services.Internal.Strong.Configurator._2014_12.ConfiguratorManagement.GetModelOptionCondResponse"""
    def __init__(self) -> None: ...
    ModelOptionCondOutputList: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class ModelOptionCondStruct:
    """Stub for Cfg0.Services.Internal.Strong.Configurator._2014_12.ConfiguratorManagement.ModelOptionCondStruct"""
    def __init__(self) -> None: ...
    ModelExpressions: typing.Sequence[typing.Any]
    OptionConditions: typing.Sequence[typing.Any]

class OverlapStateInfo:
    """Stub for Cfg0.Services.Internal.Strong.Configurator._2014_12.ConfiguratorManagement.OverlapStateInfo"""
    def __init__(self) -> None: ...
    Index: int
    OverlapStates: typing.Sequence[str]

class OverlapStateInput:
    """Stub for Cfg0.Services.Internal.Strong.Configurator._2014_12.ConfiguratorManagement.OverlapStateInput"""
    def __init__(self) -> None: ...
    ReferenceExpression: typing.Any
    Expressions: typing.Sequence[typing.Any]

class OverlapStateResponse:
    """Stub for Cfg0.Services.Internal.Strong.Configurator._2014_12.ConfiguratorManagement.OverlapStateResponse"""
    def __init__(self) -> None: ...
    OverlapInfo: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class UpdateAdmissibilityData:
    """Stub for Cfg0.Services.Internal.Strong.Configurator._2014_12.ConfiguratorManagement.UpdateAdmissibilityData"""
    def __init__(self) -> None: ...
    AdmissibilityObject: typing.Any
    AdmissibilityState: str

class UpdateAdmissibilityInputList:
    """Stub for Cfg0.Services.Internal.Strong.Configurator._2014_12.ConfiguratorManagement.UpdateAdmissibilityInputList"""
    def __init__(self) -> None: ...
    UpdateAdmissibilityInputs: typing.Sequence[typing.Any]

class UpdateAdmissibilityInputStruct:
    """Stub for Cfg0.Services.Internal.Strong.Configurator._2014_12.ConfiguratorManagement.UpdateAdmissibilityInputStruct"""
    def __init__(self) -> None: ...
    ContextObject: typing.Any
    UpdateAdmissibilityData: typing.Sequence[typing.Any]

__all__ = [
    'ConfiguratorManagement',
    'GetModelOptionCondInput',
    'GetModelOptionCondOutput',
    'GetModelOptionCondResponse',
    'ModelOptionCondStruct',
    'OverlapStateInfo',
    'OverlapStateInput',
    'OverlapStateResponse',
    'UpdateAdmissibilityData',
    'UpdateAdmissibilityInputList',
    'UpdateAdmissibilityInputStruct',
]
