# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class GetSessionInfoFromTicketResponse:
    """Stub for Teamcenter.Services.Strong.Administration._2018_11.IRM.GetSessionInfoFromTicketResponse"""
    def __init__(self) -> None: ...
    UserInfo: typing.Any
    SessionValues: typing.Any
    SiteId: int
    ServiceData: typing.Any

class GetSessionInfoTicketResponse:
    """Stub for Teamcenter.Services.Strong.Administration._2018_11.IRM.GetSessionInfoTicketResponse"""
    def __init__(self) -> None: ...
    SessionInfoTicket: str
    ServiceData: typing.Any

class IRM:
    """Stub for Teamcenter.Services.Strong.Administration._2018_11.IRM.IRM"""
    def __init__(self) -> None: ...
    def GetSessionInfoFromTicket(self, SessionInfoTicket: str) -> typing.Any: ...
    def GetSessionInfoTicket(self) -> typing.Any: ...

__all__ = [
    'GetSessionInfoFromTicketResponse',
    'GetSessionInfoTicketResponse',
    'IRM',
]
