# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class AlignmentManagement:
    """Stub for Cba1.Services.Internal.Strong.Cbaext._2014_12.AlignmentManagement.AlignmentManagement"""
    def __init__(self) -> None: ...
    def AlignCadOccsWithSolutions(self, AlignmentInput: typing.Any) -> typing.Any: ...
    def AlignDesignsWithParts(self, AlignmentInput: typing.Any) -> typing.Any: ...

class AlignmentResponse:
    """Stub for Cba1.Services.Internal.Strong.Cbaext._2014_12.AlignmentManagement.AlignmentResponse"""
    def __init__(self) -> None: ...
    ServiceData: typing.Any
    UpdatedItemRowSet: typing.Any
    ItemsToRemove: typing.Sequence[str]

class BomLineType:
    """Stub for Cba1.Services.Internal.Strong.Cbaext._2014_12.AlignmentManagement.BomLineType"""
    def __init__(self) -> None: ...
    ClientID: str
    Design: typing.Any

class Column:
    """Stub for Cba1.Services.Internal.Strong.Cbaext._2014_12.AlignmentManagement.Column"""
    def __init__(self) -> None: ...
    Name: str
    Datatype: str
    Table: str
    LogicalName: str
    Width: int

class ColumnSet:
    """Stub for Cba1.Services.Internal.Strong.Cbaext._2014_12.AlignmentManagement.ColumnSet"""
    def __init__(self) -> None: ...
    Column: typing.Sequence[typing.Any]
    Table: str

class DesignType:
    """Stub for Cba1.Services.Internal.Strong.Cbaext._2014_12.AlignmentManagement.DesignType"""
    def __init__(self) -> None: ...
    ClientID: str
    Design: typing.Any

class PartAlignmentInputType:
    """Stub for Cba1.Services.Internal.Strong.Cbaext._2014_12.AlignmentManagement.PartAlignmentInputType"""
    def __init__(self) -> None: ...
    PmmInputObject: typing.Any
    UpdateAndAlignInfo: typing.Sequence[typing.Any]
    Operation: str
    Authorization: str
    AutoCommit: bool

class PmmObjectUpdateInfoType:
    """Stub for Cba1.Services.Internal.Strong.Cbaext._2014_12.AlignmentManagement.PmmObjectUpdateInfoType"""
    def __init__(self) -> None: ...
    Field: typing.Any
    Tuid: str
    ClientID: str
    RelatedObjectUpdate: typing.Sequence[typing.Any]

class RelatedObjectType:
    """Stub for Cba1.Services.Internal.Strong.Cbaext._2014_12.AlignmentManagement.RelatedObjectType"""
    def __init__(self) -> None: ...
    Action: str
    Tuid: str
    Field: typing.Any

class RelatedObjectUpdateInfoType:
    """Stub for Cba1.Services.Internal.Strong.Cbaext._2014_12.AlignmentManagement.RelatedObjectUpdateInfoType"""
    def __init__(self) -> None: ...
    Table: str
    RelatedObjects: typing.Sequence[typing.Any]

class Row:
    """Stub for Cba1.Services.Internal.Strong.Cbaext._2014_12.AlignmentManagement.Row"""
    def __init__(self) -> None: ...
    Value: typing.Sequence[str]
    ClientID: str

class RowColumn:
    """Stub for Cba1.Services.Internal.Strong.Cbaext._2014_12.AlignmentManagement.RowColumn"""
    def __init__(self) -> None: ...
    ColumnSet: typing.Any
    RowSet: typing.Any

class RowSet:
    """Stub for Cba1.Services.Internal.Strong.Cbaext._2014_12.AlignmentManagement.RowSet"""
    def __init__(self) -> None: ...
    Row: typing.Sequence[typing.Any]

class SolutionAlignmentInputType:
    """Stub for Cba1.Services.Internal.Strong.Cbaext._2014_12.AlignmentManagement.SolutionAlignmentInputType"""
    def __init__(self) -> None: ...
    PmmInputObject: typing.Any
    UpdateAndAlignInfo: typing.Sequence[typing.Any]
    Operation: str
    Authorization: str
    AutoCommit: bool

class UpdateAndAlignBomLineInfoType:
    """Stub for Cba1.Services.Internal.Strong.Cbaext._2014_12.AlignmentManagement.UpdateAndAlignBomLineInfoType"""
    def __init__(self) -> None: ...
    PmmObjectUpdateInfo: typing.Any
    Designs: typing.Sequence[typing.Any]

class UpdateAndAlignDesignInfoType:
    """Stub for Cba1.Services.Internal.Strong.Cbaext._2014_12.AlignmentManagement.UpdateAndAlignDesignInfoType"""
    def __init__(self) -> None: ...
    PmmObjectUpdateInfo: typing.Any
    Designs: typing.Sequence[typing.Any]

__all__ = [
    'AlignmentManagement',
    'AlignmentResponse',
    'BomLineType',
    'Column',
    'ColumnSet',
    'DesignType',
    'PartAlignmentInputType',
    'PmmObjectUpdateInfoType',
    'RelatedObjectType',
    'RelatedObjectUpdateInfoType',
    'Row',
    'RowColumn',
    'RowSet',
    'SolutionAlignmentInputType',
    'UpdateAndAlignBomLineInfoType',
    'UpdateAndAlignDesignInfoType',
]
