# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class ElementInfo:
    """Stub for Awb0.Services.Internal.Strong.Activeworkspacebom._2022_06.OccurrenceManagement.ElementInfo"""
    def __init__(self) -> None: ...
    Element: typing.Any
    VisibleElement: typing.Any

class ElementsInput:
    """Stub for Awb0.Services.Internal.Strong.Activeworkspacebom._2022_06.OccurrenceManagement.ElementsInput"""
    def __init__(self) -> None: ...
    ProductContext: typing.Any
    TypeOfElementUids: str
    ElementUids: typing.Sequence[str]
    RequestPref: typing.Any

class ElementsResp:
    """Stub for Awb0.Services.Internal.Strong.Activeworkspacebom._2022_06.OccurrenceManagement.ElementsResp"""
    def __init__(self) -> None: ...
    ElementsInfo: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class OccurrenceInfo4:
    """Stub for Awb0.Services.Internal.Strong.Activeworkspacebom._2022_06.OccurrenceManagement.OccurrenceInfo4"""
    def __init__(self) -> None: ...
    Occurrence: typing.Any
    OccurrenceId: str
    StableId: str
    DisplayName: str
    NumberOfChildren: int
    UnderlyingObjectType: str
    Position: int

class OccurrenceManagement:
    """Stub for Awb0.Services.Internal.Strong.Activeworkspacebom._2022_06.OccurrenceManagement.OccurrenceManagement"""
    def __init__(self) -> None: ...
    def GetElementsForIds(self, ElementsIn: typing.Any) -> typing.Any: ...
    def GetOccurrences4(self, InputData: typing.Any) -> typing.Any: ...

class OccurrencesResp4:
    """Stub for Awb0.Services.Internal.Strong.Activeworkspacebom._2022_06.OccurrenceManagement.OccurrencesResp4"""
    def __init__(self) -> None: ...
    RootProductContext: typing.Any
    ParentProductContext: typing.Any
    ParentOccurrence: typing.Any
    FocusProductContext: typing.Any
    FocusChildOccurrence: typing.Any
    Cursor: typing.Any
    UserWorkingContextInfo: typing.Any
    Filter: typing.Any
    ElementToPCIMap: typing.Any
    SourceContextToInfoMap: typing.Any
    ParentChildrenInfos: typing.Sequence[typing.Any]
    RequestPref: typing.Any
    ServiceData: typing.Any

class ParentChildrenInfo4:
    """Stub for Awb0.Services.Internal.Strong.Activeworkspacebom._2022_06.OccurrenceManagement.ParentChildrenInfo4"""
    def __init__(self) -> None: ...
    ParentInfo: typing.Any
    ChildrenInfo: typing.Sequence[typing.Any]
    Cursor: typing.Any

__all__ = [
    'ElementInfo',
    'ElementsInput',
    'ElementsResp',
    'OccurrenceInfo4',
    'OccurrenceManagement',
    'OccurrencesResp4',
    'ParentChildrenInfo4',
]
