# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class InternalContext:
    """Stub for Teamcenter.Services.Internal.Strong.Administration._2007_06.PreferenceManagement.InternalContext"""
    def __init__(self) -> None: ...
    ContextName: str
    Value: typing.Sequence[str]

class InternalPreferenceDefinition:
    """Stub for Teamcenter.Services.Internal.Strong.Administration._2007_06.PreferenceManagement.InternalPreferenceDefinition"""
    def __init__(self) -> None: ...
    PreferenceName: str
    PreferenceCategory: str
    PreferenceDescription: str
    PreferenceScope: str
    PreferenceType: str
    IsArray: bool
    IsDisabled: bool

class InternalPreferenceInfo:
    """Stub for Teamcenter.Services.Internal.Strong.Administration._2007_06.PreferenceManagement.InternalPreferenceInfo"""
    def __init__(self) -> None: ...
    PreferenceDefinition: typing.Any
    ContextInformation: typing.Sequence[typing.Any]

class InternalPreferencesInfo:
    """Stub for Teamcenter.Services.Internal.Strong.Administration._2007_06.PreferenceManagement.InternalPreferencesInfo"""
    def __init__(self) -> None: ...
    PrefsInfo: typing.Sequence[typing.Any]

class PreferenceExportResponse:
    """Stub for Teamcenter.Services.Internal.Strong.Administration._2007_06.PreferenceManagement.PreferenceExportResponse"""
    def __init__(self) -> None: ...
    FileTicket: str
    ServiceData: typing.Any

class PreferenceManagement:
    """Stub for Teamcenter.Services.Internal.Strong.Administration._2007_06.PreferenceManagement.PreferenceManagement"""
    def __init__(self) -> None: ...
    def CreatePreferenceCategories(self, CategoryNames: typing.Sequence[str]) -> typing.Any: ...
    def DeletePreferences(self, DeletePrefs: typing.Sequence[typing.Any]) -> typing.Any: ...
    def ExportPreferences(self, ExportPrefs: typing.Any) -> typing.Any: ...
    def GetModifiedSitePreferences(self) -> typing.Any: ...
    def GetNonSessionPreferences(self, PreferenceScope: str, Object: typing.Any) -> typing.Any: ...
    def ImportPreferences(self, ImportPrefs: typing.Any) -> typing.Any: ...

class PreferenceResponse:
    """Stub for Teamcenter.Services.Internal.Strong.Administration._2007_06.PreferenceManagement.PreferenceResponse"""
    def __init__(self) -> None: ...
    PreferencesArray: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class PreferencesDeleteInput:
    """Stub for Teamcenter.Services.Internal.Strong.Administration._2007_06.PreferenceManagement.PreferencesDeleteInput"""
    def __init__(self) -> None: ...
    PreferenceScope: str
    PreferenceName: str
    Object: typing.Any

class PreferencesExportInput:
    """Stub for Teamcenter.Services.Internal.Strong.Administration._2007_06.PreferenceManagement.PreferencesExportInput"""
    def __init__(self) -> None: ...
    PreferenceScope: str
    CategoryNames: typing.Sequence[str]

class PreferencesImportInput:
    """Stub for Teamcenter.Services.Internal.Strong.Administration._2007_06.PreferenceManagement.PreferencesImportInput"""
    def __init__(self) -> None: ...
    PreferenceScope: str
    FileTicket: str
    CategoryNames: typing.Sequence[str]
    ImportAction: str

__all__ = [
    'InternalContext',
    'InternalPreferenceDefinition',
    'InternalPreferenceInfo',
    'InternalPreferencesInfo',
    'PreferenceExportResponse',
    'PreferenceManagement',
    'PreferenceResponse',
    'PreferencesDeleteInput',
    'PreferencesExportInput',
    'PreferencesImportInput',
]
