# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class ImportConfigRuntimeOverrideInfo2:
    """Stub for Cae0.Services.Strong.Simproc._2016_05.SimulationToolLaunch.ImportConfigRuntimeOverrideInfo2"""
    def __init__(self) -> None: ...
    ItemCreationSetting: str
    DatasetCreationSetting: str
    AutoProcessOptions: str
    OutputNamePatterns: typing.Sequence[str]

class LaunchInputInfo2:
    """Stub for Cae0.Services.Strong.Simproc._2016_05.SimulationToolLaunch.LaunchInputInfo2"""
    def __init__(self) -> None: ...
    InputObject: typing.Any
    InputDataset: typing.Any
    InputFile: typing.Any
    ConfigurationContext: typing.Any

class SimulationToolLaunch:
    """Stub for Cae0.Services.Strong.Simproc._2016_05.SimulationToolLaunch.SimulationToolLaunch"""
    def __init__(self) -> None: ...
    def ExecuteSimulationToolLaunch(self, SimulationTool: typing.Any, InputObjects: typing.Sequence[typing.Any], WorkingDirectory: str, LaunchType: str, ExportRuntimeConfiguration: typing.Any, ImportRuntimeConfiguration: typing.Any, PedigreeCaptureInfo: typing.Sequence[typing.Any]) -> typing.Any: ...

__all__ = [
    'ImportConfigRuntimeOverrideInfo2',
    'LaunchInputInfo2',
    'SimulationToolLaunch',
]
