# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class AddUsersAsGroupMembersStructure:
    """Stub for Teamcenter.Services.Strong.Administration._2017_05.UserManagement.AddUsersAsGroupMembersStructure"""
    def __init__(self) -> None: ...
    ClientId: str
    UsersToAdd: typing.Sequence[typing.Any]
    UsersToCreateAndAdd: typing.Sequence[typing.Any]
    Grp: typing.Any
    Role: typing.Any

class ExistingUserDetailsForGroupMember:
    """Stub for Teamcenter.Services.Strong.Administration._2017_05.UserManagement.ExistingUserDetailsForGroupMember"""
    def __init__(self) -> None: ...
    User: typing.Any
    UserAttributes: typing.Any

class NewUserDetailsForGroupMember:
    """Stub for Teamcenter.Services.Strong.Administration._2017_05.UserManagement.NewUserDetailsForGroupMember"""
    def __init__(self) -> None: ...
    User: typing.Any
    UserAttributes: typing.Any

class UserAttributesStructure:
    """Stub for Teamcenter.Services.Strong.Administration._2017_05.UserManagement.UserAttributesStructure"""
    def __init__(self) -> None: ...
    IsGroupAdmin: bool
    Status: bool
    IsDefaultRole: bool

class UserManagement:
    """Stub for Teamcenter.Services.Strong.Administration._2017_05.UserManagement.UserManagement"""
    def __init__(self) -> None: ...
    def AddUsersAsGroupMembers(self, UserRoleGroupStructs: typing.Sequence[typing.Any]) -> typing.Any: ...
    def RemoveGroupMembers(self, UserRoleGroupStructs: typing.Sequence[typing.Any]) -> typing.Any: ...

class UserManagementResponse:
    """Stub for Teamcenter.Services.Strong.Administration._2017_05.UserManagement.UserManagementResponse"""
    def __init__(self) -> None: ...
    UserRoleGrpStructs: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class UserRoleGroupStructure:
    """Stub for Teamcenter.Services.Strong.Administration._2017_05.UserManagement.UserRoleGroupStructure"""
    def __init__(self) -> None: ...
    Users: typing.Sequence[typing.Any]
    Grp: typing.Any
    Role: typing.Any

__all__ = [
    'AddUsersAsGroupMembersStructure',
    'ExistingUserDetailsForGroupMember',
    'NewUserDetailsForGroupMember',
    'UserAttributesStructure',
    'UserManagement',
    'UserManagementResponse',
    'UserRoleGroupStructure',
]
