# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class DataManagement:
    """Stub for Teamcenter.Services.Internal.Strong.Core._2010_09.DataManagement.DataManagement"""
    def __init__(self) -> None: ...
    def GetDatasetFiles(self, Inputs: typing.Sequence[typing.Any], RetrieveFiles: bool) -> typing.Any: ...

class DatasetAttrInfo:
    """Stub for Teamcenter.Services.Internal.Strong.Core._2010_09.DataManagement.DatasetAttrInfo"""
    def __init__(self) -> None: ...
    AttrName: str
    AttrValues: typing.Sequence[str]

class DatasetFileInfo:
    """Stub for Teamcenter.Services.Internal.Strong.Core._2010_09.DataManagement.DatasetFileInfo"""
    def __init__(self) -> None: ...
    Dataset: typing.Any
    ReferenceFileTicket: str

class DatasetFileQueryInfo:
    """Stub for Teamcenter.Services.Internal.Strong.Core._2010_09.DataManagement.DatasetFileQueryInfo"""
    def __init__(self) -> None: ...
    ClientID: str
    DatasetType: str
    ReferenceTypes: typing.Sequence[str]
    AttrInfo: typing.Sequence[typing.Any]

class DatasetFilesOutput:
    """Stub for Teamcenter.Services.Internal.Strong.Core._2010_09.DataManagement.DatasetFilesOutput"""
    def __init__(self) -> None: ...
    ClientID: str
    DatasetType: str
    DatasetReferenceFileInfo: typing.Sequence[typing.Any]

class DatasetFilesResponse:
    """Stub for Teamcenter.Services.Internal.Strong.Core._2010_09.DataManagement.DatasetFilesResponse"""
    def __init__(self) -> None: ...
    DatasetFilesOutput: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class DatasetReferenceFileInfo:
    """Stub for Teamcenter.Services.Internal.Strong.Core._2010_09.DataManagement.DatasetReferenceFileInfo"""
    def __init__(self) -> None: ...
    DatasetReferenceTypeName: str
    DatasetFiles: typing.Sequence[typing.Any]

__all__ = [
    'DataManagement',
    'DatasetAttrInfo',
    'DatasetFileInfo',
    'DatasetFileQueryInfo',
    'DatasetFilesOutput',
    'DatasetFilesResponse',
    'DatasetReferenceFileInfo',
]
