# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class CreateOrUpdateRevisionRuleInput:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2024_06.RevisionRuleAdministration.CreateOrUpdateRevisionRuleInput"""
    def __init__(self) -> None: ...
    RuleInfo: typing.Any
    PropValues: typing.Any
    UpdateExisting: bool

class CreateOrUpdateRevisionRuleResponse:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2024_06.RevisionRuleAdministration.CreateOrUpdateRevisionRuleResponse"""
    def __init__(self) -> None: ...
    RevRuleInfo: typing.Any
    ServiceData: typing.Any

class GetRevisionRuleInfoResponse:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2024_06.RevisionRuleAdministration.GetRevisionRuleInfoResponse"""
    def __init__(self) -> None: ...
    RevRuleInfo: typing.Any
    ServiceData: typing.Any

class PropertyValueInfo:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2024_06.RevisionRuleAdministration.PropertyValueInfo"""
    def __init__(self) -> None: ...
    BoolProps: typing.Any
    DateProps: typing.Any
    DoubleProps: typing.Any
    IntProps: typing.Any
    ReferenceProps: typing.Any
    StringProps: typing.Any

class RevisionRuleAdministration:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2024_06.RevisionRuleAdministration.RevisionRuleAdministration"""
    def __init__(self) -> None: ...
    def CreateOrUpdateRevisionRule(self, Input: typing.Any) -> typing.Any: ...
    def GetRevisionRuleInfo3(self, Uid: str) -> typing.Any: ...

class RevisionRuleEntryInfo:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2024_06.RevisionRuleAdministration.RevisionRuleEntryInfo"""
    def __init__(self) -> None: ...
    EntryType: int
    DisplayText: str
    PropValues: typing.Any
    SubEntriesInfo: typing.Sequence[typing.Any]

class RevisionRuleInfo:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2024_06.RevisionRuleAdministration.RevisionRuleInfo"""
    def __init__(self) -> None: ...
    RevRule: typing.Any
    Uid: str
    EntriesInfo: typing.Sequence[typing.Any]
    IsTransient: bool

__all__ = [
    'CreateOrUpdateRevisionRuleInput',
    'CreateOrUpdateRevisionRuleResponse',
    'GetRevisionRuleInfoResponse',
    'PropertyValueInfo',
    'RevisionRuleAdministration',
    'RevisionRuleEntryInfo',
    'RevisionRuleInfo',
]
