# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class CreateIn3:
    """Stub for Teamcenter.Services.Strong.Core._2018_06.DataManagement.CreateIn3"""
    def __init__(self) -> None: ...
    ClientId: str
    CreateData: typing.Any
    TargetObject: typing.Any
    PasteProp: str

class DataManagement:
    """Stub for Teamcenter.Services.Strong.Core._2018_06.DataManagement.DataManagement"""
    def __init__(self) -> None: ...
    def CreateObjectsInBulkAndRelate(self, CreateInputs: typing.Sequence[typing.Any]) -> typing.Any: ...

__all__ = [
    'CreateIn3',
    'DataManagement',
]
