# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
from teamcenter.tca0.services.strong.tcmaccess import StudyManagementService

class StudyManagementRestBindingStub(StudyManagementService):
    """Stub for Tca0.Services.Strong.Tcmaccess.StudyManagementRestBindingStub"""
    def __init__(self, connection: typing.Any) -> None: ...
    def FindStudiesInCC1(self, Input: typing.Sequence[typing.Any]) -> typing.Any: ...
    def OpenContexts(self, Input: typing.Sequence[typing.Any]) -> typing.Any: ...

class StudyManagementService:
    """Stub for Tca0.Services.Strong.Tcmaccess.StudyManagementService"""
    def __init__(self) -> None: ...
    def FindStudiesInCC1(self, Input: typing.Sequence[typing.Any]) -> typing.Any: ...
    def OpenContexts(self, Input: typing.Sequence[typing.Any]) -> typing.Any: ...
    @classmethod
    def getService(cls, connection: typing.Any) -> typing.Any: ...

__all__ = [
    'StudyManagementRestBindingStub',
    'StudyManagementService',
    '_2016_12',
    '_2017_06',
]
