# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class Finder:
    """Stub for Teamcenter.Services.Strong.Query._2014_11.Finder.Finder"""
    def __init__(self) -> None: ...
    def GroupObjectsByProperties(self, ObjectPropertyGroupInputList: typing.Sequence[typing.Any]) -> typing.Any: ...
    def PerformSearch(self, SearchInput: typing.Any) -> typing.Any: ...

class ObjectPropertyGroupInput:
    """Stub for Teamcenter.Services.Strong.Query._2014_11.Finder.ObjectPropertyGroupInput"""
    def __init__(self) -> None: ...
    InternalPropertyName: str
    PropertyValues: typing.Sequence[typing.Any]
    ObjectList: typing.Sequence[typing.Any]

class ObjectsGroupedByProperty:
    """Stub for Teamcenter.Services.Strong.Query._2014_11.Finder.ObjectsGroupedByProperty"""
    def __init__(self) -> None: ...
    InternalPropertyName: str
    GroupedObjectsMap: typing.Any
    UnmatchedObjectList: typing.Sequence[typing.Any]

class ObjectsGroupedByPropertyResponse:
    """Stub for Teamcenter.Services.Strong.Query._2014_11.Finder.ObjectsGroupedByPropertyResponse"""
    def __init__(self) -> None: ...
    GroupedObjectsList: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class PropertyGroupingValue:
    """Stub for Teamcenter.Services.Strong.Query._2014_11.Finder.PropertyGroupingValue"""
    def __init__(self) -> None: ...
    PropertyGroupID: str
    StartValue: str
    EndValue: str

class SearchFilter2:
    """Stub for Teamcenter.Services.Strong.Query._2014_11.Finder.SearchFilter2"""
    def __init__(self) -> None: ...
    SearchFilterType: str
    StringValue: str
    StringDisplayValue: str
    StartDateValue: typing.Any
    EndDateValue: typing.Any
    StartNumericValue: float
    EndNumericValue: float
    Count: int
    Selected: bool
    StartEndRange: str

class SearchInput2:
    """Stub for Teamcenter.Services.Strong.Query._2014_11.Finder.SearchInput2"""
    def __init__(self) -> None: ...
    ProviderName: str
    SearchCriteria: typing.Any
    StartIndex: int
    MaxToReturn: int
    MaxToLoad: int
    SearchFilterMap: typing.Any
    SearchSortCriteria: typing.Sequence[typing.Any]
    SearchFilterFieldSortType: str
    AttributesToInflate: typing.Sequence[str]
    InternalPropertyName: str

class SearchResponse2:
    """Stub for Teamcenter.Services.Strong.Query._2014_11.Finder.SearchResponse2"""
    def __init__(self) -> None: ...
    SearchResults: typing.Sequence[typing.Any]
    TotalFound: int
    TotalLoaded: int
    SearchFilterMap: typing.Any
    SearchFilterCategories: typing.Sequence[typing.Any]
    DefaultFilterFieldDisplayCount: int
    ServiceData: typing.Any
    ObjectsGroupedByProperty: typing.Any

__all__ = [
    'Finder',
    'ObjectPropertyGroupInput',
    'ObjectsGroupedByProperty',
    'ObjectsGroupedByPropertyResponse',
    'PropertyGroupingValue',
    'SearchFilter2',
    'SearchInput2',
    'SearchResponse2',
]
