# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class BomLineVariantCondition:
    """Stub for Teamcenter.Services.Strong.Cad._2007_12.StructureManagement.BomLineVariantCondition"""
    def __init__(self) -> None: ...
    BomLine: typing.Any
    ConditionClauses: typing.Sequence[typing.Any]

class ClassicOptionData:
    """Stub for Teamcenter.Services.Strong.Cad._2007_12.StructureManagement.ClassicOptionData"""
    def __init__(self) -> None: ...
    ItemRevision: typing.Any
    OptionData: typing.Sequence[typing.Any]

class ClassicOptionsResponse:
    """Stub for Teamcenter.Services.Strong.Cad._2007_12.StructureManagement.ClassicOptionsResponse"""
    def __init__(self) -> None: ...
    ItemRevisionOptionData: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class CreateOrUpdateAbsoluteStructureInfo2:
    """Stub for Teamcenter.Services.Strong.Cad._2007_12.StructureManagement.CreateOrUpdateAbsoluteStructureInfo2"""
    def __init__(self) -> None: ...
    LastModifiedOfBVR: typing.Any
    ContextItemRev: typing.Any
    BvrAbsOccInfo: typing.Sequence[typing.Any]
    ArrAbsOccInfo: typing.Sequence[typing.Any]

class CreateOrUpdateAbsoluteStructurePref2:
    """Stub for Teamcenter.Services.Strong.Cad._2007_12.StructureManagement.CreateOrUpdateAbsoluteStructurePref2"""
    def __init__(self) -> None: ...
    OverwriteForLastModDate: bool
    CadOccIdAttrName: str

class CreateOrUpdateRelativeStructureInfo2:
    """Stub for Teamcenter.Services.Strong.Cad._2007_12.StructureManagement.CreateOrUpdateRelativeStructureInfo2"""
    def __init__(self) -> None: ...
    LastModifiedOfBVR: typing.Any
    Parent: typing.Any
    ChildInfo: typing.Sequence[typing.Any]
    Precise: bool

class CreateOrUpdateRelativeStructurePref2:
    """Stub for Teamcenter.Services.Strong.Cad._2007_12.StructureManagement.CreateOrUpdateRelativeStructurePref2"""
    def __init__(self) -> None: ...
    OverwriteForLastModDate: bool
    CadOccIdAttrName: str
    ItemTypes: typing.Sequence[str]

class DeleteAssemblyArrangementsInfo2:
    """Stub for Teamcenter.Services.Strong.Cad._2007_12.StructureManagement.DeleteAssemblyArrangementsInfo2"""
    def __init__(self) -> None: ...
    LastModifiedOfBVR: typing.Any
    ItemRev: typing.Any
    Arrangements: typing.Sequence[typing.Any]

class DeleteAssemblyArrangementsPref:
    """Stub for Teamcenter.Services.Strong.Cad._2007_12.StructureManagement.DeleteAssemblyArrangementsPref"""
    def __init__(self) -> None: ...
    OverwriteForLastModDate: bool

class DeleteRelativeStructureInfo2:
    """Stub for Teamcenter.Services.Strong.Cad._2007_12.StructureManagement.DeleteRelativeStructureInfo2"""
    def __init__(self) -> None: ...
    LastModifiedOfBVR: typing.Any
    Parent: typing.Any
    ChildInfo: typing.Sequence[str]

class DeleteRelativeStructurePref2:
    """Stub for Teamcenter.Services.Strong.Cad._2007_12.StructureManagement.DeleteRelativeStructurePref2"""
    def __init__(self) -> None: ...
    OverwriteForLastModDate: bool
    CadOccIdAttrName: str

class StructureManagement:
    """Stub for Teamcenter.Services.Strong.Cad._2007_12.StructureManagement.StructureManagement"""
    def __init__(self) -> None: ...
    def CreateOrUpdateAbsoluteStructure(self, Info: typing.Sequence[typing.Any], BomViewTypeName: str, Complete: bool, Pref: typing.Any) -> typing.Any: ...
    def CreateOrUpdateRelativeStructure(self, Inputs: typing.Sequence[typing.Any], BomViewTypeName: str, Complete: bool, Pref: typing.Any) -> typing.Any: ...
    def DeleteAssemblyArrangements(self, Info: typing.Sequence[typing.Any], BomViewTypeName: str, Pref: typing.Any) -> typing.Any: ...
    def DeleteRelativeStructure(self, Inputs: typing.Sequence[typing.Any], BomViewTypeName: str, Pref: typing.Any) -> typing.Any: ...
    def QueryClassicOptions(self, InputRevisions: typing.Sequence[typing.Any]) -> typing.Any: ...
    def QueryVariantConditions(self, InputBomLines: typing.Sequence[typing.Any]) -> typing.Any: ...

class VariantConditionResponse:
    """Stub for Teamcenter.Services.Strong.Cad._2007_12.StructureManagement.VariantConditionResponse"""
    def __init__(self) -> None: ...
    VariantConditions: typing.Sequence[typing.Any]
    ServiceData: typing.Any

__all__ = [
    'BomLineVariantCondition',
    'ClassicOptionData',
    'ClassicOptionsResponse',
    'CreateOrUpdateAbsoluteStructureInfo2',
    'CreateOrUpdateAbsoluteStructurePref2',
    'CreateOrUpdateRelativeStructureInfo2',
    'CreateOrUpdateRelativeStructurePref2',
    'DeleteAssemblyArrangementsInfo2',
    'DeleteAssemblyArrangementsPref',
    'DeleteRelativeStructureInfo2',
    'DeleteRelativeStructurePref2',
    'StructureManagement',
    'VariantConditionResponse',
]
