# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class CrfReports:
    """Stub for Teamcenter.Services.Strong.Reports._2015_03.CrfReports.CrfReports"""
    def __init__(self) -> None: ...
    def GeneratePrintReports(self, ReportDefObj: typing.Any, Inputs: typing.Sequence[typing.Any]) -> typing.Any: ...
    def GenerateReport(self, Inputs: typing.Sequence[typing.Any]) -> typing.Any: ...
    def GetPrintTemplates(self, ContextObjects: typing.Sequence[typing.Any]) -> typing.Any: ...

class GeneratePrintReportsOutput:
    """Stub for Teamcenter.Services.Strong.Reports._2015_03.CrfReports.GeneratePrintReportsOutput"""
    def __init__(self) -> None: ...
    ClientID: str
    TransientFileReadTickets: typing.Sequence[str]
    TransientFileTicketInfos: typing.Sequence[typing.Any]

class GeneratePrintReportsResponse:
    """Stub for Teamcenter.Services.Strong.Reports._2015_03.CrfReports.GeneratePrintReportsResponse"""
    def __init__(self) -> None: ...
    Outputs: typing.Sequence[typing.Any]
    ServiceData: typing.Any
    ExecutedAsynchronously: bool

class GenerateReportsCriteria2Async:
    """Stub for Teamcenter.Services.Strong.Reports._2015_03.CrfReports.GenerateReportsCriteria2Async"""
    def __init__(self) -> None: ...
    ClientId: str
    ReportDefinition: typing.Any
    ReportName: str
    Stylesheet: typing.Any
    StylesheetName: str
    ContextObjects: typing.Sequence[typing.Any]
    DatasetName: str
    CriteriaNames: typing.Sequence[str]
    CriteriaValues: typing.Sequence[str]
    DatasetCtxUID: str
    DatasetCtxObj: typing.Any
    RelationName: str
    DatasetType: str
    ReportOptionsNames: typing.Sequence[str]
    ReportOptionsValues: typing.Sequence[str]

class GenerateReportsResponse2:
    """Stub for Teamcenter.Services.Strong.Reports._2015_03.CrfReports.GenerateReportsResponse2"""
    def __init__(self) -> None: ...
    TransientFileReadTickets: typing.Sequence[str]
    TransientFileTicketInfos: typing.Sequence[typing.Any]
    ServiceData: typing.Any
    AsyncFlagInfo: bool

class PrintReportsCriteria:
    """Stub for Teamcenter.Services.Strong.Reports._2015_03.CrfReports.PrintReportsCriteria"""
    def __init__(self) -> None: ...
    ClientID: str
    InputObject: typing.Any
    IsBatchPrint: bool
    PrintInfos: typing.Sequence[typing.Any]

class PrintReportsCriteriaAsync:
    """Stub for Teamcenter.Services.Strong.Reports._2015_03.CrfReports.PrintReportsCriteriaAsync"""
    def __init__(self) -> None: ...
    ClientID: str
    InputObject: typing.Any
    IsBatchPrint: bool
    PrintInfos: typing.Sequence[typing.Any]

class PrintSubmitRequestInfo:
    """Stub for Teamcenter.Services.Strong.Reports._2015_03.CrfReports.PrintSubmitRequestInfo"""
    def __init__(self) -> None: ...
    ClientID: str
    PrintObjs: typing.Sequence[typing.Any]
    PrinterConfigurationName: str
    PrinterName: str
    ColorMode: str
    UserStamp: str
    PaperSize: str
    PrintStamp: str
    PageRange: str
    NumberCopies: str
    Collate: bool
    PrintToScale: str
    Orientation: str
    BannerPage: str
    ExtraInfo: typing.Any

__all__ = [
    'CrfReports',
    'GeneratePrintReportsOutput',
    'GeneratePrintReportsResponse',
    'GenerateReportsCriteria2Async',
    'GenerateReportsResponse2',
    'PrintReportsCriteria',
    'PrintReportsCriteriaAsync',
    'PrintSubmitRequestInfo',
]
