# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class IMDSIntegration:
    """Stub for Sci0.Services.Strong.Imdsintegration._2021_12.IMDSIntegration.IMDSIntegration"""
    def __init__(self) -> None: ...
    def SendDataToIMDS(self, ImdsIn: typing.Sequence[typing.Any], RunInBackground: bool) -> typing.Any: ...

class SendToIMDSOut:
    """Stub for Sci0.Services.Strong.Imdsintegration._2021_12.IMDSIntegration.SendToIMDSOut"""
    def __init__(self) -> None: ...
    SentObject: typing.Any
    FailureReason: str

class SendToIMDSResponse:
    """Stub for Sci0.Services.Strong.Imdsintegration._2021_12.IMDSIntegration.SendToIMDSResponse"""
    def __init__(self) -> None: ...
    ResponseData: typing.Sequence[typing.Any]
    ServiceData: typing.Any

__all__ = [
    'IMDSIntegration',
    'SendToIMDSOut',
    'SendToIMDSResponse',
]
