# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class AdvancedProgramManagement:
    """Stub for Prg1.Services.Internal.Strong.Programplanningapp._2018_11.AdvancedProgramManagement.AdvancedProgramManagement"""
    def __init__(self) -> None: ...
    def GetVolumeTargets(self, InputInfo: typing.Sequence[typing.Any]) -> typing.Any: ...

class GetVolumeTargetsInputInfo:
    """Stub for Prg1.Services.Internal.Strong.Programplanningapp._2018_11.AdvancedProgramManagement.GetVolumeTargetsInputInfo"""
    def __init__(self) -> None: ...
    ProductLine: typing.Any
    ProductModels: typing.Sequence[typing.Any]
    RevisionRule: typing.Any

class GetVolumeTargetsResponse:
    """Stub for Prg1.Services.Internal.Strong.Programplanningapp._2018_11.AdvancedProgramManagement.GetVolumeTargetsResponse"""
    def __init__(self) -> None: ...
    VolumeTargets: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class MixRateTarget:
    """Stub for Prg1.Services.Internal.Strong.Programplanningapp._2018_11.AdvancedProgramManagement.MixRateTarget"""
    def __init__(self) -> None: ...
    ProductModelLevelTarget: typing.Any
    ProductModel: typing.Any
    DistributionFactor: float
    Goal: float
    TakeRates: typing.Sequence[typing.Any]

class TakeRateTarget:
    """Stub for Prg1.Services.Internal.Strong.Programplanningapp._2018_11.AdvancedProgramManagement.TakeRateTarget"""
    def __init__(self) -> None: ...
    FeatureLevelTarget: typing.Any
    Feature: typing.Any
    DistributionFactor: float
    Goal: float

class VolumeTarget:
    """Stub for Prg1.Services.Internal.Strong.Programplanningapp._2018_11.AdvancedProgramManagement.VolumeTarget"""
    def __init__(self) -> None: ...
    PlanLevelTarget: typing.Any
    ProductLine: typing.Any
    Goal: float
    MixRates: typing.Sequence[typing.Any]

__all__ = [
    'AdvancedProgramManagement',
    'GetVolumeTargetsInputInfo',
    'GetVolumeTargetsResponse',
    'MixRateTarget',
    'TakeRateTarget',
    'VolumeTarget',
]
