# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class ExportConfigRuntimeOverrideInfo2:
    """Stub for Cae0.Services.Strong.Simproc._2023_06.SimulationToolLaunch.ExportConfigRuntimeOverrideInfo2"""
    def __init__(self) -> None: ...
    PlmxmlExportFileName: str
    RuntimeArguments: typing.Sequence[str]

class ExportFileOptions2:
    """Stub for Cae0.Services.Strong.Simproc._2023_06.SimulationToolLaunch.ExportFileOptions2"""
    def __init__(self) -> None: ...
    IsAutoProcessSelected: bool
    AutoProcessOption: str
    PromptUserOptions: typing.Sequence[typing.Any]

class ExportFilePromptUserOption2:
    """Stub for Cae0.Services.Strong.Simproc._2023_06.SimulationToolLaunch.ExportFilePromptUserOption2"""
    def __init__(self) -> None: ...
    FileObject: typing.Any
    ExportOption: str

class ImportConfigRuntimeOverrideInfo3:
    """Stub for Cae0.Services.Strong.Simproc._2023_06.SimulationToolLaunch.ImportConfigRuntimeOverrideInfo3"""
    def __init__(self) -> None: ...
    ItemCreationSetting: str
    DatasetCreationSetting: str
    AutoProcessOptions: str
    OutputNamePatterns: typing.Sequence[str]

class LaunchInputInfo4:
    """Stub for Cae0.Services.Strong.Simproc._2023_06.SimulationToolLaunch.LaunchInputInfo4"""
    def __init__(self) -> None: ...
    InputObject: typing.Any
    InputDataset: typing.Any
    InputFile: typing.Any
    InputWebLink: typing.Any
    ConfigurationContext: typing.Any

class OptionalInputInfo2:
    """Stub for Cae0.Services.Strong.Simproc._2023_06.SimulationToolLaunch.OptionalInputInfo2"""
    def __init__(self) -> None: ...
    InputObject: typing.Any
    ExportDirectory: str

class SimulationToolLaunch:
    """Stub for Cae0.Services.Strong.Simproc._2023_06.SimulationToolLaunch.SimulationToolLaunch"""
    def __init__(self) -> None: ...
    def ExecuteSimulationToolLaunch(self, SimulationTool: typing.Any, InputObjects: typing.Sequence[typing.Any], ScratchDirectory: str, UserStagingLocation: str, UserStagingDir: str, LaunchType: str, ExportRuntimeConfiguration: typing.Any, ImportRuntimeConfiguration: typing.Any, PedigreeCaptureInfo: typing.Sequence[typing.Any], OptionalInputInfo: typing.Sequence[typing.Any], FileExportOptions: typing.Sequence[typing.Any], HpcConnectionObject: typing.Any) -> typing.Any: ...

__all__ = [
    'ExportConfigRuntimeOverrideInfo2',
    'ExportFileOptions2',
    'ExportFilePromptUserOption2',
    'ImportConfigRuntimeOverrideInfo3',
    'LaunchInputInfo4',
    'OptionalInputInfo2',
    'SimulationToolLaunch',
]
