# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class EffectivityConditionInfo:
    """Stub for Fnd0.Services.Strong.Configfiltercriteria._2017_05.EffectivityManagement.EffectivityConditionInfo"""
    def __init__(self) -> None: ...
    TargetObjects: typing.Sequence[typing.Any]
    Expression: typing.Any

class EffectivityConditionSource:
    """Stub for Fnd0.Services.Strong.Configfiltercriteria._2017_05.EffectivityManagement.EffectivityConditionSource"""
    def __init__(self) -> None: ...
    SourceObject: typing.Any
    SourceExpression: typing.Any

class EffectivityManagement:
    """Stub for Fnd0.Services.Strong.Configfiltercriteria._2017_05.EffectivityManagement.EffectivityManagement"""
    def __init__(self) -> None: ...
    def GetEffectivitySubsetTables(self, ProductName: str, ProductNamespace: str, SubsetCriteria: typing.Any, EffectivityConditions: typing.Sequence[typing.Any]) -> typing.Any: ...
    def SetEffectivityConditionSubsets(self, ProductName: str, ProductNamespace: str, SubsetCriteria: typing.Any, ActionCode: int, EffectivityConditions: typing.Sequence[typing.Any]) -> typing.Any: ...

__all__ = [
    'EffectivityConditionInfo',
    'EffectivityConditionSource',
    'EffectivityManagement',
]
