# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class DefaultWebRequestCreator:
    """Stub for Teamcenter_SSO.sso_applib.com.teamcenter._ss.client.login.DefaultWebRequestCreator"""
    def __init__(self) -> None: ...
    def CreateWebRequest(self, uri: typing.Any) -> typing.Any: ...

class IWebRequestCreator:
    """Stub for Teamcenter_SSO.sso_applib.com.teamcenter._ss.client.login.IWebRequestCreator"""
    def __init__(self) -> None: ...
    def CreateWebRequest(self, uri: typing.Any) -> typing.Any: ...

class SessionAgentJsonHttpBinding:
    """Stub for Teamcenter_SSO.sso_applib.com.teamcenter._ss.client.login.SessionAgentJsonHttpBinding"""
    def __init__(self, URLstr: str) -> None: ...
    @typing.overload
    def Init(self, URLstr: str) -> None: ...
    @typing.overload
    def Init(self, URLstr: str, creator: typing.Any) -> None: ...
    def SendRequest(self, payload: dict[str, typing.Any]) -> dict[str, typing.Any]: ...

__all__ = [
    'DefaultWebRequestCreator',
    'IWebRequestCreator',
    'SessionAgentJsonHttpBinding',
]
