# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
from teamcenter.microsoft.xml.serialization.generatedassembly import XmlSerializer1
from teamcenter.system.xml.serialization import XmlSerializationReader
from teamcenter.system.xml.serialization import XmlSerializationWriter
from teamcenter.system.xml.serialization import XmlSerializer
from teamcenter.system.xml.serialization import XmlSerializerImplementation

class XmlBindingUtilsSerializer(XmlSerializer1):
    """Stub for Microsoft.Xml.Serialization.GeneratedAssembly.XmlBindingUtilsSerializer"""
    def __init__(self) -> None: ...
    def CanDeserialize(self, xmlReader: typing.Any) -> bool: ...

class XmlSerializationReaderXmlBindingUtils(XmlSerializationReader):
    """Stub for Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderXmlBindingUtils"""
    def __init__(self) -> None: ...
    def Read3_XmlBindingUtils(self) -> typing.Any: ...

class XmlSerializationWriterXmlBindingUtils(XmlSerializationWriter):
    """Stub for Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterXmlBindingUtils"""
    def __init__(self) -> None: ...
    def Write3_XmlBindingUtils(self, o: typing.Any) -> None: ...

class XmlSerializer1(XmlSerializer):
    """Stub for Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializer1"""
    def __init__(self) -> None: ...

class XmlSerializerContract(XmlSerializerImplementation):
    """Stub for Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializerContract"""
    def __init__(self) -> None: ...
    @property
    def Reader(self) -> typing.Any: ...
    @property
    def Writer(self) -> typing.Any: ...
    @property
    def ReadMethods(self) -> typing.Any: ...
    @property
    def WriteMethods(self) -> typing.Any: ...
    @property
    def TypedSerializers(self) -> typing.Any: ...
    def CanSerialize(self, type: typing.Any) -> bool: ...
    def GetSerializer(self, type: typing.Any) -> typing.Any: ...

__all__ = [
    'XmlBindingUtilsSerializer',
    'XmlSerializationReaderXmlBindingUtils',
    'XmlSerializationWriterXmlBindingUtils',
    'XmlSerializer1',
    'XmlSerializerContract',
]
