# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class EditOccEffectivityInput:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2015_10.Effectivity.EditOccEffectivityInput"""
    def __init__(self) -> None: ...
    BomLine: typing.Any
    EffectivityComponent: typing.Any
    EffectivityInfoInput: typing.Any

class EditRelStatusEffectivityInput:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2015_10.Effectivity.EditRelStatusEffectivityInput"""
    def __init__(self) -> None: ...
    ReleaseStatus: typing.Any
    EffectivityComponent: typing.Any
    EffectivityInfoInput: typing.Any

class Effectivity:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2015_10.Effectivity.Effectivity"""
    def __init__(self) -> None: ...
    def EditOccurrenceEffectivity(self, Input: typing.Sequence[typing.Any]) -> typing.Any: ...
    def EditReleaseStatusEffectivity(self, Input: typing.Sequence[typing.Any]) -> typing.Any: ...
    def RemoveOccurrenceEffectivities(self, Input: typing.Sequence[typing.Any]) -> typing.Any: ...
    def RemoveReleaseStatusEffectivity(self, Input: typing.Sequence[typing.Any]) -> typing.Any: ...

class RemoveOccEffectivitiesInput:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2015_10.Effectivity.RemoveOccEffectivitiesInput"""
    def __init__(self) -> None: ...
    BomLine: typing.Any
    EffectivityComponents: typing.Sequence[typing.Any]

class RemoveRelStatusEffectivityInput:
    """Stub for Teamcenter.Services.Strong.Structuremanagement._2015_10.Effectivity.RemoveRelStatusEffectivityInput"""
    def __init__(self) -> None: ...
    ReleaseStatus: typing.Any
    EffectivityComponent: typing.Any

__all__ = [
    'EditOccEffectivityInput',
    'EditRelStatusEffectivityInput',
    'Effectivity',
    'RemoveOccEffectivitiesInput',
    'RemoveRelStatusEffectivityInput',
]
