# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class CalendarContainer:
    """Stub for Teamcenter.Services.Strong.Calendarmanagement._2008_06.CalendarManagement.CalendarContainer"""
    def __init__(self) -> None: ...
    TccalendarAttributes: typing.Any
    NewEvents: typing.Sequence[typing.Any]

class CalendarData:
    """Stub for Teamcenter.Services.Strong.Calendarmanagement._2008_06.CalendarManagement.CalendarData"""
    def __init__(self) -> None: ...
    Name: str
    Description: str
    Schedule: typing.Any
    Source: typing.Any
    BaseCalendar: typing.Any
    Type: int
    SunRanges: typing.Sequence[typing.Any]
    MonRanges: typing.Sequence[typing.Any]
    TueRanges: typing.Sequence[typing.Any]
    WedRanges: typing.Sequence[typing.Any]
    ThuRanges: typing.Sequence[typing.Any]
    FriRanges: typing.Sequence[typing.Any]
    SatRanges: typing.Sequence[typing.Any]
    TimeZone: str

class CalendarManagement:
    """Stub for Teamcenter.Services.Strong.Calendarmanagement._2008_06.CalendarManagement.CalendarManagement"""
    def __init__(self) -> None: ...
    def CreateCalendars(self, NewTCCalendars: typing.Sequence[typing.Any]) -> typing.Any: ...
    def UpdateCalendars(self, TccalendarUpdates: typing.Sequence[typing.Any]) -> typing.Any: ...

class CalendarUpdate:
    """Stub for Teamcenter.Services.Strong.Calendarmanagement._2008_06.CalendarManagement.CalendarUpdate"""
    def __init__(self) -> None: ...
    Calendar: typing.Any
    CalendarAttributes: typing.Any
    EventsToAdd: typing.Sequence[typing.Any]
    EventsToDelete: typing.Sequence[typing.Any]
    EventsToUpdate: typing.Sequence[typing.Any]

__all__ = [
    'CalendarContainer',
    'CalendarData',
    'CalendarManagement',
    'CalendarUpdate',
]
