# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class MoveMilestoneInput:
    """Stub for Psi0.Services.Strong.Ppsminterfaceaw._2023_06.PPSMInterface.MoveMilestoneInput"""
    def __init__(self) -> None: ...
    ScheduleTaskObject: typing.Any
    NewDate: typing.Any
    UpdateSecondaryObjects: bool

class PPSMInterface:
    """Stub for Psi0.Services.Strong.Ppsminterfaceaw._2023_06.PPSMInterface.PPSMInterface"""
    def __init__(self) -> None: ...
    def MoveMilestones(self, MoveMilestonesInput: typing.Sequence[typing.Any], RunInBackground: bool) -> typing.Any: ...

__all__ = [
    'MoveMilestoneInput',
    'PPSMInterface',
]
