# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class CreateOrUpdateAttachmentsData:
    """Stub for Teamcenter.Services.Strong.Manufacturing._2009_06.StructureManagement.CreateOrUpdateAttachmentsData"""
    def __init__(self) -> None: ...
    BomLine: typing.Any
    AttLine: typing.Any
    Objects: typing.Any

class GetAttachmentLineChildrenResponse:
    """Stub for Teamcenter.Services.Strong.Manufacturing._2009_06.StructureManagement.GetAttachmentLineChildrenResponse"""
    def __init__(self) -> None: ...
    Lines: typing.Any
    ServiceData: typing.Any

class GetBOMLineActivitiesResponse:
    """Stub for Teamcenter.Services.Strong.Manufacturing._2009_06.StructureManagement.GetBOMLineActivitiesResponse"""
    def __init__(self) -> None: ...
    Lines: typing.Any
    ServiceData: typing.Any

class GetBOMLineAttachmentsResponse:
    """Stub for Teamcenter.Services.Strong.Manufacturing._2009_06.StructureManagement.GetBOMLineAttachmentsResponse"""
    def __init__(self) -> None: ...
    Lines: typing.Any
    ServiceData: typing.Any

class GetStructureContextActivityLinesResponse:
    """Stub for Teamcenter.Services.Strong.Manufacturing._2009_06.StructureManagement.GetStructureContextActivityLinesResponse"""
    def __init__(self) -> None: ...
    Lines: typing.Any
    ServiceData: typing.Any

class GetStructureContextTopLinesResponse:
    """Stub for Teamcenter.Services.Strong.Manufacturing._2009_06.StructureManagement.GetStructureContextTopLinesResponse"""
    def __init__(self) -> None: ...
    Lines: typing.Any
    ServiceData: typing.Any

class StructureManagement:
    """Stub for Teamcenter.Services.Strong.Manufacturing._2009_06.StructureManagement.StructureManagement"""
    def __init__(self) -> None: ...
    def CloseAttachmentWindow(self, Lines: typing.Sequence[typing.Any]) -> typing.Any: ...
    def CreateOrUpdateAttachments(self, Attachments: typing.Sequence[typing.Any]) -> typing.Any: ...
    def DeleteAttachments(self, Lines: typing.Sequence[typing.Any]) -> typing.Any: ...
    def GetAttachmentLineChildren(self, Attlines: typing.Sequence[typing.Any]) -> typing.Any: ...
    def GetBOMLineActivities(self, BomLines: typing.Sequence[typing.Any]) -> typing.Any: ...
    def GetBOMLineAttachments(self, Bomlines: typing.Sequence[typing.Any], Filter: typing.Sequence[str]) -> typing.Any: ...
    def GetStructureContextActivityLines(self, Scs: typing.Sequence[typing.Any]) -> typing.Any: ...
    def GetStructureContextTopLines(self, Scs: typing.Sequence[typing.Any]) -> typing.Any: ...

__all__ = [
    'CreateOrUpdateAttachmentsData',
    'GetAttachmentLineChildrenResponse',
    'GetBOMLineActivitiesResponse',
    'GetBOMLineAttachmentsResponse',
    'GetStructureContextActivityLinesResponse',
    'GetStructureContextTopLinesResponse',
    'StructureManagement',
]
