# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class Session:
    """Stub for Teamcenter.Services.Strong.Core._2023_12.Session.Session"""
    def __init__(self) -> None: ...
    def Logout(self, ClientIDs: typing.Sequence[str]) -> bool: ...

__all__ = [
    'Session',
]
