# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class AttachmentComparisonDetailsResponse:
    """Stub for Teamcenter.Services.Internal.Strong.Structuremanagement._2017_05.StructureVerification.AttachmentComparisonDetailsResponse"""
    def __init__(self) -> None: ...
    Details: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class AttachmentDetail:
    """Stub for Teamcenter.Services.Internal.Strong.Structuremanagement._2017_05.StructureVerification.AttachmentDetail"""
    def __init__(self) -> None: ...
    Attachments: typing.Sequence[typing.Any]
    MatchType: int

class AttachmentTypeDetail:
    """Stub for Teamcenter.Services.Internal.Strong.Structuremanagement._2017_05.StructureVerification.AttachmentTypeDetail"""
    def __init__(self) -> None: ...
    Index: int
    EquivalentLines: typing.Sequence[typing.Any]
    AttachmentExtDetails: typing.Sequence[typing.Any]

class AttachmentTypeDetailElement:
    """Stub for Teamcenter.Services.Internal.Strong.Structuremanagement._2017_05.StructureVerification.AttachmentTypeDetailElement"""
    def __init__(self) -> None: ...
    AttachmentRelType: typing.Any
    AttachmentsDetails: typing.Sequence[typing.Any]

class ExtensionAttachmentTypeDetails:
    """Stub for Teamcenter.Services.Internal.Strong.Structuremanagement._2017_05.StructureVerification.ExtensionAttachmentTypeDetails"""
    def __init__(self) -> None: ...
    ExtensionName: str
    AttachmentTypesDetails: typing.Sequence[typing.Any]

class StructureVerification:
    """Stub for Teamcenter.Services.Internal.Strong.Structuremanagement._2017_05.StructureVerification.StructureVerification"""
    def __init__(self) -> None: ...
    def GetAttachmentComparisonDetails(self, EquivalentObjects: typing.Sequence[typing.Any], PartialMatchCriteria: typing.Sequence[typing.Any]) -> typing.Any: ...

__all__ = [
    'AttachmentComparisonDetailsResponse',
    'AttachmentDetail',
    'AttachmentTypeDetail',
    'AttachmentTypeDetailElement',
    'ExtensionAttachmentTypeDetails',
    'StructureVerification',
]
