# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class ReSequenceParameter:
    """Stub for Teamcenter.Services.Internal.Strong.Structuremanagement._2010_09.Structure.ReSequenceParameter"""
    def __init__(self) -> None: ...
    BomLines: typing.Sequence[typing.Any]
    StartNumber: int
    IncreNumber: int
    Recursive: bool
    IgnoreFlows: bool

class Structure:
    """Stub for Teamcenter.Services.Internal.Strong.Structuremanagement._2010_09.Structure.Structure"""
    def __init__(self) -> None: ...
    def Resequence(self, Input: typing.Sequence[typing.Any]) -> typing.Any: ...

__all__ = [
    'ReSequenceParameter',
    'Structure',
]
