# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class EventDateRanges:
    """Stub for Saw1.Services.Strong.Projectmanagementaw._2016_12.ScheduleManagementAw.EventDateRanges"""
    def __init__(self) -> None: ...
    EventDate: typing.Any
    Ranges: typing.Sequence[str]

class LoadScheduleInfo:
    """Stub for Saw1.Services.Strong.Projectmanagementaw._2016_12.ScheduleManagementAw.LoadScheduleInfo"""
    def __init__(self) -> None: ...
    Schedule: typing.Any
    ReferenceTask: typing.Any
    ParentTasks: typing.Sequence[typing.Any]

class LoadScheduleResponse:
    """Stub for Saw1.Services.Strong.Projectmanagementaw._2016_12.ScheduleManagementAw.LoadScheduleResponse"""
    def __init__(self) -> None: ...
    ScheduleTasks: typing.Sequence[typing.Any]
    ParentTasks: typing.Sequence[typing.Any]
    ProxyTasks: typing.Sequence[typing.Any]
    TaskDependencies: typing.Sequence[typing.Any]
    HasMoreTasks: bool
    DayRanges: typing.Any
    EventRanges: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class ReplaceMemberAssignmentData:
    """Stub for Saw1.Services.Strong.Projectmanagementaw._2016_12.ScheduleManagementAw.ReplaceMemberAssignmentData"""
    def __init__(self) -> None: ...
    OldResource: typing.Any
    NewResource: typing.Any

class ScheduleManagementAw:
    """Stub for Saw1.Services.Strong.Projectmanagementaw._2016_12.ScheduleManagementAw.ScheduleManagementAw"""
    def __init__(self) -> None: ...
    def LoadSchedule(self, LoadScheduleInfo: typing.Any) -> typing.Any: ...
    def RemoveAssignments(self, MembersToRemoveAssignments: typing.Sequence[typing.Any], RunInBackground: bool) -> typing.Any: ...
    def ReplaceMemberAssignments(self, ReplaceMemberAssignmentData: typing.Sequence[typing.Any], RunInBackground: bool) -> typing.Any: ...

__all__ = [
    'EventDateRanges',
    'LoadScheduleInfo',
    'LoadScheduleResponse',
    'ReplaceMemberAssignmentData',
    'ScheduleManagementAw',
]
