# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class BranchFoundation:
    """Stub for Bhv0.Services.Strong.Branchfoundation._2017_11.BranchFoundation.BranchFoundation"""
    def __init__(self) -> None: ...
    def GetPromoteBranchCandidates(self, Inputs: typing.Sequence[typing.Any]) -> typing.Any: ...

class GetPromoteBranchCandidatesInfo:
    """Stub for Bhv0.Services.Strong.Branchfoundation._2017_11.BranchFoundation.GetPromoteBranchCandidatesInfo"""
    def __init__(self) -> None: ...
    ClientID: str
    SourceBranchObject: typing.Any
    VersionObjects: typing.Sequence[typing.Any]

class GetPromoteBranchCandidatesOutput:
    """Stub for Bhv0.Services.Strong.Branchfoundation._2017_11.BranchFoundation.GetPromoteBranchCandidatesOutput"""
    def __init__(self) -> None: ...
    ClientID: str
    ParentBranches: typing.Sequence[typing.Any]

class GetPromoteBranchCandidatesResponse:
    """Stub for Bhv0.Services.Strong.Branchfoundation._2017_11.BranchFoundation.GetPromoteBranchCandidatesResponse"""
    def __init__(self) -> None: ...
    Results: typing.Sequence[typing.Any]
    ServiceData: typing.Any

__all__ = [
    'BranchFoundation',
    'GetPromoteBranchCandidatesInfo',
    'GetPromoteBranchCandidatesOutput',
    'GetPromoteBranchCandidatesResponse',
]
