# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class Changes:
    """Stub for Cm1.Services.Strong.Cmaws._2020_05.Changes.Changes"""
    def __init__(self) -> None: ...
    def GenerateStructureEdit(self, GenerateStructureEditInput: typing.Any, ProcessingMode: int) -> typing.Any: ...

class GenerateStructureEditInput:
    """Stub for Cm1.Services.Strong.Cmaws._2020_05.Changes.GenerateStructureEditInput"""
    def __init__(self) -> None: ...
    InputData: typing.Sequence[typing.Any]
    ChangeItemRevision: typing.Any
    IsGenerateStructureEdit: bool

class GenerateStructureEditInputData:
    """Stub for Cm1.Services.Strong.Cmaws._2020_05.Changes.GenerateStructureEditInputData"""
    def __init__(self) -> None: ...
    SolutionObject: typing.Any
    ImpactedObject: typing.Any

class GenerateStructureEditResponse:
    """Stub for Cm1.Services.Strong.Cmaws._2020_05.Changes.GenerateStructureEditResponse"""
    def __init__(self) -> None: ...
    BomEdits: typing.Sequence[typing.Any]
    Supercedures: typing.Sequence[typing.Any]
    ServiceData: typing.Any

__all__ = [
    'Changes',
    'GenerateStructureEditInput',
    'GenerateStructureEditInputData',
    'GenerateStructureEditResponse',
]
