# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class Finder:
    """Stub for Awp0.Services.Internal.Strong.Aws2._2017_12.Finder.Finder"""
    def __init__(self) -> None: ...

class SearchFilter4:
    """Stub for Awp0.Services.Internal.Strong.Aws2._2017_12.Finder.SearchFilter4"""
    def __init__(self) -> None: ...
    SearchFilterType: str
    StringValue: str
    StringDisplayValue: str
    StartDateValue: typing.Any
    EndDateValue: typing.Any
    StartNumericValue: float
    EndNumericValue: float
    Count: int
    Selected: bool
    StartEndRange: str
    ColorValue: str

__all__ = [
    'Finder',
    'SearchFilter4',
]
