# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class Cae1SimToolConfigResponse5:
    """Stub for Cae1.Services.Internal.Strong.Caeaw._2023_06.SimulationManagementAw.Cae1SimToolConfigResponse5"""
    def __init__(self) -> None: ...
    ServiceData: typing.Any
    ShowLaunchSimToolDialog: bool
    FmsTicket: str
    ToolConfig: typing.Any
    ShowLaunchFileInfo: bool
    LaunchFileInfo: typing.Any
    ShowStagingDirExportInfo: bool
    ExportFileInfo: typing.Any

class Cae1SimToolConfiguration5:
    """Stub for Cae1.Services.Internal.Strong.Caeaw._2023_06.SimulationManagementAw.Cae1SimToolConfiguration5"""
    def __init__(self) -> None: ...
    DisplayProgressMonitor: bool
    UseStagingDirectory: bool
    DefaultScratchDirectory: str
    StagingDirectory: str
    FolderNamingConvention: str
    LaunchMethods: typing.Sequence[str]
    InputParamList: typing.Sequence[typing.Any]
    OptionalInputExists: bool
    OptionalInputConfigList: typing.Sequence[typing.Any]
    FileUploadConflictOptionExists: bool
    FileUploadConflictOption: typing.Any
    HpcConnectionInfo: typing.Any

class Cae1SimToolExportFileInfo2:
    """Stub for Cae1.Services.Internal.Strong.Caeaw._2023_06.SimulationManagementAw.Cae1SimToolExportFileInfo2"""
    def __init__(self) -> None: ...
    ExportOption: str
    FileName: str
    FileDSName: str
    FileIRObjStr: str
    SelectedIRObjStr: str
    FileSize: str
    File: typing.Any
    FileDS: typing.Any
    FileIR: typing.Any

class Cae1SimToolInputParams3:
    """Stub for Cae1.Services.Internal.Strong.Caeaw._2023_06.SimulationManagementAw.Cae1SimToolInputParams3"""
    def __init__(self) -> None: ...
    Type: str
    PropertyDisplayName: str
    DbValue: str
    PropertyDescription: str
    InputType: str
    PropertyLabelDisplay: str
    IsEditable: bool
    IsEnabled: bool
    HasLov: bool
    LovValues: typing.Sequence[str]

class Cae1SimToolLaunchDialogInfo5:
    """Stub for Cae1.Services.Internal.Strong.Caeaw._2023_06.SimulationManagementAw.Cae1SimToolLaunchDialogInfo5"""
    def __init__(self) -> None: ...
    LaunchWithoutConfigInput: bool
    OpenLaunchDirectory: bool
    DisplayProgressMonitor: bool
    LaunchType: str
    DefaultScratchDirectory: str
    StagingDirectory: str
    FolderNamingConvention: str
    SimToolInputParamList: typing.Sequence[typing.Any]
    SimToolOptionalInputList: typing.Sequence[typing.Any]
    FileUploadConflictOptionExists: bool
    FileUploadConflictOption: typing.Any
    SelectedHPCConnObjName: str

class Cae1SimToolLaunchFileInfo4:
    """Stub for Cae1.Services.Internal.Strong.Caeaw._2023_06.SimulationManagementAw.Cae1SimToolLaunchFileInfo4"""
    def __init__(self) -> None: ...
    IsSelected: bool
    FileName: str
    FileDSName: str
    FileWLName: str
    FileIRObjStr: str
    SelectedIRObjStr: str
    FileSize: str
    File: typing.Any
    FileDS: typing.Any
    FileWL: typing.Any
    FileIR: typing.Any

class Cae1SimToolLaunchHPCInfo:
    """Stub for Cae1.Services.Internal.Strong.Caeaw._2023_06.SimulationManagementAw.Cae1SimToolLaunchHPCInfo"""
    def __init__(self) -> None: ...
    SelectedHPCConnObjName: str
    ConfiguredHPCConnObjNames: typing.Sequence[str]

class Cae1SimToolOptionalInputConfig2:
    """Stub for Cae1.Services.Internal.Strong.Caeaw._2023_06.SimulationManagementAw.Cae1SimToolOptionalInputConfig2"""
    def __init__(self) -> None: ...
    InputDesc: str
    InputRevisionType: str
    InputValueObject: typing.Any
    ExportDirectoryName: str
    InputVisible: bool
    OptionalInputObject: typing.Any

class OutputFileUploadConflictOption2:
    """Stub for Cae1.Services.Internal.Strong.Caeaw._2023_06.SimulationManagementAw.OutputFileUploadConflictOption2"""
    def __init__(self) -> None: ...
    IsPromptUser: bool
    OptionName: str

class SimulationManagementAw:
    """Stub for Cae1.Services.Internal.Strong.Caeaw._2023_06.SimulationManagementAw.SimulationManagementAw"""
    def __init__(self) -> None: ...
    def ProcessSimulationToolLaunchWithHPC(self, SelectedObjects: typing.Sequence[typing.Any], ProductContextInfo: typing.Any, SimTool: typing.Any, IsLaunchDialogInfoPresent: bool, LaunchDialogInfo: typing.Any, IsLaunchFileInfoPresent: bool, SelectedFileInfo: typing.Any, IsExportFileInfoPresent: bool, ExportFileInfo: typing.Any, UserSessionInfo: typing.Any, IsDSMEnabled: bool, IsClientOnWindows: bool) -> typing.Any: ...
    def UpdateCAEStructureAndGenerateReport(self, ModelBOMInput: typing.Any, ProductBOMInput: typing.Any, UpdateCriteriaAction: typing.Any, Domain: str, IsStructureMap: bool, StructureMapIR: typing.Any, IsAsyncMode: bool) -> typing.Any: ...

class UserSessionInfo2:
    """Stub for Cae1.Services.Internal.Strong.Caeaw._2023_06.SimulationManagementAw.UserSessionInfo2"""
    def __init__(self) -> None: ...
    SecurityToken: str
    TcSSOEnabled: bool
    TcSSOURL: str
    TcSSOAppId: str
    HostPath: str

__all__ = [
    'Cae1SimToolConfigResponse5',
    'Cae1SimToolConfiguration5',
    'Cae1SimToolExportFileInfo2',
    'Cae1SimToolInputParams3',
    'Cae1SimToolLaunchDialogInfo5',
    'Cae1SimToolLaunchFileInfo4',
    'Cae1SimToolLaunchHPCInfo',
    'Cae1SimToolOptionalInputConfig2',
    'OutputFileUploadConflictOption2',
    'SimulationManagementAw',
    'UserSessionInfo2',
]
