# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class ActivityManagement:
    """Stub for Tm0.Services.Internal.Strong.Testmanagement._2014_12.ActivityManagement.ActivityManagement"""
    def __init__(self) -> None: ...
    def GetTestResults(self, Inputs: typing.Sequence[typing.Any]) -> typing.Any: ...

class TestResultsInputInfo:
    """Stub for Tm0.Services.Internal.Strong.Testmanagement._2014_12.ActivityManagement.TestResultsInputInfo"""
    def __init__(self) -> None: ...
    ClientId: str
    TestActivity: typing.Any
    TestInstance: typing.Any

class TestResultsOutput:
    """Stub for Tm0.Services.Internal.Strong.Testmanagement._2014_12.ActivityManagement.TestResultsOutput"""
    def __init__(self) -> None: ...
    ClientId: str
    TestResults: typing.Sequence[typing.Any]

class TestResultsResponse:
    """Stub for Tm0.Services.Internal.Strong.Testmanagement._2014_12.ActivityManagement.TestResultsResponse"""
    def __init__(self) -> None: ...
    TestResultsOutput: typing.Sequence[typing.Any]
    SrvcData: typing.Any

__all__ = [
    'ActivityManagement',
    'TestResultsInputInfo',
    'TestResultsOutput',
    'TestResultsResponse',
]
