# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class AbsOccAttachment2:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.StructureManagement.AbsOccAttachment2"""
    def __init__(self) -> None: ...
    OverrideObject: typing.Any
    RelationTypeName: str

class AbsOccCreateDatasetAttachmentInfo:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.StructureManagement.AbsOccCreateDatasetAttachmentInfo"""
    def __init__(self) -> None: ...
    ClientId: str
    DatasetInfo: typing.Any
    RelationTypeName: str
    CreateIfFound: bool

class AbsOccCreateFormAttachmentInfo:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.StructureManagement.AbsOccCreateFormAttachmentInfo"""
    def __init__(self) -> None: ...
    ClientId: str
    FormInfo: typing.Any
    RelationTypeName: str
    CreateIfFound: bool

class AbsOccDataGRMExpansionInfo:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.StructureManagement.AbsOccDataGRMExpansionInfo"""
    def __init__(self) -> None: ...
    RelationName: str
    Objects: typing.Sequence[typing.Any]

class AbsOccDataInfo2:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.StructureManagement.AbsOccDataInfo2"""
    def __init__(self) -> None: ...
    OverridesToSet: typing.Sequence[typing.Any]
    OverridesToRemove: typing.Sequence[str]
    AsRequired: bool
    OccTransform: typing.Sequence[float]
    OccNotes: typing.Sequence[typing.Any]
    Attachments: typing.Sequence[typing.Any]
    AttachmentsToUnattach: typing.Sequence[typing.Any]
    DatasetAttachments: typing.Sequence[typing.Any]
    FormAttachments: typing.Sequence[typing.Any]
    ClientIdOfUsedArrangement: str
    UsedArr: typing.Any
    BoundingBoxInfo: typing.Sequence[typing.Any]

class AbsOccDataPref:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.StructureManagement.AbsOccDataPref"""
    def __init__(self) -> None: ...
    RelationFilterInfos: typing.Sequence[typing.Any]
    QualifierFilter: str

class AbsOccInfo2:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.StructureManagement.AbsOccInfo2"""
    def __init__(self) -> None: ...
    ClientId: str
    AbsOcc: typing.Any
    CadOccIdPath: typing.Sequence[str]
    AbsOccData: typing.Any

class AbsOccQualifierInfo:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.StructureManagement.AbsOccQualifierInfo"""
    def __init__(self) -> None: ...
    QualifyingBVR: typing.Any
    UpperQualifier: typing.Any

class AbsOccStructureDataInfo:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.StructureManagement.AbsOccStructureDataInfo"""
    def __init__(self) -> None: ...
    OccThreadPaths: typing.Sequence[typing.Any]
    DataOverrideInfo: typing.Any

class ApnToThreadPathStruct:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.StructureManagement.ApnToThreadPathStruct"""
    def __init__(self) -> None: ...
    Apn: typing.Any
    OccThreadPath: typing.Sequence[typing.Any]

class BoundingBox:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.StructureManagement.BoundingBox"""
    def __init__(self) -> None: ...
    Xmin: float
    Ymin: float
    Zmin: float
    Xmax: float
    Ymax: float
    Zmax: float

class BoundingBoxInfo:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.StructureManagement.BoundingBoxInfo"""
    def __init__(self) -> None: ...
    Dataset: typing.Any
    BoundingBoxVector: typing.Sequence[typing.Any]

class CommitDatasetFileInfo:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.StructureManagement.CommitDatasetFileInfo"""
    def __init__(self) -> None: ...
    Dataset: typing.Any
    CreateNewVersion: bool
    DatasetFileTicketInfos: typing.Sequence[typing.Any]

class CreateOrUpdateAbsoluteStructureInfo3:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.StructureManagement.CreateOrUpdateAbsoluteStructureInfo3"""
    def __init__(self) -> None: ...
    LastModifiedOfBVR: typing.Any
    ContextItemRev: typing.Any
    BvrAbsOccInfo: typing.Sequence[typing.Any]
    ArrAbsOccInfo: typing.Sequence[typing.Any]

class CreateOrUpdateAbsoluteStructurePref3:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.StructureManagement.CreateOrUpdateAbsoluteStructurePref3"""
    def __init__(self) -> None: ...
    OverwriteForLastModDate: bool
    OverridesToSynchronize: typing.Sequence[str]
    RelationFilters: typing.Sequence[typing.Any]
    CadOccIdAttrName: str

class CreateOrUpdateAbsoluteStructureResponse2:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.StructureManagement.CreateOrUpdateAbsoluteStructureResponse2"""
    def __init__(self) -> None: ...
    AbsOccOutput: typing.Any
    AsmArrangementOutput: typing.Any
    FormOutput: typing.Any
    DatasetOutput: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class CreateOrUpdateRelativeStructureInfo3:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.StructureManagement.CreateOrUpdateRelativeStructureInfo3"""
    def __init__(self) -> None: ...
    LastModifiedOfBVR: typing.Any
    Parent: typing.Any
    ChildInfo: typing.Sequence[typing.Any]
    Precise: bool

class CreateOrUpdateRelativeStructurePref3:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.StructureManagement.CreateOrUpdateRelativeStructurePref3"""
    def __init__(self) -> None: ...
    OverwriteForLastModDate: bool
    ContinueOnError: bool
    CadOccIdAttrName: str
    ObjectTypes: typing.Sequence[str]

class CreateVariantRulesInfo:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.StructureManagement.CreateVariantRulesInfo"""
    def __init__(self) -> None: ...
    ClientID: str
    VruleName: str
    VruleDescription: str
    Rev: typing.Any
    Parent: typing.Any
    Relation: str
    Options: typing.Sequence[typing.Any]

class CreateVariantRulesResponse:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.StructureManagement.CreateVariantRulesResponse"""
    def __init__(self) -> None: ...
    ServiceData: typing.Any
    Output: typing.Sequence[typing.Any]

class DataOverrideInfo:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.StructureManagement.DataOverrideInfo"""
    def __init__(self) -> None: ...
    OverrideData: typing.Any
    ExpandedOverrides: typing.Sequence[typing.Any]

class DatasetFileInfo:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.StructureManagement.DatasetFileInfo"""
    def __init__(self) -> None: ...
    ClientId: str
    FileName: str
    NamedReferencedName: str
    IsText: bool
    AllowReplace: bool
    BoundingBoxesAvailable: bool
    BoundingBoxes: typing.Sequence[typing.Any]

class DatasetFileTicketInfo:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.StructureManagement.DatasetFileTicketInfo"""
    def __init__(self) -> None: ...
    DatasetFileInfo: typing.Any
    Ticket: str

class DatasetInfo:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.StructureManagement.DatasetInfo"""
    def __init__(self) -> None: ...
    ClientId: str
    Dataset: typing.Any
    Name: str
    BasisName: str
    Description: str
    Type: str
    LastModifiedOfDataset: typing.Any
    Id: str
    DatasetRev: str
    CreateNewVersion: bool
    NamedReferencePreference: str
    DataList: typing.Sequence[typing.Any]
    DatasetFileInfos: typing.Sequence[typing.Any]
    NamedReferenceObjectInfos: typing.Sequence[typing.Any]

class DatasetOutput:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.StructureManagement.DatasetOutput"""
    def __init__(self) -> None: ...
    ClientId: str
    Dataset: typing.Any
    CommitInfo: typing.Sequence[typing.Any]

class DeleteRelativeStructureInfo3:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.StructureManagement.DeleteRelativeStructureInfo3"""
    def __init__(self) -> None: ...
    LastModifiedOfBVR: typing.Any
    Parent: typing.Any
    ChildInfo: typing.Sequence[str]

class ExpandPSAllLevelsInfo:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.StructureManagement.ExpandPSAllLevelsInfo"""
    def __init__(self) -> None: ...
    ParentBomLines: typing.Sequence[typing.Any]
    ExcludeFilter: str

class ExpandPSAllLevelsOutput:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.StructureManagement.ExpandPSAllLevelsOutput"""
    def __init__(self) -> None: ...
    Parent: typing.Any
    Children: typing.Sequence[typing.Any]

class ExpandPSAllLevelsPref:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.StructureManagement.ExpandPSAllLevelsPref"""
    def __init__(self) -> None: ...
    ExpItemRev: bool
    Info: typing.Sequence[typing.Any]
    IncludeOccurrenceTypes: typing.Sequence[str]
    ExcludeOccurrenceTypes: typing.Sequence[str]

class ExpandPSAllLevelsResponse2:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.StructureManagement.ExpandPSAllLevelsResponse2"""
    def __init__(self) -> None: ...
    Output: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class ExpandPSData:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.StructureManagement.ExpandPSData"""
    def __init__(self) -> None: ...
    BomLine: typing.Any
    ObjectOfBOMLine: typing.Any
    RelatedObjects: typing.Sequence[typing.Any]

class ExpandPSNamedReferenceInfo:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.StructureManagement.ExpandPSNamedReferenceInfo"""
    def __init__(self) -> None: ...
    NamedReferenceType: str
    NamedReferenceName: str
    ReferenceObject: typing.Any
    FileTicket: str

class ExpandPSOneLevelInfo:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.StructureManagement.ExpandPSOneLevelInfo"""
    def __init__(self) -> None: ...
    ParentBomLines: typing.Sequence[typing.Any]
    ExcludeFilter: str

class ExpandPSOneLevelOutput:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.StructureManagement.ExpandPSOneLevelOutput"""
    def __init__(self) -> None: ...
    Parent: typing.Any
    Children: typing.Sequence[typing.Any]

class ExpandPSOneLevelPref:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.StructureManagement.ExpandPSOneLevelPref"""
    def __init__(self) -> None: ...
    ExpItemRev: bool
    Info: typing.Sequence[typing.Any]
    IncludeOccurrenceTypes: typing.Sequence[str]
    ExcludeOccurrenceTypes: typing.Sequence[str]

class ExpandPSOneLevelResponse2:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.StructureManagement.ExpandPSOneLevelResponse2"""
    def __init__(self) -> None: ...
    Output: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class ExpandPSParentData:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.StructureManagement.ExpandPSParentData"""
    def __init__(self) -> None: ...
    BomLine: typing.Any
    ObjectOfBOMLine: typing.Any
    ParentRelatedObjects: typing.Sequence[typing.Any]

class ExpandPSRelatedObjectInfo:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.StructureManagement.ExpandPSRelatedObjectInfo"""
    def __init__(self) -> None: ...
    RelatedObject: typing.Any
    NamedRefList: typing.Sequence[typing.Any]

class FormInfo:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.StructureManagement.FormInfo"""
    def __init__(self) -> None: ...
    FormObject: typing.Any
    Name: str
    Description: str
    FormType: str
    Attributes: typing.Sequence[typing.Any]

class GetAbsoluteStructureDataResponse:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.StructureManagement.GetAbsoluteStructureDataResponse"""
    def __init__(self) -> None: ...
    Overrides: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class NameValueStruct:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.StructureManagement.NameValueStruct"""
    def __init__(self) -> None: ...
    Name: str
    Values: typing.Sequence[str]

class NamedReferenceObjectInfo:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.StructureManagement.NamedReferenceObjectInfo"""
    def __init__(self) -> None: ...
    ClientId: str
    Object: typing.Any
    NamedReferenceName: str
    TypeName: str
    DataNameValuePairs: typing.Sequence[typing.Any]

class OptionsInfo:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.StructureManagement.OptionsInfo"""
    def __init__(self) -> None: ...
    OptionName: str
    OptionValue: str
    AssocRev: typing.Any

class ReconfigureBOMWindowsInfo:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.StructureManagement.ReconfigureBOMWindowsInfo"""
    def __init__(self) -> None: ...
    ClientID: str
    BomWindow: typing.Any
    ObjectForConfigure: typing.Any
    RevRuleConfigInfo: typing.Any

class ReconfigureBOMWindowsOutput:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.StructureManagement.ReconfigureBOMWindowsOutput"""
    def __init__(self) -> None: ...
    ClientID: str
    BomWindow: typing.Any

class ReconfigureBOMWindowsResponse:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.StructureManagement.ReconfigureBOMWindowsResponse"""
    def __init__(self) -> None: ...
    Output: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class RelatedObjectTypeAndNamedRefs:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.StructureManagement.RelatedObjectTypeAndNamedRefs"""
    def __init__(self) -> None: ...
    ObjectTypeName: str
    NamedReferenceNames: typing.Sequence[str]

class RelationAndTypesFilter:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.StructureManagement.RelationAndTypesFilter"""
    def __init__(self) -> None: ...
    RelationName: str
    RelatedObjAndNamedRefs: typing.Sequence[typing.Any]
    NamedRefHandler: str

class RelativeStructureChildInfo2:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.StructureManagement.RelativeStructureChildInfo2"""
    def __init__(self) -> None: ...
    ClientId: str
    CadOccId: str
    Child: typing.Any
    OccInfo: typing.Any

class SaveBOMWindowsResponse:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.StructureManagement.SaveBOMWindowsResponse"""
    def __init__(self) -> None: ...
    ServiceData: typing.Any

class StructureManagement:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.StructureManagement.StructureManagement"""
    def __init__(self) -> None: ...
    def CreateOrUpdateAbsoluteStructure(self, AbsOccInfos: typing.Sequence[typing.Any], BomViewTypeName: str, Complete: bool, Pref: typing.Any) -> typing.Any: ...
    def CreateOrUpdateRelativeStructure(self, Inputs: typing.Sequence[typing.Any], BomViewTypeName: str, Complete: bool, Pref: typing.Any) -> typing.Any: ...
    def CreateVariantRules(self, Input: typing.Sequence[typing.Any]) -> typing.Any: ...
    def DeleteRelativeStructure(self, Inputs: typing.Sequence[typing.Any], BomViewTypeName: str, Pref: typing.Any) -> typing.Any: ...
    def ExpandPSAllLevels(self, Info: typing.Any, Pref: typing.Any) -> typing.Any: ...
    def ExpandPSOneLevel(self, Info: typing.Any, Pref: typing.Any) -> typing.Any: ...
    def GetAbsoluteStructureData(self, AbsOccDataQualInfos: typing.Sequence[typing.Any], AbsOccDataPref: typing.Any) -> typing.Any: ...
    def ReconfigureBOMWindows(self, Info: typing.Sequence[typing.Any]) -> typing.Any: ...
    def SaveBOMWindows(self, BomWindows: typing.Sequence[typing.Any]) -> typing.Any: ...

class VariantRulesOutput:
    """Stub for Teamcenter.Services.Strong.Cad._2008_06.StructureManagement.VariantRulesOutput"""
    def __init__(self) -> None: ...
    ClientId: str
    Vrule: typing.Any

__all__ = [
    'AbsOccAttachment2',
    'AbsOccCreateDatasetAttachmentInfo',
    'AbsOccCreateFormAttachmentInfo',
    'AbsOccDataGRMExpansionInfo',
    'AbsOccDataInfo2',
    'AbsOccDataPref',
    'AbsOccInfo2',
    'AbsOccQualifierInfo',
    'AbsOccStructureDataInfo',
    'ApnToThreadPathStruct',
    'BoundingBox',
    'BoundingBoxInfo',
    'CommitDatasetFileInfo',
    'CreateOrUpdateAbsoluteStructureInfo3',
    'CreateOrUpdateAbsoluteStructurePref3',
    'CreateOrUpdateAbsoluteStructureResponse2',
    'CreateOrUpdateRelativeStructureInfo3',
    'CreateOrUpdateRelativeStructurePref3',
    'CreateVariantRulesInfo',
    'CreateVariantRulesResponse',
    'DataOverrideInfo',
    'DatasetFileInfo',
    'DatasetFileTicketInfo',
    'DatasetInfo',
    'DatasetOutput',
    'DeleteRelativeStructureInfo3',
    'ExpandPSAllLevelsInfo',
    'ExpandPSAllLevelsOutput',
    'ExpandPSAllLevelsPref',
    'ExpandPSAllLevelsResponse2',
    'ExpandPSData',
    'ExpandPSNamedReferenceInfo',
    'ExpandPSOneLevelInfo',
    'ExpandPSOneLevelOutput',
    'ExpandPSOneLevelPref',
    'ExpandPSOneLevelResponse2',
    'ExpandPSParentData',
    'ExpandPSRelatedObjectInfo',
    'FormInfo',
    'GetAbsoluteStructureDataResponse',
    'NameValueStruct',
    'NamedReferenceObjectInfo',
    'OptionsInfo',
    'ReconfigureBOMWindowsInfo',
    'ReconfigureBOMWindowsOutput',
    'ReconfigureBOMWindowsResponse',
    'RelatedObjectTypeAndNamedRefs',
    'RelationAndTypesFilter',
    'RelativeStructureChildInfo2',
    'SaveBOMWindowsResponse',
    'StructureManagement',
    'VariantRulesOutput',
]
