# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class Expression2:
    """Stub for Ods0.Services.Internal.Strong.Objectdataservices._2020_12.ObjectDataServices.Expression2"""
    def __init__(self) -> None: ...
    Operands: typing.Sequence[typing.Any]
    ExpressionOperator: str

class FilteredObject2:
    """Stub for Ods0.Services.Internal.Strong.Objectdataservices._2020_12.ObjectDataServices.FilteredObject2"""
    def __init__(self) -> None: ...
    FilteredObj: typing.Any
    ExpandedObject: typing.Any

class ListOfObjects2:
    """Stub for Ods0.Services.Internal.Strong.Objectdataservices._2020_12.ObjectDataServices.ListOfObjects2"""
    def __init__(self) -> None: ...
    Objects: typing.Sequence[typing.Any]
    OffsetInfo: typing.Any
    Count: int

class ObjectDataServices:
    """Stub for Ods0.Services.Internal.Strong.Objectdataservices._2020_12.ObjectDataServices.ObjectDataServices"""
    def __init__(self) -> None: ...
    def FindObjects2(self, Input: typing.Sequence[typing.Any]) -> typing.Any: ...

class Operand2:
    """Stub for Ods0.Services.Internal.Strong.Objectdataservices._2020_12.ObjectDataServices.Operand2"""
    def __init__(self) -> None: ...
    OperandType: str
    OperandValue: str
    Attributes: typing.Sequence[str]
    Expressions: typing.Sequence[typing.Any]
    StartIndex: int
    MaxToReturn: int
    OffsetInfo: typing.Any
    ExpandCriteria: typing.Any
    AttributeSortCriteria: typing.Sequence[typing.Any]
    ReferencedObjectAttributeSortCriteria: typing.Sequence[typing.Any]

class OperandAndOperator:
    """Stub for Ods0.Services.Internal.Strong.Objectdataservices._2020_12.ObjectDataServices.OperandAndOperator"""
    def __init__(self) -> None: ...
    UnaryOperator: str
    Operand: typing.Any

class ResultOffsetInfo:
    """Stub for Ods0.Services.Internal.Strong.Objectdataservices._2020_12.ObjectDataServices.ResultOffsetInfo"""
    def __init__(self) -> None: ...
    LastProcessedIndex: int
    LastProcessedObjId: str

class ReturnObjects2:
    """Stub for Ods0.Services.Internal.Strong.Objectdataservices._2020_12.ObjectDataServices.ReturnObjects2"""
    def __init__(self) -> None: ...
    Objects: typing.Sequence[typing.Any]
    ServiceData: typing.Any

__all__ = [
    'Expression2',
    'FilteredObject2',
    'ListOfObjects2',
    'ObjectDataServices',
    'Operand2',
    'OperandAndOperator',
    'ResultOffsetInfo',
    'ReturnObjects2',
]
