# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class DataManagement:
    """Stub for Teamcenter.Services.Strong.Core._2015_10.DataManagement.DataManagement"""
    def __init__(self) -> None: ...
    def ReassignParticipants(self, ReassignParticipantInfo: typing.Sequence[typing.Any]) -> typing.Any: ...

class ReassignParticipantInfo:
    """Stub for Teamcenter.Services.Strong.Core._2015_10.DataManagement.ReassignParticipantInfo"""
    def __init__(self) -> None: ...
    ItemRevs: typing.Sequence[typing.Any]
    FromAssignee: typing.Any
    ToAssignee: typing.Any
    ParticipantTypes: typing.Sequence[str]
    AllParticipantTypes: bool
    Comments: str
    ClientId: str

class ReassignParticipantOutput:
    """Stub for Teamcenter.Services.Strong.Core._2015_10.DataManagement.ReassignParticipantOutput"""
    def __init__(self) -> None: ...
    ClientId: str
    FailedItemRevs: typing.Sequence[typing.Any]

class ReassignParticipantResponse:
    """Stub for Teamcenter.Services.Strong.Core._2015_10.DataManagement.ReassignParticipantResponse"""
    def __init__(self) -> None: ...
    FailedObjects: typing.Sequence[typing.Any]
    ServiceData: typing.Any

__all__ = [
    'DataManagement',
    'ReassignParticipantInfo',
    'ReassignParticipantOutput',
    'ReassignParticipantResponse',
]
