# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class RegisterIndex:
    """Stub for Teamcenter.Services.Loose.Core._2012_02.Session.RegisterIndex"""
    def __init__(self) -> None: ...
    RegistryIndex: int

class Session:
    """Stub for Teamcenter.Services.Loose.Core._2012_02.Session.Session"""
    def __init__(self) -> None: ...
    def RegisterState(self, Level: str) -> typing.Any: ...
    def SetObjectPropertyPolicy(self, PolicyName: str, UseRefCounting: bool) -> typing.Any: ...
    def UnregisterState(self, Index: int) -> bool: ...

class SetPolicyResponse:
    """Stub for Teamcenter.Services.Loose.Core._2012_02.Session.SetPolicyResponse"""
    def __init__(self) -> None: ...
    PolicyId: str
    Policy: typing.Any

__all__ = [
    'RegisterIndex',
    'Session',
    'SetPolicyResponse',
]
