# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class LowlevelOwnershipTransfer:
    """Stub for Teamcenter.Services.Internal.Strong.Globalmultisite._2010_02.LowlevelOwnershipTransfer.LowlevelOwnershipTransfer"""
    def __init__(self) -> None: ...
    def GetObjectsForOwnershipTransfer(self, TcGSMessageId: str, ChangeOwnershipToSite: int, Dryrun: bool) -> typing.Any: ...
    def TransferOwnership(self, TcGSMessageId: str, Dryrun: bool, IsSrcSiteExtinct: bool, FmsTicketOfObjs: str) -> typing.Any: ...
    def UpdateOwnershipTransfer(self, TcGSMessageId: str, ChangeOwnershipToSite: int, Dryrun: bool, IsSrcSiteExtinct: bool, FmsTicketOfObjs: str) -> typing.Any: ...

class ObjectsForOwnershipTransferResponse:
    """Stub for Teamcenter.Services.Internal.Strong.Globalmultisite._2010_02.LowlevelOwnershipTransfer.ObjectsForOwnershipTransferResponse"""
    def __init__(self) -> None: ...
    FileFmsTickets: str
    ServiceData: typing.Any

class TransferOwnershipResponse:
    """Stub for Teamcenter.Services.Internal.Strong.Globalmultisite._2010_02.LowlevelOwnershipTransfer.TransferOwnershipResponse"""
    def __init__(self) -> None: ...
    FileFmsTickets: str
    ServiceData: typing.Any

class UpdateOwnershipTransferResponse:
    """Stub for Teamcenter.Services.Internal.Strong.Globalmultisite._2010_02.LowlevelOwnershipTransfer.UpdateOwnershipTransferResponse"""
    def __init__(self) -> None: ...
    FileFmsTickets: str
    ServiceData: typing.Any

__all__ = [
    'LowlevelOwnershipTransfer',
    'ObjectsForOwnershipTransferResponse',
    'TransferOwnershipResponse',
    'UpdateOwnershipTransferResponse',
]
