# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class FileImportExport:
    """Stub for Teamcenter.Services.Internal.Strong.Importexport._2017_11.FileImportExport.FileImportExport"""
    def __init__(self) -> None: ...
    def ImportDocumentOffline(self, Inputs: typing.Sequence[typing.Any]) -> typing.Any: ...

class ImportDocumentInputData:
    """Stub for Teamcenter.Services.Internal.Strong.Importexport._2017_11.FileImportExport.ImportDocumentInputData"""
    def __init__(self) -> None: ...
    ClientId: str
    TransientFileWriteTicket: str
    ChildSpecElementType: str
    SpecificationType: str
    SelectedObject: typing.Any
    KeywordImportOptions: typing.Any
    SpecDesc: str

class KeywordImporCondition:
    """Stub for Teamcenter.Services.Internal.Strong.Importexport._2017_11.FileImportExport.KeywordImporCondition"""
    def __init__(self) -> None: ...
    OpType: str
    Keyword: str

class KeywordImportOptions:
    """Stub for Teamcenter.Services.Internal.Strong.Importexport._2017_11.FileImportExport.KeywordImportOptions"""
    def __init__(self) -> None: ...
    ImportOptions: typing.Sequence[typing.Any]
    KeywordImportRules: typing.Sequence[typing.Any]

class KeywordImportRule:
    """Stub for Teamcenter.Services.Internal.Strong.Importexport._2017_11.FileImportExport.KeywordImportRule"""
    def __init__(self) -> None: ...
    TargetChildType: str
    ConditionProcessingType: str
    KeywordImportConditions: typing.Sequence[typing.Any]

__all__ = [
    'FileImportExport',
    'ImportDocumentInputData',
    'KeywordImporCondition',
    'KeywordImportOptions',
    'KeywordImportRule',
]
