# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class DataManagement:
    """Stub for Cpd0.Services.Internal.Strong.Cpdcore._2017_05.DataManagement.DataManagement"""
    def __init__(self) -> None: ...
    def ProductContextSearch(self, ProductContextSearchInfos: typing.Sequence[typing.Any]) -> typing.Any: ...

class ProductContextResponse:
    """Stub for Cpd0.Services.Internal.Strong.Cpdcore._2017_05.DataManagement.ProductContextResponse"""
    def __init__(self) -> None: ...
    ClientIdMap: typing.Any
    ServiceData: typing.Any

class ProductContextSearchInfo:
    """Stub for Cpd0.Services.Internal.Strong.Cpdcore._2017_05.DataManagement.ProductContextSearchInfo"""
    def __init__(self) -> None: ...
    ClientId: str
    SearchObjects: typing.Sequence[typing.Any]

class ProductContextSearhData:
    """Stub for Cpd0.Services.Internal.Strong.Cpdcore._2017_05.DataManagement.ProductContextSearhData"""
    def __init__(self) -> None: ...
    ConfigurationContext: typing.Any
    Contents: typing.Sequence[typing.Any]

__all__ = [
    'DataManagement',
    'ProductContextResponse',
    'ProductContextSearchInfo',
    'ProductContextSearhData',
]
