# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class LicAdminInput:
    """Stub for Teamcenter.Services.Loose.Core._2019_06.Session.LicAdminInput"""
    def __init__(self) -> None: ...
    FeatureKey: str
    LicensingAction: str

class Session:
    """Stub for Teamcenter.Services.Loose.Core._2019_06.Session.Session"""
    def __init__(self) -> None: ...
    def LicenseAdmin(self, LicAdminInput: typing.Sequence[typing.Any]) -> typing.Any: ...

__all__ = [
    'LicAdminInput',
    'Session',
]
