# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class DataManagement:
    """Stub for Teamcenter.Services.Internal.Strong.Cad._2008_03.DataManagement.DataManagement"""
    def __init__(self) -> None: ...
    def ExportConfiguredNXAssembly(self, Inputs: typing.Sequence[typing.Any]) -> typing.Any: ...

class ExportConfiguredNXAssemblyInfo:
    """Stub for Teamcenter.Services.Internal.Strong.Cad._2008_03.DataManagement.ExportConfiguredNXAssemblyInfo"""
    def __init__(self) -> None: ...
    Bomline: typing.Any
    NamingFormat: str

class ExportConfiguredNXAssemblyOutput:
    """Stub for Teamcenter.Services.Internal.Strong.Cad._2008_03.DataManagement.ExportConfiguredNXAssemblyOutput"""
    def __init__(self) -> None: ...
    TransientZipFileReadTicket: str
    TransientLogFileReadTicket: str
    Bomline: typing.Any

class ExportConfiguredNXAssemblyResponse:
    """Stub for Teamcenter.Services.Internal.Strong.Cad._2008_03.DataManagement.ExportConfiguredNXAssemblyResponse"""
    def __init__(self) -> None: ...
    Output: typing.Sequence[typing.Any]
    ServiceData: typing.Any

__all__ = [
    'DataManagement',
    'ExportConfiguredNXAssemblyInfo',
    'ExportConfiguredNXAssemblyOutput',
    'ExportConfiguredNXAssemblyResponse',
]
