# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class ApplConfigExprWithDisplayString:
    """Stub for Cfg0.Services.Internal.Strong.Configurator._2015_10.ConfiguratorManagement.ApplConfigExprWithDisplayString"""
    def __init__(self) -> None: ...
    ApplConfigExpr: typing.Any
    ApplConfigExprDisplayString: str
    ConfigExprSetsInfo: typing.Sequence[typing.Any]

class ApplicationConfigExpression:
    """Stub for Cfg0.Services.Internal.Strong.Configurator._2015_10.ConfiguratorManagement.ApplicationConfigExpression"""
    def __init__(self) -> None: ...
    Formula: str
    ExprID: str
    ExpressionType: int
    ConfigExprSets: typing.Sequence[typing.Any]

class AvailableProductVariabilityInput:
    """Stub for Cfg0.Services.Internal.Strong.Configurator._2015_10.ConfiguratorManagement.AvailableProductVariabilityInput"""
    def __init__(self) -> None: ...
    CriteriaExpression: typing.Any
    FamiliesToTest: typing.Sequence[typing.Any]
    Context: typing.Any
    ApplyConstraints: int

class AvailableProductVariabilityOutput:
    """Stub for Cfg0.Services.Internal.Strong.Configurator._2015_10.ConfiguratorManagement.AvailableProductVariabilityOutput"""
    def __init__(self) -> None: ...
    AvailabilityExpressions: typing.Sequence[typing.Any]
    Violations: typing.Sequence[typing.Any]
    SuggestedSatisfyingExpr: typing.Any
    CriteriaStatus: str
    RequiredFamilies: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class AvailableVariability:
    """Stub for Cfg0.Services.Internal.Strong.Configurator._2015_10.ConfiguratorManagement.AvailableVariability"""
    def __init__(self) -> None: ...
    DefaultValues: typing.Sequence[typing.Any]
    Availability: typing.Sequence[typing.Any]

class BusinessObjectConfigExpression:
    """Stub for Cfg0.Services.Internal.Strong.Configurator._2015_10.ConfiguratorManagement.BusinessObjectConfigExpression"""
    def __init__(self) -> None: ...
    TargetObject: typing.Any
    Expressions: typing.Sequence[typing.Any]
    ClientId: str

class ConfigExprWithDisplayString:
    """Stub for Cfg0.Services.Internal.Strong.Configurator._2015_10.ConfiguratorManagement.ConfigExprWithDisplayString"""
    def __init__(self) -> None: ...
    ConfigExprDisplayString: str

class ConfigExpression:
    """Stub for Cfg0.Services.Internal.Strong.Configurator._2015_10.ConfiguratorManagement.ConfigExpression"""
    def __init__(self) -> None: ...
    ClientID: str
    ExpressionType: int
    Formula: str
    SubExpressions: typing.Sequence[typing.Any]

class ConfigExpressionGroup:
    """Stub for Cfg0.Services.Internal.Strong.Configurator._2015_10.ConfiguratorManagement.ConfigExpressionGroup"""
    def __init__(self) -> None: ...
    Context: typing.Any
    GroupName: str
    Terms: typing.Sequence[typing.Any]

class ConfigExpressionSet:
    """Stub for Cfg0.Services.Internal.Strong.Configurator._2015_10.ConfiguratorManagement.ConfigExpressionSet"""
    def __init__(self) -> None: ...
    ConfigExpressions: typing.Sequence[typing.Any]

class ConfigExpressionSetInfo:
    """Stub for Cfg0.Services.Internal.Strong.Configurator._2015_10.ConfiguratorManagement.ConfigExpressionSetInfo"""
    def __init__(self) -> None: ...
    ConfigExprsWithDisplayString: typing.Sequence[typing.Any]

class ConfigExpressionTerm:
    """Stub for Cfg0.Services.Internal.Strong.Configurator._2015_10.ConfiguratorManagement.ConfigExpressionTerm"""
    def __init__(self) -> None: ...
    Family: typing.Any
    FamilyID: str
    FamilyNamespace: str
    OperatorCode: int
    RangeExpressions: typing.Sequence[typing.Any]
    Value: typing.Any
    ValueText: str
    SelectionClass: str

class ConfigSubExpression:
    """Stub for Cfg0.Services.Internal.Strong.Configurator._2015_10.ConfiguratorManagement.ConfigSubExpression"""
    def __init__(self) -> None: ...
    ExpressionGroups: typing.Sequence[typing.Any]

class ConfiguratorManagement:
    """Stub for Cfg0.Services.Internal.Strong.Configurator._2015_10.ConfiguratorManagement.ConfiguratorManagement"""
    def __init__(self) -> None: ...
    def ConvertVariantExpressions(self, Inputs: typing.Sequence[typing.Any]) -> typing.Any: ...
    def GetAvailableProductVariability(self, Input: typing.Any) -> typing.Any: ...
    def GetProductDefaults(self, Inputs: typing.Sequence[typing.Any]) -> typing.Any: ...
    def GetRevRulesForConfiguratorContext(self) -> typing.Any: ...
    def GetVariantExpressions(self, TargetObjects: typing.Sequence[typing.Any], RevisionRule: typing.Any) -> typing.Any: ...
    def SetVariantExpressions(self, Inputs: typing.Sequence[typing.Any], RevisionRule: typing.Any) -> typing.Any: ...
    def ValidateProductConfiguration(self, Inputs: typing.Sequence[typing.Any]) -> typing.Any: ...

class ConvertVariantExpressionInput:
    """Stub for Cfg0.Services.Internal.Strong.Configurator._2015_10.ConfiguratorManagement.ConvertVariantExpressionInput"""
    def __init__(self) -> None: ...
    ClientId: str
    ExprsToConvert: typing.Sequence[typing.Any]
    Context: typing.Any
    ExpressionFormat: int

class ConvertVariantExpressionOutput:
    """Stub for Cfg0.Services.Internal.Strong.Configurator._2015_10.ConfiguratorManagement.ConvertVariantExpressionOutput"""
    def __init__(self) -> None: ...
    ClientId: str
    ApplConfigExprsWithDisplayString: typing.Sequence[typing.Any]

class ConvertVariantExpressionsResponse:
    """Stub for Cfg0.Services.Internal.Strong.Configurator._2015_10.ConfiguratorManagement.ConvertVariantExpressionsResponse"""
    def __init__(self) -> None: ...
    Outputs: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class GetProductDefaultsConfigOutput:
    """Stub for Cfg0.Services.Internal.Strong.Configurator._2015_10.ConfiguratorManagement.GetProductDefaultsConfigOutput"""
    def __init__(self) -> None: ...
    ExpressionWithDefaults: typing.Any
    CriteriaStatus: str
    RequiredFamilies: typing.Sequence[typing.Any]

class GetProductDefaultsResponse:
    """Stub for Cfg0.Services.Internal.Strong.Configurator._2015_10.ConfiguratorManagement.GetProductDefaultsResponse"""
    def __init__(self) -> None: ...
    Outputs: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class GetRevisionRulesResponse:
    """Stub for Cfg0.Services.Internal.Strong.Configurator._2015_10.ConfiguratorManagement.GetRevisionRulesResponse"""
    def __init__(self) -> None: ...
    ApplicableRevisionRules: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class GetVariantExpressionsResponse:
    """Stub for Cfg0.Services.Internal.Strong.Configurator._2015_10.ConfiguratorManagement.GetVariantExpressionsResponse"""
    def __init__(self) -> None: ...
    ConfigObjectExpressions: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class ProductDefaultsInput:
    """Stub for Cfg0.Services.Internal.Strong.Configurator._2015_10.ConfiguratorManagement.ProductDefaultsInput"""
    def __init__(self) -> None: ...
    ApplyDefaults: int
    ExpressionsToUpdate: typing.Sequence[typing.Any]
    Families: typing.Sequence[typing.Any]
    Context: typing.Any

class RangeExpression:
    """Stub for Cfg0.Services.Internal.Strong.Configurator._2015_10.ConfiguratorManagement.RangeExpression"""
    def __init__(self) -> None: ...
    OperatorCode: int
    ValueText: str
    Feature: typing.Any

class SetVariantExpressionInput:
    """Stub for Cfg0.Services.Internal.Strong.Configurator._2015_10.ConfiguratorManagement.SetVariantExpressionInput"""
    def __init__(self) -> None: ...
    BusinessObjectExpressions: typing.Sequence[typing.Any]
    RevisionRule: typing.Any
    SaveExpressions: bool

class ValidateProductConfigInput:
    """Stub for Cfg0.Services.Internal.Strong.Configurator._2015_10.ConfiguratorManagement.ValidateProductConfigInput"""
    def __init__(self) -> None: ...
    ApplyConstraints: int
    ExpressionsToValidate: typing.Sequence[typing.Any]
    Context: typing.Any

class ValidateProductConfigOutput:
    """Stub for Cfg0.Services.Internal.Strong.Configurator._2015_10.ConfiguratorManagement.ValidateProductConfigOutput"""
    def __init__(self) -> None: ...
    UpdatedExpression: typing.Any
    Violations: typing.Sequence[typing.Any]
    CriteriaStatus: str
    RequiredFamilies: typing.Sequence[typing.Any]

class ValidateProductConfigurationResponse:
    """Stub for Cfg0.Services.Internal.Strong.Configurator._2015_10.ConfiguratorManagement.ValidateProductConfigurationResponse"""
    def __init__(self) -> None: ...
    ServiceData: typing.Any
    Outputs: typing.Sequence[typing.Any]

class Violation:
    """Stub for Cfg0.Services.Internal.Strong.Configurator._2015_10.ConfiguratorManagement.Violation"""
    def __init__(self) -> None: ...
    Message: str
    Severity: str
    ViolatedRule: typing.Any
    ConfiguratorWSO: typing.Any

__all__ = [
    'ApplConfigExprWithDisplayString',
    'ApplicationConfigExpression',
    'AvailableProductVariabilityInput',
    'AvailableProductVariabilityOutput',
    'AvailableVariability',
    'BusinessObjectConfigExpression',
    'ConfigExprWithDisplayString',
    'ConfigExpression',
    'ConfigExpressionGroup',
    'ConfigExpressionSet',
    'ConfigExpressionSetInfo',
    'ConfigExpressionTerm',
    'ConfigSubExpression',
    'ConfiguratorManagement',
    'ConvertVariantExpressionInput',
    'ConvertVariantExpressionOutput',
    'ConvertVariantExpressionsResponse',
    'GetProductDefaultsConfigOutput',
    'GetProductDefaultsResponse',
    'GetRevisionRulesResponse',
    'GetVariantExpressionsResponse',
    'ProductDefaultsInput',
    'RangeExpression',
    'SetVariantExpressionInput',
    'ValidateProductConfigInput',
    'ValidateProductConfigOutput',
    'ValidateProductConfigurationResponse',
    'Violation',
]
