# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
from teamcenter.swi1.services.strong.svcworkinstructionsaw import SvcWorkInstructionsAwService

class SvcWorkInstructionsAwRestBindingStub(SvcWorkInstructionsAwService):
    """Stub for Swi1.Services.Strong.Svcworkinstructionsaw.SvcWorkInstructionsAwRestBindingStub"""
    def __init__(self, connection: typing.Any) -> None: ...
    def GetServiceWorkInstructions(self, Input: typing.Sequence[typing.Any]) -> typing.Any: ...
    def GetServiceWorkInstructions2(self, Input: typing.Sequence[typing.Any]) -> typing.Any: ...

class SvcWorkInstructionsAwService:
    """Stub for Swi1.Services.Strong.Svcworkinstructionsaw.SvcWorkInstructionsAwService"""
    def __init__(self) -> None: ...
    def GetServiceWorkInstructions(self, Input: typing.Sequence[typing.Any]) -> typing.Any: ...
    def GetServiceWorkInstructions2(self, Input: typing.Sequence[typing.Any]) -> typing.Any: ...
    @classmethod
    def getService(cls, connection: typing.Any) -> typing.Any: ...

__all__ = [
    'SvcWorkInstructionsAwRestBindingStub',
    'SvcWorkInstructionsAwService',
    '_2021_06',
]
