# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class BaselineTaskInfo:
    """Stub for Saw1.Services.Strong.Projectmanagementaw._2018_12.ScheduleManagementAw.BaselineTaskInfo"""
    def __init__(self) -> None: ...
    BaselineTask: typing.Any
    Properties: typing.Any

class CalendarInfo:
    """Stub for Saw1.Services.Strong.Projectmanagementaw._2018_12.ScheduleManagementAw.CalendarInfo"""
    def __init__(self) -> None: ...
    DayRanges: typing.Any
    EventRanges: typing.Sequence[typing.Any]

class LoadBaselineInfo:
    """Stub for Saw1.Services.Strong.Projectmanagementaw._2018_12.ScheduleManagementAw.LoadBaselineInfo"""
    def __init__(self) -> None: ...
    SourceSchedule: typing.Any
    BaselineSchedule: typing.Any
    ScheduleTasks: typing.Sequence[typing.Any]
    LoadOptions: typing.Any

class LoadBaselineResponse:
    """Stub for Saw1.Services.Strong.Projectmanagementaw._2018_12.ScheduleManagementAw.LoadBaselineResponse"""
    def __init__(self) -> None: ...
    BaselineTasksInfo: typing.Any
    ServiceData: typing.Any

class LoadScheduleInfo2:
    """Stub for Saw1.Services.Strong.Projectmanagementaw._2018_12.ScheduleManagementAw.LoadScheduleInfo2"""
    def __init__(self) -> None: ...
    Schedule: typing.Any
    ReferenceTask: typing.Any
    ParentTasks: typing.Sequence[typing.Any]
    LoadOptions: typing.Any

class LoadScheduleResponse2:
    """Stub for Saw1.Services.Strong.Projectmanagementaw._2018_12.ScheduleManagementAw.LoadScheduleResponse2"""
    def __init__(self) -> None: ...
    ScheduleTasksInfo: typing.Sequence[typing.Any]
    ProxyTasks: typing.Sequence[typing.Any]
    TaskDependenciesInfo: typing.Sequence[typing.Any]
    HasMoreTasks: bool
    TaskBaselineMap: typing.Any
    CalendarInfo: typing.Any
    ServiceData: typing.Any

class RecalculateInput:
    """Stub for Saw1.Services.Strong.Projectmanagementaw._2018_12.ScheduleManagementAw.RecalculateInput"""
    def __init__(self) -> None: ...
    Schedule: typing.Any
    RecalcType: int

class ScheduleManagementAw:
    """Stub for Saw1.Services.Strong.Projectmanagementaw._2018_12.ScheduleManagementAw.ScheduleManagementAw"""
    def __init__(self) -> None: ...
    def CreateMultipleTaskDeliverables(self, TaskDeliverableInputs: typing.Sequence[typing.Any]) -> typing.Any: ...
    def DesignateDiscipline(self, Schedule: typing.Any, Discipline: typing.Any, User: typing.Any, Revert: bool, RunInBackground: bool) -> typing.Any: ...
    def LoadBaseline(self, LoadBaselineInfo: typing.Any) -> typing.Any: ...
    def LoadSchedule2(self, LoadScheduleInfo: typing.Any) -> typing.Any: ...
    def RecalculateSchedules(self, RecalculateInputs: typing.Sequence[typing.Any], RunInBackground: bool) -> typing.Any: ...

class ScheduleTaskInfo:
    """Stub for Saw1.Services.Strong.Projectmanagementaw._2018_12.ScheduleManagementAw.ScheduleTaskInfo"""
    def __init__(self) -> None: ...
    ScheduleTask: typing.Any
    ParentTask: typing.Any

class TaskDeliverableInput:
    """Stub for Saw1.Services.Strong.Projectmanagementaw._2018_12.ScheduleManagementAw.TaskDeliverableInput"""
    def __init__(self) -> None: ...
    Schedule: typing.Any
    ScheduleTasks: typing.Sequence[typing.Any]
    SubmitType: int
    DeliverableReference: typing.Any
    DeliverableName: str
    DeliverableType: str

class TaskDependencyInfo:
    """Stub for Saw1.Services.Strong.Projectmanagementaw._2018_12.ScheduleManagementAw.TaskDependencyInfo"""
    def __init__(self) -> None: ...
    TaskDependency: typing.Any
    Properties: typing.Any

__all__ = [
    'BaselineTaskInfo',
    'CalendarInfo',
    'LoadBaselineInfo',
    'LoadBaselineResponse',
    'LoadScheduleInfo2',
    'LoadScheduleResponse2',
    'RecalculateInput',
    'ScheduleManagementAw',
    'ScheduleTaskInfo',
    'TaskDeliverableInput',
    'TaskDependencyInfo',
]
