# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class ESMBase:
    """Stub for Esm0.Services.Strong.Esmbase._2011_06.ESMBase.ESMBase"""
    def __init__(self) -> None: ...
    def GenerateHardwareSoftwareReport(self, GenerateReportInputs: typing.Sequence[typing.Any]) -> typing.Any: ...
    def GenerateSoftwareHardwareReport(self, GenerateReportInputs: typing.Sequence[typing.Any]) -> typing.Any: ...

class GenerateReportInput:
    """Stub for Esm0.Services.Strong.Esmbase._2011_06.ESMBase.GenerateReportInput"""
    def __init__(self) -> None: ...
    ClientId: str
    ItemRevision: typing.Any
    ConfigRule: typing.Any
    ReportFormatType: int
    CreateDataset: bool
    DatasetName: str

class GenerateReportOutput:
    """Stub for Esm0.Services.Strong.Esmbase._2011_06.ESMBase.GenerateReportOutput"""
    def __init__(self) -> None: ...
    ClientId: str
    DatasetObject: typing.Any
    FileName: str

class GenerateReportResponse:
    """Stub for Esm0.Services.Strong.Esmbase._2011_06.ESMBase.GenerateReportResponse"""
    def __init__(self) -> None: ...
    ReportOutputs: typing.Sequence[typing.Any]
    ServiceData: typing.Any

__all__ = [
    'ESMBase',
    'GenerateReportInput',
    'GenerateReportOutput',
    'GenerateReportResponse',
]
