# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class ChangeSummaryDataInput2:
    """Stub for Cm1.Services.Internal.Strong.Cmaws._2021_06.Changes.ChangeSummaryDataInput2"""
    def __init__(self) -> None: ...
    ChangeNoticeRevision: typing.Any
    InputObject: typing.Any
    IsOddRowSelected: bool
    StartIndex: int
    PageSize: int
    AdditionalData: typing.Any

class ChangeSummaryDataResponse2:
    """Stub for Cm1.Services.Internal.Strong.Cmaws._2021_06.Changes.ChangeSummaryDataResponse2"""
    def __init__(self) -> None: ...
    DataObjects: typing.Sequence[typing.Any]
    TotalFound: int
    EndIndex: int
    CurrentColumnConfig: typing.Sequence[typing.Any]
    DefaultColumnConfig: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class ChangeSummaryTableDataObject2:
    """Stub for Cm1.Services.Internal.Strong.Cmaws._2021_06.Changes.ChangeSummaryTableDataObject2"""
    def __init__(self) -> None: ...
    Id: str
    PrimaryObject: typing.Any
    SecondaryObject: typing.Any
    SupportingPrimaryObject: typing.Any
    SupportingSecondaryObject: typing.Any
    ObjectProperties: typing.Sequence[typing.Any]
    SiblingDataObjects: typing.Sequence[typing.Any]
    ChildDataObjects: typing.Sequence[typing.Any]
    AdditionalData: typing.Any

class Changes:
    """Stub for Cm1.Services.Internal.Strong.Cmaws._2021_06.Changes.Changes"""
    def __init__(self) -> None: ...
    def GetChangeSummaryData2(self, ChangeSummaryInput: typing.Any) -> typing.Any: ...

__all__ = [
    'ChangeSummaryDataInput2',
    'ChangeSummaryDataResponse2',
    'ChangeSummaryTableDataObject2',
    'Changes',
]
