# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class AttributeTargetManagement:
    """Stub for Att1.Services.Strong.Attrtargetmgmtaw._2019_12.AttributeTargetManagement.AttributeTargetManagement"""
    def __init__(self) -> None: ...
    def RemoveParameters(self, Inputs: typing.Sequence[typing.Any], ToDelete: bool) -> typing.Any: ...
    def ReplaceParameters(self, Inputs: typing.Sequence[typing.Any]) -> typing.Any: ...

class RemoveParametersInput:
    """Stub for Att1.Services.Strong.Attrtargetmgmtaw._2019_12.AttributeTargetManagement.RemoveParametersInput"""
    def __init__(self) -> None: ...
    ClientId: str
    Parent: typing.Any
    SelectedParams: typing.Sequence[typing.Any]

class RemoveParametersOutput:
    """Stub for Att1.Services.Strong.Attrtargetmgmtaw._2019_12.AttributeTargetManagement.RemoveParametersOutput"""
    def __init__(self) -> None: ...
    ClientId: str
    RemovedParams: typing.Sequence[typing.Any]
    IgnoredParams: typing.Sequence[typing.Any]
    DeletedParams: typing.Sequence[str]

class RemoveParametersResp:
    """Stub for Att1.Services.Strong.Attrtargetmgmtaw._2019_12.AttributeTargetManagement.RemoveParametersResp"""
    def __init__(self) -> None: ...
    Outputs: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class ReplaceParamInput:
    """Stub for Att1.Services.Strong.Attrtargetmgmtaw._2019_12.AttributeTargetManagement.ReplaceParamInput"""
    def __init__(self) -> None: ...
    SelectedParam: typing.Any
    TargetParam: typing.Any
    RevisePropInput: typing.Any
    ReviseAndReplace: bool

class ReplaceParametersInput:
    """Stub for Att1.Services.Strong.Attrtargetmgmtaw._2019_12.AttributeTargetManagement.ReplaceParametersInput"""
    def __init__(self) -> None: ...
    ClientId: str
    Parent: typing.Any
    ReplaceParams: typing.Sequence[typing.Any]

class ReplaceParametersOutput:
    """Stub for Att1.Services.Strong.Attrtargetmgmtaw._2019_12.AttributeTargetManagement.ReplaceParametersOutput"""
    def __init__(self) -> None: ...
    ClientId: str
    OldParams: typing.Sequence[typing.Any]
    NewParams: typing.Sequence[typing.Any]
    IgnoredParams: typing.Sequence[typing.Any]

class ReplaceParametersResp:
    """Stub for Att1.Services.Strong.Attrtargetmgmtaw._2019_12.AttributeTargetManagement.ReplaceParametersResp"""
    def __init__(self) -> None: ...
    Outputs: typing.Sequence[typing.Any]
    ServiceData: typing.Any

__all__ = [
    'AttributeTargetManagement',
    'RemoveParametersInput',
    'RemoveParametersOutput',
    'RemoveParametersResp',
    'ReplaceParamInput',
    'ReplaceParametersInput',
    'ReplaceParametersOutput',
    'ReplaceParametersResp',
]
