# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class DataManagement:
    """Stub for Teamcenter.Services.Internal.Strong.Visualization._2017_05.DataManagement.DataManagement"""
    def __init__(self) -> None: ...
    def GetSnapshot3DInfo2(self, Snapshot3DInputList: typing.Sequence[typing.Any]) -> typing.Any: ...

class Snapshot3DInfoInput2:
    """Stub for Teamcenter.Services.Internal.Strong.Visualization._2017_05.DataManagement.Snapshot3DInfoInput2"""
    def __init__(self) -> None: ...
    ClientId: str
    Snapshot3DDataset: typing.Any
    GetStaticFilesInfo: bool

class Snapshot3DInfoOutput2:
    """Stub for Teamcenter.Services.Internal.Strong.Visualization._2017_05.DataManagement.Snapshot3DInfoOutput2"""
    def __init__(self) -> None: ...
    NamedRefFileInfoList: typing.Sequence[typing.Any]
    RelObjList: typing.Sequence[typing.Any]
    Snapshot3DVisibleLines: typing.Any

class Snapshot3DInfoResponse2:
    """Stub for Teamcenter.Services.Internal.Strong.Visualization._2017_05.DataManagement.Snapshot3DInfoResponse2"""
    def __init__(self) -> None: ...
    Snapshot3DInfoMap: typing.Any
    ServiceData: typing.Any

class Snapshot3DRelObjInfo2:
    """Stub for Teamcenter.Services.Internal.Strong.Visualization._2017_05.DataManagement.Snapshot3DRelObjInfo2"""
    def __init__(self) -> None: ...
    RelType: str
    RelObj: typing.Any
    Relation: typing.Any

class Snapshot3DVisibleLines2:
    """Stub for Teamcenter.Services.Internal.Strong.Visualization._2017_05.DataManagement.Snapshot3DVisibleLines2"""
    def __init__(self) -> None: ...
    UidType: str
    VisibleLinesMap: typing.Any
    RelDatasetInfoMap: typing.Any

class StaticFileInfo2:
    """Stub for Teamcenter.Services.Internal.Strong.Visualization._2017_05.DataManagement.StaticFileInfo2"""
    def __init__(self) -> None: ...
    DatasetUID: str
    ImanFileUID: str
    OriginalFileName: str

class VisibleLine2:
    """Stub for Teamcenter.Services.Internal.Strong.Visualization._2017_05.DataManagement.VisibleLine2"""
    def __init__(self) -> None: ...
    UidString: str
    RelDatasetRef: str
    ParentRef: str
    AltKeyType: str
    AltKeyValue: str

__all__ = [
    'DataManagement',
    'Snapshot3DInfoInput2',
    'Snapshot3DInfoOutput2',
    'Snapshot3DInfoResponse2',
    'Snapshot3DRelObjInfo2',
    'Snapshot3DVisibleLines2',
    'StaticFileInfo2',
    'VisibleLine2',
]
