# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class Changes:
    """Stub for Cm1.Services.Internal.Strong.Cmaws._2020_12.Changes.Changes"""
    def __init__(self) -> None: ...
    def MergeRedLineChanges(self, MergeRedLineChangesInput: typing.Any) -> typing.Any: ...
    def RevertChanges(self, RevertInput: typing.Sequence[typing.Any]) -> typing.Any: ...

class MergeRedLineChangesInput:
    """Stub for Cm1.Services.Internal.Strong.Cmaws._2020_12.Changes.MergeRedLineChangesInput"""
    def __init__(self) -> None: ...
    SourceLines: typing.Sequence[typing.Any]
    TargetLine: typing.Any
    PropertiesToMerge: typing.Sequence[str]
    MergeChildren: bool

class RevertRedlineInput:
    """Stub for Cm1.Services.Internal.Strong.Cmaws._2020_12.Changes.RevertRedlineInput"""
    def __init__(self) -> None: ...
    SelectedBOMLine: typing.Any
    SelectedObject: typing.Any
    PropertiesToRevert: typing.Sequence[str]
    SecondarySelections: typing.Sequence[typing.Any]
    RevertChildren: bool

__all__ = [
    'Changes',
    'MergeRedLineChangesInput',
    'RevertRedlineInput',
]
