# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class GroupMembershipInput2:
    """Stub for Awp0.Services.Internal.Strong.Aws2._2013_12.OrganizationManagement.GroupMembershipInput2"""
    def __init__(self) -> None: ...
    UserId: str
    UserName: str
    GroupName: str
    RoleName: str
    SearchForSubGroup: bool
    StartIndex: int
    MaxToReturn: int
    MaxToLoad: int

class OrganizationManagement:
    """Stub for Awp0.Services.Internal.Strong.Aws2._2013_12.OrganizationManagement.OrganizationManagement"""
    def __init__(self) -> None: ...
    def GetGroupMembership2(self, Input: typing.Any) -> typing.Any: ...

__all__ = [
    'GroupMembershipInput2',
    'OrganizationManagement',
]
