# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class GetGroupRoleViewModelInput:
    """Stub for Teamcenter.Services.Internal.Strong.Administration._2019_06.UserManagement.GetGroupRoleViewModelInput"""
    def __init__(self) -> None: ...
    UserObject: typing.Any
    StartIndex: int
    PageSize: int

class GetGroupRoleViewModelResponse:
    """Stub for Teamcenter.Services.Internal.Strong.Administration._2019_06.UserManagement.GetGroupRoleViewModelResponse"""
    def __init__(self) -> None: ...
    ViewModelRows: typing.Sequence[typing.Any]
    TotalFound: int
    EndIndex: int
    ServiceData: typing.Any

class UserManagement:
    """Stub for Teamcenter.Services.Internal.Strong.Administration._2019_06.UserManagement.UserManagement"""
    def __init__(self) -> None: ...
    def GetGroupRoleViewModelRows(self, Input: typing.Any) -> typing.Any: ...

class ViewModelObject:
    """Stub for Teamcenter.Services.Internal.Strong.Administration._2019_06.UserManagement.ViewModelObject"""
    def __init__(self) -> None: ...
    ModelObject: typing.Any
    ViewModelProperties: typing.Sequence[typing.Any]

class ViewModelProperty:
    """Stub for Teamcenter.Services.Internal.Strong.Administration._2019_06.UserManagement.ViewModelProperty"""
    def __init__(self) -> None: ...
    PropInternalName: str
    PropDisplayName: str
    PropDBValue: str
    PropUIValue: str
    PropDataType: str
    IsEditable: bool
    HasLOV: bool
    IsModifiable: bool
    PropBO: typing.Any

__all__ = [
    'GetGroupRoleViewModelInput',
    'GetGroupRoleViewModelResponse',
    'UserManagement',
    'ViewModelObject',
    'ViewModelProperty',
]
