# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class FetchNextChildrenCursor:
    """Stub for Ptn0.Services.Strong.Partition._2021_06.PartitionManagement.FetchNextChildrenCursor"""
    def __init__(self) -> None: ...
    Cursor: typing.Any
    IsFinished: bool
    EstimatedElementsLeft: int

class GetAllChildPtnInAppModelInInfo:
    """Stub for Ptn0.Services.Strong.Partition._2021_06.PartitionManagement.GetAllChildPtnInAppModelInInfo"""
    def __init__(self) -> None: ...
    ClientId: str
    InputAppModel: typing.Any
    MaxLevelCount: int
    MaxChildCount: int
    LoadCount: int
    ConfigurationContext: typing.Any

class GetAllChildPtnInAppModelOutInfo:
    """Stub for Ptn0.Services.Strong.Partition._2021_06.PartitionManagement.GetAllChildPtnInAppModelOutInfo"""
    def __init__(self) -> None: ...
    ClientId: str
    AppModelSchemesMap: typing.Any
    SchemesPartitionMap: typing.Any
    ParentChildPartitionMap: typing.Any
    ChildPartitionListTruncated: bool
    ExpandedLevelCount: int
    Cursor: typing.Any

class GetAllChildPtnInAppModelResponse:
    """Stub for Ptn0.Services.Strong.Partition._2021_06.PartitionManagement.GetAllChildPtnInAppModelResponse"""
    def __init__(self) -> None: ...
    Output: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class GetNextChildPtnInAppModelInInfo:
    """Stub for Ptn0.Services.Strong.Partition._2021_06.PartitionManagement.GetNextChildPtnInAppModelInInfo"""
    def __init__(self) -> None: ...
    ClientId: str
    Cursor: typing.Any
    LoadCount: int

class GetNextChildPtnInAppModelOutInfo:
    """Stub for Ptn0.Services.Strong.Partition._2021_06.PartitionManagement.GetNextChildPtnInAppModelOutInfo"""
    def __init__(self) -> None: ...
    ClientId: str
    ParentChildPartitionMap: typing.Any
    ChildPartitionListTruncated: bool
    ExpandedLevelCount: int
    Cursor: typing.Any

class GetNextChildPtnInAppModelResponse:
    """Stub for Ptn0.Services.Strong.Partition._2021_06.PartitionManagement.GetNextChildPtnInAppModelResponse"""
    def __init__(self) -> None: ...
    Output: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class PartitionManagement:
    """Stub for Ptn0.Services.Strong.Partition._2021_06.PartitionManagement.PartitionManagement"""
    def __init__(self) -> None: ...
    def GetAllChildPtnInAppModel(self, Inputs: typing.Sequence[typing.Any]) -> typing.Any: ...
    def GetNextChildPtnInAppModel(self, Inputs: typing.Sequence[typing.Any]) -> typing.Any: ...
    def StopGetChildren(self, Cursor: typing.Any) -> typing.Any: ...

class StopGetChildrenResponse:
    """Stub for Ptn0.Services.Strong.Partition._2021_06.PartitionManagement.StopGetChildrenResponse"""
    def __init__(self) -> None: ...
    IsFinished: bool
    ServiceData: typing.Any

__all__ = [
    'FetchNextChildrenCursor',
    'GetAllChildPtnInAppModelInInfo',
    'GetAllChildPtnInAppModelOutInfo',
    'GetAllChildPtnInAppModelResponse',
    'GetNextChildPtnInAppModelInInfo',
    'GetNextChildPtnInAppModelOutInfo',
    'GetNextChildPtnInAppModelResponse',
    'PartitionManagement',
    'StopGetChildrenResponse',
]
