# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class AuxObjectInfo:
    """Stub for Mdl0.Services.Strong.Modelcore._2014_10.DataManagement.AuxObjectInfo"""
    def __init__(self) -> None: ...
    SourceObject: typing.Any
    AttrInfo: typing.Any

class CloneModelContentInfo:
    """Stub for Mdl0.Services.Strong.Modelcore._2014_10.DataManagement.CloneModelContentInfo"""
    def __init__(self) -> None: ...
    CreateInfo: typing.Sequence[typing.Any]

class CloneModelContentResponse:
    """Stub for Mdl0.Services.Strong.Modelcore._2014_10.DataManagement.CloneModelContentResponse"""
    def __init__(self) -> None: ...
    Output: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class DataManagement:
    """Stub for Mdl0.Services.Strong.Modelcore._2014_10.DataManagement.DataManagement"""
    def __init__(self) -> None: ...
    def CloneModelContent(self, Info: typing.Any) -> typing.Any: ...

class ErrorValuesStruct:
    """Stub for Mdl0.Services.Strong.Modelcore._2014_10.DataManagement.ErrorValuesStruct"""
    def __init__(self) -> None: ...
    Code: int
    Message: str
    Level: str

class FailedObjsErrorStruct:
    """Stub for Mdl0.Services.Strong.Modelcore._2014_10.DataManagement.FailedObjsErrorStruct"""
    def __init__(self) -> None: ...
    SourceObject: typing.Any
    ErrorValue: typing.Any

class ModelContentOutputInfo:
    """Stub for Mdl0.Services.Strong.Modelcore._2014_10.DataManagement.ModelContentOutputInfo"""
    def __init__(self) -> None: ...
    SourceToTargetMap: typing.Any
    FailedObjects: typing.Sequence[typing.Any]
    ClientID: str

class SourceModelInfo:
    """Stub for Mdl0.Services.Strong.Modelcore._2014_10.DataManagement.SourceModelInfo"""
    def __init__(self) -> None: ...
    SourceModelObject: typing.Any
    ConfigContext: typing.Any
    SubsetDef: typing.Any
    IncludeSourceElements: typing.Sequence[typing.Any]
    AuxInfo: typing.Any
    AuxObjectInfo: typing.Sequence[typing.Any]

class SourceTargetContentInfo:
    """Stub for Mdl0.Services.Strong.Modelcore._2014_10.DataManagement.SourceTargetContentInfo"""
    def __init__(self) -> None: ...
    ClientID: str
    SourceModelInfo: typing.Any
    TargetModel: typing.Any

__all__ = [
    'AuxObjectInfo',
    'CloneModelContentInfo',
    'CloneModelContentResponse',
    'DataManagement',
    'ErrorValuesStruct',
    'FailedObjsErrorStruct',
    'ModelContentOutputInfo',
    'SourceModelInfo',
    'SourceTargetContentInfo',
]
