# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class ObjectManagement:
    """Stub for Teamcenter.Services.Internal.Strong.Cadbomalignment._2015_10.ObjectManagement.ObjectManagement"""
    def __init__(self) -> None: ...
    def UpdatePSFromPMM(self, PsForPMMInput: typing.Sequence[typing.Any]) -> typing.Any: ...

class PSForPMMInput:
    """Stub for Teamcenter.Services.Internal.Strong.Cadbomalignment._2015_10.ObjectManagement.PSForPMMInput"""
    def __init__(self) -> None: ...
    ClientId: str
    Window: typing.Any
    SelectedLines: typing.Sequence[typing.Any]

__all__ = [
    'ObjectManagement',
    'PSForPMMInput',
]
