# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class ProgramManagement:
    """Stub for Prg0.Services.Strong.Programinfra._2021_12.ProgramManagement.ProgramManagement"""
    def __init__(self) -> None: ...
    def MoveEvents(self, Events: typing.Sequence[typing.Any], NewEventDate: typing.Any, UpdateSecondaryEvents: bool, RunInBackground: bool) -> typing.Any: ...

__all__ = [
    'ProgramManagement',
]
