# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class CreateOrUpdateDesignControlElementOutput:
    """Stub for Cpd0.Services.Strong.Cpdcore._2012_06.DataManagement.CreateOrUpdateDesignControlElementOutput"""
    def __init__(self) -> None: ...
    DesignControlElement: typing.Any
    ShapeDesign: typing.Any
    CsIdMap: typing.Any

class CreateOrUpdateDesignControlElementsResponse2:
    """Stub for Cpd0.Services.Strong.Cpdcore._2012_06.DataManagement.CreateOrUpdateDesignControlElementsResponse2"""
    def __init__(self) -> None: ...
    ClientIdToDCEOutputMap: typing.Any
    ServiceData: typing.Any

class DataManagement:
    """Stub for Cpd0.Services.Strong.Cpdcore._2012_06.DataManagement.DataManagement"""
    def __init__(self) -> None: ...
    def CreateOrUpdateDesignControlElements2(self, ElementInfos: typing.Sequence[typing.Any]) -> typing.Any: ...
    def SubstituteAsReuseDesignElement2(self, SubstituteInfos: typing.Sequence[typing.Any]) -> typing.Any: ...

class SubstituteAsReuseDesignElementResponse:
    """Stub for Cpd0.Services.Strong.Cpdcore._2012_06.DataManagement.SubstituteAsReuseDesignElementResponse"""
    def __init__(self) -> None: ...
    ClientIDMap: typing.Any
    SubordinateElements: typing.Any
    ServiceData: typing.Any

__all__ = [
    'CreateOrUpdateDesignControlElementOutput',
    'CreateOrUpdateDesignControlElementsResponse2',
    'DataManagement',
    'SubstituteAsReuseDesignElementResponse',
]
