# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class CadAttrMappingDefinitionInfo:
    """Stub for Teamcenter.Services.Strong.Cad._2008_03.DataManagement.CadAttrMappingDefinitionInfo"""
    def __init__(self) -> None: ...
    ClientId: str
    CadAttrMappingDefinition: typing.Any

class DataManagement:
    """Stub for Teamcenter.Services.Strong.Cad._2008_03.DataManagement.DataManagement"""
    def __init__(self) -> None: ...
    def CreateOrUpdateParts(self, Info: typing.Sequence[typing.Any], Pref: typing.Any) -> typing.Any: ...
    def ResolveAttrMappings(self, Info: typing.Sequence[typing.Any]) -> typing.Any: ...

class DatasetInfo3:
    """Stub for Teamcenter.Services.Strong.Cad._2008_03.DataManagement.DatasetInfo3"""
    def __init__(self) -> None: ...
    ClientId: str
    Dataset: typing.Any
    Name: str
    BasisName: str
    Description: str
    Type: str
    LastModifiedOfDataset: typing.Any
    Id: str
    DatasetRev: str
    ItemRevRelationName: str
    CreateNewVersion: bool
    MapAttributesWithoutDataset: bool
    NamedReferencePreference: str
    AttrList: typing.Sequence[typing.Any]
    MappingAttributes: typing.Sequence[typing.Any]
    ExtraObject: typing.Sequence[typing.Any]
    DatasetFileInfos: typing.Sequence[typing.Any]
    NamedReferenceObjectInfos: typing.Sequence[typing.Any]

class MappedDatasetAttrPropertyInfo:
    """Stub for Teamcenter.Services.Strong.Cad._2008_03.DataManagement.MappedDatasetAttrPropertyInfo"""
    def __init__(self) -> None: ...
    CadAttrMappingDefinition: typing.Any
    ResolvedObject: typing.Any
    ResolvedPropertyName: str

class PartInfo3:
    """Stub for Teamcenter.Services.Strong.Cad._2008_03.DataManagement.PartInfo3"""
    def __init__(self) -> None: ...
    ClientId: str
    ItemInput: typing.Any
    ItemRevInput: typing.Any
    DatasetInput: typing.Sequence[typing.Any]

class ResolveAttrMappingsInfo:
    """Stub for Teamcenter.Services.Strong.Cad._2008_03.DataManagement.ResolveAttrMappingsInfo"""
    def __init__(self) -> None: ...
    Dataset: typing.Any
    ItemRev: typing.Any
    MappingDefinitionInfos: typing.Sequence[typing.Any]

class ResolveAttrMappingsResponse:
    """Stub for Teamcenter.Services.Strong.Cad._2008_03.DataManagement.ResolveAttrMappingsResponse"""
    def __init__(self) -> None: ...
    ResolvedMappingsMap: typing.Any
    ServiceData: typing.Any

__all__ = [
    'CadAttrMappingDefinitionInfo',
    'DataManagement',
    'DatasetInfo3',
    'MappedDatasetAttrPropertyInfo',
    'PartInfo3',
    'ResolveAttrMappingsInfo',
    'ResolveAttrMappingsResponse',
]
