# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class ConvertSVGInputData:
    """Stub for Arm1.Services.Internal.Strong.Awreqmgmtse._2019_12.SpecNavigation.ConvertSVGInputData"""
    def __init__(self) -> None: ...
    SvgFileTicket: str
    Height: int
    Width: int
    OutputType: str
    Options: typing.Sequence[str]

class ConvertSVGResponse:
    """Stub for Arm1.Services.Internal.Strong.Awreqmgmtse._2019_12.SpecNavigation.ConvertSVGResponse"""
    def __init__(self) -> None: ...
    GeneratedFileTicket: str
    Data: typing.Any

class ExportSpecificationInfo:
    """Stub for Arm1.Services.Internal.Strong.Awreqmgmtse._2019_12.SpecNavigation.ExportSpecificationInfo"""
    def __init__(self) -> None: ...
    SelectedObjects: typing.Sequence[typing.Any]
    TypePropsData: typing.Sequence[typing.Any]
    InputCtxt: typing.Any
    Mode: str
    IsRunInBackground: bool
    Options: typing.Sequence[str]

class ExportSpecificationResponse:
    """Stub for Arm1.Services.Internal.Strong.Awreqmgmtse._2019_12.SpecNavigation.ExportSpecificationResponse"""
    def __init__(self) -> None: ...
    FileTickets: typing.Sequence[str]
    ServiceData: typing.Any

class PropInfo2:
    """Stub for Arm1.Services.Internal.Strong.Awreqmgmtse._2019_12.SpecNavigation.PropInfo2"""
    def __init__(self) -> None: ...
    PropName: str
    DispPropName: str
    IsRequired: bool
    IsEditable: bool
    HasLOV: bool
    LovValues: typing.Sequence[str]
    LovDispValues: typing.Sequence[str]
    PropType: str
    MinValue: int
    MaxValue: int
    IsArray: bool

class SaveTraceLinkMatrixInput:
    """Stub for Arm1.Services.Internal.Strong.Awreqmgmtse._2019_12.SpecNavigation.SaveTraceLinkMatrixInput"""
    def __init__(self) -> None: ...
    TracelinkInput: typing.Any
    MatrixType: str
    TargetFolder: typing.Any
    Operation: str

class SpecNavigation:
    """Stub for Arm1.Services.Internal.Strong.Awreqmgmtse._2019_12.SpecNavigation.SpecNavigation"""
    def __init__(self) -> None: ...
    def ConvertSVG(self, InputData: typing.Any) -> typing.Any: ...
    def ExportSpecifications(self, Input: typing.Any) -> typing.Any: ...
    def GetSpecificationMetadata(self, Input: typing.Any) -> typing.Any: ...
    def SaveTraceabilityMatrix(self, InputData: typing.Any) -> typing.Any: ...

class SpecResponse:
    """Stub for Arm1.Services.Internal.Strong.Awreqmgmtse._2019_12.SpecNavigation.SpecResponse"""
    def __init__(self) -> None: ...
    TypePropInfos: typing.Sequence[typing.Any]
    ReqIFTypePropInfos: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class SpecificationInfo:
    """Stub for Arm1.Services.Internal.Strong.Awreqmgmtse._2019_12.SpecNavigation.SpecificationInfo"""
    def __init__(self) -> None: ...
    SelectedObjects: typing.Sequence[typing.Any]
    FileTicket: str
    InputCtxt: typing.Any
    TypePropMap: typing.Any
    Options: typing.Sequence[str]

class TypePropInfo2:
    """Stub for Arm1.Services.Internal.Strong.Awreqmgmtse._2019_12.SpecNavigation.TypePropInfo2"""
    def __init__(self) -> None: ...
    TypeInfo: str
    ObjectType: str
    DispTypeName: str
    ObjectTypeRev: str
    PropInfos: typing.Sequence[typing.Any]

__all__ = [
    'ConvertSVGInputData',
    'ConvertSVGResponse',
    'ExportSpecificationInfo',
    'ExportSpecificationResponse',
    'PropInfo2',
    'SaveTraceLinkMatrixInput',
    'SpecNavigation',
    'SpecResponse',
    'SpecificationInfo',
    'TypePropInfo2',
]
