# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
from teamcenter.clr0.services.strong.colorappearance import AppearanceManagementService

class AppearanceManagementRestBindingStub(AppearanceManagementService):
    """Stub for Clr0.Services.Strong.Colorappearance.AppearanceManagementRestBindingStub"""
    def __init__(self, connection: typing.Any) -> None: ...
    def GetColorAppearance(self, TargetObjects: typing.Sequence[typing.Any]) -> typing.Any: ...
    def SetColorAppearance(self, CreateInput: typing.Sequence[typing.Any]) -> typing.Any: ...

class AppearanceManagementService:
    """Stub for Clr0.Services.Strong.Colorappearance.AppearanceManagementService"""
    def __init__(self) -> None: ...
    def GetColorAppearance(self, TargetObjects: typing.Sequence[typing.Any]) -> typing.Any: ...
    def SetColorAppearance(self, CreateInput: typing.Sequence[typing.Any]) -> typing.Any: ...
    @classmethod
    def getService(cls, connection: typing.Any) -> typing.Any: ...

__all__ = [
    'AppearanceManagementRestBindingStub',
    'AppearanceManagementService',
    '_2014_12',
]
