# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
from teamcenter.awb0.services.internal.strong.structure import WhereUsedService

class WhereUsedRestBindingStub(WhereUsedService):
    """Stub for Awb0.Services.Internal.Strong.Structure.WhereUsedRestBindingStub"""
    def __init__(self, connection: typing.Any) -> None: ...
    def GetWhereUsedInfo(self, WhereUsedInput: typing.Any) -> typing.Any: ...

class WhereUsedService:
    """Stub for Awb0.Services.Internal.Strong.Structure.WhereUsedService"""
    def __init__(self) -> None: ...
    def GetWhereUsedInfo(self, WhereUsedInput: typing.Any) -> typing.Any: ...
    @classmethod
    def getService(cls, connection: typing.Any) -> typing.Any: ...

__all__ = [
    'WhereUsedRestBindingStub',
    'WhereUsedService',
    '_2020_12',
]
