# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class CreateOrUpdateStaticTableDataResponse:
    """Stub for Teamcenter.Services.Strong.Core._2010_09.DataManagement.CreateOrUpdateStaticTableDataResponse"""
    def __init__(self) -> None: ...
    ServiceData: typing.Any
    StaticTableObject: typing.Any

class DataManagement:
    """Stub for Teamcenter.Services.Strong.Core._2010_09.DataManagement.DataManagement"""
    def __init__(self) -> None: ...
    def CreateOrUpdateStaticTableData(self, StaticTableInfo: typing.Any, RowProperties: typing.Sequence[typing.Any]) -> typing.Any: ...
    def GetEventTypes(self, Input: typing.Sequence[typing.Any]) -> typing.Any: ...
    def GetStaticTableData(self, StaticTable: typing.Any) -> typing.Any: ...
    def PostEvent(self, Input: typing.Sequence[typing.Any], EventTypeName: str) -> typing.Any: ...
    def SetProperties(self, Info: typing.Sequence[typing.Any], Options: typing.Sequence[str]) -> typing.Any: ...
    def VerifyExtension(self, ExtensionInfo: typing.Sequence[typing.Any]) -> typing.Any: ...

class EventObject:
    """Stub for Teamcenter.Services.Strong.Core._2010_09.DataManagement.EventObject"""
    def __init__(self) -> None: ...
    ClientId: str
    BusinessObject: typing.Any

class EventTypesOutput:
    """Stub for Teamcenter.Services.Strong.Core._2010_09.DataManagement.EventTypesOutput"""
    def __init__(self) -> None: ...
    ClientId: str
    AuditableEvents: typing.Sequence[str]
    SubscribableEvents: typing.Sequence[str]

class EventTypesResponse:
    """Stub for Teamcenter.Services.Strong.Core._2010_09.DataManagement.EventTypesResponse"""
    def __init__(self) -> None: ...
    Output: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class NameValueStruct1:
    """Stub for Teamcenter.Services.Strong.Core._2010_09.DataManagement.NameValueStruct1"""
    def __init__(self) -> None: ...
    Name: str
    Values: typing.Sequence[str]

class PostEventObjectProperties:
    """Stub for Teamcenter.Services.Strong.Core._2010_09.DataManagement.PostEventObjectProperties"""
    def __init__(self) -> None: ...
    ClientId: str
    PrimaryObject: typing.Any
    SecondaryObject: typing.Any
    PropertyCount: int
    PropertyNames: typing.Sequence[str]
    PropertyValues: typing.Sequence[str]
    ErrorCode: int
    ErrorMessage: str

class PostEventOutput:
    """Stub for Teamcenter.Services.Strong.Core._2010_09.DataManagement.PostEventOutput"""
    def __init__(self) -> None: ...
    ClientId: str
    IfailError: int

class PostEventResponse:
    """Stub for Teamcenter.Services.Strong.Core._2010_09.DataManagement.PostEventResponse"""
    def __init__(self) -> None: ...
    Output: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class PropInfo:
    """Stub for Teamcenter.Services.Strong.Core._2010_09.DataManagement.PropInfo"""
    def __init__(self) -> None: ...
    Object: typing.Any
    VecNameVal: typing.Sequence[typing.Any]
    Timestamp: typing.Any

class RowData:
    """Stub for Teamcenter.Services.Strong.Core._2010_09.DataManagement.RowData"""
    def __init__(self) -> None: ...
    ClientId: str
    RowObject: typing.Any
    RowType: str
    RowAttrValueMap: typing.Any

class SetPropertyResponse:
    """Stub for Teamcenter.Services.Strong.Core._2010_09.DataManagement.SetPropertyResponse"""
    def __init__(self) -> None: ...
    Data: typing.Any
    ObjPropMap: typing.Any

class StaticTableDataResponse:
    """Stub for Teamcenter.Services.Strong.Core._2010_09.DataManagement.StaticTableDataResponse"""
    def __init__(self) -> None: ...
    ClientId: str
    ServiceData: typing.Any

class StaticTableInfo:
    """Stub for Teamcenter.Services.Strong.Core._2010_09.DataManagement.StaticTableInfo"""
    def __init__(self) -> None: ...
    TableType: str
    TableObject: typing.Any

class VerifyExtensionInfo:
    """Stub for Teamcenter.Services.Strong.Core._2010_09.DataManagement.VerifyExtensionInfo"""
    def __init__(self) -> None: ...
    TypeName: str
    OperationName: str
    ExtensionName: str
    ExtensionType: int

class VerifyExtensionResponse:
    """Stub for Teamcenter.Services.Strong.Core._2010_09.DataManagement.VerifyExtensionResponse"""
    def __init__(self) -> None: ...
    Output: typing.Sequence[bool]
    ServiceData: typing.Any

__all__ = [
    'CreateOrUpdateStaticTableDataResponse',
    'DataManagement',
    'EventObject',
    'EventTypesOutput',
    'EventTypesResponse',
    'NameValueStruct1',
    'PostEventObjectProperties',
    'PostEventOutput',
    'PostEventResponse',
    'PropInfo',
    'RowData',
    'SetPropertyResponse',
    'StaticTableDataResponse',
    'StaticTableInfo',
    'VerifyExtensionInfo',
    'VerifyExtensionResponse',
]
