# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class AlignAssemblyData:
    """Stub for Teamcenter.Services.Internal.Strong.Manufacturing._2015_03.StructureManagement.AlignAssemblyData"""
    def __init__(self) -> None: ...
    SourceNode: typing.Any
    TargetNode: typing.Any
    ReuseAssemblyNode: typing.Any
    AlignMode: str

class ConfigurationsInfo:
    """Stub for Teamcenter.Services.Internal.Strong.Manufacturing._2015_03.StructureManagement.ConfigurationsInfo"""
    def __init__(self) -> None: ...
    Window: typing.Any
    RootLine: typing.Any
    RevisionRule: typing.Any
    VariantRule: typing.Any
    EffGrpRevisions: typing.Sequence[typing.Any]
    ShowUnconfigVariants: bool
    ShowUnconfigOccEffectivity: bool
    ShowSupressedOccurrences: bool
    ShowUnconfigICs: bool
    ShowUnconfigAssignedOccs: bool
    SaveCC: typing.Any

class ConfigureMultipleStructuresResponse:
    """Stub for Teamcenter.Services.Internal.Strong.Manufacturing._2015_03.StructureManagement.ConfigureMultipleStructuresResponse"""
    def __init__(self) -> None: ...
    ServiceData: typing.Any
    LogFileTicket: typing.Any

class CreateReuseAssembly:
    """Stub for Teamcenter.Services.Internal.Strong.Manufacturing._2015_03.StructureManagement.CreateReuseAssembly"""
    def __init__(self) -> None: ...
    ParentNodes: typing.Sequence[typing.Any]
    ModelAssemblyNode: typing.Any
    BasisOccurrenceChain: str
    NodesAssignedInModelAssembly: typing.Sequence[typing.Any]
    ClusterElements: typing.Sequence[typing.Any]

class CreateReuseAssemblyResp:
    """Stub for Teamcenter.Services.Internal.Strong.Manufacturing._2015_03.StructureManagement.CreateReuseAssemblyResp"""
    def __init__(self) -> None: ...
    Nodes: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class FileTicketDetails:
    """Stub for Teamcenter.Services.Internal.Strong.Manufacturing._2015_03.StructureManagement.FileTicketDetails"""
    def __init__(self) -> None: ...
    Filename: str
    FileTicket: str

class GetClusterDetails:
    """Stub for Teamcenter.Services.Internal.Strong.Manufacturing._2015_03.StructureManagement.GetClusterDetails"""
    def __init__(self) -> None: ...
    Clusters: typing.Sequence[typing.Any]

class SearchForClusters:
    """Stub for Teamcenter.Services.Internal.Strong.Manufacturing._2015_03.StructureManagement.SearchForClusters"""
    def __init__(self) -> None: ...
    MbomModelAssemblyNode: typing.Any
    EbomContext: typing.Any

class SearchForClustersElement:
    """Stub for Teamcenter.Services.Internal.Strong.Manufacturing._2015_03.StructureManagement.SearchForClustersElement"""
    def __init__(self) -> None: ...
    Line: typing.Any
    IsBasis: bool
    Idic: str

class SearchForClustersResponse:
    """Stub for Teamcenter.Services.Internal.Strong.Manufacturing._2015_03.StructureManagement.SearchForClustersResponse"""
    def __init__(self) -> None: ...
    BasisOccurrenceChain: str
    NodesAssignedInModelAssembly: typing.Sequence[typing.Any]
    Patterns: typing.Sequence[typing.Any]
    UnassignedModelAssemblyNodes: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class SearchForClustersResponseElement:
    """Stub for Teamcenter.Services.Internal.Strong.Manufacturing._2015_03.StructureManagement.SearchForClustersResponseElement"""
    def __init__(self) -> None: ...
    PatternNodes: typing.Sequence[typing.Any]
    OwningModelAssemblies: typing.Sequence[typing.Any]

class StructureManagement:
    """Stub for Teamcenter.Services.Internal.Strong.Manufacturing._2015_03.StructureManagement.StructureManagement"""
    def __init__(self) -> None: ...
    def AlignAssemblies(self, Input: typing.Sequence[typing.Any]) -> typing.Any: ...
    def ConfigureMultipleStructures(self, ConfigurationsInfo: typing.Sequence[typing.Any]) -> typing.Any: ...
    def CreateReuseAssemblies(self, Input: typing.Sequence[typing.Any]) -> typing.Any: ...
    def GetClusterDetails(self, Input: typing.Sequence[typing.Any]) -> typing.Any: ...
    def SearchForClusters(self, Input: typing.Sequence[typing.Any]) -> typing.Any: ...

__all__ = [
    'AlignAssemblyData',
    'ConfigurationsInfo',
    'ConfigureMultipleStructuresResponse',
    'CreateReuseAssembly',
    'CreateReuseAssemblyResp',
    'FileTicketDetails',
    'GetClusterDetails',
    'SearchForClusters',
    'SearchForClustersElement',
    'SearchForClustersResponse',
    'SearchForClustersResponseElement',
    'StructureManagement',
]
