# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class Session:
    """Stub for Teamcenter.Services.Internal.Strong.Core._2007_05.Session.Session"""
    def __init__(self) -> None: ...
    def RefreshPOMCachePerRequest(self, Refresh: bool) -> bool: ...

__all__ = [
    'Session',
]
