# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class AssignLotInfo:
    """Stub for Teamcenter.Services.Strong.Mrocore._2014_06.MROCore.AssignLotInfo"""
    def __init__(self) -> None: ...
    ClientId: str
    PhysicalBOMLine: typing.Any
    PhysicalPartRevision: typing.Any
    Lot: typing.Any
    Quantity: int

class MROCore:
    """Stub for Teamcenter.Services.Strong.Mrocore._2014_06.MROCore.MROCore"""
    def __init__(self) -> None: ...
    def AssignLot(self, Info: typing.Sequence[typing.Any]) -> typing.Any: ...

__all__ = [
    'AssignLotInfo',
    'MROCore',
]
