# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class AddBranchContentInput:
    """Stub for Bhv1.Services.Internal.Strong.Branchandversioning._2018_05.BranchingAndVersioning.AddBranchContentInput"""
    def __init__(self) -> None: ...
    ClientID: str
    TargetBranch: typing.Any
    ContextObject: typing.Any
    Contents: typing.Sequence[typing.Any]
    CheckoutFlag: bool
    Comment: typing.Any
    Config: typing.Any

class AddBranchContentResponse:
    """Stub for Bhv1.Services.Internal.Strong.Branchandversioning._2018_05.BranchingAndVersioning.AddBranchContentResponse"""
    def __init__(self) -> None: ...
    ServiceData: typing.Any
    AddedNodeInfo: typing.Sequence[typing.Any]

class AddedNodeInfo:
    """Stub for Bhv1.Services.Internal.Strong.Branchandversioning._2018_05.BranchingAndVersioning.AddedNodeInfo"""
    def __init__(self) -> None: ...
    ClientID: str
    BranchContents: typing.Sequence[typing.Any]
    Edges: typing.Sequence[typing.Any]
    RelativeObjects: typing.Sequence[typing.Any]
    FailedToAddVersionNodes: typing.Sequence[typing.Any]

class BranchingAndVersioning:
    """Stub for Bhv1.Services.Internal.Strong.Branchandversioning._2018_05.BranchingAndVersioning.BranchingAndVersioning"""
    def __init__(self) -> None: ...
    def AddBranchContents(self, Inputs: typing.Sequence[typing.Any]) -> typing.Any: ...
    def CancelCheckoutNodes(self, Inputs: typing.Sequence[typing.Any]) -> typing.Any: ...
    def CreateBaselineObjects(self, Inputs: typing.Sequence[typing.Any]) -> typing.Any: ...
    def MergeBranchNodes(self, Inputs: typing.Sequence[typing.Any]) -> typing.Any: ...

class CancelCheckoutNodeInput:
    """Stub for Bhv1.Services.Internal.Strong.Branchandversioning._2018_05.BranchingAndVersioning.CancelCheckoutNodeInput"""
    def __init__(self) -> None: ...
    ClientID: str
    CancelCONodeObjects: typing.Sequence[typing.Any]
    Config: typing.Any

class CancelCheckoutNodesResponse:
    """Stub for Bhv1.Services.Internal.Strong.Branchandversioning._2018_05.BranchingAndVersioning.CancelCheckoutNodesResponse"""
    def __init__(self) -> None: ...
    CanceledCheckoutInfo: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class CanceledNodeInfo:
    """Stub for Bhv1.Services.Internal.Strong.Branchandversioning._2018_05.BranchingAndVersioning.CanceledNodeInfo"""
    def __init__(self) -> None: ...
    ClientID: str
    BranchVersionNodes: typing.Sequence[typing.Any]
    FailedVersionNodes: typing.Sequence[typing.Any]

class CreateBaselineInput:
    """Stub for Bhv1.Services.Internal.Strong.Branchandversioning._2018_05.BranchingAndVersioning.CreateBaselineInput"""
    def __init__(self) -> None: ...
    ClientID: str
    Name: str
    Description: str
    Branch: typing.Any
    ContextObject: typing.Any
    Contents: typing.Sequence[typing.Any]
    Config: typing.Any

class CreateBaselineResponse:
    """Stub for Bhv1.Services.Internal.Strong.Branchandversioning._2018_05.BranchingAndVersioning.CreateBaselineResponse"""
    def __init__(self) -> None: ...
    ServiceData: typing.Any
    BranchInfos: typing.Sequence[typing.Any]

class MergeBranchNodeInput:
    """Stub for Bhv1.Services.Internal.Strong.Branchandversioning._2018_05.BranchingAndVersioning.MergeBranchNodeInput"""
    def __init__(self) -> None: ...
    ClientID: str
    SourceNode: typing.Any
    DestinationNode: typing.Any
    Config: typing.Any

class MergeNodesResponse:
    """Stub for Bhv1.Services.Internal.Strong.Branchandversioning._2018_05.BranchingAndVersioning.MergeNodesResponse"""
    def __init__(self) -> None: ...
    MergedInfo: typing.Sequence[typing.Any]
    ServiceData: typing.Any

class NodeRelativeInfo:
    """Stub for Bhv1.Services.Internal.Strong.Branchandversioning._2018_05.BranchingAndVersioning.NodeRelativeInfo"""
    def __init__(self) -> None: ...
    NewNode: typing.Any
    ParentNode: typing.Any

__all__ = [
    'AddBranchContentInput',
    'AddBranchContentResponse',
    'AddedNodeInfo',
    'BranchingAndVersioning',
    'CancelCheckoutNodeInput',
    'CancelCheckoutNodesResponse',
    'CanceledNodeInfo',
    'CreateBaselineInput',
    'CreateBaselineResponse',
    'MergeBranchNodeInput',
    'MergeNodesResponse',
    'NodeRelativeInfo',
]
