# This file is auto-generated by generate_tc_stubs.py
# Type hints only – improves VS Code/Pylance & Codex suggestions.
from __future__ import annotations
import typing
import enum
# stub package
class BranchOutNodeInput2:
    """Stub for Bhv1.Services.Internal.Strong.Branchandversioning._2018_12.BranchingAndVersioning.BranchOutNodeInput2"""
    def __init__(self) -> None: ...
    ClientID: str
    CurrentBranch: typing.Any
    NewBranchName: str
    BranchObjectNodes: typing.Sequence[typing.Any]
    BranchOutComment: typing.Any
    Config: typing.Any

class BranchingAndVersioning:
    """Stub for Bhv1.Services.Internal.Strong.Branchandversioning._2018_12.BranchingAndVersioning.BranchingAndVersioning"""
    def __init__(self) -> None: ...
    def BranchOutNodes2(self, Inputs: typing.Sequence[typing.Any]) -> typing.Any: ...
    def CancelCheckoutNodes2(self, Inputs: typing.Sequence[typing.Any]) -> typing.Any: ...
    def CheckoutNodes2(self, Inputs: typing.Sequence[typing.Any]) -> typing.Any: ...
    def PromoteBranchNodes2(self, Inputs: typing.Sequence[typing.Any]) -> typing.Any: ...
    def PublishBranchNodes2(self, Inputs: typing.Sequence[typing.Any]) -> typing.Any: ...

class CancelCheckoutNodeInput2:
    """Stub for Bhv1.Services.Internal.Strong.Branchandversioning._2018_12.BranchingAndVersioning.CancelCheckoutNodeInput2"""
    def __init__(self) -> None: ...
    ClientID: str
    TargetBranch: typing.Any
    CancelCONodeObjects: typing.Sequence[typing.Any]
    Config: typing.Any

class CheckoutNodeInput2:
    """Stub for Bhv1.Services.Internal.Strong.Branchandversioning._2018_12.BranchingAndVersioning.CheckoutNodeInput2"""
    def __init__(self) -> None: ...
    ClientID: str
    Branch: typing.Any
    CheckoutNodeObjects: typing.Sequence[typing.Any]
    Config: typing.Any

class PromoteBranchNodeInput2:
    """Stub for Bhv1.Services.Internal.Strong.Branchandversioning._2018_12.BranchingAndVersioning.PromoteBranchNodeInput2"""
    def __init__(self) -> None: ...
    ClientID: str
    TargetBranch: typing.Any
    PromoteNodeObjects: typing.Sequence[typing.Any]
    PromoteComment: typing.Any
    Config: typing.Any

class PublishBranchNodeInput2:
    """Stub for Bhv1.Services.Internal.Strong.Branchandversioning._2018_12.BranchingAndVersioning.PublishBranchNodeInput2"""
    def __init__(self) -> None: ...
    ClientID: str
    PublishNodeObjects: typing.Sequence[typing.Any]
    PublishComment: typing.Any
    Config: typing.Any

__all__ = [
    'BranchOutNodeInput2',
    'BranchingAndVersioning',
    'CancelCheckoutNodeInput2',
    'CheckoutNodeInput2',
    'PromoteBranchNodeInput2',
    'PublishBranchNodeInput2',
]
